### ISSUE TITLE
Somfy home alarm, unable to arm

### ISSUE THREAD

**Issue by motaker** [dubocr/homebridge-tahoma#100]
Hi, I bought Somfy home alarm set (Myfox) and installed via Somfy protect app and integrated into Tahoma bridge.

I can arm and disarm alarm by tahoma & somfy protect app but I cannot controll it via homekit.
There is Alarm accessory (Away, Night, Off) but when I press Away or Night, it shows  no response. please help.

Here is corresponding information.

**Obtained config**
1 Alarm > MyFoxAlarmController
Devices click on a device to display current states
Somfy Alarm 

States Somfy Alarm myfox://SOMFY_PROTECT-2lyQ8X9LHbbyJNYZ4aeZ5lk2scA0ZTwr/site_alarm
core:CloudDeviceStatusState (offline,online,uninstalled) online
core:IntrusionState (detected,notDetected)
core:NameState
myfox:AlarmStatusState (armed,disarmed,partial) disarmed
myfox:AlertTrespassState
Commands
arm
disarm
getName
partial
setName + 1 parameter
refreshAlarmStatus
setAlarmStatus + 1 parameter

**Error message on homebridge**
5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] [Somfy Alarm] arm[]
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] [Somfy Alarm] alarmOn[]
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] Error 400 Managed action group is invalid : No such command : alarmOn on device myfox://SOMFY_PROTECT-2lyQ8X9LHbbyJNYZ4aeZ5lk2scA0ZTwr/site_alarm (myfox:SomfyProtectAlarmController) (UNSPECIFIED_ERROR)
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] [Somfy Alarm] arm +1 others Error 400 Managed action group is invalid : No such command : alarmOn on device myfox://SOMFY_PROTECT-2lyQ8X9LHbbyJNYZ4aeZ5lk2scA0ZTwr/site_alarm (myfox:SomfyProtectAlarmController) (UNSPECIFIED_ERROR)
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] Callback already triggered
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] [Somfy Alarm] disarm[]
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] [Somfy Alarm] alarmOff[]
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] Error 400 Managed action group is invalid : No such command : alarmOff on device myfox://SOMFY_PROTECT-2lyQ8X9LHbbyJNYZ4aeZ5lk2scA0ZTwr/site_alarm (myfox:SomfyProtectAlarmController) (UNSPECIFIED_ERROR)
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] [Somfy Alarm] disarm +1 others Error 400 Managed action group is invalid : No such command : alarmOff on device myfox://SOMFY_PROTECT-2lyQ8X9LHbbyJNYZ4aeZ5lk2scA0ZTwr/site_alarm (myfox:SomfyProtectAlarmController) (UNSPECIFIED_ERROR)
 5月 23 13:50:46 raspberrypi homebridge[2550]: [2019-5-23 13:50:46] [Tahoma] Callback already triggered

**config.json**
		{
			"platform": "Tahoma",
			"name": "Tahoma",
			"user": "*************",
			"password": "*************",
			"exclude": ["Alarm"],
			"ExteriorScreen": {
				"reverse": true
			}
		},

**Comment by motaker** [comment]
of course I have tried https://github.com/dubocr/homebridge-tahoma/issues/27
but If I use the Alarm.js.zip, it result in failire of initializing homebridge it self.

**Comment by dubocr** [comment]
Hi,

Thank you for reporting this issue. Can you please try this new file. If it fix I'll publish it in next release.
[Alarm.zip](https://github.com/dubocr/homebridge-tahoma/files/3215428/Alarm.zip)

Thanks.

**Comment by motaker** [comment]
Hi Dubocr
It worked ! Thank you for your kind help ;)
Now I can control via homekit but the status is not updating on time
(in the case of Away or Night mode, status showing as Arming... during few minute)
Is there any additional parameter to adjust it ? 

One more thing, I can see occupancy sensor as an accessory from Alarm system.
Is it from indoor alarm or present sensor ? neither of them wont update status as occupied when I lift them up. I am wondering what is that for ?

Takeru

**Comment by dubocr** [comment]
Hi,

For status, could you try this new file. If don't fix. Can you send me logs as I add some debug.
[Alarm.zip](https://github.com/dubocr/homebridge-tahoma/files/3216173/Alarm.zip)

Occupancy sensor is a mirror of the alarm detection state. But updates will not be triggered in realtime cause to #84

You can try to add the 2 config param in the #84 if your need shorter refresh than 30 minutes.

Thanks.

**Comment by motaker** [comment]
Perfect. now the alarm accessory is working as I wanted.
Thank you for your support !

Takeru
