### ISSUE TITLE
How to configure "reverse" for an Awning?

### ISSUE THREAD

**Issue by asheiner** [dubocr/homebridge-tahoma#101]
I already tried some changes to my config, but I didn't manage to get it resolved.
In my homebridge log I have the following accessory:

> [Sat Jun 01 2019 13:55:25 GMT+0200 (CEST)] [Tahoma] [Terrasse Markise] type: Awning > PositionableHorizontalAwning, protocol: io
> [Sat Jun 01 2019 13:55:25 GMT+0200 (CEST)] [Tahoma] Instanciate Terrasse Markise as WindowCovering

Unfortunately (at least for me) it's shown as 'open' when I extend it to have sun protection.
My vertical covering is just the other way round.

> [Sat Jun 01 2019 13:55:25 GMT+0200 (CEST)] [Tahoma] [Senkrechtmarkise] type: ExteriorScreen > PositionableScreen, protocol: io
> [Sat Jun 01 2019 13:55:25 GMT+0200 (CEST)] [Tahoma] Instanciate Senkrechtmarkise as WindowCovering

This is very confusing because when I want both sun protection I have to close the vertical one and open the horizontal awning.

I'd like to have the same behaviour as for my shutters, which means I have to reverse the horizontal one.

But .... I don't get it done 😞
I tried it like that without success:

>   "platforms": [
>     {
>       "platform": "Tahoma",
>       "name": "Tahoma",
>       "user": "no@name.eu",
>       "password": "secret",
>       "PositionableHorizontalAwning": {
>         "reverse": true
>       }
> 

Can someone give me a hint, please?

**Comment by dubocr** [comment]
Hi,

You can set the following config. However, it will reverse behavior for any device of type WindowCovering.

```
"WindowCovering": {
  "reverse": true
}
```

If you want to apply only to some device type, keep this config and update plugin 

```
"PositionableScreen": {
    "reverse": true
}
"PositionableHorizontalAwning": {
    "reverse": true
}
```

**Comment by asheiner** [comment]
Hi Romain,

thanks for your reply, but I already tried that.
As you can see in my initial post I had that in the second config.

> "platforms": [ 
> {
> "platform": "Tahoma",
> "name": "Tahoma",
> "user": "no@name.eu",
> "password": "secret",
> "PositionableHorizontalAwning": {
> "reverse": true
> }

But that doesn't change anything.
My PositionableHorizontalAwning still shows as closed, when the awning is in fact 'rolled in' and not covering anything.
Do I have to place this statement anywhere else?

**Comment by dubocr** [comment]
Hi,

Did you update the plugin
`sudo npm install -g homebridge-tahoma`
Your config is good but is only taken into account in the latest version.

**Comment by asheiner** [comment]
hi,

yep, upgrading from homebridge-tahoma@0.2.8 to 0.2.9 resolved my problem.
Thanks again for your rapid support.
