### ISSUE TITLE
Tahoma Remote Control

### ISSUE THREAD

**Issue by koupus** [dubocr/homebridge-tahoma#102]
Bonjour,
Est il possible d'utiliser la télécommande "Remote Control" avec HomeKit afin d' agir sur l'alarme interne à Tahoma (Serenity)?
Merci pour ton retour, Thomas.

[6/2/2019, 9:02:02 AM] [Tahoma] [Remote] type: RemoteController > AlarmRemoteController, protocol: rtds
[6/2/2019, 9:02:02 AM] [Tahoma] No definition found for RemoteController > AlarmRemoteController in mapping.json file

**Comment by dubocr** [comment]
Bonjour,

Le RemoteControl est en lecture seule. Il serait possible de l'ajouter en tant qu'interrupteur multi position pour déclencher des actions dans HomeKit mais ce ne serait pas instantané compte tenu du fonctionnement de l'API Somfy.
Je vais voir pour ajouté ce type de device mais si le retour d'état ne fonctionne pas sur l'alarme cela risque de ne pas être mieux.
