### ISSUE TITLE
Commande stop Raspberry

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#106]
Bonjour,
J’ai installé homebridge Tahoma sur un Raspberry pour un collègue, mais chez lui la commande stop sur les volets RTS ne fonctionne pas. On l’a redémarré: idem. On a tenté un update par le terminal: idem. Toujours pas de fonction stop. En fait au moment où on clic sur le widget pendant la fermeture, ça arrête le volet puis ça l’ouvre.
Ça fait comme chez moi lorsque je t’avais demandé la commande stop (#83).
La commande my fonctionne.

Une idée?

**Comment by dubocr** [comment]
Bonjour,

Est-il possible qu'il se connecte sur https://dev.duboc.pro/tools/setup pour vérifier déjà si le type de volet est reconnu de façon identique.

Merci.

**Comment by Tontonpat** [comment]
Bonjour Romain. C’est fait

**Comment by dubocr** [comment]
Bonjour,

Je vois dans l'historique des "CMDCANCELLED" qui doivent normalement arrêter le mouvement. Ils n'ont pas eu d'effet du coup si je comprends bien ? Ce qui est étrange, c'est que l'historique affiche les commandes up/down alors que ce sont les commande open/close qui devraient apparaître.

Pourrait-il lancer un mouvement et le stopper depuis l'application TaHoma puis se connecter à la page afin que je puisse déjà vérifier les opérations attendues.

**Comment by Tontonpat** [comment]
Bonjour.
C’est fait, à l'instant

**Comment by Tontonpat** [comment]
Penses tu qu’il faut réinstaller le Raspberry?

**Comment by dubocr** [comment]
Je ne pense pas, je vais faire un test ce soir avec la config récupérée. Je te tiens au courant.

**Comment by dubocr** [comment]
C'est possible que la version ne soit pas complètement à jour car les commandes ne correspondent pas.
Peux-tu vérifier la version avec `npm list -g --depth=0 | grep homebridge-tahoma`
Et essayé une nouvelle mise à jour `nom -g install homebridge-tahoma`

**Comment by Tontonpat** [comment]
Bonjour Romain, merci pour tes conseils et le temps passé. Mon collègue a fait ce que tu as dit et tout fonctionne normalement. Merci pour lui

**Comment by dubocr** [comment]
Hello,

Impeccable. Les plugins NPM ne sont pas mis à jour automatiquement il faut le faire manuellement.

De rien et bonne journée.

**Comment by Tontonpat** [comment]
Sais tu si il est possible de les mettre à jour automatiquement au reboot par exemple?

**Comment by dubocr** [comment]
Nativement je ne pense pas, après ça doit être possible avec les taches de démarrage mais je ne sais pas si c'est possible de mettre à jour tout les packages NPM d'un coup.
