### ISSUE TITLE
Status on the Icon Does not change

### ISSUE THREAD

**Issue by Shana611** [dubocr/homebridge-tahoma#107]
My Gate status doesn't change. When I open the gate it shows opening but at the end it shows "Gate Closed" status on the HomeKit Icon.

**Comment by dubocr** [comment]
https://dev.duboc.pro/tools/setup

**Comment by Shana611** [comment]
I updated to your lats update but the status still same nothing change.

**Comment by dubocr** [comment]
Your gate is a "Cyclic" gate. Normally it automatically close after some time. So the plugin emulate the closing by switching the icon to "closed" after 5 seconds. Is that you're observing ?

**Comment by Shana611** [comment]
No, that’s not automatically close. We need to close it. But the problem is when I’m opening the gate it shows opening but after opening status shows close.

**Comment by dubocr** [comment]
HI,
I've remove the default 'cycle' behavior. Can you try to update and the me if it's better or not.

Thanks.

**Comment by Shana611** [comment]
Hi, 
Now end of the procedure status perfect it shows Open & Close thank you so much. But there is another issue now. It doesn't show opening..... & closing..... status while it's opening or closing

**Comment by dubocr** [comment]
Hi,

That's normal as you device doesn't reports his status we can't know when it is opening and when it is opened.

**Comment by Shana611** [comment]
Hi,
I have a small problem again when I give the open command the gate opens but when give the close command according to home app it's closing and status closed but actual status on gate is open basically the doesn't close

**Comment by Shana611** [comment]
Aug 15 10:25:41 raspberrypi homebridge[309]: [8/15/2019, 10:25:41 AM] [Config] Console v4.5.2 is listening on :: port 8080
Aug 15 10:26:01 raspberrypi homebridge[309]: [8/15/2019, 10:26:01 AM] [Alexa] alexaDiscovery - returned 14 devices
Aug 15 10:26:32 raspberrypi homebridge[309]: [8/15/2019, 10:26:32 AM] [Tahoma] [Main Gate] cycle[]
Aug 15 10:26:32 raspberrypi homebridge[309]: [8/15/2019, 10:26:32 AM] [Tahoma] Listener registered 9499a290-3626-5439-51c1-05c2297115aa
Aug 15 10:27:04 raspberrypi homebridge[309]: [8/15/2019, 10:27:04 AM] [Tahoma] [Main Gate] cycle COMPLETED
Aug 15 10:27:04 raspberrypi homebridge[309]: [8/15/2019, 10:27:04 AM] [Tahoma] Callback already triggered
Aug 15 10:27:15 raspberrypi homebridge[309]: [8/15/2019, 10:27:15 AM] [Tahoma] [Main Gate] cycle[]
Aug 15 10:27:16 raspberrypi homebridge[309]: [8/15/2019, 10:27:16 AM] [Tahoma] Listener registered 949a4d88-3626-5439-51c1-05c271a2e681
Aug 15 10:27:48 raspberrypi homebridge[309]: [8/15/2019, 10:27:48 AM] [Tahoma] [Main Gate] cycle COMPLETED
Aug 15 10:27:48 raspberrypi homebridge[309]: [8/15/2019, 10:27:48 AM] [Tahoma] Callback already triggered
