### ISSUE TITLE
Clim Hitachi

### ISSUE THREAD

**Issue by Seb0101** [dubocr/homebridge-tahoma#109]
Bsr, c'est encore moi avec mes clims Hitachi.
Plus de redémarrages et de pbs de connexion, tout ça va très bien.
J'ai par contre des soucis de passerelle, plus exactement il me semble d'interprétation par HomeKit des données qui sont envoyées. Et qui se répercutent vers home assistant ensuite.
Selon les logs, les données envoyées à HomeKit sont les suivantes :
     [Seb Clim] globalControl["on",25,"auto","cooling","manu"]
HomeKit semble mélanger la donnée on/off avec la donnée relative au mode d'opération (cool, etc).
En tous cas presque systématiquement est pris en compte la fonction mode d'opération au lieu de on/off, ce qui fait qu'une clim éteinte mais en mode précédent cool est considérée active en mode cool.
Je ne sais pas si je suis clair. Et si ça provient de l'architecture de HomeKit ou des données transférées. 
Homekit ne renvoit pas le bon état des clims, ça s'est certain.
Je te remercie de ton retour.

**Comment by Seb0101** [comment]
Bsr, je rectifie : après plusieurs essais finalement mon problème est que l’etat des équipements ne se met pas à jour si l’action ne transite pas par homebridge. Et, même si j’arrête ou change quoi que ce soit via Home l’etat se met à jour brièvement et ensuite nada ça revient à n’importe quoi.
Homebridge est sur Synology, via le paquet et docker.
Est-ce un problème de port non ouvert ? 
Merci.

**Comment by dubocr** [comment]
Bonjour Seb,

Il faudrait distinguer si le problème provient de la non mise à jour ou d'une mauvaise mise à jour.

Dans le premier cas, après 1/2h max, l'affichage sur home devrait être correct. Pour améliorer cette gestion, tu peux regarder le ticket #112 pour comprendre les différents niveaux du système Cozytouch et les changements de configuration envisageable. Dans tout les cas, il n'est pas question de port car malheureusement l'API Cozytouch ne permet pas de "pousser" les mises à jour.

Dans le second cas, alors même après plusieurs heures l'affichage sur home serait incorrect. Dans ce cas, il y a probablement un correctif à apporter dans la gestion des paramètres mais de ce que je comprends nous serions plutôt dans le premier cas.

Pour tester, tu peux réaliser une action et lorsque tu constates une incohérence sur Home, alors ferme (kill) l'application Cozytouch et rouvre la. Cela va forcer un refresh global de toute la clim je pense et tu devrais avoir un état cohérent sur Home. Si ce n'est toujours pas le cas, connecte toi alors sur https://dev.duboc.pro/tools/setup et indique moi quel état sur Home serait attendu pour que je vérifie la cohérence entre les paramètres de la clim et homebridge.

**Comment by Seb0101** [comment]
Bonjour Romain,
J'ai regardé ce matin : une commande depuis home est bien transmise à tahoma, mais aucun retour d'état de la clim. Et ce soir ça n'a pas changé. Donc plutôt cas 2.
Je te joins le log depuis la fin du dernier redémarrage de homebridge. Pour précision, je n'essaye de commander pour l'instant que la clim, les volets le sont par ailleurs.
[log.txt](https://github.com/dubocr/homebridge-tahoma/files/3387289/log.txt)

Fermer l'application cozytouch (je suis sur tahoma) ? 
Je me suis connecté sur https://dev.duboc.pro/tools/setup.
Une des clim devrait retourner off pendant deux jours, Arthur Clim.
Et en ce moment 26° dans la pièce, précédemment 25° de consigne.
Homebridge retourne le mode frais, 27 dans la pièce, et soit 24, soit 25 soit 26 de consigne.
(précision encore : je n'utilise pas home directement mais via home assistant; le faire en direct n'a rien changé - si ce n'est que j'ai du tout reparamétrer...).
Voilà. Merci.

**Comment by Seb0101** [comment]
Bjr Romain,
Il semble que mon problème soit le même que la #114 
Même erreur dans le log.

**Comment by Seb0101** [comment]
Bjr,
Je suis aussi revenu au paramètre "refreshPeriod": 300" pour éviter l'erreur #114.
L'état de mes clim ne se met toujours pas à jour, mais leurs commandes fonctionnent.

**Comment by Seb0101** [comment]
bonsoir Romain,
Tout semble stable maintenant, j'ai pu revenir à la config "alwaysPoll": true" & "pollingPeriod": 10.
Plus d'erreurs sauf sporadiquement aujourd'hui., et la connexion est revenue.
MAIS, j'ai toujours ce problème de confusion de HomeKit : températures bonnes, info sur l'état du mode froid / chaud / auto correcte, mais pour homekit les clim restent en fonctionnement et ne passent jamais en off. Du coup je ne sais pas si elles fonctionnent ou pas.
Merci si tu peux corriger la bonne remontée d'info
Seb

**Comment by Seb0101** [comment]
Bsr Romain,
J'ai trouvé l'erreur qui faisait que l'état de mes clims n'était pas le bon.
Il y a une erreur dans le fichier Thermostat.js : 'off' doit être écrit 'Off' à la ligne if(this.device.states['ovp:MainOperationState'] == 'off')...
Bonne soirée.
Sébastien
