### ISSUE TITLE
RTS Awning Up / Down reversed

### ISSUE THREAD

**Issue by imsturmdernacht** [dubocr/homebridge-tahoma#11]
At first a big "thank you" for programming this plugin,

maybe you can help me with this little beauty issue. I have an Somfy RTS awning without position signal installed. Controlling my awning works just fine (up and down) but the up and down commands are reversed. Normaly, on shutters, the commands where correct. Shutter closed = down, shutter open = up. But it doesn't make sense on an awning. When awning has moved outside it's like open and when awning has moved back it's like closed. I'm not a coding specialist. Can you tell me how to change up and down commands in awning.js?

Regards Oli

**Comment by imsturmdernacht** [comment]
Okay,

I've just found the solution by myself. I've replaced lines 119-121 in awning.js

case 100: cmd = 'up'; break;
case 0: cmd = 'down'; break;
default: cmd = 'my'; break;

with

case 100: cmd = 'down'; break;
case 0: cmd = 'up'; break;
default: cmd = 'my'; break;

Now it's all fine.

Issue can be closed.

Regards, Oli

**Comment by dubocr** [comment]
Hey Oli,

Thanks for your feedback. I see you find by yourself how to reverse open/close commands. Very nice. May I could add a config option to reverse it for awning for future release.

Good automation !
Romain
