### ISSUE TITLE
Icone Alarme dans HomeKit

### ISSUE THREAD

**Issue by nanoupi42** [dubocr/homebridge-tahoma#110]
Bonjour Romain,

J'ai une icône alarme dans mon HomeKit alors que je ne possède (pas encore) d'alarme Somfy.
Un collègue qui possède une alarme Somfy me dit que lui il en voit deux (une fonctionnelle qui pilote bien son alarme et une autre où il ne peut rien faire).

Morgane

**Comment by chicochaleur29** [comment]
Bonjour
Rajoute ce code dans ta config : 

"exclude": [
                "Alarm"
            ]


Cordialement

**Comment by nanoupi42** [comment]
Hello,

Merci pour ton message chicochaleur29.

Pour mon cas j'avais effectivement penser à cette solution, mais dans le cas de mon ami ça va lui exclure également son alarme fonctionnelle je pense ? 

Morgane

**Comment by dubocr** [comment]
Bonjour Morgane,

Effectivement certaines config font apparaître une alarme interne, pour certains utilisateurs elle est utile mais pas pour les autres et je n'arrive pas à savoir sur quel critère me baser pour l'afficher ou non.
Dans le doute, elle s'affiche pas défaut, tu peux l'exclure via cette config :
"exclude": ["internal"]
Ton collègue peut également masquer l'alarme sur laquelle il ne peut pas agir avec cette config.

**Comment by nanoupi42** [comment]
Merci Romain ça marche. 

Je transmets l'info à mon collègue :-)

**Comment by navjul** [comment]
> Bonjour Morgane,
> 
> Effectivement certaines config font apparaître une alarme interne, pour certains utilisateurs elle est utile mais pas pour les autres et je n'arrive pas à savoir sur quel critère me baser pour l'afficher ou non.
> Dans le doute, elle s'affiche pas défaut, tu peux l'exclure via cette config :
> "exclude": ["internal"]
> Ton collègue peut également masquer l'alarme sur laquelle il ne peut pas agir avec cette config.

Hello,

Je pense qu'il s'agit des personnes équipées de la base Serenity sur Tahoma. C'est mon cas et effectivement le pilotage de l'alarme fonctionne (j'ai encore des tests à réaliser, j'ai l'impression que tout n'est pas fonctionnel : la désactivation fonctionne, le reste c'est moins sûr).
