### ISSUE TITLE
Homebridge restart not possible - Too many requests

### ISSUE THREAD

**Issue by URBANsUNITED** [dubocr/homebridge-tahoma#112]
Hi!

I recently installed all new for Homebridge on my rpi3b, but everytime I restart my homebridge server using the homebridge-config-ui-x v4.5.1, homebridge doesn't start as of too many login requests:

Jul 01 22:26:17 raspberrypi homebridge[1108]: [7/1/2019, 10:26:17 PM] [Tahoma] Login fail: Too many requests, try again later : login with a.wuexxxxxn@gmail.com
Jul 01 22:26:17 raspberrypi homebridge[1108]: [7/1/2019, 10:26:17 PM] TypeError: Cannot read property 'length' of null
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:407:44)
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at /usr/local/lib/node_modules/homebridge-tahoma/index.js:100:6
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at TahomaPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/index.js:202:5)
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:185:5
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at Request._callback (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:250:6)
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at Request.emit (events.js:198:13)
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
Jul 01 22:26:17 raspberrypi homebridge[1108]:     at Request.emit (events.js:198:13)
Jul 01 22:26:17 raspberrypi homebridge[1108]: [7/1/2019, 10:26:17 PM] [Tahoma] Login fail: Too many requests, try again later : login with a.wuexxxxxn@gmail.com
Jul 01 22:26:17 raspberrypi homebridge[1108]: [7/1/2019, 10:26:17 PM] [Tahoma] Too many requests, try again later : login with a.wuexxxxxn@gmail.com

When I wait a bit, all start as normal, but a restart is forbidden for me :(

I start homebridge as root

My config
{
            "platform": "Tahoma",
            "name": "Tahoma",
            "user": "a.wuexxxxxn@gmail.com",
            "password": "password",
            "service": "TaHoma",
            "refreshPeriod": "300",
            "exclude": [
                "Garage Door"
            ]
        },

**Comment by dubocr** [comment]
Bonjour,

C'est probablement du au paramètre "refreshPeriod" que vous avez fixé à 5 minutes. On doit s'approcher des limites de connexion de l'API Somfy.

**Comment by URBANsUNITED** [comment]
Bonjour Romain,

thanks for your respose. 
But in case I restart my server, the time is always shorter than my refreshPeriod of 300 seconds.
The server doesn't stop and wait till the 300 sec. are over

Do you know the time Somfy sets between each login?

Originally I want to have a shorter refreshPeriod as of a scence:
When the roller shutters are below 25% switch on light

Here you want a near direct communication. Shutters drive down and the light switches on. You don't want to way 5 or more minutes till the light is on as the room is dark and you are waiting for light.

Can you implement different refreshPeriod based on the items you want to control?
Like a smike sensor must act very fast, a light/sun sensor can act slower for example

What can I do now? Before my new installation all was fine, now it acts different. I used the same installation way than before. Only I switch from Stretch to Buster Debian. But everythin is working fine.

Thanks

URBANsUNITED

**Comment by dubocr** [comment]
These limitations comes from Somfy API. Refreshing 1 sensor more often than other won't change the limitation. I just add a feature to postpone login when we detect "Too many request" error, it must fix your restart issue. (will be available tomorrow)
Concerning your automation, I advise you to replace your config "refreshPeriod" by this 2 :
```
"alwaysPoll": true,
"pollingPeriod": 10
```
This will allow "push" device (light sensor for eg.) to be monitored. May the roller shutter will also be reported faster.

For your information :
**Device <-1-> API/Server <-2-> Plugin**
_refreshPeriod_ => force API to refresh IO device states (link 1), and report it to plugin (link 2). Involves local radio communication.
_pollingPeriod_ => get fresher device states from server (link 2). Allows more frequent request.

**Comment by URBANsUNITED** [comment]
Thanks Romain for taking care!

I will report tomorrow night. And thanks also for the config suggestion and explanation.

Bye
URBANsUNITED

**Comment by URBANsUNITED** [comment]
Good morning Romain,

so, I've noticed two things:
1. My login problems after restarting are "gone" The situation is explaineable. After keeping the Homebridge running for several hours, the Somfy system goes back into normal status. I can restart my system with 2-3 minutes between with no issue. BUT when you do this too often, the Somfy system claims about too many logins. So, it has nothing to do with your extension, more the security way of Somfy. Under normal circumstances 2-3 restarts are ok and don't hurt. Will see your modification later on.

2. I've changed my config to your advicce:

{
            "platform": "Tahoma",
            "name": "Tahoma",
            "user": "a.xxxxxxx@gmail.com",
            "password": "password",
            "service": "TaHoma",
            "alwaysPoll": true,
            "pollingPeriod": 10
        },

But my 2 light sensors are still not reachable. Using the Tahoma app, the sensors are working 100%, I did a check using your tools this morning already and all devices are reachable, no issues, only the link from Tahoma to Homebridge is not working. RSSI is ca. 70-76, batteries are ok.
During the day, they will be available, but not constant. The connection to the sensors get lost, but only for Homebridge/Homekit.
My 3 smoke detectors are working fine, no issues, always reachable!
My log file gives no indication of errors in normal mode.

Btw. do you know a way to change the ip to static or change the dns server of the tahoma box?

Have a good one

Andi

**Comment by URBANsUNITED** [comment]
Hi Romain,

no update on NPM available yet. Did you publish it?
Btw. my light sensors are still very often unavailable

best regards

Andi

**Comment by dubocr** [comment]
Update was published, you can try to updated. May it'll not fully fix but you will have some logs showing "Retry in 2 min" that could be increased.

**Comment by URBANsUNITED** [comment]
I set up my system yesterday evening, fresh install and the issue was still present. 
I noticed the too many logins but nothing further, no retry in 2min or similar.
Maybe the update is not yet available on npm?

**Comment by dubocr** [comment]
Updated was just pushed today. Version 0.3.7

**Comment by URBANsUNITED** [comment]
Ok! 

Works half way:
[7/11/2019, 5:57:02 PM] [Tahoma] Login fail: Too many requests, try again later : login with a.xxx@gmail.com
[7/11/2019, 5:57:02 PM] [Tahoma] Too many requests, try again later : login with a.xxx@gmail.com
[7/11/2019, 5:57:02 PM] [Tahoma] Retry in 2 min
[7/11/2019, 5:57:02 PM] ReferenceError: requestWithLogin is not defined
    at Request._callback (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:254:36)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

There is no retry for a new login. It simply doesn't restart the homebridge service. Good thing is that it doesn't try and try and try again. But after the 2 min a new attempt would make sense...
Possible?
Btw. 2min are not enough. tried after 5 min now and login still not possible.

[7/11/2019, 6:02:19 PM] [Tahoma] Login fail: Too many requests, try again later : login with a.xxx@gmail.com
[7/11/2019, 6:02:19 PM] [Tahoma] Too many requests, try again later : login with a.xxx@gmail.com
[7/11/2019, 6:02:19 PM] [Tahoma] Retry in 2 min
[7/11/2019, 6:02:19 PM] ReferenceError: requestWithLogin is not defined
    at Request._callback (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:254:36)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by dubocr** [comment]
Corrigé dans la 0.3.11

Merci.
