### ISSUE TITLE
The requested platform 'Tahoma' was not registered by any plugin.

### ISSUE THREAD

**Issue by nevoalani** [dubocr/homebridge-tahoma#119]
first of all, thank you for the plugin!
Im pretty new to homebridge. I got my Somfy Connexoon RTS, and found this homebridge plugin. I installed the plugin and added that to my config (under platforms):
{
			"platform": "Tahoma",
			"name": "My TaHoma Box",
		  
			"user": "xxxx@xxxx.com",
			"password": "xxxx",
			"service": "Connexoon RTS"
}
and what I get after trying to activate homebridge is:
"Error: The requested platform 'connexoon' was not registered by any plugin."
can anyone help me fix it? thanks in advance to all of you!!!

**Comment by dubocr** [comment]
Hi,

Please make sure `"platform": "Tahoma"`
Then go back in the log to be sure there is no other error before :
`sudo journalctl | grep homebridge`

**Comment by nevoalani** [comment]
Thank you!
