### ISSUE TITLE
Thermostats et radiateurs 

### ISSUE THREAD

**Issue by nanoupi42** [dubocr/homebridge-tahoma#12]
Bonjour,
Tout d'abord un très GRAND merci pour ce plugin, depuis le temps que j'en cherchais un je suis comblée !! Merci beaucoup.

Je voulais regarder si je pouvais faire fonctionner mes radiateurs chez moi sur HomeKit.
Actuellement je les vois, mais lorsque je clique dessus ça me fait planter mon homebridge :-) J'ai bien vu que le fonctionnement n'était pas testé sur les radiateurs donc que le fonctionnement n'était pas garanti. 
 
Au niveau de l'installation il s'agit de 2 thermostats 
https://boutique.somfy.fr/programmateur-radio-fil-pilote-1-recepteur-dispo-fevrier-2015.html
https://www.somfy.fr/produits/2401242/thermostat-programmable-sans-fil-contact-sec

Et j'ai des récepteurs sur les radiateurs 
https://boutique.somfy.fr/recepteur-sans-fil-fil-pilote-pour-programmateur-radio-fil-pilote.html

Mon homebridge tourne dans un docker sous debian 9. 

Pensez-vous que je peux réussir à le faire fonctionner ? Par où dois-je commencer ?

Merci encore

Morgane.

**Comment by dubocr** [comment]
Bonjour Morgane,

Ravi que ce plugin te plaise :-). J'ai effectivement implémenté à l'aveugle les radiateurs mais avant tout les produits Atlantic/Thermor/Sauter. Il n'est donc doublement pas étonnant que les produits mentionnés ne fonctionnent pas ou que partiellement.
Pour commencer, peux-tu accéder à [cette page](http://home.dubocr.fr/tools/setup) avec tes identifiants TaHoma ce qui me fera parvenir ta configuration (aucune donnée sensible).
A partir de là, cela me permettra de faire correspondre des commandes/états TaHoma avec des commandes/états HomeKit pour faire évoluer le fichier correspondant aux produits (probablement HeatingSystem.js).

Merci d'avance.

**Comment by nanoupi42** [comment]
Hello,
Merci pour ta réponse.

Mes radiateurs sont des Sauter pour info :-)

Je viens de me loger sur la page mentionnée.

**Comment by dubocr** [comment]
Ce sont des Sauter mais ils ne sont pas 'nativement' connectés. Du coup le passage par fil pilote rend l'interface moins idéal.
Voici un fichier pour remplacer le contenu de 'HeatingSystem.js' dans le répertoire 'accessories' du plugin. [HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1322311/HeatingSystem.txt)
Il permet normalement (à tester et peut-être debugger un peu) de piloter un minima les produits.
Le fil pilote n'étant pas très (du tout même) international, les différents modes n'existent pas dans homekit. Les radiateurs et l'interface fil pilotent apparaitront donc désormais sous forme de switch On/Off. Pour le plancher chauffant la modification de la T° modifiera la T° de confort.
Tout se passe dans ce fichier en tout cas. Le but du jeu étant de faire correspondre les commandes d'un produit homekit (Thermostat, Switch, ou [autre](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js)) avec les commandes disponibles sur TaHoma (liste JSON dans definition->commands pour chaque produit dans la config)

**Comment by nanoupi42** [comment]
Bonjour,
Je viens d'essayer de remplacer le contenu de HeatingSystem.js. Homebridge plante lorsque que je souhaite modifier la température (ça fait la même chose qu'avant modification :

/usr/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:44
        var command = new OverkizCommand('setHeatingTargetTemperature');
                          ^
ReferenceError: OverkizCommand is not defined
    at Object.setTemperature (/usr/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:44:27)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/usr/lib/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:812:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:757:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:972:10)

Ce n'est peut-être pas faisable avec ma config...

**Comment by dubocr** [comment]
Effectivement, ce fichier n'a jamais du être testé. Il faut remplacer 'OverkizCommand' par 'Command' partout où il apparait dans le fichier. Cela devrait déjà ne plus planter.

**Comment by nanoupi42** [comment]
Je ne sais pas si ça avait bien pris le fichier joint tout à l'heure, car maintenant dès que je place le fichier que vous m'avez donné et que je relance homebridge j'ai l'erreur suivante :

/usr/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:178
            this.heatingCurrentState.updateValue(converted);
                                    ^

TypeError: Cannot read property 'updateValue' of undefined
    at Object.onStateUpdate (/usr/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:178:37)
    at /usr/lib/node_modules/homebridge-tahoma/index.js:80:20
    at /usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:173:5
    at Request.authCallback [as _callback] (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:205:17)
    at Request.self.callback (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)

**Comment by nanoupi42** [comment]
Pour info je viens de passer sur un système Debian avec home bridge installé, plus de docker et j'ai pas la même erreur 👍 
[Tahoma] Error 400 Managed action group is invalid : No such command : setHeatingTargetTemperature on device ovp://1202-5350-4906/12300327#1 (ovp:SomfyHeatingTemperatureInterfaceOVPComponent) (UNSPECIFIED_ERROR)

Et le home bridge plante plus c'est déjà ça, par contre là je suis avec le Heatingsystem.js d'origine.

**Comment by dubocr** [comment]
Voici un correctif à tester [HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1326739/HeatingSystem.txt)

**Comment by nanoupi42** [comment]
Merci encore pour votre assistance.
Voici mon retour : 
Je vois bien les interfaces Fil/pilote en interrupteur on/off.
Par contre dès qu'il y a une interaction avec eux ça plante : 
Dans homebridge.err j'ai 

/usr/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:143
                    that.targetState.updateValue(that.currentState.value);
                                    ^

TypeError: Cannot read property 'updateValue' of undefined
    at /usr/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:143:37
    at /usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:101:11
    at pollingtoevent.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:102:21)
    at emitOne (events.js:96:13)
    at pollingtoevent.emit (events.js:188:7)
    at done (/usr/lib/node_modules/homebridge-tahoma/node_modules/polling-to-event/index.js:63:20)
    at /usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:84:14
    at Request.authCallback [as _callback] (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:205:17)
    at Request.self.callback (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)

![img_13347cacfd81-1](https://user-images.githubusercontent.com/32174046/30776131-6e4ebf80-a0a1-11e7-91ac-e121c0d3d171.jpeg)

Sur la capture on voit bien le thermostat Salon Etage 24 ° (aucune interaction possible à l'heure actuel mais je ne pense pas que ce soit faisable) 
Ensuite, 1-Salon c'est le récepteur placé au niveau du fil pilote
Et Salon Etages-1 Je suppose que c'est le radiateur.

dès que j'interagis avec 1-Salon ou Salon Etages-1 j'ai l'erreur précisée plus haut, et quelques secondes plus tard le plantage d'homebridge.

**Comment by dubocr** [comment]
Désolé pour le compte goutte je n'ai pas ce qu'il faut pour tester malheureusement. Voici un correctif pour l'erreur : [HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1326779/HeatingSystem.txt)
Je pense que Salon Etage 24°C correspond à un capteur de T° si aucune interaction n'est possible. Il s'agit probablement du thermostat physiquement mais il apparait sous plusieurs sorte de capteur dans TaHoma.

**Comment by nanoupi42** [comment]
Pas de soucis !! C'est déjà très gentil d'aller plus loin dans le diagnostic, surtout que là c'est pas mal du tout, on touche au but je crois :-) 

- Plancher chauffant : fonctionnement nickel je peux choisir le mode de chauffe ainsi que la température c'est TOP !
![img_f56905a0a37d-1](https://user-images.githubusercontent.com/32174046/30776875-b8a345ee-a0ae-11e7-95cd-5b14c849f617.jpeg)

- Un peu plus compliqué pour la partie fil pilote, en fait lorsque je sélectionne 1-Salon (capture précédente) ça passe mon thermostat en ECONOMIE et allume les 3 radiateurs en même temps sur la température ECONOMIE. 
Par contre je ne peux pas piloter l'allumage d'un radiateur pour le couper par exemple. J'ai tenté via les boutons Salon Etages-1 par exemple mais ça n'éteint pas le radiateur en question, aucun effet et pas d'erreur de les logs à première vue. Cette problématique me rappelle quelque chose, l'année passée je m'étais aperçue que je ne pouvais pas interagir sur un radiateur en particulier les boutons étaient grisés c'est d'ailleurs toujours le cas : 
![img_14b85f4f4288-1](https://user-images.githubusercontent.com/32174046/30776908-75b12eee-a0af-11e7-8c04-87162cd58f21.jpeg)

Je n'ai jamais compris pourquoi, je trouve cela dommage d'être contraint de piloter toutes les zones en même temps... A moins que quelque chose m'échappe... 
Est-ce possible de passer directement les zones en confort plutôt qu'Economie lors de l'appuie sur 1-Salon ? Il n'est pas possible de choisir son programme (eco/confort) via ce bouton à cause de l'interface fil pilote c'est ça ?

Encore un grand merci, plus de plantage de home bridge en plus du coup :-)

**Comment by nanoupi42** [comment]
Je viens de retrouver comment gérer les radiateurs indépendamment : je dois d'abord passer le thermostat sur "Auto" et les boutons Eco/Confort sur chaque radiateurs ne sont plus grisés sur Tahoma :-) 
Du coup je ne sais pas du tout si c'est adaptable sur HomeKit.

**Comment by dubocr** [comment]
Voici comment je vois la chose de mon côté. Est-ce bien cela ?
_1-Salon, 2-Chambre, 3-Bureau : Radiateur fil pilote
Etages-1 : Thermostat fil pilote
Plancher Chauffant : Thermostat
Plancher Chauffant-1, Etages : Capteur de température_

Actuellement le comportement est le suivant : 
Produit | Commande   Homekit | Commande TaHoma
-- | -- | --
Radiateur fil   pilote | On/Off | On/Off
Thermostat fil   pilote | On/Off | On/Off
Thermostat | Chaud/Froid/Auto | On
 | Eteint | Off
 | Changemt T° | Changemt T° confort

Est-il possible qu'en mode "manuel" tous les radiateurs soient synchronisés ce qui expliquerait que le "on" sur 1-Salon ai provoqué l'allumage de tout les autres. Lorsque tu es en mode "auto", que provoque une action homekit sur un radiateur seul (1-Salon, 2-Chambre, 3-Bureau) ?

**Comment by dubocr** [comment]
Autre précision, "Salon Etages-1" sur les copie d'écran correspond à "Etages-1" dans mes commentaires. Le terme "Salon" est ajouté par l'application Apple car le produit à été mis dans la pièce "Salon" de l'application. Il est donc "normal" qu'une action sur "Etages-1" agisse sur tout les radiateurs (car "Etages-1" correspond au Thermostat fil pilote d'après moi).
Serait-il possible d'avoir une copie d'écran de l'application TaHoma faisant apparaitre tous les produits de chauffage pour que je puisse comprendre comment ils sont gérés côté TaHoma.

**Comment by dubocr** [comment]
Voici 3 nouveaux fichiers (overkiz-api est situé dans le répertoire principal, les deux autres dans 'accessories').
[HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1327224/HeatingSystem.txt)
[overkiz-api.txt](https://github.com/dubocr/homebridge-tahoma/files/1327226/overkiz-api.txt)
[AbstractAccessory.txt](https://github.com/dubocr/homebridge-tahoma/files/1327225/AbstractAccessory.txt)

Le comportement devrait normalement être le suivant avec cette implémentation : 
![commandes](https://user-images.githubusercontent.com/5015156/30781898-3d2fa9c8-a128-11e7-9f20-4fb970c3bb26.png)

Bons tests

**Comment by nanoupi42** [comment]
Hello,
Effectivement pour moi le bouton Etages-1 correspond bien au thermostat fil pilote, lorsque je clique dessus le thermostat réagi et affiche "Economie". Tous les radiateurs passent en Economie. Je ne comprend pas pourquoi par contre, c'est comme s'il agissait sur toutes les zones en même temps. 
Je me souviens avoir affecté mes récepteurs dans 3 zones différentes : 
Zone 1 : recepteur Salon
Zone 2 : recepteur Chambre
Zone 3 : recepteur Bureau 
Il me semble, et là ça impact donc bien les 3 zones en même temps. 

Je viens de passer le thermostat en mode Auto, il se base sur les programmations que j'avais mis en place l'année passé, voici les programmations durant cette plage horaire : 
Zone 1 : Confort 
Zone 2 : Economie 
Zone 3 : Economie 

Lorsque je clique sur 2-Chambre ça force le radiateur en mode Confort, par contre si j'appuie de nouveau il reste en confort. Pareil pour Bureau. Lorsque je clique sur le recepteur Salon il reste en confort, ça ne fait rien. Je peux pas l'éteindre pour dire de forcer en mode Eco par exemple. 

Je viens de copier les 3 nouveaux .js pour test et home bridge ne veut pas démarrer : 

[2017-9-24 13:12:43] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.2
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [homebridge]
 2: 0x109f0ac [homebridge]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [homebridge]
 4: 0x10c9496 [homebridge]
 5: 0x2058ebf4f6f8
Abandon


Merci encore pour votre assistance

**Comment by nanoupi42** [comment]
Au cas ou voici une capture de l'application Tahoma : 
![img_985f126df6fd-1](https://user-images.githubusercontent.com/32174046/30782050-9bb702b4-a12a-11e7-8faa-964812d3fa63.jpeg)

**Comment by dubocr** [comment]
Les 3 zones correspondent à 1-Salon, 2-Chambre, 3-Bureau. Etages-1 correspondant au thermostat, il agit sur toutes les zones en même temps c'est donc logique. Sur TaHoma, quelles sont les actions possibles en cliquant sur l'une des 3 zones 1-Salon, 2-Chambre ou 3-Bureau ? Et le boutons "Chauffages (3)" à quoi correspond t'il ?

Un petit bug s'est glissé dans les précédents fichiers, voici de quoi corriger.

[AbstractAccessory.txt](https://github.com/dubocr/homebridge-tahoma/files/1327240/AbstractAccessory.txt)
[HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1327241/HeatingSystem.txt)

**Comment by nanoupi42** [comment]
Ca ne fonctionne pas j'ai la même erreur : 
[2017-9-24 13:33:48] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.2
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: node::Abort() [homebridge]
 2: 0x109f0ac [homebridge]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [homebridge]
 4: 0x10c9496 [homebridge]
 5: 0x39e5f4bee598
Abandon

Lorsque le thermostat salon est OFF, et que je clique sur 1-Salon par exemple, tout est grisé sur Tahoma : 

![img_e4c858d8e3db-1](https://user-images.githubusercontent.com/32174046/30782199-75be604a-a12d-11e7-896d-c115e0d6a395.jpeg)

Par contre, si le thermostat est en auto, je peux changer forcer un mode sur les radiateurs : 
Confort ou Eco : 
![img_e4c858d8e3db-1](https://user-images.githubusercontent.com/32174046/30782208-920b7166-a12d-11e7-97da-79fd5e1a71c6.jpeg)

Je ne peux interagir sur les radiateurs que si le thermostat est en auto. Si je passe le thermostat en confort les boutons sont grisés sur les radiateurs comme dans le cas ou le thermostat est éteint.

**Comment by dubocr** [comment]
OK merci la dernière implémentation devrait donc être proche du comportement sur TaHoma. Ma correction ne concerne pas l'erreur au démarrage car je ne vois pas de quoi il s'agit. As-tu remplacer les fichiers ou remplacer le contenu ? Le plus simples serait de désinstaller puis réinstaller le plugin complètement afin d'avoir des fichiers propres puis voir si ca redémarre. Ensuite remplacer un à un le contenu de chaque fichier (en commençant pas overkiz-api puis redémarrage puis Abstract... puis redémarrage puis Heating...).

**Comment by dubocr** [comment]
Voici les fichiers originaux complets au cas où ce soit mieux : 
[TaHoma.zip](https://github.com/dubocr/homebridge-tahoma/files/1327270/TaHoma.zip)

**Comment by nanoupi42** [comment]
C'est Good après réinstalle, je soupçonne un mauvais copier coller de ma part désolé, j'ai fait du scp ce coup-ci. 

Alors voici le retour de mes tests
Je peux maintenant bien choisir le mode sur mon thermostat salon : 
Par contre le mode chauffer passe le thermostat en mode Economie un instant et quelques secondes plus tard bien en mode confort. 
Le mode Refroidir passe en mode économie.
Le mode auto en mode auto :-) 

Je peux interagir avec les récepteurs des chauffages que lorsque je suis en mode Auto. Par exemple je passe le thermostat Salon en mode Auto. Les radiateurs se mettent dans le mode définit dans la programmation. Je peux forcer l'extinction d'un radiateur via le bouton on/off du récepteurs. Ca l'éteint ça ne le met pas en mode Economie. 
Cela n'est pas possible dans les autres modes, l'appui sur un récepteur ne fait rien. 
Cela fait comme sur l'application Tahoma, on dirait un bug somfy pour le coup car je trouve ça étrange que ça marche que dans le mode auto...  Je suis bien tenté de reset un récepteur pour voir car j'avais entendu parlé de ce bug et c'était sensé être réglé. 

Normalement l'appuie sur un bouton de récepteur On = Confort / Off = Economie c'est bien ça d'après le tableau si j'ai bien interprété ?

Pour la température j'ai bien compris que ce n'était pas faisable j'ai testé pour voir ça met ne répond pas, mais je peux quand même continuer mes interactions avec le thermostat pour info :)

Sinon petite question, il n'est pas possible de merger le bouton à gauche où il y a la température avec le bouton à droite ou je contrôle les modes du thermostat ? c'est forcément 2 boutons distinct ? 
![img_c093ba298ce7-1](https://user-images.githubusercontent.com/32174046/30782628-f37cd13a-a135-11e7-99e3-b5c3f7f01086.jpeg)

**Comment by nanoupi42** [comment]
Par contre, pour le chauffage au sol je ne peux plus utiliser la commande éteindre home bridge plante : 
/usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:89
        	cmdName = commands[0].name;
        	                     ^

TypeError: Cannot read property 'name' of undefined
    at Object.executeCommand (/usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:89:31)
    at Object.setHeatingCooling (/usr/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:173:14)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at Characteristic.setValue (/usr/lib/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:812:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:757:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)

**Comment by dubocr** [comment]
Pour le passage en mode confort, tu peux essayer de modifier l'ordre des lignes 130 à 132 du fichier HeatingSystem.js pour arriver à ça : 
```
commands.push(new Command('setOnOff', ['on']));
commands.push(new Command('setSetPointMode', ['comfort']));
commands.push(new Command('setActiveMode', ['manu']));
```
> Je peux forcer l'extinction d'un radiateur via le bouton on/off du récepteurs. Ca l'éteint ça ne le met pas en mode Economie.
Physiquement sur le radiateur c'est ça ?

> Normalement l'appuie sur un bouton de récepteur On = Confort / Off = Economie c'est bien ça d'après le tableau si j'ai bien interprété ?
C'est bien ça, et effectivement c'est normal que cela ne fonctionne qu'en mode Auto car le comportement est le même que sur TaHoma. A voir effectivement si c'est un bug chez eux.

Pour la T°, effectivement il n'y à rien d'associé derrière donc l'action reste sans effet. Malheureusement le thermostat est explicitement dissocié dans TaHoma (tout comme dans l'appli TaHoma où il apparait sous 2 icônes) voici de nouveaux fichiers pour essayer une manip afin de faire apparaitre la T° sur le thermostat (fichier index.js à la racine du dossier).
[TaHoma.zip](https://github.com/dubocr/homebridge-tahoma/files/1327347/TaHoma.zip)


Il faudra également ajouter un paramètre dans le fichier config : 
`"exclude": ["Etage"],`

Ces fichiers corrigent également le problème de plantage du chauffage au sol.

**Comment by nanoupi42** [comment]
Mon retour : 
Le "exclude": ["Etages"], fait bien disparaitre le bouton avec la température par contre le merge des 2 ne semble pas fonctionner : 
![img_c3306f99adbe-1](https://user-images.githubusercontent.com/32174046/30783480-de75669a-a143-11e7-8e98-d519474600a0.jpeg)

Lorsque je clique sur Chauffer sur le thermostat salon maintenant ça fait Economie>Confort>Economie et ça reste en éco.

Pour le chauffage au sol ça fait une autre erreur lorsque j'essaye de l'éteindre : 
[2017-9-24 16:16:44] [Tahoma] Error 400 Action is empty (FIELD_NOT_SET)

**Comment by dubocr** [comment]
Cela devrait être mieux avec cette version : 
[TaHoma.zip](https://github.com/dubocr/homebridge-tahoma/files/1327474/TaHoma.zip)

**Comment by nanoupi42** [comment]
Merci, plus de plantage pour le chauffage au sol :-)
Par contre je vois bien le merged au lancement de homebridge "Device Etages merged with Etages-1" mais pas de température affichée, c'est n'est peut être pas possible : 

![img_feba7894f083-1](https://user-images.githubusercontent.com/32174046/30784689-7ef24e60-a15a-11e7-80ad-7aad5e9cd602.jpeg)

Par ailleurs je n'ai plus la température sur le plancher chauffant : 
![img_73f0e85f9f34-1](https://user-images.githubusercontent.com/32174046/30784686-78e378f0-a15a-11e7-9d27-ea5e8af6e4c4.jpeg)

**Comment by dubocr** [comment]
Oui je viens de voir un souci pour obtenir la T°, d'ailleurs celle du plancher chauffant devait être incohérente avant je pense ?
Peux tu essayer avec ce fichier (pas besoin de reprendre le index il est identique) : [TaHoma.zip](https://github.com/dubocr/homebridge-tahoma/files/1327480/TaHoma.zip)

**Comment by nanoupi42** [comment]
Ca marche pour le merge des deux boutons ! :-) 
![img_2ec7ac43f5cf-1](https://user-images.githubusercontent.com/32174046/30784845-374aece0-a15d-11e7-846c-b45e56e03b7f.jpeg)

Pour le chauffage au sol il me semble que la température était juste auparavant mais je n'en suis pas sûr, je n'avais pas vérifié, elle me paraissait cohérente en tout cas.

Là j'ai bien de nouveau la température sur le bouton mais il s'agit de la température du mode choisi et pas celle qui est affichée sur le thermostat.
Quand je passe en mode Eco 19° est affiché, quand je suis en confort 21°.
![1](https://user-images.githubusercontent.com/32174046/30784888-bb044838-a15d-11e7-9037-d4a80cadc1da.png)
![2](https://user-images.githubusercontent.com/32174046/30784889-bb236d12-a15d-11e7-90c5-9f043f2df93d.png)

**Comment by dubocr** [comment]
Est-ce que le comportement est différent avec cette version : ?
[HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1327508/HeatingSystem.txt)

**Comment by dubocr** [comment]
Si ce n'est pas mieux, peux-tu reaccéder à la page d'envoi de [config](http://home.dubocr.fr/tools/setup) car il est possible qu'un paramètre soit apparut suite à la mise en marche du plancher chauffant qui était off auparavant.
merci

**Comment by dubocr** [comment]
J'anticipe car je ne vois que ça qui pourrait arriver à ce comportement : si ce n'est pas mieux avec le précédent fichier, celui-ci 
[HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1327529/HeatingSystem.txt)
 devrait afficher correctement les T° ambiantes (dans les bulles de couleur) et pour le plancher chauffant afficher la T° de consigne en gris selon le mode en cours (confort/eco).

Pour le thermostat fil pilote, au lieu de passer en "manuel" confort/éco avec les modes "chauffer"/"refroidir", il est possible de passer en "auto" confort/éco. Il s'agirait donc d'une dérogation jusqu'au prochain changement dans la programmation. Si tu préfères je peux changer sans problème.

**Comment by nanoupi42** [comment]
Je viens de tester les 2 nouveau HeatingSystem.js.
Je n'ai pas l'affichage de la température mais 0°. 
Je viens de me loguer sur la page mentionnée. 

Je veux bien essayer la dérogation si c'est pas trop galère à coder :-)

**Comment by dubocr** [comment]
J'ai modifier pour avoir le comportement dérogation.
Pour la T° le tout dernier fichier aurait du être bon : peux-tu me donner les valeur (en bas et dans la bulle) pour le plancher chauffant avec ce fichier au redémarrage puis après une modification de consigne.
[HeatingSystem.txt](https://github.com/dubocr/homebridge-tahoma/files/1327545/HeatingSystem.txt)

Merci

**Comment by nanoupi42** [comment]
Après redémarrage de HB : 
![img_221cf943deb8-1](https://user-images.githubusercontent.com/32174046/30785412-d3fd1668-a166-11e7-8acf-aa2c3c4166a5.jpeg)
Consigne chauffer : 
![img_24f1dfdeca05-1](https://user-images.githubusercontent.com/32174046/30785414-d429316c-a166-11e7-81cd-29a16e128108.jpeg)
Consigne Economie : 
![img_8993c31e7659-1](https://user-images.githubusercontent.com/32174046/30785413-d423c768-a166-11e7-962b-1c8068f553af.jpeg)

Pour la dérogation, si j'ai bien compris avec ce fichier, si je passe mon thermostat salon en mode auto, les actions réalisées sur les radiateurs bascule soit en Eco ou Confort c'est bien ça ?

**Comment by nanoupi42** [comment]
Update : dans mon fichier config.json je viens de faire un exclude de PlancherChauffant-1 qui était un bouton inutile pour moi et j'ai bien  la température maintenant :-) 
Je retest pour voir et je te dis

**Comment by dubocr** [comment]
La Tº ambiante de Etage-1 est aussi à 0 ?
Pour la dérogation c’est plutôt :
Si le Thermostat était en auto :
Passer en « chauffer » ou « refroidir » passe en confort/eco jusqu’au prochain changement d’état (dérogation par rapport a la programmation). Le thermostat ne passe ps en manuel
Si le Thermostat est en manuel (défini directement sur le produit) :
Même comportement que jusqu’à maintenant

**Comment by dubocr** [comment]
Ha OK c’était ma proposition d’exclure également le plancher chauffant du coup je pensais a tord que c’était déjà fait comme une Tº est apprut a un moment. C’est donc cohérent et c’est bien ce qu’il fallait faire.

**Comment by nanoupi42** [comment]
Désolé je ne l'avais pas exclu non et je confirme qu'après exclusion ça fonctionne :-) 

Exemple quand je suis en Automatique : 
![sans titre](https://user-images.githubusercontent.com/32174046/30785609-a65f32d8-a169-11e7-9ea0-cb425265fdc5.png)

Pour la dérogation ça marche nickel !! 
On est d'accord qu'il n'est pas possible lorsqu'on est en confort par exemple d'interagir avec les récepteurs pour forcer l'extinction d'un radiateur par exemple tout en laissant les autres en confort par exemple ?

Sinon c'est top ça marche nickel, encore une fois un grand merci !!

**Comment by dubocr** [comment]
Parfait 👍.
Pour ta question, peux-tu me préciser :
« Lorsqu’on est en confort » : En confort auto ou manuel ?
« Forcer l’extinction » : Arret complet ou juste ‘eco’ ?
« Un radiateur » : Un radiateur unique ou une zone ?

Ce que je peux déjà dire :
Il n’est possible d’agir que sur une zone au maximum. En confort/eco, peut-être off mais pas sur (à tester)
Actuellement avec les switch, il est possible de faire confort/eco (a priori que lorsque le thermostat est en mode auto) sur une des zones. Ce n’est pas cela dont tu parles ? Peut-être que les switch ne fonctionnent pas ce qui fait que je ne comprends pas la question ?

**Comment by nanoupi42** [comment]
Je voulais dire : 
Lorsqu'on est en confort manuel est-ce qu'on peut arrêter complètement un seul radiateur ?
J'ai tenté via le commutateur d'un radiateur mais ça ne fait rien. 
S'il était possible de mettre en mode Eco avec le commutateur lorsqu'on en est mode Confort manuel ça pourrait être intéressant aussi.
Les commutateurs ne fonctionnent qu'avec le mode Auto du Thermostat effectivement. Mais comme je te disais c'est également le cas avec l'app tahoma donc je me demande si c'est pas "voulu" par Somfy.

**Comment by dubocr** [comment]
D’accord, non effectivement si ça ne marche pas avec le commutateur c’est que c’est bien une limitation (technique ou voulue) par somfy. En tout cas le fait qu’ils aient grisé le changement de mode lorsqu’on est en manuel correspondant bien au fait qu’il ne se passe rien avec le commutateur chauffage sur homekit (ils ont grisé car de toute façon ca ne fonctionne pas)
Tu peux essayer de voir si l’arrêt fonctionne en remplaçant ‘eco’ par ‘off’ ligne 198.
J’avoue que cette restriction est assez étrange. Tu peux aussi essayer de supprimer complètement de tahoma le thermostat et les radiateurs puis de les rajouter ce qui actualisera la configuration interne au cas où elle ait évolué suite a une correction.

**Comment by nanoupi42** [comment]
Hello,
J'utilise tous les jours ton plugin c'est un réel bonheur :-) 

Petite question, est-ce possible pour moi de modifier la température qui s'affiche en dessous de la bulle (cf photo) ? J'ai tenté de voir cela dans heatingsystem.js mais je n'ai pas trouvé :( 

Comme tu peux le voir dans la photo quand je suis en mode Clim (mode éco en fait) il me dit que la température va descendre à 10°. Je voulais modifier cela par la valeur réelle de mon mode éco qui est de 19° : 
![img_289c9e264729-1](https://user-images.githubusercontent.com/32174046/33397792-0d72df1c-d54d-11e7-8630-6840cf37efe3.jpeg)
Cela concert le T-Salon

Je n'ai pas le problème pour le plancher chauffant, j'ai bien la valeur de l'éco : 
![img_6406dbfe3617-1](https://user-images.githubusercontent.com/32174046/33397864-4b962bdc-d54d-11e7-9137-0f90fbb75db7.jpeg)

Merci encore !!

**Comment by dubocr** [comment]
Hello,

On est daccord qu'il s'agit des chauffages commandés en fil pilote. N'ayant pas de contrôle de la température centralisé mais uniquement sur chaque chauffage la valeur n'est pas connue de TaHoma. Si c'est bien ça et que tu souhaites fixer "manuellement" une valeur dans le code pour ce soit cohérent avec ton paramètrage tu peux ajouter ce code 
`this.targetState.updateValue(19);`
après ce bloc de code (après la ligne 31)
```
this.targetState = service.getCharacteristic(Characteristic.TargetTemperature)
this.targetState.on('set', this.setTemperature.bind(this));
```

10 est la valeur min et par défaut de la caractéristique "TargetTemperature". Comme il n'y a pas de T° de consigne pour ce device dans TaHoma elle reste à cette valeur par défaut.

**Comment by nanoupi42** [comment]
Hello,
Nickel c'est exactement ça, je voulais mettre la température à la main juste pour que ce soit bon, niveau "affichage" :-) 

Ça fonctionne nickel ! 

Merci encore !
