### ISSUE TITLE
BUG Merge with Zone Control

### ISSUE THREAD

**Issue by photos13x** [dubocr/homebridge-tahoma#120]
Bonjour,

Je rencontre ce problème depuis le redémarrage de la Tahoma et du Raspberry cette nuit :

Device Chambre T° merged with Zone Control
/usr/local/lib/node_modules/homebridge-tahoma/accessories/HeatingSystem.js:103
                        zone.merge(device);

J'ai donc mis à jour le plugin Homebridge, mais rien n'y fait.

Pouvez vous m'aider ?

Merci d'avance

**Comment by dubocr** [comment]
Bonjour,

Avez-vous le reste des logs avec la dernière version du plugin svp.

Merci d'avance.
