### ISSUE TITLE
Somfy Sensors are not available as sensors in Homekit

### ISSUE THREAD

**Issue by maschbaer** [dubocr/homebridge-tahoma#121]
Hello,
Thanks for the great plug in. We love it to control your Somfy stuff by voice.

Now I wanted to overtake some if-thens from the Somfy app to the automation of Homekit.
However, when I want to use my Somfy temperature and light sensors these do not appear within the sensors tap (fire alarms show up only).
In the general overview these are visible and show their actual measurement.

What do I need to change to get access to these sensors for automation?

Regards,
Jan
![6D2F3D30-0818-4B55-9CE3-067D0CA31C34](https://user-images.githubusercontent.com/56022085/65949238-169bf100-e43c-11e9-8f99-f57f2ddbd037.jpeg)

**Comment by dubocr** [comment]
Hi Jan,

You have to use app like "Eve" (or maybe "shortcuts" with iOS 13) to automate with this kind of sensors. However, somfy sensor data are not reported in realtime in HomeKit so making automation in HomeKit with Somfy trigger is not the best choice at know. You might have to wait the official support of HomeKit by Somfy.

**Comment by maschbaer** [comment]
Just as a tip for others who have the same issue (reported above).

I found a workaround to a least make the Somfy Light Sensor useable (realtime and usable a trigger for automations) in Homekit:
1. Install [Homeassistant](https://www.home-assistant.io)
2. Install [Tahoma Plugin](https://www.home-assistant.io/integrations/tahoma/) for Homeassistant
3. Exclude all your other Somfy Devices except the light sensor
4. Install [Homekit Plugin](https://www.home-assistant.io/integrations/homekit/) 

However my Somfy temperature sensor does not show up in homeassistant this way, but there is a nother [Somfy API plugin](https://www.home-assistant.io/integrations/somfy) which I have not tried, but which seems to support also the temperature sensor 

Good Luck
Jan

**Comment by dubocr** [comment]
Hi looked at homeassistant plugin and it seems this is not realtime but pooling every 60 sec. So you could have the same behaviour with the following settings in homebridge tahoma plugin :

"alwaysPoll": true,
"pollingPeriod": 60

**Comment by maschbaer** [comment]
Unfortunately Somfy closed the access by the Homeassistant as described above some days ago.

With the changed poll etc. can the Temperature and Light Sensor now be used as a trigger in Homekit automations?

**Comment by maschbaer** [comment]
I tried this
"alwaysPoll": true,
"pollingPeriod": 60

The temperature-sensor works well, the temperature value turns immediately black. 
However, the light-sensor does not reliably update and usually stays grey, which makes it unusable in Homekit.

Marry Christmas
Jan

**Comment by SanderBaron** [comment]
Hi is there are work around for this? Everything is working perfect on my HomeBridge but only the Somfy Sunlight sensors can't be used as a sensor in a sensor based rule, they simply don't show up.
Thanks, Sander

**Comment by maschbaer** [comment]
Hey Sander,
the only way I found to get the Somfy light sensor into Homekit so that it can used for automations is via Homeassistant.
However, I noticed that sometimes Homebridge and Homeassistant get into conflict when both accessing Somfy. That is why I lost the Light Sensor in Homekit twice and with it all automations, scenes etc.

I switched to a Light sensor from Homematic which actually is much cheaper and works better. However, I connected it via Homeassistant to Homekit.

Jan

**Comment by SanderBaron** [comment]
Thanks! It is really frustration Somfy doesn’t keep word for the HomeKit support… 
I’m I correct that the Homematic sensor needs an extra bridge? 
Also found that Hue has native homekit supported motion and light sensors, might try these since I have Hue up und running.

Thanks, Sander
