### ISSUE TITLE
Chauffage ou clim 

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#123]
Bonjour, je viens de rallumer les chauffages, et je viens de voir dans Maison, que la gestion du chauffage à changé depuis iOS 13 j'imagine.
Quand le chauffage est en mode confort sur tahoma, çà l'indique en clim à 19°c. Si je passe en ECO sur Tahoma, çà reste en clim mais à 17°c.
![Capture d’écran 2019-10-19 à 14 52 52](https://user-images.githubusercontent.com/49283285/67145421-c6b58a80-f281-11e9-9252-be8bcd6748fb.png)

Si je passe en chauffage sur maison çà passe bien en confort sur tahome, mais l'icône reste en bleu et indique clim, et si je passe en clim sur maison, çà passe en eco sur tahoma.
![Capture d’écran 2019-10-19 à 15 14 58](https://user-images.githubusercontent.com/49283285/67145635-48f27e80-f283-11e9-9b6b-60dacff6cbd1.png)

![Capture d’écran 2019-10-19 à 14 56 02](https://user-images.githubusercontent.com/49283285/67145472-30ce2f80-f282-11e9-862b-c7a98345df03.png)

Et si je joue avec la température ( qui ne me sert pas à grand chose ) çà marque sans réponse.

Je penses plus à un problème d'affichage du mode qu'à autre chose.

**Comment by Tontonpat** [comment]
Autre chose, si c’est en confort sur Tahoma et que j’ouvre la commande ( qui affiche clim 19°c ), ça passe en eco sur Tahoma..
En résumé, j’ai l’impression que la température indique le mode: 17 pour eco et 19 pour confort. Et que par défaut c’est toujours en clim dans Maison

**Comment by Tontonpat** [comment]
Bonjour Romain, J'ai tenter une ré-installation propre du homebridge Tahoma, sans succès.
Je viens de voir lors de l'install un message : Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-tahoma' since we already loaded the same plugin from '/homebridge/node_modules/homebridge-tahoma'.
Je découvre également un nouveau dossier "node_modules" que je n'avais pas lors de la première installation.
![Capture d’écran 2019-10-22 à 15 28 48](https://user-images.githubusercontent.com/49283285/67290654-b64f1b00-f4e0-11e9-85d9-442df57f1295.png)

**Comment by Tontonpat** [comment]
Bonjour Romain, as tu jeté un œil à mon problème? Merci

**Comment by dubocr** [comment]
Bonjour Tontonpat,

Désolé pour l'absence.

Si tu souhaites revenir à un switch sous Homekit, tu devrais pouvoir avec la configuration suivante (en mettant à jour le plugin dans sa dernière version) :
"forceType": { "AtlanticElectricalHeater": "Switch" }

Pour la partie Thermostat, Il y avait effectivement un conflit avec d'autre type de chauffage. C'est corrigé sur la dernière version. Par contre je pense qu'il y à un soucis sur Homekit qui fait envoyer la commande de l'état courant quand on ouvre le widget. Quand on change de mode ensuite la nouvelle commande est envoyée également.

**Comment by Tontonpat** [comment]
Merci pour ta réponse, et ne sois pas désolé. Je pensais que tu avais laissé tomber. 
Je ne souhaite pas revenir à un switch.
Pour la partie thermostat, çà à l'air d'être bon. Le seul truc, c'est si tu change la température çà indique sans réponse.
Quand as tu fait la mise jour?
J'ai redémarré homebridge en début de semaine en espérant que tu ai fait la correction, mais sans succès.
Merci encore pour ton temps

**Comment by Tontonpat** [comment]
Bonjour Romain, les modes fonctionnent parfaitement!! Est ce possible d’enlever la notion de température, qui a priori ne sert a pas grand chose ( en tout cas chez moi )?

**Comment by Tontonpat** [comment]
A voir si le « mappage » peut aider. Dans mon cas si je change la température ça ne fait rien côté Tahoma mais ça indique sans réponse sur home pendant un moment.

**Comment by dubocr** [comment]
J'ai ajouté le mapping. Cela permettra toujours d'avoir un comportement cohérent en demandant par ex à Siri d'augmenter la T° (passage en confort)

**Comment by Tontonpat** [comment]
Parfait! Merci encore

**Comment by Tontonpat** [comment]
Bonjour Romain, j’ai une automatisation avec l’ouverture de mes fenêtres qui coupe le chauffage. La commande est envoyée deux fois au chauffage dans la même seconde. Ce qui étrange, c’est qu’il envoi l’état actuel (eco) puis  l’état demandé (off) en même temps. Du coup, il y a une chance sur deux pour que la bonne commande soit activée. Je me suis connecté sur ton lien.

**Comment by dubocr** [comment]
Bonsoir Totonpat,

Effectivement le fait d'avoir ajouté le changement de mode sur la T° provoque 2 envoi pour la même commande car Homekit envoi 1 changement de mode et 1 T°. 
J'ai limité le changement de mode sur un changement de T° que si elle est > 0°C. Cela devrait être bon. J'ai fait la mise à jour si tu peux mettre à jour ton plugin et me confirmer que cela suffit.

Merci

**Comment by dubocr** [comment]
Mieux, j'ai enfin réussi à supprimer la T°.

**Comment by Tontonpat** [comment]
Bonjour Romain, ça fonctionne parfaitement. Il n’y a plus qu’une seule commande envoyée.
Merci beaucoup, tu es au top!!
