### ISSUE TITLE
About to Buy Somfy Roller Blinds

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#124]
If I use this plug in, will i see it exposed as a blind in the homekit app? Will this only allow open and close or will it also allow me to set 45% or 65% as examples?

Thanks in advance

**Comment by primal79** [comment]
It will allow to set any percentage and will act appropriately.

**Comment by dubocr** [comment]
Hi,
If you buy IO roller blinds, you will be able to set exact position between 0 to 100%. RTS blinds will only allow open/close and "my" position.
primal79, can you log there : https://dev.duboc.pro/tools/setup as I'll be able to check how to improve behaviour for dimmer to obtain a full range.

Thanks

**Comment by morkjt** [comment]
Hi - can you help me with that topic? I got RTS blinds, I really hoped by using your great work, I could tie it into HomeKit and somehow create scenes based on percentage opens.  I'm suspecting not possible from your comment above.  I've logged my setup in the URL as provided above.

**Comment by morkjt** [comment]
If anyone is interested, I've done a hack on this to enable RTS blinds to be moved to any position using a combination of open/close and my commands based on a timer - meaning in your 'Home' app you can set  any % position open for the RTS blind and it will move to an approximation of that position!  It's a nasty hack but happy to share should someone want it.  Thanks @dubocr for all the work enabling this!

**Comment by adavison007** [comment]
> If anyone is interested, I've done a hack on this to enable RTS blinds to be moved to any position using a combination of open/close and my commands based on a timer - meaning in your 'Home' app you can set any % position open for the RTS blind and it will move to an approximation of that position! It's a nasty hack but happy to share should someone want it. Thanks @dubocr for all the work enabling this!

@morkjt please share

**Comment by iOSGeekster** [comment]
> If anyone is interested, I've done a hack on this to enable RTS blinds to be moved to any position using a combination of open/close and my commands based on a timer - meaning in your 'Home' app you can set  any % position open for the RTS blind and it will move to an approximation of that position!  It's a nasty hack but happy to share should someone want it.  Thanks @dubocr for all the work enabling this!

Hi! I would love to check it out

**Comment by adavison007** [comment]
> If anyone is interested, I've done a hack on this to enable RTS blinds to be moved to any position using a combination of open/close and my commands based on a timer - meaning in your 'Home' app you can set any % position open for the RTS blind and it will move to an approximation of that position! It's a nasty hack but happy to share should someone want it. Thanks @dubocr for all the work enabling this!



> > If anyone is interested, I've done a hack on this to enable RTS blinds to be moved to any position using a combination of open/close and my commands based on a timer - meaning in your 'Home' app you can set  any % position open for the RTS blind and it will move to an approximation of that position!  It's a nasty hack but happy to share should someone want it.  Thanks @dubocr for all the work enabling this!
> 
> @morkjt I would love to check it out

@morkjt I would love this hack :)

**Comment by morkjt** [comment]
I dont really know how to share what I've done - wouldn't know how to upload to git.  I have mucked with one fille within the package - WindowCovering.js - so far every update, just slotting that change in has worked - using this you will get a good ability to set a % on each blind.

[WindowCovering.zip](https://github.com/dubocr/homebridge-tahoma/files/5390378/WindowCovering.zip)

**Comment by iOSGeekster** [comment]
> I dont really know how to share what I've done - wouldn't know how to upload to git. I have mucked with one fille within the package - WindowCovering.js - so far every update, just slotting that change in has worked - using this you will get a good ability to set a % on each blind.
> 
> [WindowCovering.zip](https://github.com/dubocr/homebridge-tahoma/files/5390378/WindowCovering.zip)

Thanks, I'll check it out

**Comment by iOSGeekster** [comment]
Seems to work 👍. I'll just have to modify it a bit as my blinds have different sizes. But thanks for sharing. Pretty cool.

**Comment by morkjt** [comment]
Yes. There are some defines somewhere about timing. I based it on how Long it takes to shut a blind. 

Mark Turner
mark.turner@morks.net
07957 344103

**Comment by iOSGeekster** [comment]
> Yes. There are some defines somewhere about timing. I based it on how Long it takes to shut a blind. Mark Turner mark.turner@morks.net 07957 344103
> […](#)

Yes, I got it working on one of my smaller blinds by altering it.. So I guess I could switch on the device name, and have different shutting times 👍

**Comment by adavison007** [comment]
> > Yes. There are some defines somewhere about timing. I based it on how Long it takes to shut a blind. Mark Turner [mark.turner@morks.net](mailto:mark.turner@morks.net) 07957 344103
> > […](#)
> 
> Yes, I got it working on one of my smaller blinds by altering it.. So I guess I could switch on the device name, and have different shutting times 👍

@iOSGeekster @morkjt Thanks for sharing guys... Sorry I am being a bit thick here... where do you edit this file?

**Comment by adavison007** [comment]
> > I dont really know how to share what I've done - wouldn't know how to upload to git. I have mucked with one fille within the package - WindowCovering.js - so far every update, just slotting that change in has worked - using this you will get a good ability to set a % on each blind.
> > [WindowCovering.zip](https://github.com/dubocr/homebridge-tahoma/files/5390378/WindowCovering.zip)
> 
> Thanks, I'll check it out

@dubocr Can you add this code for blind percentage into your code please?

**Comment by Foseti** [comment]
Hi all 
i hve the same issues with RTS Blinds downloaded the WindowCovering. zip from morkjt, thanks for that. but did not know where to start to implement the .js in homebridge. 
Maybe someone can give me a hint, with short example, where to start to insert the code? Sorry very new to that topic. thanks in advanced.

**Comment by morkjt** [comment]
Install the homebridge-tahoma  plugin then replace WindowCovering.js with the hacked file; mine is located in /usr/local/lib/node-modules/homebridge-tahoma/services 

>

**Comment by Foseti** [comment]
@morkjt so many thanks works great after adjusting the timings!

**Comment by dubocr** [comment]
Will be implemented in latest release with config param
