### ISSUE TITLE
Bad credentials after reboot

### ISSUE THREAD

**Issue by mikeleijs** [dubocr/homebridge-tahoma#125]
I’ve rebooted my raspberry pi and homebridge failed on me. Checked it and it hangs on Tahoma having bad credentials. They weren’t changed so that couldn’t be the problem. To be sure i changed my password in tahoma, and also in the config.json, but still the same error. Is there an easy way to fix this? Evert password i generate and modify in the config is echoing bad credentials. Regards.

**Comment by renajohn** [comment]
Same for me. The problem is at Somfy's end. They probably blacklisted your home IP. I don't know how to prevent that.

To verify, try to login on the tahoma website, I bet it will say "bad credentials":
https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/
