### ISSUE TITLE
Transfer all Enocean states to Homekit?

### ISSUE THREAD

**Issue by mahuch** [dubocr/homebridge-tahoma#127]
Hi,

I use Hoppe handles, which are integrated into TaHoma via Enocean.

https://www.hoppe.com/de/de/fenstergriffe/hoppe-innovationen/secusignal

In Tahoma I have the states: "Open", "Closed" and "Tilted".

In HomeKit there are only the status "open" and "closed".

Is it possible to transfer all states to Homekit?

Thank you and please continue to develop!
Martin

**Comment by dubocr** [comment]
Hi,

Unfortunately homekit as only 2 states for "contact sensor". So I can't map the tilted state to any homekit third states at moment.
