### ISSUE TITLE
Pilotage volets battant et portail

### ISSUE THREAD

**Issue by raphaelpregnon** [dubocr/homebridge-tahoma#128]
Bonjour, J'ai mis en place sur mon NAS synology homebridge  via Docker avec votre plugin et cela fonctionne plutôt bien pour les volets roulants, prises, capteurs, Alarme. Mais je n'arrive pas à utilise mes volets battants et portail.

Dans le journal, il est inscrit cela:

_[11/5/2019, 9:07:11 PM] [Tahoma] [Bureau] type: SwingingShutter > UpDownSwingingShutter, protocol: rts 
[11/5/2019, 9:07:11 PM] [Tahoma] No definition found for SwingingShutter > UpDownSwingingShutter in mapping.json_

Apparement, il ne connait pas SwingingShutter donc j'ai ajouté dans le fichier config.json la ligne suivante:

_"forceType": {
	"Bureau": "WindowCovering",
	"Porte Salon": "WindowCovering"
	}_
Mais il ne remplace pas par un volet roulant, je pense que les volants battant sont piloté comme les roulants car c'est le protocole RTS. 

Ensuite dans le fichier "mapping.json", j'ai ajouté l'article SwingingShutter comme un WindowCovering et là j'ai vu apparaitre tous mes volets roulant dans HomeKit, mais impossible de fermer ou ouvrir les volets.
Je n'ai pas essayé mon portail mais il est aussi RTS donc j'imagine que c'est le même soucis.

En vous remerciant pour votre aide, bien cordialement.

**Comment by dubocr** [comment]
Bonjour Raphael,

Peux tu te connecter sur la page https://dev.duboc.pro/tools/setup afin que j'examine le composant SwingingShutter pour voir si il serait 100% compatible avec le type volets.

Merci d'avance.

**Comment by dubocr** [comment]
J'ai trouvé ta configuration. Je fais l'ajout de ce type de device cela devrait être OK en mettant à jour le plugin.
