### ISSUE TITLE
No response from Smoove Uno A/M io

### ISSUE THREAD

**Issue by imsturmdernacht** [dubocr/homebridge-tahoma#13]
Dear developer and users,

at first a big thank you for developing this plugin.

I use Tahoma with Smoove Uno A / M io roller shutter controls for shutters without io. Smoove Uno A / M io does not know in which position the roller shutter has stopped. But Tahoma knows the last direction in which the roller shutter moved. My problem is the following. In the Home app the roller shutters are always closed. The roller shutters can only be raised. After the roller shutters have been raised, the Home app still shows status closed. Is there a way for asking Tahoma which direction was last approached? To use this information for open / closed status in the home app?

Esszimmer (RollerShutter,PositionableRollerShutterUno)
**********************************************************
Commands:
close
delayedStopIdentify (1 paramètres)
down
getName
identify
my
open
refreshMemorized1Position
setClosure (1 paramètres)
setDeployment (1 paramètres)
setMemorized1Position (1 paramètres)
setName (1 paramètres)
setPosition (1 paramètres)
setSecuredPosition (1 paramètres)
startIdentify
stopIdentify
up
wink (1 paramètres)

States:
core:NameState
core:PriorityLockTimerState
core:TargetClosureState
core:StatusState
core:RSSILevelState

Regards, Oli

**Comment by dubocr** [comment]
Dear Oli,

Could you please browse [this page](http://home.dubocr.fr/tools/setup) and login to let me see if I can retrieve this information.
However, Home must shows "open" after the roller shutters have been raised.
Did you raised it manually (physically on the product) ?

Best,
Romain

**Comment by imsturmdernacht** [comment]
Dear Roman,

I just updated my first comment with this informations. I raised the shutters with the Tahoma App on my iPhone. The Tahoma App shows the last direction the shutters moved.

Regards,
Oli

**Comment by dubocr** [comment]
Mmm yes "core:TargetClosureState" seem to be a good candidate. Can you operate one blind and browse the page again to confirm the value change from "0" to "100" (or other).

Thanks

**Comment by dubocr** [comment]
Could you please try to modify line 111 of your RollerShutter.js file from
`if (name == State.STATE_CLOSURE) {`
to
`if (name == State.STATE_CLOSURE || name == 'core:TargetClosureState') {`

**Comment by imsturmdernacht** [comment]
Dear Roman,

thank you very very much. Now it works perfectly. Open, close and current position are correct in the Home app. I'm very very happy.

A lot of thanks.... 

Regards,
Oli

**Comment by dubocr** [comment]
Great, that's perfect. You're welcome. It's a pleasure to teach Siri in which position are your blinds ;-).

Enjoy,
Romain
