### ISSUE TITLE
Improvement: Bind garage door to blind to bypass faceID check

### ISSUE THREAD

**Issue by artik** [dubocr/homebridge-tahoma#131]
I saw many people complaining about automations regarding garage door, myself included. As Apple ask for a face ID check before opening a garage door, I was thinking it could be an amazing option to fake Homekit using Homebridge regarding this check.

Many users have a garage door that don't need this security face ID check to be open, as it's not an inside house access for example. And it would be really good to have your garage opening with an automation when you arrive home with any action from the user.

Romain, do you think this could be added? I'm sure it will a highly appreciated feature.

**Comment by dubocr** [comment]
Did you try this config

```
forceType: {
"Garage": "WindowCovering"
}
```

Tis must force your door named "Garage" to be displayed as roller shutter.

**Comment by artik** [comment]
I tried :

```
            "forceType": {
                "Office main": "WindowCovering"
            },
```

the garage is now displayed as a window (Yeah!!) But opening/closing don't work. The logs:

```
[12/3/2019, 7:35:02 PM] [My TaHoma Box] [Office main] setClosure[100]
[12/3/2019, 7:35:02 PM] [My TaHoma Box] Error 400 Managed action group is invalid : No such command : setClosure on device io://0808-3777-8983/16008733 (io:CyclicSlidingGarageOpenerIOComponent) (UNSPECIFIED_ERROR)
```

**Comment by dubocr** [comment]
Di you try with latest release ?

**Comment by artik** [comment]
Almost there!

Garage door is properly show as window. When I click on it, "opening" status appears, but garage door doesn't open. When I click again, "closed" status appears straight away, and now my garage door is opening. We're close to the perfect result!

**Comment by dubocr** [comment]
Ok je m'attendait à un comportement cyclic. En open/close je viens de corriger ça devrait être bon.

**Comment by artik** [comment]
Ca ouvre! Seul detail, le status n'st plus envoyé du tout apres une ouverture. Le garage s'est ouvert, puis refermé, et tout reste en "opening". Il y a possibilité de récupérer au moins l'état "closed" quand la porte s'est refermée ? (pour ne pas laisser l'état "opening" charger dans le vide sans fin).

```
[12/11/2019, 8:32:16 PM] [My TaHoma Box] [Portal home] open[]
[12/11/2019, 8:32:51 PM] [My TaHoma Box] [Portal home] open COMPLETED
```

Puis plus rien ;)

**Comment by dubocr** [comment]
Peux-tu te logguer avec ce compte sur https://dev.duboc.pro/tools/setup pour que je jette un oeil.

Merci

**Comment by artik** [comment]
C'est fait: meme nom de git, et nickaardo en login

**Comment by dubocr** [comment]
Ca devrait être mieux dans la dernière version. Désolé pour le délai.
