### ISSUE TITLE
Ouverture/fermeture volets inversées depuis dernière mise à jour

### ISSUE THREAD

**Issue by koupus** [dubocr/homebridge-tahoma#132]
Bonjour Romain,

merci beaucoup pour la mise à jour du plugin qui a résolu le problème de mon "issue" précédente.

Cependant et depuis celle ci, l' ouverture/fermeture de mes volets depuis l'application Maison est inversée...
Je me suis connecté au dev et ci dessous un extrait du log:

[12/2/2019, 9:37:59 AM] [Tahoma] [Salon Baie] setClosure[0]
[12/2/2019, 9:38:21 AM] [Tahoma] [Salon Baie] setClosure COMPLETED
[12/2/2019, 9:40:23 AM] [Tahoma] [Salon Baie] setClosure[100]
[12/2/2019, 9:40:52 AM] [Tahoma] [Salon Baie] setClosure COMPLETED

En gros désormais, quand setClosure = 0 ça ouvre le volet là ou avant ça le fermait.... et vice versa.

Une idée ?

++ Thomas

**Comment by artik** [comment]
Salut Thomas, tu peux poster les logs du nom de tes fenetres ?
Jette aussi un oeil a ce thread: https://github.com/dubocr/homebridge-tahoma/issues/40#issuecomment-560109256

**Comment by dubocr** [comment]
Bonsoir,

Cela devrait être bon avec là 0.3.14.

**Comment by koupus** [comment]
C’est parfait et résolu! Merci Romain!
