### ISSUE TITLE
new radiator thermostats not work

### ISSUE THREAD

**Issue by Auraya83** [dubocr/homebridge-tahoma#134]
Good Morning. Somfy has been offering the new radiator thermostats since Monday. These are already displayed in IO broker, but you can not control them there yet. It would be great if you could activate the different modes in the radiator thermostats.

![iobrokerthermostat](https://user-images.githubusercontent.com/58505185/70124174-726d3b00-1674-11ea-81d6-7f825253e9a5.PNG)

**Comment by dubocr** [comment]
Hi,

can you please log here to get your config : https://dev.duboc.pro/tools/setup

**Comment by Auraya83** [comment]
I have already uploaded them

**Comment by dubocr** [comment]
Thank you,
Is that concerning your 6 : Thermostat Büro Thermostat WZ Thermostat Bad Thermostat Küche Thermostat Sz Thermostat Ez ?
I'll look at it to map good commands. Is the "states" already good ? Displayed temperatures
Also, can you exit derogation mode on one thermostat (via TaHoma) then relog to https://dev.duboc.pro/tools/setup.

Thanks

**Comment by Auraya83** [comment]
Yes it concerns the 6 mentioned thermostats. All Stats are good. The actually Temperature are shown in an extra Temperature Sensor . I have now given everyone a different status. As soon as the temperature on the thermostat is changed manually, it jumps into manual mode, I once tried to assign the Api. if you still need something, let me know. I hope it helps.

![thermostat2](https://user-images.githubusercontent.com/58505185/70265779-6c25ae80-179b-11ea-9ebb-733023626411.png)

**Comment by dubocr** [comment]
Hi,
I've push first run to implements your heaters. This will merge T° sensor into Thermostat and allow you to send commands. But there are missing point :
- Are you able to put the system in "auto"/"program" mode ? Can you do it and log again to the page as I can't find command for that.
Can you update the plugin and give me first feedback.

Thanks.

**Comment by Auraya83** [comment]
Hi, wow very fast. Thank you. 1st test is working. I see the temperature in dhe Thermostat and when i Change it it will be send to the thermostat. I have Set The Thermostat Büro & Küche in Programming mode. The Programming mode is the intern Kalender from the Thermostat. My Wish is that i can set it to the different Modes. When you need Anything write it to me ;)

Big Thanks for yor Support.

**Comment by dubocr** [comment]
Hi,
I've made a smal correction as the "auto" mode were not as I expected.
With the last release you will be able to :
- Set Thermostat in "auto" (auto mode in Homekit)
- Derogate to force comfort (heating mode in Homekit)
- Derogate to force eco (cooling mode in Homekit)
- Set to "away" mode (off mode in Homekit) => Not sure it will work as expected, you may try it and put your Thermostat in OFF mode via TaHoma then log to the page to let me see what is the good command
- Derogate to force T° (change T° in Homekit)

Let me know if something doesn't work as expected.

Have a nice day.

**Comment by Auraya83** [comment]
Wow thanks.
What i have testet: Settings to an custom temperature Works.
Setting to Mode away, comfort, eco works. 
Switch to Programming mode after derogate works.
all my wishes are fulfilled.
I have already send my config

**Comment by dubocr** [comment]
Thank you for using Homebridge TaHoma plugin.

Please follow these step to obtain better support :
1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)

Thank you.
