### ISSUE TITLE
Velux Windows operate the wrong way

### ISSUE THREAD

**Issue by newbeetle59** [dubocr/homebridge-tahoma#135]
Hi Romain, since a couple of days, I have a weird issue with my Velux roof windows (Connexoon):
Open / Close are completely messed up: they are closing when they should open and vice versa.
Please, Is it possible to check that ?
Thx

**Comment by dubocr** [comment]
Hi,

Did you try to update to last plugin release. As there were issues in 0.3.11 to 0.3.15 versions.
0.3.16 must fix it. Tell me if it's not the case.

**Comment by newbeetle59** [comment]
Hi Romain,

Yes, I’m running v0.3.16, I saw the issue for the first time yesterday (was running previous version at that time) as my Windows were opened instead of being closed (through automated process).  So according to your answer I just decided to restart Homebridge. It looks ok right now.

Thanks !

Amaury.

**Comment by dubocr** [comment]
Perfect, and sorry for this inconvenience.
