### ISSUE TITLE
Awning > AwningValance

### ISSUE THREAD

**Issue by Gr3yB34rd** [dubocr/homebridge-tahoma#136]
Hi,

Plugin is great, thank you for your efforts.
From reading other issues, i gathered there was an awning service. Right now my awning works like a window shutter, but as a result it always extends , when i open all my shutters. Or can i just force a type that homekit recognizes as Awning ?

BR

Matthias

**Comment by torandreroland** [comment]
I had the same problem (AwningValance device). I think I have fixed it with this pull request #140 .

**Comment by Gr3yB34rd** [comment]
Looks good , i will modify my local copy and do some testing tonight

**Comment by dubocr** [comment]
Hi,

Thank you so much. I'll integrate it in next release.

**Comment by torandreroland** [comment]
You're welcome. Hopefully it's the same issue as @Gr3yB34rd had.

I as well just want to say thank you, @dubocr, for your excellent plugin and hard work!

**Comment by dubocr** [comment]
Thank you too for your help guys.

**Comment by dubocr** [comment]
> I had the same problem (AwningValance device). I think I have fixed it with this pull request #140 .

Hi, @torandreroland, as you have AwningValance devices, I'll be interested in feedback about behaviour with latest release 2.1.6 if you plan to upgrade in future.

Thanks in advance.
