### ISSUE TITLE
Window sensors status not updated

### ISSUE THREAD

**Issue by stone79** [dubocr/homebridge-tahoma#137]
Hi there!

I am new to Homebridge and got it installed with HOOBS 3. I used the standard Tahoma plugin and everything works fine and I can control all roller shutter and lights. 

Not working are the window contacts. Means the status (open/closed) will not update, unless I reboot Homebridge. Can you walk me through how I need to adjust the plugin to get instant updates on the window sensors in Homekit?

Many thanks!

**Comment by dubocr** [comment]
Hi,

You can try to add this parameters to your config file but you'll never obtain a true realtime as TaHoma doesn't have push system to push state update :

```
"alwaysPoll": true,
"pollingPeriod": 60
```
