### ISSUE TITLE
Tahoma - Too many requests

### ISSUE THREAD

**Issue by realdannys** [dubocr/homebridge-tahoma#138]
Hi,

I'm getting the following issue a lot - it fills my error logs and sometimes it stops Homebridge starting for ages. Any idea why?

[12/8/2019, 10:26:08 PM] [Tahoma] Login fail: Too many requests, try again later : login with emailredacted
[12/8/2019, 10:26:08 PM] [Tahoma] Fail to retrieve accessories, retry in 60 sec...

**Comment by dubocr** [comment]
Hi,

Have you polling config enable in your config file ?

**Comment by realdannys** [comment]
I haven't no.

**Comment by nscheffer** [comment]
How do you enabled polling in the config file ?
I don't find it anywhere.

**Comment by iRonin** [comment]
@dubocr would it be possible to add configuration option to increase the retry time when login fail? The problem is that if there are too many requests the user has to wait lot longer than the standard 60s polling, which I think is also used for retries, causing the quota to stay in place.

**Comment by dubocr** [comment]
State polling improved in latests releases
