### ISSUE TITLE
WindowCovering with blindMode: true not closing properly

### ISSUE THREAD

**Issue by mman** [dubocr/homebridge-tahoma#141]
I have several Somfy Tahoma shades configured in ``blindMode: true``. Everything worked fine since couple of releases back (do not remember as I updated randomly today) and now when I invoke siri to close the shades, the following happens:

ACTUAL: Close the office shades: ``setClosureAndOrientation[100,0]``

The shades will go fully down (good) but then set their orientation to 0 which will cause them to remain horizontal and pass though max light. I think the expected is:

EXPECTED: Close the office shades: ``setClosureAndOrientation[100,100]``

P.S. Opening the shades and setting to given percentage working fine. Just closing is not setting the orientation to 100 but to 0.

**Comment by mman** [comment]
Probably related to #145

**Comment by mman** [comment]
Forgot to mention that Somfy pushed gateway update some time back in Oct/Nov 2019 and the problem might have started to appear after that.

**Comment by primal79** [comment]
@mman I experience the vary same issue with one of my shades set with 'blindMode' and I can confirm this appeared since Somfy Tahoma update.

**Comment by dubocr** [comment]
Hi,

Thank for your feedback. Should be fix in last release. Could your check please and tell me if not.

Thanks.

**Comment by mman** [comment]
Happy New Year @dubocr. Today just went to `npm update` and it still does not work properly. Using siri to "close" still invokes ``setClosureAndOrientation[100,0]`` whereas it should be ``setClosureAndOrientation[100,100]`` I belive. Also setting using Home app slider to 99% open closes sets the orientation to 100 instead of 1 and setting to 1% open sets the orientation to 1 instad of 99. 

Need more help or data here?

**Comment by dubocr** [comment]
Hi,

New updated in few minute, please update and try again. Thanks.

**Comment by mman** [comment]
0.3.30 seems to work great again, thanks :)

**Comment by dubocr** [comment]
Hi,

Starting 0.3.41, you will have to change your config for using blinds in "orientation mode".
Here is the new config

		"WindowCovering": {
			"blindMode": "orientation"
		}
