### ISSUE TITLE
Code Thermostat (Hitachi)

### ISSUE THREAD

**Issue by Seb0101** [dubocr/homebridge-tahoma#142]
Bsr Romain,
Comme je te l'écrivais le 11/11, j'ai trouvé une erreur qui faisait que l'état de mes clims n'était pas le bon. Mais tes dernières mises à jour n'en tiennent pas compte.
Il y a une erreur dans le fichier Thermostat.js : 'off' doit être écrit 'Off' à la ligne if(this.device.states['ovp:MainOperationState'] == 'off')...
Je n'avais pas fait de mise à jour depuis, j'ai corrigé le fichier à nouveau.
Bonne soirée.
Sébastien

**Comment by dubocr** [comment]
Bonsoir Sébastien,

Désolé j'ai du passé à côté. Ce sera bon pour la prochaine mise à jour.

Merci pour le rappel.
