### ISSUE TITLE
Blinds don't update their positions using io wall switch - by app they do

### ISSUE THREAD

**Issue by URBANsUNITED** [dubocr/homebridge-tahoma#143]
Hi Roman!

I am discovering a strange behaviour.
When pressing on my io wall switch, the blinds move to the desired position, BUT the status will not get updated.
Ex.

Press up on the switch, the blind fully opens to 100%
But Home app and others report the old position like 17% and never updates this.

When I do the same function using Home app or similar or Homebridge config-ui-x the position will be directly reported and corrected to the new value.

Shouldn’t the motors report their new position to the Tahoma box? Doesn’t matter from where the command came? Or is there a bug somewhere?

I really believe that this worked already some time ago, as I control the night light of my daughter with the position of the blinds. But now it doesn’t work. Discovered this with the combination of Xmas lights control in the windows…

My config:

```
   "platforms": [
        {
            "platform": "Tahoma",
            "name": "Tahoma",
            "user": "email@gmail.com",
            "password": "123456",
            "service": "TaHoma",
            "alwaysPoll": true,
            "pollingPeriod": 10,
            "WindowCovering": {
                "reverse": false,
                "blindMode": false
            }
        },
```

Tried instead of the polling method also refreshperiod! No difference

Thanks

URBANsUNITED

**Comment by dubocr** [comment]
Hi,

I think stare are not updated when command isn't coming from TaHoma box. As the switch act as local remote and the Blind is not a sensor so it don't reports its position outside a command request.
Polling period won't help as it only sync states between Homebridge and TaHoma (and TaHoma don't have a fresher state).
But polling period + refresh period will as refresh period as TaHoma box to refresh states of each devices (by requesting it). By default, refresh period is set to 30min. So normally, after 30min your state must be synced. Could you confirm ?

**Comment by URBANsUNITED** [comment]
Good morning and thanks for answering!

Unfortunately it doesn't work.

No refresh after 30 minutes, or in my case 30 seconds as I've modified the refreshperiod:

```
platforms": [
        {
            "platform": "Tahoma",
            "name": "Tahoma",
            "user": "email@gmail.com",
            "password": "password",
            "service": "TaHoma",
            "refreshPeriod": 30,
            "alwaysPoll": true,
            "pollingPeriod": 60,
            "WindowCovering": {
                "reverse": false,
                "blindMode": false
            }
        },

```

The lights stay off. Btw. tried with your lastest 0.3.23 version already

Best regards

URBANsUNITED

**Comment by dubocr** [comment]
Woh, 30 is too short. Your TaHoma box may not have the time to query each of your devices. And refreshPeriod should be higher than polling one. A refresh trigger lots of radio exchange. With a 30 sec config your home is continuously flooded of radio waves.

Could you check if the status is different in TaHoma app ?

**Comment by URBANsUNITED** [comment]
Ok! Changed the refreshperiod to 300

So, checked the behavior of the Tahoma app. I pressed on the io wall switch, the blind moved up and it stopped at fully open (100%), ca. 10 sec. later, the icon showed a fully open window.
I checked Home app, the window was still closed and it to ca 10 minutes to get the icon change. 
BUT there was no log entry of this action in the log file. 
So it looks like that the switch actions are completely happen without that Homekit recorgnize these actions.
But how got Tahoma App got the new status????

**Comment by dubocr** [comment]
alwaysPoll was tru during this last test ?
Can you try to load the page https://dev.duboc.pro/tools/setup when state is reported to Tahoma and not yet in Home app.
Before testing, please update plugin and add 
"debug":true in the plugin config

**Comment by URBANsUNITED** [comment]
Done!

> alwaysPoll was tru during this last test ?
Yes!

The Window I've changed was Madita. Stop done by the wall switch.
Home App reports now 56%

**Comment by dubocr** [comment]
Do you have homebridge logs ?
Tell me 
- when you press wall switch
- when you see the good status in Tahoma app
- when it appears in Home
compared to homebridge log timestamps
