### ISSUE TITLE
WindowCovering with blindMode: true uses wrong percentage for orientation

### ISSUE THREAD

**Issue by mman** [dubocr/homebridge-tahoma#145]
I have several Somfy Tahoma shades configured in blindMode: true. Everything worked fine since couple of releases back (do not remember as I updated randomly today) and now when I invoke siri to set shades to certain percentage or use the home app to do the same, the shades do the wrong thing.

Hey Siri Set Office Shades to 90% (90% open), it will do ``setClosure(100, 90)`` which will do 90% closed == 10% open.

Hey Siri Set Office Shades to 1% (1% open), it will do ``setClosure(100, 1)`` which will do 1% closed == 99% open.

This means that actual operation of setting the orientation is reversed.

If I remember correctly, this indeed worked well couple releases back and I guess it could be cause by update in ``homebridge-tahome`` code itself or because of the update that was pushed to Tahoma gateways some time back in Nov 2019.

**Comment by primal79** [comment]
@mman I experience the vary same issue with one of my shades set with 'blindMode' and I can confirm this appeared since Somfy Tahoma update.

**Comment by mman** [comment]
0.3.30 seems to work great again, thanks :)

**Comment by dubocr** [comment]
Hi,

Starting 0.3.41, you will have to change your config for using blinds in "orientation mode".
Here is the new config

		"WindowCovering": {
			"blindMode": "orientation"
		}
