### ISSUE TITLE
Mise en erreur suite à Automatisation et/ou scène pour volets roulants RTS

### ISSUE THREAD

**Issue by Alcor72** [dubocr/homebridge-tahoma#146]
Bonjour,

J'ai toujours le même problème de mise en erreur du sytème (obligation de redémarrer homebridge) suite a utilisation d'automatisation et/ou scène.

Je n'ai pas le problème en utilisant Siri (par exemple "dis siri ferme les volets roulants"), mais cela me génère le défaut ci-joint au bout du lancement de 2 ou 3 automatisations. 

![64565865-f73a0880-d354-11e9-883b-975fc3fce55c](https://user-images.githubusercontent.com/45826817/71175556-26231d00-2268-11ea-91d4-aebf2b341919.jpg)

**Comment by dubocr** [comment]
Bonjour,

Avez-vous mis à jour le plugin ? Normalement après l'erreur il devrait y avoir un log d'enregistrement d'un nouveau listener ce qui n'est pas le cas. Dans tout les cas pouvez-vous mettre à jour avec la dernière version j'ai ajouté des logs pour débugger. Pourrez-vous me les transmettre à la nouvelle occurence.

Merci.

**Comment by Alcor72** [comment]
Bonjour,

Je vais m'assurer que la dernière mise à jour est installée, je fais des essais et vous tient au courant.

**Comment by Alcor72** [comment]
Bonjour,
Mise à jour faites mais le problème persiste.
Ci-joint les logs.

![IMG_73C2F3EA35FE-1](https://user-images.githubusercontent.com/45826817/71415545-85b06c80-265c-11ea-9982-92aba6e27952.JPG)

**Comment by dubocr** [comment]
Listener improved in latests releases.
