### ISSUE TITLE
Windowcovering reversed

### ISSUE THREAD

**Issue by Obikela88** [dubocr/homebridge-tahoma#148]
Hi

I'm quite hew to home bridge and have probably a quite silly question:
I got several window coverings and all are fine, except one. So I checked and you even have the possibility to reverse the window covers, but since I don't want to reverse all, but just one, I'm a bit stuck...
Could you please help me on this?
Here's my log:
       {
            "platform": "Tahoma",
            "name": "My TaHoma Box",
            "user": "sb@gmail.com",
            "password": "abc"
        },

And here the Window-Covering "Kitchen" from the log which is reversed:

[12/29/2019, 3:56:05 PM] [My TaHoma Box] [Kitchen] type: Awning > PositionableHorizontalAwning, protocol: io
[12/29/2019, 3:56:05 PM] [My TaHoma Box] Instanciate Kitchen as WindowCovering

How do I now need to adapt my config?

**Comment by dubocr** [comment]
Hi,
Just add to your config 
"Kitchen": { "reverse": true }

Or

"PositionableHorizontalAwning": { "reverse": true }
If your kitchen awning in the only one of type PositionableHorizontalAwning.

Eg.

{
"platform": "Tahoma",
"name": "My TaHoma Box",
"user": "sb@gmail.com",
"password": "abc",
"Kitchen": { "reverse": true }
},

**Comment by Obikela88** [comment]
Just tested it and it worked perfect.
Thanks a lot for your great work. Really appreciate your effort, since Somfy is unable to push a HomeKit version!
