### ISSUE TITLE
 [RFC] Read Only Mode ?

### ISSUE THREAD

**Issue by Killator** [dubocr/homebridge-tahoma#149]
Bonjour Romain,

J'apprécie énormément ton travail qui me permet d'afficher l'état de mes radiateurs connectés CozyTouch dans HomeKit. Cependant, les intéractions du type "SET" restent très perfectibles et perturbe la programmation de mon installation (l'API est assez dense et Homekit n'est pas très adapté aux normes de chauffage FR).

Serait-il possible d'implémenter un mode "Read-Only" ? Où seul l'état des capteurs serait remonté mais toutes les interactions du type "SET" seraient bouchonnées/mockées par ton plugin ?

A ta dispo pour échanger sur le sujet.

Cordialement,
M@T

**Comment by dubocr** [comment]
Bonjour Mat,

Quel type de radiateurs as tu ? Je vais avoir la possibilité de tester en réél sur des produits chauffage électrique prochainement, peut-être cela me permettra d'améliorer certaines choses.
Etant donné que les capteurs ne sont déjà pas "temps réél", l’intérêt d'une option read-only me parait très limité. Tu peux peut-être essayé d'exclure ton chauffage dans la config homebridge pour que seuls les capteurs restent.
Cependant, je ne comprends pas pourquoi cela perturbe ta programmation. Si tu ne modifie pas l'état de tes chauffage depuis homekit il n'y à pas de raison que cela change quelque chose sur ta programmation.

**Comment by dubocr** [comment]
Pk je comprend le problème à l'ouverture de la tuile. Effectivement sur la dernière version d'iOS homekit envoi la config actuelle à l'ouverture de la tuile (bug ou volontaire aucune idée ???).
Est-ce que le fait d'avoir uniquement les capteurs (présence/T°) serait problématique ou le thermostat (en lecture seule) est vraiment utile ?

**Comment by Killator** [comment]
Avoir les capteurs de Présence / Ouverture fenêtre m'intéresse, effectivement.

Mais concernant la température, c'est la température de **consigne** qui m'intéresse surtout... J'ai déjà d'autres capteurs (netatmo) qui checkent toute la maison en temps réel... Hors, voir apparaitre un simple capteur de température dans homekit qui indique toujours 20° n'a pas trop de sens... C'est quand même mieux de voir "un radiateur"...

Après, je comprends qu'un mode "read-only" puisse demander pas mal d'effort de développement. Je me formaliserai pas si tu me dis que c'est trop contraignant, trop spécifique à mon usage ;-)

**Comment by dubocr** [comment]
Thank you for using Homebridge TaHoma plugin.

Please follow these step to obtain better support :
1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)

Thank you.
