### ISSUE TITLE
How to arm Somfy alarm?

### ISSUE THREAD

**Issue by iRonin** [dubocr/homebridge-tahoma#15]
Is it possible to do it at all? Would be awesome to have it as part of a Home app Scenario. Thanks!

**Comment by dubocr** [comment]
This plugin only expose Somfy devices to homekit. Managing devices and scenario is the responsibility of homekit app like Home. If you can't activate alarm with home, try to use alternative app like "Eve" or "Hesperus". They allow much more automation.

**Comment by iRonin** [comment]
@dubocr there is no alarm device per se. Is there any documentation of the API that you use? I'd like to expose the alarm as a button.

**Comment by iRonin** [comment]
Though I can see `Accessory "Alarm"` in `accessories/Alarm.js` but I cannot see in my installation (I do have `"exclude": ["hue"],` but I don't think that's the problem).

**Comment by dubocr** [comment]
There is not official API so no documentation but did you browse [this page](http://home.dubocr.fr/tools/setup) as mentioned in plugin README ? It can help you to know your devices. May your alarm model is not registered as "Alarm" in TaHoma.
