### ISSUE TITLE
Blind position default

### ISSUE THREAD

**Issue by royteeuwen** [dubocr/homebridge-tahoma#150]
Hey,

Thanks for the great work! I have a question instead of an issue. What is the reasoning of putting the blind position to 50% when starting up homebridge? And why can't it just get the open / closed position from the Tahoma box? For example my blinds are either always completely closed or completely open. 

Thanks!
Roy

**Comment by dubocr** [comment]
Hi Roy,

Setting default position to 50% allow you to avoid order without effect after a restart or external command.
As this kind of blind doesn't reports their state there is no open/closed position in tahoma box.

Ex 1:
- Your blind are closed and displayed as closed in Homekit
- If homebridge/rasberry restart, your blind will be displayed as "open" in Homekit
- You will then not be able to open it now as it is considered as "open" homekit will no send new open command

Ex 2:
- Your blind are closed and displayed as closed in Homekit
- You open you blind locally
- You will then not be able to open it now as it is considered as "open" homekit will not send new open command

But if you want, you can change the default value by changing it in homebridge config.

**Comment by royteeuwen** [comment]
Hey Romain,

Thanks for the explanation, I also noticed this when a restart happened indeed, how I fix this is by using Siri, which does allow you to execute the command, even if it is closed / open.

Another solution could be to just save the open / closed state in the script on disk and reuse that on restart?

**Comment by dubocr** [comment]
Normally homebridge restart are not "usual". So saving to reload is quite "expensive" function for this use case.
The main problem is with external command and this is the limit of stateless device.

**Comment by sahotanick** [comment]
Hi @dubocr,

So if we choose to change the default value to say 100%, how will that affect this? In the event of a raspberry pi restart will the blinds no longer functions as expected due to it no longer being set to the 50% default?

**Comment by dubocr** [comment]
Release 2.x.x support restoring last shutter position when restarting.
defaultPosition parameter is still operational to force widget to specific position after each command execution.
