### ISSUE TITLE
Porte de garage apparaissent ouvertes.

### ISSUE THREAD

**Issue by macjl** [dubocr/homebridge-tahoma#151]
Bonjour,

J'ai installé le plug-in Homebridge-Tahoma chez mon père. Je vois bien ses volets roulants, mais il semble y avoir un problème avec les portes de garages. J'ai ceci dans la log : 
`[1/6/2020, 9:55:11 PM] [Homebridge Tahoma] No target command for garage CJ`

Les portes de garages sont de type : PositionableGarageDoorWithPartialPosition

Les portes de garages apparaissent bien dans l'application maison, mais affichent l'état ouvert sans réponse, alors qu'elles sont fermées. Est-ce que ce type de portes de garage est géré par le plug-in?

PS : j'ai ouvert l'URL de debug avec mon login GitHub.

**Comment by dubocr** [comment]
Bonjour,

Le type PositionableGarageDoorWithPartialPosition sera ajouté dans la mise à jour de ce soit. Il faudra mettre à jour le plugin puis redémarrer homebridge.

Merci.
