### ISSUE TITLE
Set Position and Closure via Siri?

### ISSUE THREAD

**Issue by sebnaf** [dubocr/homebridge-tahoma#152]
Hi,

we are using outside blinds with two values (position and rotation of the blinds).
How to set the rotation of the blinds via Siri?

Thank you

**Comment by mman** [comment]
I use ``blindMode: true`` (see description for ``blindMode`` in README) for precisely this. Open and Close does full open and full close, and aything in between (hey siri set blinds to 50%) closes the blinds and adjusts the rotation appropriately. Worked like a charm until the last Tahoma October update. Now it is half broken. See #141 and #145.

**Comment by N4M3Z** [comment]
`blindMode: true` works for me, with 100% setting closing the blinds all the way and 0% opening and hiding them. The percentage in between tilts the blinds appropriately even through Siri. The only scenario that's not covered is having the blinds halfway down and then tilting them, but you can use Tahoma Scenarios for that if you really need it.

**Comment by dubocr** [comment]
Hi,

Starting 0.3.41, you will have to change your config for using blinds in "orientation mode".
Here is the new config

		"WindowCovering": {
			"blindMode": "orientation"
		}
