### ISSUE TITLE
Homekit Control: Split Position and Rotation of blinds

### ISSUE THREAD

**Issue by sebnaf** [dubocr/homebridge-tahoma#153]
I´d suggest to split the position and rotation of blinds to two different homekit tiles.
why? sometimes you just want to rotate the blinds to reflect the position of the sun.

have a look at e.g. the vorwerk vr300 vacuum robot configuration. you can have either have all in one tile or split the functionality over different tiles for quick and easy access. that´s nice.

I´ve submitted my configuration already. 
ps - i´ve donated some $$ right away ;)

**Comment by dubocr** [comment]
Hi Sebastien,

Firstly, thank you so much for your generous donation.
I think I can do something to split position and rotation in 2 services, I'll have a look on that.
However, the rotation is already updatable in the tiles option and could be updated alone in automation ton reflect the position of the sun. Are you OK with that ?
