### ISSUE TITLE
Question before buying Somfy Tahoma Roller Blinds

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#154]
I already use homebridge, I am thinking of buying some Somfy blinds and want to ensure before  that this plugin allows me in homekit to set a roller blind to 30% or 60% and the blind will move to that position?

Likewise, will Tahoma and Homekit be in 100% sync of position regardless of the device used to control the blind? i.e. use remote, homekit will update, use homekit, comfy will update?

Please confirm, many thanks in advance.

**Comment by dubocr** [comment]
Hello,
If you buy IO solfy blinds then yes you will be able to set exact position via homekit.
About syncing, updates made outside homekit are not reported in « realtime » as somfy don’t provide realtime API. By default, state will be synced every 10minutes. You’ll have option to reduce it.
One more thing: Somfy announced official Homekit support for the TaHoma box 2 years ago. There is delays but it is always « in progress » so you also could expect full homekit feature in the future if you buy a Tahoma box.
