### ISSUE TITLE
Compatibilité energeasy connect

### ISSUE THREAD

**Issue by alex45fr** [dubocr/homebridge-tahoma#155]
Bonjour,

La box de chez rexel, energeasy connect étant une box overkiz, ce plugin est-il compatible avec cette box?
Si non, la compatibilité est-elle envisageable? 

Merci pour votre travail.

**Comment by dubocr** [comment]
Bonjour,
Il faudrait tester. Avez-vous cette box et quelle application utilisez-vous pour la piloter ?

**Comment by alex45fr** [comment]
Bonjour, je devrais avoir cette box opérationnel d’ici quelques jours. L’application pour la piloter est E.connect 2 sur iOS

**Comment by dubocr** [comment]
Merci, tenez moi au courant, je vous conseille d'essayer avec la config par défaut pour voir. Vous pourrez aussi me dire si cela ne fonctionne pas si il y à possibilité d'utiliser une appli WEB (site) pour piloter les équipements, ce sera plus simple de débugger avec.

**Comment by alex45fr** [comment]
Pas de soucis, par contre il n'y à pas, à ma connaissance, d'interface web pour le pilotage mais uniquement pour les paramètres.

**Comment by tomasiz** [comment]
Bonjour,

L'adresse de l'API utilisée par Rexel pour son app E.Connect 2 est ha112-1.overkiz.com.

En ajoutant la cette ligne dans overkiz-api.js :
`Server = {
	'Rexel': 'ha112-1.overkiz.com',
	[..]
}`
Et en utilisant Rexel comme config j'arrive à faire fonctionner le bridge avec ma box Rexel !
Ce plugin est donc de base compatible avec Rexel vu que l'API d'Overkiz est la même...

De mon côté j'ai quelques ajustements à faire sur mes accessoires, d'ailleurs @dubocr si vous pouviez modifier [](https://dev.duboc.pro/tools/setup) pour y intégrer Rexel ce serait top !

**Comment by dubocr** [comment]
Merci tomasiz. C'est ajouté.

**Comment by steve41200** [comment]
Apres de nombreuses tentatives de faire communiquer cette box Econnect avec le reste de ma domotique (IFTTT, Google Home comme passerelle) je vient de tomber sur ce plug in.

Tout marche bien et avec retour d'état (les autres solutions ne le faisaient pas). 
En revanche j'ai une lumière Yokis qui s'éteint toute seule après X temps (et que ce soit la box Rexel ou homebridge, ils la voient toujours allumée). J'ai 4 autres lumières Yokis (memes modules, au meme endroit (tableau electrique) qui marchent sans pb.

Avez vous eu des remontées de ce genre avec des modules lumière ?

Le pb est apparu quand g parametré le plug in pour aller sur la Econnect.
Quand je coupe Homebridge la lumière récalcitrante ne se coupe pas "toute seule"
J'ai tenté d'exclure juste cette lumière du plug in (avec "exclude". Je ne la vois pas dans le plug in, mais elle s'éteint quand même toute seule ...
Je suis tellement fan de votre plug in (en 1 journée de tests intenses) que j'envisage de désappairer cette lumière pour avoir le reste connecté d'une meilleure facon a ma domotique (Home assistant), plutot que de garder 5 lumières et 3 radiateurs "prisonniers" de la box Econnect.

**Comment by steve41200** [comment]
voici ma config j'ai peut etre loupé un truc
       {
            "platform": "Tahoma",
            "name": "E.Connect 2",
            "user": "xxxxx@www.com",
            "password": "xxxxx",
            "service": "Rexel",
            "refreshPeriod": 60,
            "exclude": [
                "spot cuisine"
            ]
        }

**Comment by dubocr** [comment]
Bonjour,
Je n’avais pas vu vos messages l’issue étant fermée.
Si vous rencontrez toujours des problèmes pouvez-vous installer la dernière version et en une autre issue pour qu’on regarde cela.

merci
