### ISSUE TITLE
Config pour TaHoma + Cozytouch 

### ISSUE THREAD

**Issue by plusselmann** [dubocr/homebridge-tahoma#156]
Comment faire le fichier config sinon à des volets roulants sous TaHoma et des radiateurs sous Cozytouch?
J’ai l’impression que cela me créer un conflit sur certains appareils et même certains sont en doubles.

**Comment by dubocr** [comment]
Bonjour,

Tout dépend de la box/bridge dont vous disposez.
Si vous disposez des deux, il faudra deux blocs config mais si vous avez appairé vos produits sur les deux box il faudra les exclure pour ne pas les avoir en double.

L'idéal reste d'utilisez uniquement le box TaHoma et d'y appairer les produit Atlantic pour tout centraliser.
