### ISSUE TITLE
initPosition volets RTS

### ISSUE THREAD

**Issue by nanoupi42** [dubocr/homebridge-tahoma#157]
Bonjour Romain,

Lorsque je redémarre mon HomeBridge mes volets sont par défaut en position 50%, j'aimerais les fermer par défaut j'ai tenté de rajouter le paramètre initPosition dans mon json mais ça ne change rien... est-ce bien ce paramètre ?

Merci à toi :)

**Comment by dubocr** [comment]
Bonjour, le paramètre est à ajouter dans un bloc "WindowCovering":

"WindowCovering" : {
   "initPosition": 0
}

Bonne journée.

**Comment by nanoupi42** [comment]
Merci c'est nickel !!
