### ISSUE TITLE
RTS Blinds not updating blind state

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#158]
Hi, when I use the remote or Alexa to open or close the blinds, Homekit does not reflect the new state in the home app to mirror the change done by another device?

Please advise

**Comment by adavison007** [comment]
@dubocr Please can you confirm if HomeKit can discover the device open or close status from the Tahoma hub? the hub knows when it is opening or closing, so it must be able to advise this via the API... not state, but last action from the hub... this would then keep everything in sync?

If not, let me know and I will add door sensors to by blinds to keep them in sync via an automation... sensor open = blind closed etc

**Comment by dubocr** [comment]
Hi,

Getting blind state from history  command will be difficult and hazardous. But may you can ask @Tontonpat as he use Alexa with Homebridge so this could be the solution for your problem.

**Comment by adavison007** [comment]
@Tontonpat Please can you advise if you have the ability to find or sync an RTS blind state using Alexa and Homebridge? Currently I do it via door sensors stuck to the back of the blind, it works, but is complex to set up. Thanks in advance for any help ou be able to offer?

**Comment by Tontonpat** [comment]
Hi @adavison007, install homebridge-Alexa on the same homebridge as this one. 
link: https://github.com/NorthernMan54/homebridge-alexa

**Comment by adavison007** [comment]
> Hi @adavison007, install homebridge-Alexa on the same homebridge as this one.
> link: https://github.com/NorthernMan54/homebridge-alexa

@Tontonpat many thanks, so does this just enable Alexa for the blinds... or does it synch the blind position correctly in homebridge? I also use the Tahoma remote, so that's why I use the window sensors on the blinds... so today if I use Alexa, HomeKit or the Tahoma remote my blinds are 100% showing the right position every time... does your solution fix this too or not? mine works fine, but is complex, was looking for an easier way? May thanks in advance.

**Comment by Tontonpat** [comment]
@adavison007 it will enable Alexa to open/close or set to any % the blinds through homebridge to tahoma, so the position is set in HomeKit.
But if you move the blind with the remote, it doesn't update anywhere because it's RTS.
Witch remote do you have ? Telis rts? If so, you will never have a comeback to tahoma, always cause of RTS...

PS: i hope you will understand my bad English because i'm French

**Comment by dubocr** [comment]
@adavison007, as Tontonpat says you will never have any chance to get right position with the one way remote as it send order directly to the shutter. Except as you do with another sensor.
What you can do is using Homebridge as « main gateway » for every orders :
- From Alexa with the Homebridge plugin used by Tontonpat
- From HomeKit
- From remotes connected to Homebridge/HomeKit
So if you replace your physical remote by another one linked to HomeKit that trigger automation it became possible to sync everything.
But need some configuration too.
