### ISSUE TITLE
Somfy Servers down = Homebridge won't restart

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#161]
When Somfy servers are down and you reboot homebridge, homebridge service will not start... can it be coded to ignore a login failure and carry on so it does not interupt other homebridge services?
<img width="420" alt="Screenshot 2020-02-17 at 19 41 59" src="https://user-images.githubusercontent.com/47482260/74682303-93e2bb00-51bd-11ea-88fa-c8ab78e6c7b5.png">

**Comment by dubocr** [comment]
Fix in 2.x.x
