### ISSUE TITLE
Error 400 Exeution queue is full

### ISSUE THREAD

**Issue by jufu182** [dubocr/homebridge-tahoma#162]
When I try to close my 14 Tahoma roller shutters at the same time („Siri, close all..“) 4 of them will stay opened. In Log I find a message „Error 400 Execution queue is full on gateway … (Soft Limit: 10)“
Can I increase this limit somehow?

**Comment by mman** [comment]
0.3.33 Fixes this issue

**Comment by jufu182** [comment]
Good work! Thank you!
