### ISSUE TITLE
when i use i/o button no state update

### ISSUE THREAD

**Issue by henkied** [dubocr/homebridge-tahoma#163]
If I open sunscreen via external button, there is no correct status in homekit. When the awning with home kit open then the status is correct. The status at Tahoma is also correct in both cases.

[
        {
            "platform": "Tahoma",
            "name": "Tahoma",
            "user": "XXXXXXXX",
            "exclude": [
                "hue",
                "Sonos SUB",
                "Sonos PLAY:5",
                "Sonos PLAY:1",
                "Alarm",
                "Garagedeur"
            ],
            "password": "xxxxxx",
            "WindowCovering": {
                "defaultPosition": 0,
                "alwaysPoll": true,
                "initPosition": 0,
                "pollingPeriod": 10
            }

**Comment by N4M3Z** [comment]
I have the same problem and it seems to also apply to TaHoma scenarios as they happen throughout the day. I haven't tried `alwaysPoll`. I'm also seeing issues with `blindMode: true` as it repeatedly switches states between open and closed.

**Comment by Siriusmac** [comment]
I use refreshPeriod set to 60 (seconds) and it works

**Comment by Supermarco333** [comment]
I might have the same problem with my LED Dimmers and my shutters. I don't have the correct status when I use the i/o button. Here's my config:

        {
            "platform": "Tahoma",
            "name": "Connexoon",
            "user": "xxxx@xxx.fr",
            "password": "xxxxxxx",
            "service": "Connexoon",
            "polingPeriod": 10,
            "pollingPeriod": 60
        },

Any idea ?

**Comment by Siriusmac** [comment]
instead of “polling period” try with "refreshPeriod": “60"

**Comment by dubocr** [comment]
Hi,

Please reopen and browse https://dev.duboc.pro/tahoma then give me your last 4 bridge digit if issue is still there after upgrading to latest release 2.1.22.

Thanks
