### ISSUE TITLE
Further paremeters for blinds

### ISSUE THREAD

**Issue by N4M3Z** [dubocr/homebridge-tahoma#164]
My blinds also rotate only between 0 to +90 degrees and I don't see any available setting for that. It would also help to have the ability to set the incremental step. Could you also add some additional information on `alwaysPoll` and `pollingPeriod`? Also, does it hurt to set `refreshPeriod` to something like 10 seconds?

**Comment by dubocr** [comment]
Hi,

HomeKit has option for that when you open accessory settings.
refreshPeriod should be around 30 minutes as it force all your devices to refresh all their params and so generate huge radio traffic.
