### ISSUE TITLE
[Tahoma] Error 400 Execution queue is full on gateway:

### ISSUE THREAD

**Issue by mman** [dubocr/homebridge-tahoma#169]
Hi Romain, hope you are safe WFH :)

When invoking "Hey Siri good Morning" or "Hey Siri Good Night" I noticed that some blinds would not react at all. I have currently 13 blinds that are configured in the scenes.

Looking at the log I'm getting:

```
[Tahoma] Error 400 Execution queue is full on gateway: #0204-8225-0087 (soft limit: 10) (EXEC_QUEUE_FULL)
[Tahoma] [XXX] setClosure Error 400 Execution queue is full on gateway: #0204-8225-0087 (soft limit: 10) (EXEC_QUEUE_FULL)
[Tahoma] Error 400 Execution queue is full on gateway: #0204-8225-0087 (soft limit: 10) (EXEC_QUEUE_FULL)
[Tahoma] [YYY] setClosure Error 400 Execution queue is full on gateway: #0204-8225-0087 (soft limit: 10) (EXEC_QUEUE_FULL)
[Tahoma] Error 400 Execution queue is full on gateway: #0204-8225-0087 (soft limit: 10) (EXEC_QUEUE_FULL)
[Tahoma] [ZZZ] setClosureAndOrientation Error 400 Execution queue is full on gateway: #0204-8225-0087 (soft limit: 10) (EXEC_QUEUE_FULL)
```

Looks like the command is set to 10 blinds and fails for the three random.

Is there any way around this?

thanks and stay safe,
Martin

**Comment by mman** [comment]
I am aware of https://github.com/dubocr/homebridge-tahoma/issues/162, https://github.com/dubocr/homebridge-tahoma/issues/50, and https://github.com/dubocr/homebridge-tahoma/issues/7.

I think ``homebridge-tahoma`` is so great and works so well, and given Somfy seems unable to implement their own proper HomeKit support, this needs to be somehow addressed.

Could you give me a couple hints how this works in general? I will try to make a PR :)

thanks,
Martinb

**Comment by mman** [comment]
A simple fix could be to automatically retry the command after several seconds when you get back 400 EXEC_QUEUE_FULL

**Comment by dubocr** [comment]
Hi mman,

Thanks for your simple suggestion, I'll even do more by storing number of pending command to postpone other one when queue has 10 commands or more.
I published an update today, could you try if it's better for your ?

Thank you.

**Comment by dubocr** [comment]
Re,

I've succeed to do even better. Now HomeKit scene are executed in the same command when possible. So you will now have no device limitation nor postpone delay.

Waiting for your feedback.

**Comment by mman** [comment]
Excellent @dubocr, I just tried to re-add multiple devices into the good morning / good night scene and it works flawlessly... that is 0.3.33...

great job,
Martin

**Comment by MirkoKas** [comment]
This update is amazing. I used to have multiple automations with a minute difference for closing and opening my 19 shutters. Now I have everything in two automations. Great job!
