### ISSUE TITLE
Accessories

### ISSUE THREAD

**Issue by alexanderniebuhr** [dubocr/homebridge-tahoma#17]
Hey folks,

I am currently working on an little project with my Tahoma shutters.
For this I really would like to use node-red to set my shutter opening value. So far I only find the option to use mqtt to connect homebridge with node-red, for that I would use all my shutters as single accessories in homebridge.

How can I access and set the value for the Tahoma shutters from the outside of Homekit (Node-Red)?

Cheers
Alex

**Comment by dubocr** [comment]
Hi Alex,

Your question is related to homebridge. This plugin is only a plugin on top of homebridge. You can look at [homebridge page](https://github.com/nfarina/homebridge) to understand or ask how to connect Node-Red or you can fork this project to refactor index.js file to interact with accessories.

Best,
Romain
