### ISSUE TITLE
Open and close horizontal shutter

### ISSUE THREAD

**Issue by matijus91** [dubocr/homebridge-tahoma#170]
What a great plugin but I like to make this happen:

I have horizontal shutters they work with RTS on connexoon. When I select Close de shutters go Up (no light comes in) and when select Open the shutters go down (no light comes in). The shutters are open (light comes in) when I select 50%. Is there a way I can make is when I select Open it sets de shutters half way just like 50% does? Or even better everything from 100% to 1% sets my shutters halfway.

Please let me know if there is a proper way to get this done

**Comment by dubocr** [comment]
Hi,
can you log ther to let me know your config : https://dev.duboc.pro/tahoma and send me the SETUP-XXXX-XXXX-XXXX code of your bridge.

Thanks
