### ISSUE TITLE
New Homebridge version 1.0.0 Beta test

### ISSUE THREAD

**Issue by nscheffer** [dubocr/homebridge-tahoma#171]
Hi,

Did you test your plugin with the new homebridge upcoming version 1.0.0 actually in Beta ?
I didn't see your name on the list :
https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Plugin-Status

Thanks in advance.
Regards,
Nicolas

**Comment by nscheffer** [comment]
I just upgrade my Homebridge to 1.0.0 and your plugin seems to be ok !

**Comment by hoefs** [comment]
Works perfectly with 1.03 here!
