### ISSUE TITLE
HeatingSystem > AtlanticPassAPCHeatPump

### ISSUE THREAD

**Issue by Blaster681** [dubocr/homebridge-tahoma#172]
Bonjour

D'abord, merci pour ce plugin ;-)

- J'ai ajouter ma PAC Atlantic Extensa Duo AI: tout fonctionne bien mais j'ai un accessoire qui indique la température de consigne de l'eau chaude et qui se nomme chauffage dans Home ce qui est une confusion pour Siri, est-il possible de changer cela ?
- Que je demande a Siri de modifier la température elle ne recois aucun retour.

Merci d'avance,

Cordialement

**Comment by dubocr** [comment]
Bonjour,
Vous pouvez renommer les accessoires directement depuis Home.
Pour exclure des produits, utilisez "exclude" et le nom du produit.

Pour le problème de T°, pouvez-vous réaliser l'opération à nouveau puis vous connecter sur https://dev.duboc.pro/tahoma et m'indiquer le N° de votre bridge (SETUP-XXX)

merci

**Comment by Blaster681** [comment]
Bonjour,

Merci pour votre retour.

Numéro de Bridge: SETUP-1217-3365-5696

Merci d'avance
Cordialment.

**Comment by dubocr** [comment]
Bonjour,

Pourriez-vous réaliser l'opération avec Cozytouch et vous reconnecter pour que l'opération apparaisse dans l'historique. L'opération de 12h30 passe la T° à 21°C mais peut-être la durée de dérogation est inadaptée.

**Comment by Blaster681** [comment]
Bonjour 

Voilà - SETUP-1217-3365-5696

La température demander est bien envoyer à la PAC mais en retour Siri m’informe n’avoir aucune nouvelle de l’appareil. 

Merci

**Comment by dubocr** [comment]
La commande est probablement longue à s'exécuter. J'ai fait quelques modifications pour gérer un retour intermédiaire, cela devrait être mieux dans la dernière version.

Vous n'avez pas activer le paramètre "alwaysPoll" ?

**Comment by Blaster681** [comment]
Bonjour,

Désoler de la résponse tardive.

Je n'est pas trouver ce paramètre ?

Cordialement.

**Comment by dubocr** [comment]
Je vous invite à me remonter d'éventuels problèmes sur la dernière version 2.1.6

Merci.
