### ISSUE TITLE
RollerShutter - Quiet mode

### ISSUE THREAD

**Issue by thedriverplus** [dubocr/homebridge-tahoma#173]
Hello,

On my Somfy window blinds there is an option to set a quiet mode for opening and closing. (With the normal Somfy remote, this is controlled by a mechanical switch with a feather symbol).

Is there a parameter possible to always set the movement to quiet?
Thanks in advance, best regards,

Dominik

**Comment by Bartus78** [comment]
Dear Dubocr,

Thank you for this feature, it is very helpful. May I ask if it would be possible to define an optional user defined time periode each day where the window covering uses low speed mode and uses normal speed mode during the other times of day. In defining a wake up period, say between 6:30-10:30hrs, the window covering would then go up slow. But when you lower your window covering during the night it would then go down more rapid.

Thanks in advance, best regards,

Benno

**Comment by dubocr** [comment]
Hi @Bartus78,

Latest release implement this feature. Juste replace `"lowSpeed": true` param by `"lowSpeed": "6:30-10:30"`
