### ISSUE TITLE
Zwave On-Off Plug

### ISSUE THREAD

**Issue by firefighter79** [dubocr/homebridge-tahoma#175]
Hi all,
does the "Zwave On-Off Plug" works with homebridge-tahoma PlugIn in Apple HomeKit App?
I have integrate them, but by switching in Apple Home App it works just one single time and then they are marked in Home App as "no answer" and it's not possible to activate or deactivate them a second time...
Looks like there is somethings wrong, isn't it? Thank you for any response!
BR // Martin

**Comment by firefighter79** [comment]
Nobody out there with "Somfy Zwave On-Off Plug"?

**Comment by dubocr** [comment]
Hi,

Could you please log here : http://dev.duboc.pro/tahoma
Then give me the SETUP-XXXX-XXXX-XXXX of your config.

Thanks

**Comment by dubocr** [comment]
Please try the operationn just before login as I'll be able to see last operation in history.

Thanks.

**Comment by firefighter79** [comment]
SETUP-1204-1469-8712
Actions between Execute scene - HomeKit (18/06/2020 22:56:56) and Execute scene - HomeKit (18/06/2020 22:59:43
I switched the "Esszimmer" lamp on -> ok. But then I tried twice to switch the "Esszimmer" lamp off, both actions failed. I can see in the history, that Homebridge tried to switch the "Esszimmer" lamp on again?!
Thank you for any help!

**Comment by dubocr** [comment]
Do you have "alwaysPoll" config set to true ?
Can you set "debug": true in your config and retry then get the log.

HomeKit what for COMPLETED or FAILED state but it may be too late. Do you always have "No answer" flag in HomeKit ?

**Comment by firefighter79** [comment]
I had not "alwaysPoll" in my config. Now I do, but there is no change in the behavior.

This is the expected behavior on an other device (Eltako FSR61NP-230V Relais). I switch the lamp on/off with Apple Homekit:
[6/20/2020, 23:59:11] [My Tahoma] [Deckenlampe Wohnen] on[]
[6/20/2020, 23:59:12] [My Tahoma] [Deckenlampe Wohnen] on COMPLETED
[6/20/2020, 23:59:16] [My Tahoma] [Deckenlampe Wohnen] off[]
[6/20/2020, 23:59:18] [My Tahoma] [Deckenlampe Wohnen] off COMPLETED

This is the behavior with the Somfy Z-Wave OnOff Plugs by switching it on/off:
[6/20/2020, 23:59:50] [My Tahoma] [Esszimmer] on[]
[6/20/2020, 23:59:54] [My Tahoma] core:OnOffState -> on
[6/21/2020, 00:00:06] [My Tahoma] [Esszimmer] on[]
[6/21/2020, 00:00:18] [My Tahoma] [Esszimmer] off[]
[6/21/2020, 00:00:22] [My Tahoma] core:OnOffState -> off

I do just have that issue with my Somfy Z-Wave OnOff plugs (3 devices in my system). All other devices works well.

This is my config now:
{
            "platform": "Tahoma",
            "name": "My Tahoma",
            "user": „_MYMAIL_",
            "password": „_MYPW_",
            "service": "TaHoma",
            "alwaysPoll": true,
            "debug": true,
            "Q-Bus senkrecht": {
                "reverse": true
            },
            "Q-Bus horizontal": {
                "reverse": true
            },
            "exclude": [
                "hue",
                "zzzz",
                "Alarm"
            ]
        },

Thank you for your support!

**Comment by dubocr** [comment]
I, could you try with latest version, I've changed response to Homekit before waiting real execution.

**Comment by firefighter79** [comment]
Hi sorry, was some time off.
I have now the latest version from today, but obviously no change in behavior switching the lamp on/off via button in the Apple Home App:
[7/2/2020, 20:39:51] [My Tahoma] [Esszimmer] on[]
[7/2/2020, 20:39:51] [My Tahoma] undefined
[7/2/2020, 20:39:52] [My Tahoma] Listener registered 10d3f0c4-ac10-3e01-2775-8dbb57a23dbf
[7/2/2020, 20:40:05] [My Tahoma] [Esszimmer] on[]
[7/2/2020, 20:40:05] [My Tahoma] undefined
[7/2/2020, 20:40:06] [My Tahoma] Listener registered 10d4278d-ac10-3e01-2775-8dbbbfa5655c
[7/2/2020, 20:40:18] [My Tahoma] [Esszimmer] on[]
[7/2/2020, 20:40:18] [My Tahoma] undefined
[7/2/2020, 20:40:18] [My Tahoma] Listener registered 10d4576d-ac10-3e01-2775-8dbb7348475d
I get always the "no answer" exclamation mark in Apple Home App...

But if I control the lamp (via On-Off Plug) with Siri voice command, it is possible to switch it on or off by voice. That works. But there seams to be an error also, because Siri performs the action (lamp switch on and off by command) but my HomePod says always "I'm there, one more moment, I'm sorry, I couldn't do that!"...

**Comment by dubocr** [comment]
Hi,

When switching on/off with Home button the plug is switching on/off (and only "no answer" issue) or did it also don't change its state ?
Hi've change something else in latest release (0.3.50), can you please try it.

If it's not better, could you update the file "overkiz-device.js" in the plugin folder to remove ".debug" in line 168.
Then retry and send me logs.

Thank you.

**Comment by firefighter79** [comment]
Hi,
with the latest version 0.3.50 it now works perfectly also in Home App! There was no need to change the file "overkiz-device.js".
Thank you so much for your effort.
Kind regards
Martin
