### ISSUE TITLE
Tahoma / Cozytouch et status

### ISSUE THREAD

**Issue by Philou93260** [dubocr/homebridge-tahoma#179]
Bonjour,

je suis un newbie sur le sujet mais j'aime apprendre et comprendre.
En l'occurrence j ai installé HOOBs sur un PI 4. le top

J'utilise votre plugin qui me convient pour Tahoma et je souhaiterais pour Cozytouch

- Tahoma : parfait, mes volets roulants et stores sont apparus
- Cozytouch (meme login / mot de passe) : rien

J'ai tenté plusieurs choses mais rien. Je ne souhaite pas faire apparaitre mes radiateurs dans le Tahoma. Mais cela est il obligatoire ?

Question supplémentaire : le plugin peut il remonter le dernier status du volet ? Par exemple je ferme le volet avec l'app home ==> ca ferme.
J ouvre mon volet avec son bouton ==> dans l'app Home le volet reste fermé.
Pourtant dans Tahoma, le volet est bien ouvert.

Merci pour votre aide et retour.

**Comment by dubocr** [comment]
Bonjour,

Vous n'êtes pas obligé de passé par TaHoma pour gérer vos radiateur. Il faut ajouter une section avec le service "Cozytouch" dans votre fichier de config.
Le statut des appareils modifiés localement est remonté au maximum 30 min après.

**Comment by Philou93260** [comment]
j ai rajouté service Tahoma (pour les volets ) et Cozytouch (pour les radiateurs) 
remontée direct ! 
Merci j'aurais pu y penser....

Le rafraichissement on ne pourrait pas le forcer ?
Merci

**Comment by dubocr** [comment]
Pour le rafraichissement, vous pouvez forcer une période plus courte avec les paramètres suivants :
"alwaysPoll": true,
"pollingPeriod": 30

pollingPeriod en secondes

Concernant le message d'erreur, je ne sais pas si il est lié au plugin [Refresh Services] ne correspond à rien et l'IP 127.0.0.1 n'à pas de raison d'être appelée.

**Comment by Philou93260** [comment]
j ai pas de chance :o( et comme je suis vraiment pas expert mais j'aimerais faire marcher mes volets avec Tahoma et les radiateurs avec le Cozytouch via l appli home d apple

voici ce que j ai fait
config 1
{
    "platform": "Tahoma",
    "name": "My TaHoma Box",
    "user": "xxx.xxxxx@xxxx.xxx",
    "password": "yyYYYyyyYYY",
"alwaysPoll": true,
"pollingPeriod": 900 ==> pour toutes les 15 min. A cote des volets j'ai la roue qui tourne en permanence en ouverture ou fermeture. J ai enlevé, je resterai ensuite
}

config 2
{
    "platform": "Tahoma",
    "name": "My TaHoma Box",
    "user": "xxx.xxxxx@xxxx.xxx",
    "password": "yyYYYyyyYYY",
   "service":"Tahoma",
   "service":"Cozytouch"
}
apres enregistrement  la ligne "service":"Tahoma" est supprimé , les radiateur remontent bien puis  puis j ai erreur : [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826

config 3

{
    "platform": "Tahoma",
    "name": "My TaHoma Box",
    "user": "xxx.xxxxx@xxxx.xxx",
    "password": "yyYYYyyyYYY",
   "service":"Tahoma"
},
{
    "platform": "Cozytouch",
    "name": "My Cozytouch Box",
    "user": "xxx.xxxxx@xxxx.xxx",
    "password": "yyYYYyyyYYY",
   "service":"Cozytouch"
}
impossible d enregistrer la config, l'enregistrement mouline....
je n arrive pas à voir ou je rate quelques choses pourtant cela parait clair

merci pour l aide

**Comment by dubocr** [comment]
J'ai regardé un peu HOOBS. Il faudrait que vous puissiez ajouter 2 fois le plugin.

La version suivante serait la bonne sous homebridge (attention au majuscules pour "service": "TaHoma" sur le 1er et "platform": "Tahoma" pour les 2).
Mais sous Hoobs je pense qu'il faudrait 2 plugins Tahoma avec dans chacun. Essayez déjà comme ça.

{
"platform": "Tahoma",
"name": "My TaHoma Box",
"user": "xxx.xxxxx@xxxx.xxx",
"password": "yyYYYyyyYYY",
"service":"TaHoma"
},
{
"platform": "Tahoma",
"name": "My Cozytouch Box",
"user": "xxx.xxxxx@xxxx.xxx",
"password": "yyYYYyyyYYY",
"service":"Cozytouch"
}

Pour le pollingPeriod, il doit être de l'ordre de quelques dizaines de secondes mais en fait les volets ne remontent pas l'information quand ils sont pilotés par la télécommande.

Il faudrait donc plutôt supprimer alwaysPoll et pollingPeriod et ajouter :
"refreshPeriod": 900

Ce qui provoquera une interrogation de TOUS les devices par la box toutes les 15 minutes. C'est généralement l'opération que fait l'application lorsqu'on l'ouvre c'est pour ça que l'état est le bon à l'ouverture de l'application.

**Comment by Philou93260** [comment]
Bonjour

mille merci, j ai pas fait attention au minuscule / majuscule.... désolé
J'ai fait cette configuration
- Tahoma = ok
- Cozutouch = presque presque ;o)

Pour la partie Cozytouch : il remonte bien tous les radiateurs avec température et leur fonction sauf pour 1 : le seche serviette. Il le remonte mais les infos sont erronées. si je cliques dessus = le serveur s'arrête. 
Message d'erreur : [My Cozytouch Box] No target command for Sèche-serviettes

Ensuite je constate que le cozytouch regarde toute la plateforme Tahoma (volet, store) les fonctions etc etc donc ca fait presque tout en double avec le service Tahoma.

je continue de regarder et creuser.
Merci pour l'aide et les explications associées ca m'aide à comprendre ce que je fais et ce qu'il se passe

**Comment by Philou93260** [comment]
Bonsoir

je dois stopper la config avec le cosytouch pour le moment.
J'ai un radiateur i/o qui plante tout et qui se plante en fonction des configurations.
J'ai souhaité passer par la tahoma box, le seche serviette ne repond plus

j'ai demandé des infos à Altantics et j'ai demandé à Tahoma de supprimer les éléments i/o car il m'est impossible de les enlever par moi meme... :(

Merci pour l'aide en tout cas

**Comment by dubocr** [comment]
Pour le seche serviette, je devrais pouvoir tester prochainement mais sinon vous pouvez vous connecter ici : https://dev.duboc.pro/tahoma
Afin que je regarde la config.

Pour tout ce qui apparait en double, c'est possible de les ajouter dans un exclude: ["Nom1","Nom2"]

**Comment by Philou93260** [comment]
je me suis loggé si cela peut aider.
Je vais etre honnete j'y comprends rien ;o)

**Comment by dubocr** [comment]
Bonjour,

Mon sèche serviette vient d'être installé du coup j'ai pu correctement mapper son fonctionnement pour Homebridge.As-tu réussi à supprimer les éléments sur TaHoma ?

Pour tes produits qui remontent en double, deux options :
- Les supprimer de la box où ils ne sont pas censés être pas possible via l'appli Cozytouch/Tahoma puisqu'il n'apparaissent pas mais possible autrement, je peux te guider.
- Les exclures via la config Homebridge.

Exemple, tu ajoutes `"exclude": ["Volet Salon", "Porte Garage"]` dans ta config Homebridge Cozytouch pour supprimer les volets qui sont normalement géré par TaHoma.

N'hésites pas si tu as des questions.

**Comment by Philou93260** [comment]
Bonjour 

Pour le moment, je suis dans une situation bloquée ;o)
Somfy m a supprimé tous les équipements I/O Altantics de la box Tahoma...mais ce fut complexe
Maintenant j'ai du écrire à Cozytouch et Altantics car depuis les dernières manipulations, je ne peux plus commander mes radiateurs et sèche serviette...j'ai un message d'erreur Bad MAC Error....
je ne sais que faire car bloqué :(

**Comment by dubocr** [comment]
Bonjour,

Si vous avez un erreur Bad MAC Error, je vous conseille de supprimer les devices depuis l'application cozytouch puis de refaire l'appairage (l'ajout sur Cozytouch) pour que tout soit propre.

**Comment by Philou93260** [comment]
Bonsoir,

Merci pour les infos. J'ai eu un support de la part d'atlantic / Cosytouch, Tahoma avait foutu le bordel....
Somfy pas au point.
Je vais refaire la configuration donc en séparer avec cosytouch.
Donc si j ai bien compris le radiateur I/O devrait fonctionner correctement ?

je teste cela dans la semaine

**Comment by dubocr** [comment]
Bonsoir,

Oui concernant le sèche serviette j'ai réalisé l'intégration avec mon Serenis. Cela devrait correspondre sinon on pourra affiner avec votre config exacte sur https://dev.duboc.pro/tahoma/login

**Comment by Philou93260** [comment]
Bonjour

Desole cela a pris pas mal de temps. Mais enfin tout fonctionne....
pour le seche linge ca fonctionne juste le % d humidité qui dit tout le temps 100%

les capteurs de presence se déclenche parfois ou alors c est lié au rafraichissement

Merci en tout cas pour l'aide et les explications.
