### ISSUE TITLE
[Cozytouch] Chauffe eau Thermor 

### ISSUE THREAD

**Issue by pimoon** [dubocr/homebridge-tahoma#180]
Bonjour,

J'ai un pont cozytouch et un chauffe eau Thermor électrique connecté.
Cela fonctionne normalement avec l'application officielle Thermor.

Dans Home, je vois bien le chauffe eau avec les 3 modes : éteint, chauffer, auto. (il manque le mode boost mais passons)
Problème : Rien ne se passe quand je change de mode. (Au bout de plusieurs minutes il revient en mode auto pour info).

Des idées ?

Merci

![Capture d’écran 2020-06-06 à 14 18 49](https://user-images.githubusercontent.com/46498300/83944005-bcd89b80-a800-11ea-9d0a-187a295c5e5d.png)

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous vous connecter ici après avoir réalisé l'opération à nouveau et m'envoyer le N° du SETUP-XXXX-XXXX-XXXX : https://dev.duboc.pro/tahoma

Pour le boost, normalement vous devriez avoir un bouton en faisant glisser l'écran de votre capture vers le haut. Je vérifierai avec votre config si il n'apparait pas.

**Comment by Yannazay** [comment]
Bonjour
J'ai le même problème. J'ai bien le mode boot mais lorsque que j'essaie de l'activer il revient sur sa position par défaut (off)
Avez vous des idées?
Merci
