### ISSUE TITLE
Tahoma shades - defaultposition not working

### ISSUE THREAD

**Issue by reeko182** [dubocr/homebridge-tahoma#181]
Hi, 

please see my config.json in attachment. Whatever I do, i cant force my shades to close fully. They always stay horizontaly opened. I do not wish to use blind mode since i sometimes open them only half way.
In summary, when i click on a shade i just want it to close down fully (defaultposition 0 or 100?). Do i have an error in the code?

Thank you very much

Martin

![Annotation 2020-06-09 080625](https://user-images.githubusercontent.com/11313843/84111951-28e91880-aa28-11ea-8950-a658e58bf8b4.png)

**Comment by bigmadf** [comment]
Hi there,

I have the same issue with the latest version 0.3.35.
Regardless of the values entered for "defaultPosition" the blinds open fully after reaching the desired position (blindMode=false). Everything works as expected from the Somfy app.

When using blindMode=true the Apple Home App displays the devices as "closed" despite them being fully opened. When activating the device via Home App (expectation to close the device) nothing happens. From the Home App the Slider has to be used (or voice command) to operate the devices.

It would be awesome to either have the devices working normally when using blindMode=false in the way, that closing the device loweres the blinds and have the shingles stay closed fully (no light comes in) and when raising the blinds fully have it keep the topmost position without "tilting the blinds" (lowering again a little bit after having reached the topmost position). 
Or when using blindMode=true have the Apple Home App display the correct status for the devices ("Open" when in topmost position and "Closed" when in lowest position).

Thanks for looking into it.

Regards,
Matt

**Comment by bigmadf** [comment]
Hi there,

I just upgraded my HomeKit installation to HomeKit 1.1 and reverted to Homebridge-tahoma version **0.3.34 (a7e66cd)**. With blindMode=false (default values for initPosition and defaultPosition) behavior is now as expected. 
I have not tried latest HomeKit Version in combination with homebridge-tahoma 0.3.35. 
My suspicion is, that with the introduction of the scene handling with latest two commits something broke.

Regards,
Matt

**Comment by dubocr** [comment]
Hi,

Can you log there : https://dev.duboc.pro/tahoma and give me the last 4 digit of your bridge.

Thanks

**Comment by bigmadf** [comment]
Hi,

I just logged in under https://dev.duboc.pro/tahoma. Last four digits of bridge are: 2646.
Regards,
Matt

**Comment by dubocr** [comment]
OK your blinds are IO so defaultPosition is not used (it's only usefull for 1-way devices). What you want is to change the tilt angle of your blinds.
Until last version, there were an issue and tilt angle were not maintained. Now tilt angle is maintained and I think it's what you see. If you whant to fully close you blind, just change the tilt angle in Homekit (in your blind option, move the slider to the right).

**Comment by bigmadf** [comment]
Hey, thanks for your input. I now went back to master branch so 0.3.35 with newest HomeKit version.
Position is topmost.
Action is "close the device"
Here is the output from HomeKit.
[6/15/2020, 4:26:48 PM] [Tahoma] [<DeviceName>] setClosureAndOrientation[100,0]                          
[6/15/2020, 4:27:28 PM] [Tahoma] [<DeviceName] setClosureAndOrientation COMPLETED

Now the device is in lowest Position, blind angle is "fully open" --> expectation is (as with 0.3.34) that the blinds are fully shut.

Action is "open the device".                                                                                                                                      
[6/15/2020, 4:27:36 PM] [Tahoma] [<DeviceName] setClosureAndOrientation[0,0]                                                                                                                                           
[6/15/2020, 4:28:13 PM] [Tahoma] [<DeviceName] setClosureAndOrientation COMPLETED     

Now the device is in the topmost position, as expected.

Sure, you are right, I can adjust the blind angle separately when the desired position is reached. But when I close the device I expect to no light pass through. So from my perspective when calling  setClosureAndOrientation with first parameter 100, then the second parameter should be 100 as well. Then the device would be in the lowest position, with blind angle "fully closed".

Until now I will go back to 0.3.34.
I can test and switch back and forth easily.

Thanks for looking into it!
Regards,
Matt

**Comment by bigmadf** [comment]
I repeated the action sequence described above with version 0.3.34.
[6/15/2020, 4:49:40 PM] [Tahoma] [<Devicename>] setClosure[100]                                                                                                                                                         
[6/15/2020, 4:50:21 PM] [Tahoma] [<Devicename>] setClosure COMPLETED                                                                                                                                                    
[6/15/2020, 4:50:46 PM] [Tahoma] [<Devicename>] setClosure[0]
[6/15/2020, 4:51:26 PM] [Tahoma] [<Devicename>] setClosure COMPLETED

**Comment by dubocr** [comment]
I understand but some people may want to close fully (deploy fully) while keeping orientation.
When you use it in automation, both closure and angle is set so I have to use setClosureAndOrientation to make sure the orientation is well set.
I've made some improvement to detect if only closure is set (eg. via voice command) or both closure and orientation (eg. in automation) to execute the best command.

That's not perfect for those who prefers Homekit behavior but as you said TaHoma fully close both closure and orientation it will be expected behavior for most people.

**Comment by dubocr** [comment]
Hi,

You will have to modify your config to keep the full close behaviour starting the latest version as I can't obtain a common behaviour for every people.

Please add the folowing options in your config file.

			"WindowCovering": {
				"blindMode": "closure"
			}
