### ISSUE TITLE
Execute scene

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#182]
Bonjour Romain,
Depuis la dernière mise à jour (je crois) dans l’historique Tahoma, ça affiche « execute scene » alors qu’avant ça affichait le nom de l’équipement piloté avec la commande demandée ou le nom du scénario.
Ce n’est pas grave en soit mais ça serait cool de savoir ce qui est demandé à Tahoma dans l’historique.

**Comment by Tontonpat** [comment]
![99621AD2-20DE-4DDB-8856-7954C382CC04](https://user-images.githubusercontent.com/49283285/84873162-22d7e500-b083-11ea-811b-ba6526d5970d.jpeg)

**Comment by dubocr** [comment]
Bonjour,

Oui lorsqu'il y a plusieurs exécutions simultanée (scenes HomeKit par ex) elles sont désormais regroupées afin de pouvoir dépasser la limite de 10 commandes simultanées. Du coup il m'est difficile de donner le nom d'un device puisqu'ils sont plusieurs à être commandés. Par contre tu as le détails des devices dans le détails de l’exécution. Malheureusement je ne peux pas metre le nom de la scène car ce n'est pas une info transmise par HomeKit.

Je peux éventuellement rajouter des infos si tu as une idée des quelles (nombre de device ?, nom du 1er de la liste ?)

**Comment by Tontonpat** [comment]
Merci pour ta réponse rapide.
En fait, même si j’actionne qu’un seul équipement ça m’affiche « execute scene ».
Par contre si il s’agit d’un automatisme HomeKit ça affiche bien le détail avec le nom de chaque équipement. Sur la capture d’écran, les actions qui n’ont pas le + sont des actions sur un seul équipement

**Comment by dubocr** [comment]
Pardon je n'avais pas vu l'absence de "+" sur ton image. Effectivement je viens de corriger le problème ça devrait être bon sur la dernières version.

Merci

**Comment by Tontonpat** [comment]
Parfait comme d’habitude !!
Merci pour ta réactivité.
![91FDDD20-5600-4EAB-81C5-5102CBA09DB1](https://user-images.githubusercontent.com/49283285/84889801-caf8a880-b099-11ea-9fc1-bebdfa56f10e.jpeg)
