### ISSUE TITLE
Reverse status for blinds window/roof and windows opener

### ISSUE THREAD

**Issue by trolli-ch** [dubocr/homebridge-tahoma#183]
Hi !
Thanks for providing this plugin. Its really cool to have this also in the Homekit.

I have an issue with the (reverse) status of my blinds.

I have 2 blinds on the side (vertical blinds group), 1 blind at the roof and two tilt windows (terrace blinds group). All controlled by Tahoma.
When the blinds on the side are up (which should be open) it will show them as closed (blinds down).
They are not affected by WindowCovering or GarageDoorOpener set to reverse: "true"
Can I also control each blind with the config ?

The roof blind and tilted windows are correct displayed.

----snip----
"WindowCovering": {
                "reverse": "true"
            },
            "GarageDoorOpener": {
                "reverse": "true"
----snip----

Thanks
Sascha

**Comment by dubocr** [comment]
Hi, You'll normaly be able to specify the config of one blind like that :
"BlindName": {
"reverse": "true"
}

With BlindName, the name in TaHoma.

**Comment by trolli-ch** [comment]
Great. Now its working how I need it.
Thanks !

Do you know what polling period time is acceptable to not be blocked ?
60 seconds too much ?


On 24 Jun 2020, at 13:05, Romain DUBOC <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi, You'll normaly be able to specify the config of one blind like that :
"BlindName": {
"reverse": "true"
}

With BlindName, the name in TaHoma.

**Comment by dubocr** [comment]
I think you could set 60 sec pollingPeriod it's technically acceptable.

**Comment by marekzrostlik** [comment]
Hello is there a way, how to make Apple Home app to display oppositely the status of my Venetian blinds? I mean, Home shows my blinds as Open even though they are pulled down = closed. The way I use the blinds, they are permanently down-closed and during the day I only modify the orientation of lamels.

**Comment by dubocr** [comment]
I,
you can use the blind mode in your config :

```
"BlindName": {
"blindMode": "orientation"
}
```

With "BlindName", the name of your blind in Home

**Comment by marekzrostlik** [comment]
Hello, thanks for the quick feedback and tip!

Below I attach my plugin config. May I did not place the section with specific name of concrete blinds correctly? However the blinds show so far both in Apple Home and in Homebridge as open. Even though they are drawn down, i.e. closed. Modification of lamels orientation works well.

Any idea what else could be done to show the status oppositelly?  I.e. when drawns down, shown as closed?

Thanks

<img width="335" alt="image" src="https://user-images.githubusercontent.com/77804367/105884203-02540e00-6008-11eb-8d43-16da4597a0ab.png">

**Comment by dubocr** [comment]
Like that :

```
"WindowCovering": {
"blindMode": "orientation",
"reverse": true,
...
}

"Zaluzie pracovna": {
 "blindMode": "closure"
 "reverse": true
}
```

But prefer a more specific description than "WindowCovering" (like "PositionableHorizontalAwning" in the following example. You can get it in the log at startup 
[1/27/2021, 9:32:15 AM] [TaHoma] [DeviceName] type: WindowCovering > PositionableHorizontalAwning, protocol: io

Then
```
"PositionableHorizontalAwning": {
"blindMode": "orientation",
"reverse": true,
"initPosition": 0,
"defaultPosition": 0,
}

"Zaluzie pracovna": {
 "blindMode": "closure"
 "reverse": true
}
```

**Comment by dubocr** [comment]
And I advise you to change your password as it was exposed in your screenshot.
