### ISSUE TITLE
HOOBS crashing at 8 AM because of Tahoma

### ISSUE THREAD

**Issue by Ciarals84** [dubocr/homebridge-tahoma#184]
Hello. Strange thing is happening on my HOOBS every morning at 8 AM. This is the log:

<img width="1349" alt="HOOBS" src="https://user-images.githubusercontent.com/67325842/85409432-14e40180-b566-11ea-95bd-14552b76774a.png">

As you see, the guilty plugin is Tahoma: in just 2 seconds everything crashes. The strange thing is that it says "Too many operations in progress" but at 8 AM it just have to do one thing: open the bedroom window ("Finestra letto"). Just one. And all days at 8 AM it goes like this.

In the other times of the day it closes and opens more than 15 devices at the same time, so I really don't know what is happening at that time.

I've asked Ovi @ hoobs.org and he said: The error seems to be related to the overkiz API which I assume is what the plugin is using. You should ask the developer directly on their github page why that’s happening.

So... Do you have any hint for me? What could it be?

Thank you! :-)

**Comment by dubocr** [comment]
Fixed in next release.

**Comment by Ciarals84** [comment]
Hello, thank you for your reply. Unfortunately today it did the same crash with the same errors in the previous log. I'm with latest version.

**Comment by dubocr** [comment]
Can you send me the line 30 of file overkiz-api.js please.

Thanks

**Comment by Ciarals84** [comment]
> Can you send me the line 30 of file overkiz-api.js please.
> 
> Thanks

If you tell me how to do that I will be happy to do that :-) I'm under HOOBS in a Box. Thank you!

**Comment by dubocr** [comment]
Are you sure the plugin is up to date or the error is the same ?

Thanks.

**Comment by Ciarals84** [comment]
Yes of course. The plugin version is 0.3.44. And here's what happens at 8 AM:

`26/6/2020, 08:00:01 [Miller TaHoma] [Finestra letto] setClosure[20]
26/6/2020, 08:00:01 [Miller TaHoma] Login TaHoma server...
26/6/2020, 08:00:02 [Miller TaHoma] Error 429 Server busy, please try again later. (Too many executions) (TOO_MANY_OPERATIONS_IN_PROGRESS)
26/6/2020, 08:00:02 TypeError: Cannot read property 'failedCommands' of undefined
    at OverkizDevice.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-tahoma/overkiz-device.js:146:40)
    at Queue.callback (/home/hoobs/.hoobs/node_modules/homebridge-tahoma/overkiz-api.js:46:25)
    at /home/hoobs/.hoobs/node_modules/homebridge-tahoma/overkiz-api.js:483:17
    at Request.authCallback [as _callback] (/home/hoobs/.hoobs/node_modules/homebridge-tahoma/overkiz-api.js:325:17)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
26/6/2020, 08:00:02 Got SIGTERM, shutting down Bridge...`

**Comment by dubocr** [comment]
Thanks, the error was different.
You can try with latest release. But this will only fix the bug, not the error. Yes I think you could try to move this exec ton another time to avoid server error.

If the bug always here, please log there : http://dev.duboc.pro/tahoma/login

Thanks

**Comment by Ciarals84** [comment]
> Thanks, the error was different.
> You can try with latest release. But this will only fix the bug, not the error. Yes I think you could try to move this exec ton another time to avoid server error.
> 
> If the bug always here, please log there : http://dev.duboc.pro/tahoma/login
> 
> Thanks

Thank you, I've installed the latest release and change the time from 8 AM to 8.05 AM. Is really the error depending on 8 AM? Does it make any sense?

I've also logged on the link you have provided. Do you see it or should I send it to you?

**Comment by dubocr** [comment]
As the server return an error too many operation', may there is other exec at this time. You could try.
Yes please send me the SETUP-XXXX-XXXX-XXXX of your bridge.

Thanks.

**Comment by Ciarals84** [comment]
> As the server return an error too many operation', may there is other exec at this time. You could try.
> Yes please send me the SETUP-XXXX-XXXX-XXXX of your bridge.
> 
> Thanks.

There's nothing else at 8 AM, that is the strange thing.

Please tell me the passages to give you the SETUP-XXXX-XXXX-XXXX, thank you.

**Comment by Ciarals84** [comment]
Hello. Just to update you that, with latest plugin updates and change from 8 AM to 8.05 AM, the problem seems to be solved.

Anyway, please tell me the passages to give you the SETUP-XXXX-XXXX-XXXX so that I can provide you the precise logs of my system.

Thank you!
