### ISSUE TITLE
Blinds not closing fully with bd7d0c2 (master)

### ISSUE THREAD

**Issue by bigmadf** [dubocr/homebridge-tahoma#186]
Hi

You just fixed that the blinds will fully close when using „blindMode“: false. That does not work anymore on master with blindMode not set or set to „closure“.
blindMode „orientation“ does not work for me since HomeKit displays the blinds as closed when fully opened and as opened when fully closed. This is confusing. BlindMode „closure“ would work for me but the orientation (blind angle) is always fully opened.
I am back to 0.3.40 for now with blindMode not set in config. Thanks for looking into it.

Regards,
Matt

**Comment by dubocr** [comment]
Here is the config :
"WindowCovering": {
"blindMode": "closure"
}

In this mode, blind will deploy and tilt to fully close.

**Comment by bigmadf** [comment]
Works as expected now (blindMode: closure) with 0.3.45.
Thanks a lot!
