### ISSUE TITLE
HOOBS crashing at 8 AM because of Tahoma (not solved)

### ISSUE THREAD

**Issue by Ciarals84** [dubocr/homebridge-tahoma#187]
Fixed in next release.

_Originally posted by @dubocr in https://github.com/dubocr/homebridge-tahoma/issues/184#issuecomment-648752900_

Hello. Sorry for bothering you again but it has NOT been solved in latest release. Today at 8 AM the problem was still there. Thank you!

**Comment by Ciarals84** [comment]
P.S.: log file is the same as previous. You can find it in my previous closed post.

**Comment by dubocr** [comment]
Duplicate #184
