### ISSUE TITLE
blindMode ignored when setting closure via automation

### ISSUE THREAD

**Issue by mman** [dubocr/homebridge-tahoma#188]
I use all my blinds in blindMode: orientation to control both closure and orientation via one slider.

Works for Siri (set blind to 70% will close to 100% and allow 70% light throughput)

Works for manual dragging of closure slider in home App

Does not work in scene mode.

Good night Siri should set one of my blinds to 70% meaning closure to 100 and orientation to 70% light Throughout but instead I see in the log

SetClosureAndOrientation(70, 0).

This used to work in the old blindMode:true

Thanks for listening
Martin

**Comment by dubocr** [comment]
Hi Martin,

Should be better in latest release. I disable angle slider in blind mode.
