### ISSUE TITLE
What are the supported services?

### ISSUE THREAD

**Issue by Siriusmac** [dubocr/homebridge-tahoma#189]
Hello, great plugin it saved my day (i made a small donation some days ago, not enough to pay your work but i have just lost mine because of the pandemic...) 
I have 9 altus io motors connected to a Connexoon Window. I added an Izymo io receiver to control an old awning. It works flawlessly but it is seen by the Connexoon as a roller shutter. Not a problem so i tryed the “forcetype” In your plugin configuration but every word i put in, i have the same result: Service XXX  not implemented. 
I tried with Curtain, Blind, Shade, Solarblind, Awning and Sunscreen.
So what are the Implemented services I can use? 
I changed the icon in Home but the the status is still “open” for closed and vice versa. Setting the correct tipe of device directly in homebridge should solve the issue.
Thank you

**Comment by dubocr** [comment]
Hi,

Thank you for your donation and support, hope you will find a better job soon.
Homekit only have on type of device for Curtain, Blind, Shade, Awning... You have the good one and changing the icon is what you need.
To reverse the behaviour, you'll have to add this in your config file :
"DeviceName": { "reverse": true }

Best,

**Comment by Siriusmac** [comment]
Thank you for the answer but i tried also the reverse. The result is still incoherent: when the awning is closed (fully retracted So light comes in) the status in homekit it’s correct (closed) but the slider it’s reversed, as it was fully extended. So without the reverse command i have to ask Siri to open if i want to close, with the reverse the only way to interact through siri it’s “put at xx%” remembering every time that the percentage it’s reversed...

**Comment by dubocr** [comment]
Hi,
When you write `slider it’s reversed`, you mean the orientation slider ?

Can you log at `https://dev.duboc.pro` to let me see your config.

Thanks

**Comment by Siriusmac** [comment]
Ok, may be only a translation problem In Home but the awning, when it’s fully retracted, in italian we say “closed”. Without the reverse, the slider it’s correct but the status description it’s wrong. For example: it says “open at 5%” as it was a roller shutter, but it should be “open at 95%” because an awning extended at 95% of its lenght it’s considered open. It seems something meaningless but when you are talking with Siri it’s all reversed. This afternoon my wife wanted to retract the awning from remote because of the incoming rain, she told Siri “close the awning”, so it kept extending untill 100%... 
![5BEC99F8-CC27-4707-9111-7B121D9EF140](https://user-images.githubusercontent.com/11944929/87713923-4342ae80-c7ab-11ea-9a17-7f0bf4de2027.jpeg) 
This is my “closed” awning...
![D4C9FB26-247B-485F-B584-CF45513F30A9](https://user-images.githubusercontent.com/11944929/87713970-58b7d880-c7ab-11ea-9c2f-0fa71506cee6.png)
As you can see, the slider it’s correct but the status it’s “open”

If i put true on reverse, the status become correct but the icon and the slider are reversed. I thought that forcing the correct type of device (awning instead of roller shutter) In Hoobs it would have behaved correctly in Home. But if it’s only a lost in translation problem, we can’t do anything...

**Comment by Siriusmac** [comment]
"SETUP-0820-1547-3229"

**Comment by dubocr** [comment]
Oh OK sorry I was not aware of this. Yes in fact here is the "normal" behaviour :
- Hey Siri, open the XXX: will put the slider to "open","retracted" (as your screenshot) **and** put device to 0% closure
- Hey Siri, close the XXX: will put the slider to "close","deployed" **and** put device to 100% closure

With "reverse" parameter, you can only reverse the behaviour beetwen the two part before and after **and** in my last sentences.
What you expected is reversing matching between "open"<->"retracted" and "close"<->"deployed". Effectivelly it's an Homekit behaviour and I don't see anything in Homebridge that allow me to change that.

You're right, when setting icon to "awning" one, you can expect a changes in UI/Siri matching. May it'll be improved in future.
