### ISSUE TITLE
Mark accessories as not working when Tahoma API is down

### ISSUE THREAD

**Issue by iRonin** [dubocr/homebridge-tahoma#19]
Couple of weeks ago Tahoma API was down a couple of times and it wasn't clear why my accessories are not responding.
When the Tahoma API is down the accessories should be reported as not responding.
See https://github.com/nfarina/homebridge/issues/1651

**Comment by lboue** [comment]
Bonjour,

Pourriez-vous me dire si la tentative à fonctionné ? 
En effet, j'au vu un commit https://github.com/dubocr/homebridge-tahoma/commit/165c4474ea6dfea324dec984bb59e1492ccb8c3f il y'a 3j à ce sujet.

Ludovic

**Comment by lboue** [comment]
C'est curieux, le Bridge V2 Philips Hue est capable de marquer les accessoire (ampoules Hue) lorsque l’alimentation électrique est coupée. 
![img_0262](https://user-images.githubusercontent.com/938089/43989209-8da639e8-9d45-11e8-8230-0afb2a7761b9.jpg)

On devrait pouvoir reproduire un comportement identique, non ?

Ludovic

**Comment by dubocr** [comment]
Je ne dis pas que ce n’est pas possible mais qu’il a fallut choisir entre cette fonction et une autre car le fonctionnement de l’API tahoma n’est pas forcément adaptée à l’utilisation avec Homebridge.

Pour reproduire le comportement observé avec les ampoules, tu peux comme indiqué modifier la ligne 38.

Par ailleurs, le hub Hue est « nativement » compatible HomeKit et ne passe donc pas par homebridge. Toutes les fonctions HomeKit ne sont pas forcément disponibles sur HomeKit (c’est le cas des scénarios il me semble).

Enfin si tu ouvres Home, que tu coupe l’alimentation de l’ampoule et que tu essaie de l'allumer/éteindre tu constateras qu’aucun message d’erreur n’apparaît. Je pense que celui que tu observes n’apparait que losque tu ouvres à nouveau l’app après un certain temps.
Pour obtenir ce comportement, il faudrait implémenter l’interrogation du capteur à chaque requête homekit (au lieu de retourner le dernier état connu) mais là encore je pense que cela ne fonctionnerait que pour l’API down et pas dans le cas d’un volet débranché (car seule une action sur le volet nous permet de savoir si il est OK/KO)

**Comment by lboue** [comment]
Merci pour tes explications très détaillées :-). Je vais tester ça. 

Oui je suis d'accord le Hue n'utilise pas Homebridge. Justement, je cherchais à savoir s'il existe un outil qui permette de visualiser/déboguer l'état des variables d'un accessoire HAP.

J'avoue la documentation HAP n'est pas très claire à ce sujet.
