### ISSUE TITLE
Login fail: Too many requests

### ISSUE THREAD

**Issue by sebnaf** [dubocr/homebridge-tahoma#190]
Starting approx 14 days ago, the integration stopped working without any settings beeing changed.

`Jul 15 15:19:55 homebridge.ohw3 homebridge[15730]: [15.7.2020, 15:19:55] [Somfy] Login fail: Too many requests, try again later : login with xyz.xyz.xyz
Jul 15 15:19:55 homebridge.ohw3 homebridge[15730]: [15.7.2020, 15:19:55] [Somfy] Fail to retrieve accessories, retry in 30 sec...`

Did somfy change something on their side?

Config - as is for almost a year:

`            "platform": "Tahoma",
            "name": "Somfy",
            "user": "user",
            "password": "pass",
            "refreshPeriod": "1800",
            "blindMode": "orientation",
            "exposeScenarios": true`

**Comment by sebnaf** [comment]
It seems like the latest homebridge needs node 12…

**Comment by RaoulHk** [comment]
I have also not been able to use the plugin under Hoobs for a few days now.

**Comment by dubocr** [comment]
Hi,

Do you have `pollingPeriod` set in your config ?
Did you try to completelly stop plugin during more than 24h then start it and check if startup succeed ?

**Comment by RaoulHk** [comment]
No, I didn’t config pollingPeriod. With what settings should i set it? It worked month till the last update.

**Comment by RaoulHk** [comment]
[My TaHoma Box] Unable to login: Error: getaddrinfo EAI_AGAIN tahomalink.com tahomalink.com:443

This is what I get.

**Comment by dubocr** [comment]
> No, I didn’t config pollingPeriod. With what settings should i set it? It worked month till the last update.

No you don't have to set it. I ask just to check you don't have it. Your last error is a network error. May you can `ping tahomalink.com` and resolve this if it fail. If fail to ping tahomalink.com, try `ping ha101-1.overkiz.com`
