### ISSUE TITLE
ExteriorVenetianBlind > UpDownExteriorVenetianBlind

### ISSUE THREAD

**Issue by cwatkins94** [dubocr/homebridge-tahoma#191]
Hello,

Thank you for such a wonderful homebridge plugin. Forgive me if this is a stupid question, but I have an RTS tilt and lift venetian blind - am I able to set the tilt manually using this plugin, or am I limited to selection of 'open', 'close' and 'my'?

**Comment by dubocr** [comment]
Thank you for using Homebridge TaHoma plugin.

Please follow these step to obtain better support :
1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)

Thank you.

**Comment by cwatkins94** [comment]
Hi there - thanks for following up with the steps! 

ExteriorVenetianBlind > UpDownExteriorVenetianBlind
Bridge ID last 4 digits: 4394
config: "devicesConfig": [
                {
                    "key": "Blind",
                    "blindMode": true,
                    "defaultPosition": 50,
                    "movementDuration": 22
                }

I see there is now a configuration for movementDuration, which I assume allows you to set relative position for RTS blinds, although I can't seem to get this to work with my blind, Homebridge logs are still showing close(), my(), and open() functions based on percentage, rather than setting relative position.

Is this possible on this type of blind?

Thank you!

**Comment by dubocr** [comment]
Hi,

This feature will be available for VenetianBlind in 2.1.26 (tonight). But blindMode is only available for IO blinds.
I'll add tilt feature in the next days too. I'll keep you informed.

**Comment by cwatkins94** [comment]
Thank you! Updated this evening and it’s working great so far. 😊

**Comment by dubocr** [comment]
Hi @cwatkins94,

I'm looking for commands used to tilt blinds. Can I ask you to operate tilt commands from your TaHoma app then log to https://dev.duboc.pro/tahoma ?

Thanks in advance.

**Comment by cwatkins94** [comment]
Hi @dubocr,

There isn’t actually a tilt command in the app, only up/my/down (and then stop, if you’re fast enough to stop, you can set the tilt).

With the remote, if you hold down either the up or down buttons, the motor moves more slowly and this is what allows you to set the tilt.

I imagine it might work in a similar fashion with setting the position approximately based on the time to fully open, I don’t know if you’re able to send the stop signals fast enough to approximate a tilt angle as well using a separate slider? Probably takes about 3 seconds on the slower motor speed from a closed tilted position (downwards) to a closed tilted position (upwards). Using the normal motor speed, it’s probably about 1 second.

Hope that helps? Happy to discuss further if necessary!
