### ISSUE TITLE
Hitachi Heating/Cooling System state isue

### ISSUE THREAD

**Issue by Blaster681** [dubocr/homebridge-tahoma#193]
Bonjour,

J'ai fais installé un nouveau Gainable Hitachi avec interface somfy.
L'état de l'appareil est toujours afficher OFF et il est impossible de l'allumer via HomeKit. Par contre si je l'allume via l'app sompfy je peux règler la température.

J'ai esseiler de me connecter sur https://dev.duboc.pro/tahoma mais une erreur s'affiche.

Dans l'historique TaHoma j'ai comme erreur sur la commande HomeKit -> L'action sur l'équipement a été annulée.

Merci d'avance pour votre aide.

Cordialement

**Comment by dubocr** [comment]
Bonjour,
Je vais (enfin) pouvoir regarder ce problème avec la dernière version.
Pouvez-vous réessayer de vous connecter à la page et me donner les 4 derniers chiffres de votre bridge.
Avant de vous connecter, exécutez les commandes principales depuis TaHoma / Cozytouch (on/off/changement de Tº) pour que je puisse les voir dans l’historique et les reproduire.

Merci.
