### ISSUE TITLE
Reverse and Procent

### ISSUE THREAD

**Issue by Teclini** [dubocr/homebridge-tahoma#195]
Hi 
I have a Problem with the Setting of a Roller Shutter. The status of open and close is correct, but if I want to open the shutter 10 % I must say open shutter door 90%. Is there a way to change this ? if I use reverse, the Percent works right but the open and close is also change. The open command will close and close will open. I only want to change the Procent.
I want that when I say Siri Shutter 10 % only 10% is close and not 90% 
Hope you understand me.

**Comment by dubocr** [comment]
Hi,

Can you log there : https://dev.duboc.pro/ and give me your SETUP-XXXX-XXXX-XXXX number after executing 1 open, 1 close and 1 X% command with your **TaHoma app**.

Thank you.
