### ISSUE TITLE
Reserve WindowCovering at just one element

### ISSUE THREAD

**Issue by Stefan-83** [dubocr/homebridge-tahoma#196]
Hi, 
i've two window covering elements:
![image](https://user-images.githubusercontent.com/52136837/90175463-c1dd3c80-dda7-11ea-82d3-b2a039b755c7.png)

I need to reverse one of them. Is this possible with the reverse-parameter for just one element?
If yes, how to setup in the config.json?

Thanks,
Stefan

**Comment by Stefan-83** [comment]
No ideas?

**Comment by dubocr** [comment]
Hi,
You can try with name :
"MAESTRIA+io": {
    "reverse": true
}
