### ISSUE TITLE
Refresh, Initial Position and Excluding Alarm

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#197]
Hi,

Thanks for the plug-in, I can't seem to exclude the alarm from appearing in homekit, how do I do this? also the Inititial position and refresh settings don't seem to work, is my code correct? Thanks in advance?

{
    "platform": "Tahoma",
    "name": "My TaHoma Box",
    "initPosition": "100",
    "refreshPeriod": "500",
    "user": "XXXXXXXX@XX.com",
    "password": "XXXXXXX"
}

**Comment by trolli-ch** [comment]
For Alarm see this post -> https://github.com/dubocr/homebridge-tahoma/issues/199
