### ISSUE TITLE
WaterHeatingSystem > DomesticHotWaterProduction

### ISSUE THREAD

**Issue by Yodacoole** [dubocr/homebridge-tahoma#198]
Bonjour,

Utilisant le plugins homebridge-tahoma, j'aimerai piloter le chauffe eau thermodynamique, via le home bridge par programmation, de ce que ne peut faire l'apps Atlantic.

Je suis allé sur https://dev.duboc.pro/tools/setup pour savoir si je pouvais charger ma configuration et cela sans problème. 

Par contre un petit coup de main serait la bienvenu pour attribuer dans le json des options complémentaire à cette gestion.

Si cela vous est possible, et vous remerciant d'avance,
Cordialement,

**Comment by hitch3478** [comment]
Bonsoir,
Avez-vous pu avancer ?
JE suis bloquer comme vous.
Merci

**Comment by dubocr** [comment]
Bonjour,

pouvez-vous le transmettre les 4 derniers chiffres de votre bridge après avoir consulté la page dev.duboc.pro

merci

**Comment by hitch3478** [comment]
Bonsoir
Merci pour votre retour
J’ai consulté le site et voici les 4 derniers chiffres
4742
Merci pour votre aide
Cdt
Sebastien

Le lun. 18 janv. 2021 à 21:30, Romain DUBOC <notifications@github.com> a
écrit :

**Comment by dubocr** [comment]
Merci,

S'agissant d'un chauffe-eau via PASS APC il devrait à minima apparaitre comme un thermostat + un switch pour l'activation du boost sur HomeKit. Le nom (modifiable sur HomeKit) est "IO (15793876#2)". Pouvez-vous me confirmer cela et m'indiquer ce qui pose problème ?

Merci d'avance.

**Comment by Yodacoole** [comment]
Bonsoir,
Merci pour vos conseils et vos recherches. Désolé de n'avoir pas pu vous répondre au plus tot.
Mon chauffe eau est un lineo atlantic.  IO (14886293#2).
J'ai bien un thermostat + Switch pour l'activation du boost sur homekit
Mon code a 4 chiffre est 1433.

**Comment by hitch3478** [comment]
Bonjour remi
Merci pour le retour. Cependant je dispose de 2 thermostat. Le IO
(15793876#2) faut-il qu'il soit mis dans le plugin ?
Et au demarrage du plugin j'ai surtout ca qui me gene
Error: You must provide credentials ('user'/'password')
Or mes credentials sont correctes à 200 %
Désolé de repondre que maintenant mais je suis a la maison que le week-end.
Cdt
Sebastien

Le lun. 18 janv. 2021 à 21:43, Romain DUBOC <notifications@github.com> a
écrit :

**Comment by hitch3478** [comment]
> Bonsoir,
> Merci pour vos conseils et vos recherches. Désolé de n'avoir pas pu vous répondre au plustot.
> En consultant mon homebridge j'ai 1433.

salut yodacoole 
aS-tu l'erreur de credentials a l'installation du plugin ?
Merci

**Comment by Yodacoole** [comment]
Bonjour Hitch3478,

Non je n'ai pas d'erreur de connexion.
As tu correctement définit le service dans le json

"service": "Cozytouch",

**Comment by Yodacoole** [comment]
Romain,
Sur le homebridge je visualise correctement un cadran indiquant la possibilité de modifier le thermostat, ainsi que les options boost, automatic, chauffe, eteint, mais ne valide pas les modifications.

Y a t il d'autres options que je dois compléter ?

    "service": "Cozytouch",
    "refreshPeriod": 5,
    "exposeScenarios": "True"

Je n'ai pas trouvé d'option genre : boost =On / Off

En fait le cozitouch ne gère pas de planification HC/HP, j'aimerais pouvoir l'effectuer avec homekit

Est ce possible ?

Vous remerciant d'avance,

**Comment by hitch3478** [comment]
Romain,
Je confirme effectivement ce que dis Yodacoole. Quand je modifie les valeurs cela n'a aucun effet sur les thermostats.
Merci pour ton aide.

**Comment by Yodacoole** [comment]
Bonsoir,

Sur le chauffe eau j'ai plusieurs état de marche depuis le cozytouch.

Boost, Boost+, Auto, manual (choix 1 a 4 pour les douches)

![image](https://user-images.githubusercontent.com/70021390/105777957-a9369c80-5f6b-11eb-86cf-aeb95675e4d0.png)

**Comment by dubocr** [comment]
Je ne sais même pas comment ils font pour s'y retrouver avec l'application officielle. Il y à effectivement une 3eme façon d'activer le boost sur ces chauffe-eau. J'ai passé celle-ci en N°1 sur la dernier version. Vous pouvez essayer après MàJ du plugin.
En ce qui concerne la programmation, cela reviendra à changer le mode avec des automatisations homekit.

**Comment by Yodacoole** [comment]
Bonjour Romain,

Merci Romaine, j'ai du mieux effectivement j'arrive a interagir sur les options eteint, chauffe, automatique.
Du moins le mode Chauffe qui active le mode boost.
Le soucis qu'il me reste est que quand je choisis l'option chauffe, cela active bien le mode boost, mais seulement pour quelques secondes.

Dans le json, y a t il une option complémentaire a rajouter ?

Vous remerciant,

**Comment by dubocr** [comment]
Pouvez-vous réaliser les différentes opérations sur l'appli cozytouch (activation boost, désactivation, ...) puis vous reconnecter sur la page https://dev.duboc.pro/tahoma cela me permettra de voir les commandes utilisées dans l'historique.

Merci

**Comment by Yodacoole** [comment]
Activation (Chauffe) :

DHWP Actuator - setBoostMode["on"] - COMPLETED

Désactivation (Automatique) :
DHWP Actuator - setBoostMode["off"] - COMPLETED
DHWP Actuator - setAbsenceMode["off"] - COMPLETED

Mode Eteint :
DHWP Actuator - setAbsenceMode["on"] - COMPLETED

Est ce que cela vous suffit ou faut il que je colle tout le debug ?

**Comment by dubocr** [comment]
C'est bon sur le principe par contre c'était à faire avec l'application Cozytouch. Pour voir les bonnes commandes qui sont transmises.

Merci.

**Comment by hitch3478** [comment]
> Activation (Chauffe) :
> 
> 
> 
> DHWP Actuator - setBoostMode["on"] - COMPLETED
> 
> 
> 
> Désactivation (Automatique) :
> 
> DHWP Actuator - setBoostMode["off"] - COMPLETED
> 
> DHWP Actuator - setAbsenceMode["off"] - COMPLETED
> 
> 
> 
> Mode Eteint :
> 
> DHWP Actuator - setAbsenceMode["on"] - COMPLETED
> 
> 
> 
> Est ce que cela vous suffit ou faut il que je colle tout le debug ?
> 
> 

Tu pourras me dire ce que tu as rajouté pour que les modifs fonctionnent à partir de HomeKit ? Si je modifie la valeur sous HomeKit elle n'est pas prise en compte sous cozytouch ? Merci

**Comment by Yodacoole** [comment]
Pardon, j'avais zappé la précision de votre demande....

Depuis cozytouch donc :

Mode Boost
![image](https://user-images.githubusercontent.com/70021390/105869222-4c80c380-5ff7-11eb-8502-5e23b04328fd.png)

Mode Boost+
![image](https://user-images.githubusercontent.com/70021390/105869318-64f0de00-5ff7-11eb-93f2-0997d8cc2bf3.png)

Desactivation Boost+
![image](https://user-images.githubusercontent.com/70021390/105869413-7e922580-5ff7-11eb-9503-72cc6c0ab3d9.png)

Mode Manuel :
![image](https://user-images.githubusercontent.com/70021390/105869505-98cc0380-5ff7-11eb-96ad-a0a2eec6b437.png)

Mode manuel choix des douches 1 a 4 : (ici choix 3)
![image](https://user-images.githubusercontent.com/70021390/105869624-b5683b80-5ff7-11eb-8cf1-e53a797f91f2.png)

Je pense avoir faire le tour
Merci

**Comment by Yodacoole** [comment]
> > Activation (Chauffe) :
> > DHWP Actuator - setBoostMode["on"] - COMPLETED
> > Désactivation (Automatique) :
> > DHWP Actuator - setBoostMode["off"] - COMPLETED
> > DHWP Actuator - setAbsenceMode["off"] - COMPLETED
> > Mode Eteint :
> > DHWP Actuator - setAbsenceMode["on"] - COMPLETED
> > Est ce que cela vous suffit ou faut il que je colle tout le debug ?
> 
> Tu pourras me dire ce que tu as rajouté pour que les modifs fonctionnent à partir de HomeKit ? Si je modifie la valeur sous HomeKit elle n'est pas prise en compte sous cozytouch ? Merci

Hitch :
Rien Romain a fait une update du code pour que cela soit pris en compte.
J'ai juste :
{
    "platform": "Tahoma",
     "user": "blabla",
    "password": "blabla",
    "service": "Cozytouch",
    "exposeScenarios": "True",
    "pollingPeriod": "5"
}

**Comment by hitch3478** [comment]
Ok merci 👍👍👍

Le mar. 26 janv. 2021 à 17:04, Yodacoole <notifications@github.com> a
écrit :

**Comment by Yodacoole** [comment]
Romain 
Tu es un chef, Super merci je viens de voire l'update et sur homekit les options ne scroll plus.

Grand merci,
Si tu veux un don pas de soucis, se sera avec grand plaisir.
Nikel

**Comment by dubocr** [comment]
Oula je ne suis pas sur d'avoir suivi :-). Quelles options ?
Concernant le boost, entre l'activation via Cozytouch et l'activation via Homekit (en passant en mode "chauffage") la durée n'est pas la même du coup ?

**Comment by Yodacoole** [comment]
en fait tu as pris l'option boost+ quand j'active chauffer sur homekit et non boost

Boost+ planifie pour 24 h de chauffe en continue que je n'utiliserais pas.
Boot chauffe jusqu'au max des douches : 4 only.

**Comment by Yodacoole** [comment]
> Oula je ne suis pas sur d'avoir suivi :-). Quelles options ?
> Concernant le boost, entre l'activation via Cozytouch et l'activation via Homekit (en passant en mode "chauffage") la durée n'est pas la même du coup ?

Sur homekit avec les options eteint, chauffer, auto, : 
sur homekit :Au début quand je choisissais, chauffé au bout de quelques secondes cela revenait  en mode auto

**Comment by Yodacoole** [comment]
Boost+ = SetBoostMode=PROG
Boost = SetBoostMode = On
Sur les 2 y a peut être une gestion du temps en complément

**Comment by dubocr** [comment]
Pourtant on voit que via Cozytouch et Homekit c'est bien setBoostMode["on"] qui est activé (donc un Boost standard).

Concernant le fait que ca repasse en auto, normalement le problème devrait toujours être d'actualité.

**Comment by Yodacoole** [comment]
je viens de regarder avec homekit c'est ok 

![image](https://user-images.githubusercontent.com/70021390/105873838-332e4600-5ffc-11eb-98e3-f17853c60710.png)

Pour le mode boost uniquement avec cozytouch y a peut etre la notion de timing

**Comment by Yodacoole** [comment]
autre comportement :
Avec cozytouch si je choisis le mode boost uniquement il conserve ce paramètre.
Homekit le selectionne d'office lorsque j'active chauffer

**Comment by Yodacoole** [comment]
Un petit plus pour le mode absence 👎 

![image](https://user-images.githubusercontent.com/70021390/105874893-6ae9bd80-5ffd-11eb-8623-e83e156bcfda.png)

Si je choisis eteint avec homekit : on pourrait avoir une période d'absence par ex... :)

**Comment by dubocr** [comment]
> autre comportement :
> Avec cozytouch si je choisis le mode boost uniquement il conserve ce paramètre.
> Homekit le selectionne d'office lorsque j'active chauffer

Avec cozytouch il conserve quel paramètre ?

**Comment by dubocr** [comment]
> Un petit plus pour le mode absence :)
> 
> ![image](https://user-images.githubusercontent.com/70021390/105874893-6ae9bd80-5ffd-11eb-8623-e83e156bcfda.png)
> 
> Si je choisis eteint avec homekit : on pourrait avoir une période d'absence par ex... :)

Il n'y a pas de "délais" d'absence sur Homekit. Du coup mieux vaut l'activer sans durée pour la désactiver via une automatisation ou manuellement à distance sinon la durée fixe risque de ne pas convenir à tout le monde.

**Comment by Yodacoole** [comment]
Sur le chauffe eau en lui même quand on active éteint depuis homekit il active le mode absence. Mais c'était un détail.

Pour le mode boost et boost+ depuis cozytouch :

Si je choisis boost+ avec homekit il restera sur boost+ dans cozytouch
Si je choisis boost avec homekit il restera sur boost dans cozytouch

Cozytouch Boost+ On / Puis off

![image](https://user-images.githubusercontent.com/70021390/105879497-87d4bf80-6002-11eb-835f-c2623b10d512.png)

Avec Homekit : Chauffer
![image](https://user-images.githubusercontent.com/70021390/105879596-aa66d880-6002-11eb-9938-67064beb0a41.png)

Je n'ai pas de changement de timing

**Comment by Yodacoole** [comment]
Le SetModeMode que devrait choisir le mode boost sur homekit remplit bien ca fonction.

Il faudrait compléter avec setdatetime et startdate et enddate, je pense.

**Comment by dubocr** [comment]
Oui l'arrêt correspond au mode absence, c'est volontaire.
L'activation du boost depuis Cozytouch ne défini pas startdate et enddate. Du coup en principe le comportement devrait être le même.

Pour résumer :
- Arrêt depuis Homekit => Absence
- Chauffage depuis Homekit => Boost
- Auto depuis Homekit => Arrêt du boost
- Boost depuis Cozytouch => Chauffage
- Bost+ depuis Cozytouch => Auto
- Absence depuis Cozytouch => Arrêt

Les changements réalisés sur Cozytouch ne sont répercuté que si le "pollingPeriod" est activé dans la config.

**Comment by Yodacoole** [comment]
Bonjour Romain,

Merci pour ce retour,
Je suis passé au mode schedule des tâches afin de planifier une activation du chauffe eau aux HC..

J'ai remarqué que si le chauffe eau est en arrêt (mode absence) vers le mode chauffer (mode boost), cela ne s'active pas.
Coté homekit cela parait correct, mais en réalité le chauffe eau n'interagit pas.

J'ai donc fait autrement :
Il faut le remettre en mode auto, puis vers le mode chauffer via homekit pour annuler le mode arrêt.

J'ai bien activé le PollingPeriod sur la conf du json

**Comment by hitch3478** [comment]
> > > Activation (Chauffe) :
> 
> > > DHWP Actuator - setBoostMode["on"] - COMPLETED
> 
> > > Désactivation (Automatique) :
> 
> > > DHWP Actuator - setBoostMode["off"] - COMPLETED
> 
> > > DHWP Actuator - setAbsenceMode["off"] - COMPLETED
> 
> > > Mode Eteint :
> 
> > > DHWP Actuator - setAbsenceMode["on"] - COMPLETED
> 
> > > Est ce que cela vous suffit ou faut il que je colle tout le debug ?
> 
> > 
> 
> > Tu pourras me dire ce que tu as rajouté pour que les modifs fonctionnent à partir de HomeKit ? Si je modifie la valeur sous HomeKit elle n'est pas prise en compte sous cozytouch ? Merci
> 
> 
> 
> Hitch :
> 
> Rien Romain a fait une update du code pour que cela soit pris en compte.
> 
> J'ai juste :
> 
> {
> 
>     "platform": "Tahoma",
> 
>      "user": "blabla",
> 
>     "password": "blabla",
> 
>     "service": "Cozytouch",
> 
>     "exposeScenarios": "True",
> 
>     "pollingPeriod": "5"
> 
> }

As tu une programmation horaire ? Car moi oui et donc toutes les modifications que j'effectue avec HomeKit ne sont pas prises en compte

**Comment by qelanhari** [comment]
Hello,

Je profite de cette issue.
Possible de remonter la température de l'eau plutôt que celle des résistances/PAC de chauffe ?
Actuellement on remonte 

```
{
      "name": "core:TemperatureState",
      "type": 2,
      "value": 54.5
}
```
La valeur est située dans 
```
{
      "name": "io:MiddleWaterTemperatureState",
      "type": 2,
      "value": 29.6
},
```

**Comment by qelanhari** [comment]
Je peux faire une PR si nécéssaire.

**Comment by Yodacoole** [comment]
A la place d'avoir une température normalisée de 60° / 65° oui cela me semble plus cohérent.

**Comment by qelanhari** [comment]
Les thermodynamiques ne dépasse les 55 degrés que pour les cycles anti legionnelle, sinon la consigne de base est 55.

**Comment by dubocr** [comment]
> Hello,
> 
> Je profite de cette issue.
> Possible de remonter la température de l'eau plutôt que celle des résistances/PAC de chauffe ?
> Actuellement on remonte
> 
> ```
> {
>       "name": "core:TemperatureState",
>       "type": 2,
>       "value": 54.5
> }
> ```
> 
> La valeur est située dans
> 
> ```
> {
>       "name": "io:MiddleWaterTemperatureState",
>       "type": 2,
>       "value": 29.6
> },
> ```

La température issue du paramètre MiddleWaterTemperatureInState sera utilisée dans la prochaine version (2.1.7)
