### ISSUE TITLE
Disable alarm?

### ISSUE THREAD

**Issue by ivantomicic-crowdhouse** [dubocr/homebridge-tahoma#199]
First off, beautiful integration! Thank you.

Is there any way not to expose alarm to homekit when I install plugin? I don't actually have somfy alarm but I still see it in homekit? Thanks.

**Comment by Silkjaer** [comment]
Put this in the config:

```
"exclude": [
   "Alarm"
]
```

**Comment by ivantomicic-crowdhouse** [comment]
Beautiful! Thank you!
