### ISSUE TITLE
Percentage and lagging movement with shutters 

### ISSUE THREAD

**Issue by MobiusOne91** [dubocr/homebridge-tahoma#20]
I'm have two questions about the functionality of the Tahoma shutters. I can set the shutters from 0% to 100% with 1% increment steps. I would like a possibility to change this value to 5%, like 0%, 5%, 10%, ..., 95%, 100%. Would this be possible?

When I'm moving for example the shutter slider in HomeKit from 100 % to 15%, the movement of the shutter is "lagging". On the Tahoma website I can see that 4, 5 or even more SetClosure commands are executed. Is there a possibility to add a tiny delay before the movement of the slider is executed?

Thanks in advance.

**Comment by dubocr** [comment]
I,

This behaviors is depending of the Homekit interface. So having 5% steps is the responsibility of Apple.

For the delay, you can try to replace 2 files in accessory directory by this 2 : [TaHoma.zip](https://github.com/dubocr/homebridge-tahoma/files/1623895/TaHoma.zip)
I had a 2 seconds delay to allow slow sliding movements.

**Comment by MobiusOne91** [comment]
Thank you Dubocr, that is exactly what I want. It works awesome. With this I don't need a specific percentage movement more!
