### ISSUE TITLE
Somfy Awning shown as blinds

### ISSUE THREAD

**Issue by pieter-1978** [dubocr/homebridge-tahoma#200]
Hi,

in general the plugin works perfect for me. I have 4 somfy io screens and 1 awning and a connexoon. the awning is now shown as a screen in Homebridge. not a big deal but is it possible to change the symbol from screen to awning?

**Comment by dubocr** [comment]
Hi,

Symbol must be changed in homekit by clicking on the symbol picture to change it.

**Comment by pieter-1978** [comment]
Hi

Thanks for the advice, works great!
