### ISSUE TITLE
error position 

### ISSUE THREAD

**Issue by danny1605** [dubocr/homebridge-tahoma#203]
After Update from Somfy Server My Connexoon doesnt work correctly. There is an fault Indication in Open and closure function.

**Comment by Silkjaer** [comment]
I am also seeing strange things after updating the Tahoma, where Homekit shows my awning as 76% opened, while it is in fact opened 24%. It is not the "reverse" setting, as it has worked fine until now.

**Comment by danny1605** [comment]
I hope that the plugin will be updated quickly

**Comment by danny1605** [comment]
as soon as the plugin refreshPeriod every 30 minutes, my awning is displayed as open although it is closed.
have now set the refreshPeriod to 24 hours so the plugin is free of errors for 24 hours

**Comment by realdannys** [comment]
> as soon as the plugin refreshPeriod every 30 minutes, my awning is displayed as open although it is closed.
> have now set the refreshPeriod to 24 hours so the plugin is free of errors for 24 hours

I have the same problem with it refreshing to the server and then just resetting my RTS blinds to 50% open no matter what the state. I don't really want it to refresh the server, does 0 turn this off? I want it to keep track of the position I put them myself.

**Comment by dubocr** [comment]
Hi,

Please upgrade to 2.x.x than open issue if remaining issues.

Thanks
