### ISSUE TITLE
blindmode 

### ISSUE THREAD

**Issue by amadeus1711** [dubocr/homebridge-tahoma#205]
i have a problem with my Venetian blinds.

If I open the venetian it open correct but if I close them there go down and than is go back for 1 secound. Is it possible to adjust the with the blindmode funktion and if yes in which way.

My venetian a configurated in the somfy system 0-90° not -90/90°

**Comment by dubocr** [comment]
Hi,

Please upgrade to 2.x.x than open issue if remaining issues.

Thanks
