### ISSUE TITLE
Awning > AwningValance

### ISSUE THREAD

**Issue by hoefs** [dubocr/homebridge-tahoma#206]
After the last tahoma update my awning shows as 100% open when it is closed. My blinds (3x Somfy + 1x Velux) still work correctly and show closed when they are closed (and keep showing closed). 
Only the awning shows incorrect. When I send the 2% open, it does open 2% en it shows for a couple of seconds in Apple Home 2% opened, but switches to 98% open after a short time.

When i close the awning again:
[9/30/2020, 10:29:35 AM] [Connexoon] [Zonnewering] setDeployment[0]
[9/30/2020, 10:29:36 AM] [Connexoon] undefined
[9/30/2020, 10:29:36 AM] [Connexoon] Listener registered de21924b-ac10-3401-2c9c-f216fa11407f
[9/30/2020, 10:29:37 AM] [Connexoon] [Zonnewering] setDeployment IN_PROGRESS
[9/30/2020, 10:29:39 AM] [Connexoon] [Zonnewering] setDeployment COMPLETED
[9/30/2020, 10:29:39 AM] [Connexoon] Unregister listener

Now it shows closed in Apple Home.
After some time I can only see this message in the logs (debug enabled):
[9/30/2020, 10:54:56 AM] [Connexoon] Login Connexoon server...
[9/30/2020, 10:54:57 AM] [Connexoon] RESP : {"success":true,"roles":[{"name":"ENDUSER"}]}
[9/30/2020, 11:24:56 AM] [Connexoon] Login Connexoon server...
[9/30/2020, 11:24:57 AM] [Connexoon] RESP : {"success":true,"roles":[{"name":"ENDUSER"}]}

But the awning shows as opened and not closed anymore...

**Comment by danny1605** [comment]
have the same problem

**Comment by drvincs** [comment]
La meme chose, clairement depuis la dernière mise à jour Tahoma et uniquement sur les stores "awning". A noter que le retour d'info est correct dans l'appli somfy...
Merci d'avance si quelqu'un a la solution !

**Comment by artik** [comment]
Same problem here. I noticed that the state is correct, till there is a login to the `TaHoma server`:

```
[10/8/2020, 1:18:52 PM] [My TaHoma Box] [Salon big right] type: Awning > PositionableHorizontalAwning, protocol: io
[10/8/2020, 1:18:52 PM] [My TaHoma Box] Instanciate Salon big right as WindowCovering
[10/8/2020, 1:26:07 PM] [My TaHoma Box] [Salon big left] setDeployment COMPLETED
[10/8/2020, 1:26:11 PM] [My TaHoma Box] [Salon big right] setDeployment COMPLETED
[10/8/2020, 1:41:49 PM] [My TaHoma Box] Login TaHoma server...
```

Between `1:26:10` and `1:41:49`, position is properlly set, and Awning show as `closed`. But after the TaHoma's server login, they show as `open`.

**Comment by Silkjaer** [comment]
Fixed temporarily by changing line 292 in services/WindowCovering.js to:

```
currentPosition = this.reverse ? (100 - value) : value;
```

**Comment by hoefs** [comment]
> Fixed temporarily by changing line 292 in services/WindowCovering.js to:
> 
> ```
> currentPosition = this.reverse ? (100 - value) : value;
> ```

How can I change this?

**Comment by Silkjaer** [comment]
Find the plug-in folder in the node_modules folder (different location based on setup). Here you’ll find this plugins folder and you can edit the files in a normal text editor. Note that your changes will be overwritten when updating the plug-in at some point :)

**Comment by hoefs** [comment]
> Find the plug-in folder in the node_modules folder (different location based on setup). Here you’ll find this plugins folder and you can edit the files in a normal text editor. Note that your changes will be overwritten when updating the plug-in at some point :)

Yes. I can confirm. Changed the file in my homebridge docker and the awning shows as closed again.

@dubocr can you maybe try to adapt the code for everyone?

**Comment by hoefs** [comment]
> > Find the plug-in folder in the node_modules folder (different location based on setup). Here you’ll find this plugins folder and you can edit the files in a normal text editor. Note that your changes will be overwritten when updating the plug-in at some point :)
> 
> Yes. I can confirm. Changed the file in my homebridge docker and the awning shows as closed again.
> 
> @dubocr can you maybe try to adapt the code for everyone?

@Silkjaer I spoke to soon. My other roller shutters from somfy and velux show now open when they are closed

@dubocr it seems to solve it for my awning but breaks it for the roller shutters

**Comment by Silkjaer** [comment]
Could check if it's an Awning. Something like this (untested):

```
if(this.device.widget == "AwningValance") {
currentPosition = this.reverse ? (100 - value) : value;
} else {
currentPosition = this.reverse ? value : (100 - value);
}
```

**Comment by artik** [comment]
Thanks for your suggestion @Silkjaer but your `if` doesn't work. It displays my `awning` as `open`. Here they are in the log:

```
[10/17/2020, 9:02:20 PM] [My TaHoma Box] [Salon big left] type: Awning > PositionableHorizontalAwning, protocol: io
[10/17/2020, 9:02:20 PM] [My TaHoma Box] Instanciate Salon big left as WindowCovering
[10/17/2020, 9:02:20 PM] [My TaHoma Box] [Salon big right] type: Awning > PositionableHorizontalAwning, protocol: io
[10/17/2020, 9:02:20 PM] [My TaHoma Box] Instanciate Salon big right as WindowCovering
```

**Comment by hoefs** [comment]
> Thanks for your suggestion @Silkjaer but your `if` doesn't work for me. It displays my `awning` as `open`. Here they are in the boot log:
> 
> ```
> [10/17/2020, 9:02:20 PM] [My TaHoma Box] [Salon big left] type: Awning > PositionableHorizontalAwning, protocol: io
> [10/17/2020, 9:02:20 PM] [My TaHoma Box] Instanciate Salon big left as WindowCovering
> [10/17/2020, 9:02:20 PM] [My TaHoma Box] [Salon big right] type: Awning > PositionableHorizontalAwning, protocol: io
> [10/17/2020, 9:02:20 PM] [My TaHoma Box] Instanciate Salon big right as WindowCovering
> ```
> 
> Maybe it's another type?
> 
> Edit: Fixed replacing `AwningValance` by `PositionableHorizontalAwning`. Thanks a lot, it works now!

Can confirm! Replaced line 292 with this: (AwningValance is only the small extra curtain at the end of some Awnings)

`if(this.device.widget == "PositionableHorizontalAwning") {
currentPosition = this.reverse ? (100 - value) : value;
} else {
currentPosition = this.reverse ? value : (100 - value);
}`

**Comment by danny1605** [comment]
> Fixed temporarily by changing line 292 in services/WindowCovering.js to:
> 
> ```
> currentPosition = this.reverse ? (100 - value) : value;
> ```

Thank you for the information.  What is the reason, that the Plugin will be no longer updated.

**Comment by hoefs** [comment]
> > Thanks for your suggestion @Silkjaer but your `if` doesn't work for me. It displays my `awning` as `open`. Here they are in the boot log:
> > ```
> > [10/17/2020, 9:02:20 PM] [My TaHoma Box] [Salon big left] type: Awning > PositionableHorizontalAwning, protocol: io
> > [10/17/2020, 9:02:20 PM] [My TaHoma Box] Instanciate Salon big left as WindowCovering
> > [10/17/2020, 9:02:20 PM] [My TaHoma Box] [Salon big right] type: Awning > PositionableHorizontalAwning, protocol: io
> > [10/17/2020, 9:02:20 PM] [My TaHoma Box] Instanciate Salon big right as WindowCovering
> > ```
> > 
> > 
> > Maybe it's another type?
> > Edit: Fixed replacing `AwningValance` by `PositionableHorizontalAwning`. Thanks a lot, it works now!
> 
> Can confirm! Replaced line 292 with this: (AwningValance is only the small extra curtain at the end of some Awnings)
> 
> `if(this.device.widget == "PositionableHorizontalAwning") { currentPosition = this.reverse ? (100 - value) : value; } else { currentPosition = this.reverse ? value : (100 - value); }`

@dubocr why wasnt this implemented?

**Comment by dubocr** [comment]
Hi,

Please upgrade to 2.x.x than open issue if remaining issues.

Thanks

**Comment by hoefs** [comment]
> Hi,
> 
> Please upgrade to 2.x.x than open issue if remaining issues.
> 
> Thanks

It was also opened for me on the 0.x.x branch but you fixed it in 234: https://github.com/dubocr/homebridge-tahoma/issues/234#issuecomment-769949433
