### ISSUE TITLE
Awningnot working anymore

### ISSUE THREAD

**Issue by pieter-1978** [dubocr/homebridge-tahoma#207]
Hi,

I have a Connexoon with 4 blinds and 1 awning. Since a while awning is not working anymore via Homebridge. I cannot control the awning but when I control it via the somphy app the status is changing in Homebridge

Anyone else having this issue?

**Comment by danny1605** [comment]
have the same problem

**Comment by dubocr** [comment]
Hi,

Please upgrade to 2.x.x than open issue if remaining issues.

Thanks
