### ISSUE TITLE
Comptabilité Climatisation Hitachi ?

### ISSUE THREAD

**Issue by nanoupi42** [dubocr/homebridge-tahoma#21]
Bonjour,
Je vais faire installer une climatisation Hitachi chez moi (compatible Tahoma)
Je voulais savoir si le plugin était compatible avec la partie clim ou s'il n'avait pas été testé sur cette partie ?

Merci :-) 

Morgane

**Comment by fafoulon** [comment]
Bonjour,

Voir l'autre sujet : https://github.com/dubocr/homebridge-tahoma/issues/9

Ca fonctionne correctement chez moi.

**Comment by dubocr** [comment]
Bonjour,

Pas personnellement mais à priori ça fonctionne. il peut y avoir des bugs selon le modèle. N’hésites pas a les remonter et a transmettre ta config sur http://home.dubocr.fr/tools/setup si jamais c’est le cas.

**Comment by vblue23** [comment]
Bonjour,
Savez vous s’il existe un plugin homebridge compatible pour faire apparaître ma clim Hitachi dans HomeKit ? En effet, mes radiateurs électriques y sont grâce à celui Tahoma/somfy, et j’aimerai que ma Clim le soit aussi pour être dans la même appli. j’utilise pour l’instant l’appli Aircloud home du constructeur, malheureusement compatible uniquement avec Google et Alexa … si quelqu’un a la réponse merci beaucoup !
