### ISSUE TITLE
graduable samrt blinds not  detected

### ISSUE THREAD

**Issue by psainzt** [dubocr/homebridge-tahoma#211]
Hi, I have several somfy io devices plus tahoma all have been integrated perfectly into home kit except a smart blind graduable  controllable by a smove uno io

Please finf attached files

https://flareapp.io/share/B5Z9Gan7

Thanks

**Comment by dubocr** [comment]
Thank you for using Homebridge TaHoma plugin.

Please follow these step to obtain better support :
1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)

Thank you.
