### ISSUE TITLE
Libellé commande envoyé

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#213]
Bonjour romain,
Serait-ce possible d’ajouter la commande exacte envoyée à HomeKit pour les chauffages?
Avant ça affichait si c’était en confort ou en éco.
![94673DF1-4CC0-4ACC-AEEA-C2BB517984BB](https://user-images.githubusercontent.com/49283285/97733213-d3490180-1ad7-11eb-924c-920ff0f9b480.jpeg)

**Comment by Tontonpat** [comment]
Voici l’exemple:
En haut: HomeKit
En bas: Tahoma
![DCA36B9C-63A6-41F2-9C55-E77BFEC25655](https://user-images.githubusercontent.com/49283285/97797651-f7632a80-1c1e-11eb-96c2-c67197783790.jpeg)

**Comment by Tontonpat** [comment]
Bonjour Romain,
Je relance pour voir si la V2 de ton plugin peut faire quelque chose.
Si besoin de test, n’hésites pas

**Comment by Tontonpat** [comment]
Bonsoir Romain, depuis la dernière mise à jour mes interfaces fil pilote IO ne s’affiche plus comme avant et sont donc inutilisables. Bon en ce moment c’est pas grave 😉
![47FC88F4-71C8-4BEA-AF0A-600481E808A2](https://user-images.githubusercontent.com/49283285/125854547-d88b5d58-d7b3-4e1b-b279-5ff125896866.jpeg)

**Comment by dubocr** [comment]
Bonjour Patrick,

Afin d'homogénéiser les chauffages et l'interprétation du mode "climatisation" je n'utilise plus `chauffage/climatisation` pour le changement d'allure.
Du coup l'appli Home n'affiche plus qu'un bouton on/off (le petit rond gris au centre). Normalement cela devrait fonctionner et passer de Hors Gel à Confort.

Pour changer eco/confort, il faut désormais utiliser la caractéristique `Eco` visible avec une app comme Eve.
La couleur du rond avec la T° sur Home sera orange en confort et bleu en eco.

Pour les interfaces IO qui ne permettent pas le changement de consigne de T° cela fait un peu vide c'est vrai.
J'imaginait éventuellement utiliser les changement de T° pour passer de éco à confort mais je ne sais pas si ce serait compréhensible.

Qu'en penses tu ?

**Comment by Tontonpat** [comment]
Je ne suis pas très fan de l’idée d’utiliser la température pour changer de mode, surtout pour ceux qui n’ont pas de thermostat comme moi.
Au mieux il faudrait mettre les 2 possibilités:
Tu peux régler le « thermostat » pour changer de mode, ou changer de mode pour régler le « thermostat ».
En gros comme au début de ton développement 😅.

Chez moi, le bouton passe bien de confort à hors-gel, mais du coup je ne peux plus utiliser le mode éco depuis home. Je préférais quand il y avait le menu déroulant confort/éco/hors-gel

**Comment by dubocr** [comment]
J’ai remis le chauffage / refroidissement dans la dernière version en plus de la gestion par température (qui nécessite de configurer les consignes confort / eco dans la config homebridge pour être en cohérence avec le chauffage).
Le changement par température est plus flexible du coup (confort / eco / hors gel).

**Comment by Tontonpat** [comment]
Merci pour cette mise à jour. La gestion par temperature est top! C’est presque parfait. Cependant, il n’y a pas vraiment de mode hors gel. Il serait bien d’avoir le mode hors gel comme celui de chauffage/refroidissement/éteint 
Sur les captures ci dessous, le « chauffage nous » est en hors gel depuis home en forçant le chauffage a 7 degrés et le « chauffage Mathys » est en hors gel depuis tahoma
![1D826200-9B67-4B68-A54D-29FF49D725A1](https://user-images.githubusercontent.com/49283285/126044080-2220b4cc-61e0-4c2f-9788-50b0a48c4175.jpeg)
![B79992B9-B64D-4A0B-907A-B723A9455C69](https://user-images.githubusercontent.com/49283285/126044082-78399493-bc42-4f66-8722-2d10f827afa9.jpeg)

**Comment by dubocr** [comment]
Qu’entends-tu pas il n’y a pas de mode hors gel ?
Si tu mets en hors gel sur TaHoma ce sera hors gel en vrai et 7°C sur Home et inversement si tu mets 7°C sur Home ce sera du Hors gel en vrai et sur TaHoma.

Pour le libellé je vais y arriver oui 😀. Comme c’était cosmétique avant tout je n’ai pas encore pris le temps mais comme tu l’as vu j’ai bien gardé le ticket ouvert car j’ai bon espoir de le faire 😉.

**Comment by Tontonpat** [comment]
Je pensais à mettre le mode hors gel dans le menu déroulant (enfin si c’est possible) :
![FD7EEC9C-080E-4A9D-9BED-D1A6D9D50BD9](https://user-images.githubusercontent.com/49283285/126059449-487f7a33-78d0-407c-9345-af17bd507671.jpeg)
Sinon, cela fonctionne comme tu le dis, mais je penses que ce n’est pas intuitif.
En tout cas merci et bravo pour le développement 👍

**Comment by dubocr** [comment]
Ha ok, non justement c’est là tout le problème si ok pouvait j’y aurais mis confort/eco/hors-gel/arrêt mais HomeKit ne gère pas la spécificité des chauffages français.
Du coup dans la logique mode et température, le contrôle on/off se fait dans le sélecteur de mode et ensuite les réglages sur la température (confort/eco/hors gel) dans le sélecteur de température.
C’est pour ça que j’avais initialement retiré « rafraîchissement » pour éviter la confusion des genres mais bon c’est la limite après chacun en fera l’expérience et s’adaptera à ce qu’il préfère tout en sachant que seul le sélecteur de température permet d’en faire plus (ou alors une appli comme Eve).

**Comment by Tontonpat** [comment]
C’est plus clair pour moi, en fait, on peut soit jouer sur la température soit sur le mode (multi-fonction) et c’est top!
J’aimerais tellement pouvoir t’aider, mais je ne sais pas comment?

**Comment by dubocr** [comment]
Tu m’aides déjà par tes retours.
Mais pour avoir quelque chose qui colle davantage au mode de fonctionnement des chauffages électriques maintenant seul Apple pourrait nous aider

**Comment by Tontonpat** [comment]
Tu dois commencer à me connaître 😅 je pinaille, mais quand je passe de chauffer à éteint le thermostat reste sur 19, idem de climatisation à éteint, il reste à 17. 
![D70348F0-0FED-4B5B-893F-85492C97C761](https://user-images.githubusercontent.com/49283285/126062357-f478418f-844f-4d46-be76-a0045c0b8855.jpeg)
Est ce possible de mettre le thermostat à 0 ( ou 7) quand c’est éteint ?

**Comment by dubocr** [comment]
La température dont tu parles correspond (sur un thermostat normal) à la température mesurée (de la pièce).
Dans le cas des interfaces il n’y a pas de capteurs donc cela correspond simplement à la T° de consigne. Et elle reste a la dernière valeur quand on passe en arrêt  puisqu’il n’y a plus de consigne en question (ni 7 ni 0 puisqu’on est éteint).

**Comment by dubocr** [comment]
Ici aussi du nouveau ;-).

J'ai commencé à intégrer la traduction des commandes. C'est encore incomplet mais tu devrais avoir des premières traductions dans l'historique TaHoma.

**Comment by Tontonpat** [comment]
Merci @dubocr, je ferai les tests et je te tiens au courant
