### ISSUE TITLE
Portail rts avec fermeture automatique

### ISSUE THREAD

**Issue by mathieusalon** [dubocr/homebridge-tahoma#214]
Bonjour, j'utilise mon portail en fermeture automatique après l'avoir ouvert, lorsque j'active l'ouverture du portail via le plugin l'icône ne revient pas automatiquement en mode fermé.
je pensais utilisé l'option cyclic 

"GarageDoorOpener": {
                "cyclic": true
            }

Mais ça ne change rien. J'ai raté une étape?
Merci d'avance et bravo pour le travail accompli.

**Comment by koupus** [comment]
Pour suivre.

**Comment by mathieusalon** [comment]
J’ai résolu pour le moment en modifiant directement le mode par défaut de cyclic dans le fichier garagedooropener.

**Comment by koupus** [comment]
Hello @mathieusalon!
Peux tu me communiquer ta modification effectuée dans le ficher garagedooropener ?
Suite à cela, as tu du compléter ta config homebridge de l'option cyclic dans le fichier .json ?
Merci !!!

**Comment by mathieusalon** [comment]
Bonjour,

Pour ma part le fichier GarageDoorOpener à modifier est ici : /usr/local/lib/node_modules/homebridge-tahoma/services/GarageDoorOpener

Dans le fichier il faut modifier la ligne this.cycle.... le false par true

--> this.cycle = config['cycle'] || true;

Cela change l'option par default pas besoin de rajout dans le fichier de config. Seulement lors d'une mise à jour cette modification va sauter d'où l'intérêt de pouvoir gérer via le fichier json.
       
Espérant t'avoir aidé.

**Comment by mathieusalon** [comment]
Du coup je viens de comprendre l'option n'est pas cyclic comme stipulé mais cycle comme dans le fichier.

Je viens de faire la modification et le fichier de config prend bien en compte la modification directement avec le terme cycle et non cyclic. Plus besoin de modifier le fichier GarageDoorOpener.
Il faudrait mettre la fiche des paramètres à jour.

"GarageDoorOpener": {
                "cycle": true
            }

**Comment by koupus** [comment]
Top ! Merci pour le tuyau😉

**Comment by drvincs** [comment]
Merci beaucoup !! Depuis le temps que ce paramètre m'embêtait !!!

**Comment by dubocr** [comment]
Bonjour,

Désolé dans la dernière version la gestion des paramètres change pour permettre une configuration via homebridge-ui / hoobs. Vous devrez mettre à jour votre config pour continuer d'utiliser cette fonction.

N'hésitez pas à me remonter tout problème
