### ISSUE TITLE
Capteur de consommation éclectrique effet joule

### ISSUE THREAD

**Issue by alex45fr** [dubocr/homebridge-tahoma#215]
Bonjour, je suis équipé d'un compteur a effet joule somfy (réf : 2401224) et celui-ci n'est pas reconnue dans mes accessoires, l'avez-vous rendu compatible?

Merci

**Comment by dubocr** [comment]
Thank you for using Homebridge TaHoma plugin.

Please follow these step to obtain better support :
1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)

Thank you.

**Comment by dubocr** [comment]
Bonjour,

Ce compteur n'est pas encore compatible mais je pourrais me pencher sur le sujet avec le votre. Pourrez-vous vous connecter sur https://dev.duboc.pro/tahoma et me transmettre les derniers chiffre de votre bridge pour que je puisse consulter les paramètre de cet équipement.

MErci

**Comment by nscheffer** [comment]
Idem j'ai aussi ce module, je pensais le supprimer définitivement du tableau électrique mais si vous allez l'intégrer je veux bien le garder et vous aider dans son développement...

**Comment by alex45fr** [comment]
Bonjour,

Merci mais je ne peut me connecter sur https://dev.duboc.pro/tahoma je n'ai aucun username qui fonctionne.
Avez vous une solution,
Merci

**Comment by dubocr** [comment]
Bonjour @alex45fr,

Vous n'avez pas de box TaHoma (ou équivalent) ?

**Comment by alex45fr** [comment]
Si la box energeasyconnect, j'ai essayer de me connecter avec les mêmes identifiants mais le message d'erreur "Bad credentials" s'affiche.

**Comment by dubocr** [comment]
As-tu essayé en sélectionnant le Endpoint "Rexel" ?
Quel service utilises tu sur le plugin Homebridge ?

Merci

**Comment by nscheffer** [comment]
De mon coté avec ma nouvelle Tahoma Switch le capteur à effet joule n'est pas encore reconnu/supporté par contre c'est bizarre je vois des traces dans Homebridge.... soit un device IO (1234#7) dans les logos ou sinon j'avais trois icône GMDE_Zone1, GMDE_Zone2 et Boost que j'ai exclu dans la config.
Je pense qu'il faut attendre pour la Switch que le capteur soit déjà supporté.

**Comment by alex45fr** [comment]
Maintenant j'ai une erreur 500 server error

**Comment by dubocr** [comment]
Merci, j'ai corrigé mais j'ai pu récupéré la config.

**Comment by alex45fr** [comment]
C’est bon la connexion est OK, bridge 4055

**Comment by nscheffer** [comment]
@alex45fr vous avez une Tahoma ? Avec ma nouvelle Switch le capteur à effet joule n'est pas reconnu, d'après Somfy il devrait arriver pour la fin de l'année !

**Comment by alex45fr** [comment]
@nscheffer non , j’ai une Energeasy connect rail Din de chez rexel
