### ISSUE TITLE
Garage door with three states

### ISSUE THREAD

**Issue by Boubik** [dubocr/homebridge-tahoma#217]
Hi, I have a garage door (IXENGO 3S io). In somfy connexoon I have three states. first is closed, the second is half-opened (only one wing) and last is fully opened (both wings are opened). Is it possible to configure here?

**Comment by qelanhari** [comment]
I think this is a limitation of homekit, there is no "partial" state for garage doors yet, nor there is a pedestrian mode for sliding gates (that are assimilated as garage doors...)

**Comment by qelanhari** [comment]
As I now have an Elixo IO with pedestrian position, I'll try to find a way to add this feature, maybe by duplicate the service. The garage door is a service from the accessory "tahoma" I cannot just add a secondary switch to the original tile, and as I stated before, the garage door service specification of homekit does not include any other capabilities.
Anyway, I'll have a look.

**Comment by qelanhari** [comment]
Good news, with the new version it became easier to add a button for the pedestrian position. I'll submit the PR within the next few days tops.
The only question I ask myself is : how do I consider the states of the switches (full open/pedestrian) depending on the actual position of the gate:
- Does being open in pedestrian position means that the gate is considered open (security issue)
- Does being full open means that the pedestrian position condition is also considered as fulfilled.
