### ISSUE TITLE
RTS My-position

### ISSUE THREAD

**Issue by SteeeveAT** [dubocr/homebridge-tahoma#218]
Hi!

Is there a  way to set the my-Position for RTS-Blinds? I wanted to wait for the native thaoma-homekit support, but they do not suport RTS blinds (just IO). 
So is there a way to simulate the My-Button on the remote?

Thanks in advance

Steeeve

**Comment by Tontonpat** [comment]
Hello, just set to 50%

**Comment by SteeeveAT** [comment]
Oh, that easy, works, thank you very much.
