### ISSUE TITLE
Tahoma preventing Homebridge start not able to login

### ISSUE THREAD

**Issue by angladacamps** [dubocr/homebridge-tahoma#219]
Hi.
Is there a chance that your plugin lets Homebridge start even when not able to login Tahoma cloud?

**Comment by Obikela88** [comment]
Hi
Have since today same problem. Worked for weeks/months and suddenly...

[2/11/2021, 18:01:09] [Tahoma] Login TaHoma server...
[2/11/2021, 18:01:09] [Tahoma] Login fail: Bad credentials
[2/11/2021, 18:01:09] [Tahoma] Error while registering listener

**Comment by Obikela88** [comment]
Just worked again without any intervention after a couple of days... 🤷🏻‍♂️

**Comment by dubocr** [comment]
Version 2.x.x won't lock homebridge statup anymore.
