### ISSUE TITLE
Error Message - Same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by wahltho** [dubocr/homebridge-tahoma#22]
Integrating the Plugin into Homebridge application results in the following error message:
________________________________
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: bf30e9f0-fbd3-4e4b-b514-026a854f0e98                                                                     
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:258:13)                                                            
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:377:24)                                                                                                         
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19                                                                                                    
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:66:16                                                                                                                             
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:115:5                                                                                                                             
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:175:5                                                                                                                       
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:207:17)                                                                                
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:186:22)                                                                             
    at Request.emit (events.js:159:13)                                                                                                                                                          
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1163:10)                                                                              
    at Request.emit (events.js:159:13)                                                                                                                                                          
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1085:12)                                                                      
    at Object.onceWrapper (events.js:254:19)                                                                                                                                                    
    at IncomingMessage.emit (events.js:164:20)                                                                                                                                                  
    at endReadableNT (_stream_readable.js:1054:12)                                                                                                                                              
    at _combinedTickCallback (internal/process/next_tick.js:138:11)    
______________________

**Comment by dubocr** [comment]
Can you try proposal posted [here](https://github.com/luisiam/homebridge-cmdswitch2/issues/8)
