### ISSUE TITLE
Problème pilotage portail RTS

### ISSUE THREAD

**Issue by raphaelpregnon** [dubocr/homebridge-tahoma#222]
Bonjour, 

J'ai un portail qui fonctionne en RTS et qui est reconnu dans Tahoma, mais lorsque je veux l'ouvrir via Homebridge, rien ne se passe. Dans Home il est indiqué Sans réponse.
Sinon, il ne propose pas non plus l'ouverture d'un seul battant.

Pourriez-vous me venir en aide, merci à vous, cordialement.

**Comment by loupied** [comment]
Bonjour,j ai le même problème que vous,avez vous trouvé la solution?si oui je suis preneur.Bonne journée

**Comment by jay972** [comment]
> Bonjour,
> 
> J'ai un portail qui fonctionne en RTS et qui est reconnu dans Tahoma, mais lorsque je veux l'ouvrir via Homebridge, rien ne se passe. Dans Home il est indiqué Sans réponse.
> Sinon, il ne propose pas non plus l'ouverture d'un seul battant.
> 
> Pourriez-vous me venir en aide, merci à vous, cordialement.

Bonsoir @raphaelpregnon avez vous trouve une solution à votre problème ? j'ai exactement le même problème et je ne sais pas comment rendre dans HomeKit le portail actif

**Comment by dubocr** [comment]
Bonjour,

Avez-vous accéder au formulaire de diagnostic : http://dev.duboc.pro/tahoma ?
Pouvez-vous m'indiquer les 3 derniers chiffres de votre bridge afin que je puisse constater votre configuration.

Merci

**Comment by dubocr** [comment]
Vous pouvez essayer quand même une mise à jour du plugin avant, j'ai corrigé le comportement par défaut pour les nouveaux produits. Cela devrait suffire à fonctionner en RTS.

**Comment by raphaelpregnon** [comment]
Bonjour, je viens de remettre a jour votre plugin et le portail fonctionne bien, mais est-ce que vous pouvez également réaliser une adaptation de votre code pour pouvoir ouvrir seulement un battant du portail?
Merci à vous, bien cordialement.

**Comment by dubocr** [comment]
Homekit ne permet pas la gestion de l'ouverture partielle.
Cela pourrait être ajouté via un second accessoire dans Home (un bouton ou une autre porte de garage), je vais réfléchir à ça.

**Comment by raphaelpregnon** [comment]
Merci pour votre retour, sous jeedom je l’avais déclaré en portillon. Merci en tout cas pour ce que vous faites, cordialement.

**Comment by raphaelpregnon** [comment]
Bonjour, est-ce qu’il serait possible de rajouter au portail une tempo indiquant au bout de x minutes qu’il est refermé ? Voir si on ne peut pas mettre ce paramètre dans la configuration du plugin. Merci pour votre retour, car le mien se referme au bout de 3 minutes, cordialement.

**Comment by dubocr** [comment]
Bonjour,

Il faut ajouter la config "GarageDoorOpener" : { "cycle" : true }
