### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by ilaninga** [dubocr/homebridge-tahoma#223]
In HomeKit all of my 4 screens are open and showed just like my lights (right now they are on) id like to change this if possible. 

So when they are open I’d like to see they are off. And when they are fully closed I’d like to see it on (so I can click it once to open them all)

![938730C0-4C2C-4B4F-A7CB-CCF969022089](https://user-images.githubusercontent.com/75586056/101292014-1d2ab300-380d-11eb-890e-2846eed9efd2.jpeg)

Thanks a lot

**Comment by dubocr** [comment]
Hi,

could you please try with latest 2.1.6 release then tell me if states are always bad ?

thanks
