### ISSUE TITLE
Yokis light on Econnect box

### ISSUE THREAD

**Issue by steve41200** [dubocr/homebridge-tahoma#224]
Hi. First thank you for this plugin.
It was exactly what i was searching. I can control 3 radiator and 4 light who where in jail on my E connect box :)
It works very well but i have one Yokis light on the 4 who frequently turn off without any actions. On the plugin Log I see anything.
On the little history of EConnect box i see anything ... It was randomly but when it beggins, it was worst and worst. I reset the yokis from Econnect box, repair it and it will be good for a few time (few hour or 1 or 2 days sometime).

I have try to exclude from homebridge the Bad Yokis but it doesn't change anything.

Have you an idea for a solution ?

Thanks a lot

**Comment by steve41200** [comment]
I have a clue who can help to understand the pb. If i've a stop the plug in  or a disconnect of network. My crazy light come out. This time without overreact i 've try to disconnect homebridge (put a wrong passwords to connect to Rexel box) a longtime. A restart him after. (Do this with a quick restart do not change the problem). and it works fine again. 
Is it possible than the plug or the Energybox keep a ghost connection ?

**Comment by dubocr** [comment]
Thank you for using Homebridge TaHoma plugin.

Please follow these step to obtain better support :
1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)

Thank you.
