### ISSUE TITLE
Portail coulissant en RTS ne répond pas

### ISSUE THREAD

**Issue by loupied** [dubocr/homebridge-tahoma#225]
Bonjour,J'ai installer votre plugin.Tout fonctionne nickel mais je n'arrive pas à ouvrir le portail coulissant qui est un moteur elixo RTS.La commande ne répond pas (no Target)
Pourriez vous m'aider svp?
Merci à vous par avance

**Comment by loupied** [comment]
Bonjour,je pense avoir résolu le problème en parametrant à nouveau mon portail avec un capteur RTS universel et non la référence du moteur
Bonne journée

**Comment by dubocr** [comment]
Bonjour,

Il est possible que la dernière mise à jour fonctionne également avec la configuration "standard" si vous avez besoin d'y revenir.

Cdt
