### ISSUE TITLE
Curtains show 50% open most of the time

### ISSUE THREAD

**Issue by ivantomicic-crowdhouse** [dubocr/homebridge-tahoma#226]
I'm not sure when it happens, but sometimes I'd get 50% open curtains, even tho they are fully closed, any ideas?

**Comment by adavison007** [comment]
It does this after a reboot of Homebridge, you can set the default value in the settings, but it doesn't work... I opened a case for this 6 months ago.

**Comment by dubocr** [comment]
This is the default position for stateless roller shutter. This way, automation are still operational for 0% or 100% command after a reboot.
As says @adavison007 you can change the default value in settings with :
"defaultPosition" : position after any command (default 0)
"initPosition" : position after reboot (default 50 or defaultPosition if set)

ex:
"WindowCovering": {
"defaultPosition": 10,
"initPosition": 0
}

**Comment by adavison007** [comment]
> This is the default position for stateless roller shutter. This way, automation are still operational for 0% or 100% command after a reboot.
> As says @adavison007 you can change the default value in settings with :
> "defaultPosition" : position after any command (default 0)
> "initPosition" : position after reboot (default 50 or defaultPosition if set)
> 
> ex:
> "WindowCovering": {
> "defaultPosition": 10,
> "initPosition": 0
> }

@dubocr Thanks for the response, can you help? I have set initial position in my settings (below) to 100, but when i restart Homebridge it still shows as 50% in homekit, any ideas? Also, what was in the last two code updates?

{
    "platform": "Tahoma",
    "name": "My TaHoma Box",
    "initPosition": 100,
    "refreshPeriod": 500,
    "user": "XXXXXXX",
    "password": "XXXXXXX"
}

**Comment by dubocr** [comment]
You must define it as the provided example : 
```
"WindowCovering": {
"initPosition": 0
}
```

so 
```
{
"platform": "Tahoma",
"name": "My TaHoma Box",
"refreshPeriod": 500,
"user": "XXXXXXX",
"password": "XXXXXXX"
"WindowCovering": {
"initPosition": 0
}
}
```

**Comment by adavison007** [comment]
That’s great, I missed that, many thanks

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 19 Jan 2021, at 15:04, Romain DUBOC <notifications@github.com> wrote:


You must define it as the provided example :

"WindowCovering": {
"initPosition": 0
}
so

{
"platform": "Tahoma",
"name": "My TaHoma Box",
"refreshPeriod": 500,
"user": "XXXXXXX",
"password": "XXXXXXX"
"WindowCovering": {
"initPosition": 0
}
}

**Comment by Tontonpat** [comment]
Bonjour Romain,
Est ce possible de filtrer certains volets avec cette configuration "WindowCovering": {
"initPosition": 0?
Mon store et ma pergola sont reconnus comme des volets et je souhaiterais que seuls ces équipements restent à 0 quand je redémarre homebridge

**Comment by dubocr** [comment]
Bonjour Patrick,

Le plus simple c'est en utilisant le nom des équipements :
"Store": {
"initPosition": 0
},
"Ma pergola": {
"initPosition": 0
}

**Comment by Tontonpat** [comment]
Parfait comme d’habitude.
Je te proposerai de détailler un peu plus les possibilités avec des exemples comme cela.

**Comment by dubocr** [comment]
Oui j'ai surtout comme objectif une nouvelle version plus propre et en profiter pour remettre à plat cette configuration et les exemples effectivement. Mais j'avance lentement malheureusement.
Le temps libre à disparu de mon emplois du temps cette année passée.

J'espère pouvoir en retrouver rapidement.

**Comment by Tontonpat** [comment]
Je sais bien, comme je t’ai dit, si je peux t’aider ce serait avec plaisir (dans le mesure de mes compétences)
