### ISSUE TITLE
Portail RTS 

### ISSUE THREAD

**Issue by jay972** [dubocr/homebridge-tahoma#228]
Bonjour , 

J'ai installé homebridge sur mon synology via Docker . j'ai du matériel SOMFY io & RTS avec une Tahoma ( io : 3 volets & 2 velux  RTS : portail motorises ) 

Grace a Homebridge j'ai désormais tout sous HomeKit manquant : il manquait le portail & les velux .

Le portail par contre ne répond pas sous HomeKit .

Etant novice  je ne sais pas comment faire pour pouvoir le piloter d'avance merci

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous m'indiquer les 3 derniers chiffres de votre bridge après l'accès au formulaire : http://dev.duboc.pro/tahoma

Merci

**Comment by dubocr** [comment]
Vous pouvez essayé quand même une mise à jour du plugin avant, j'ai corrigé le comportement par défaut pour les nouveaux produits. Cela devrait suffire à fonctionner en RTS.

**Comment by jay972** [comment]
Pour commener merci pour la reponse 

je me suis connecté au formulaire 3 derniers chiffres 350
Alors entre temps j'ai trouvé une solution que vous aviez apporté à quelqu'un et j'ai fait ça : 

"Gate": {
        "stateless": true,
        "cycle": true
    },
    "forceType": {
        "PORTAIL": "WindowCovering"
    }
}

Et Miracle ca fonctionne par contre mon portail apparait comme un store mais ca fonctionne .

Est il possible de demander qu'il se referme seul au bout de 5 min si il ne reçoit pas de demande ?

<img width="485" alt="Capture d’écran 2021-01-16 à 19 18 30" src="https://user-images.githubusercontent.com/77399085/104819719-a8955c00-582f-11eb-823a-3490b9232a06.png">

**Comment by dubocr** [comment]
Retirez simplement le "forceType" pour repasser sur un widget porte de garage. Le pilotage devrait fonctionner avec la dernière version. Pour la fermeture automatique, je pense que vous devriez avoir cette option sur la motorisation directement. dans le cas contraire je vous conseille plutôt de le faire via une automatisation Homekit que vous pourrez gérer à volonté.

Le paramètre "cycle", du plugin permet quand à lui de simuler un comportement en cycle (qui repasse à l'état "fermé") sur les portes de garages configurées comme tel (directement sur la motorisation) et sans retour d'état (en RTS)

**Comment by jay972** [comment]
C'est bon ca fonctionne à merveille 

Merci pour les conseils 




<img width="466" alt="Capture d’écran 2021-01-16 à 19 52 11" src="https://user-images.githubusercontent.com/77399085/104820344-75a19700-5834-11eb-8b68-3dac2d7b3499.png">
