### ISSUE TITLE
No minus degrees with IO-temperature sensor

### ISSUE THREAD

**Issue by MirkoKas** [dubocr/homebridge-tahoma#23]
I‘m using the Tahoma plugin since last summer with nearly no problems, but with the cold temperatures in the last couple of weeks I noticed that while the Tahoma App shows the right temperature Even with minus degrees (e.g -5C) in Homekit only 0C is shown. When it‘s warmer then 0C everything works perfect. I have the io- temperature sensor from Somfy. Anyone else having such an issue?

**Comment by dubocr** [comment]
If temperatures are still below 0ºC, could you please browse http://home.dubocr.fr/tools/setup to submit your config.
Thanks

**Comment by MirkoKas** [comment]
It‘s just -1C in the Tahoma App, but with HomeKit it’s anyway 0C. I just sent the config and it‘s telling:

States Temperatur Süd
core:RSSILevelState 74
core:SensorDefectState (dead,lowBattery,maintenanceRequired,noDefect)
core:StatusState (available,unavailable) available
core:TemperatureState 272.25

Can you work with that?

**Comment by dubocr** [comment]
Yes thanks, it seems HomeBridge min value for temperature is 0°C.
Can you try to add the following line after the line 22 in the file _homebridge-tahoma/accessories/TemperatureSensor.js_ and restart homebridge.
`this.temperatureState.setProps({ minValue: -100, maxValue: 100 });`

This will normally fix. Please tel me if yes.

Thanks

**Comment by MirkoKas** [comment]
Thanks for this fix.
Quick update: 
I inserted the code into the file and in the Home App on iOS it's showing now -0°C (the Minus ist new) and that's also the value Tahoma is showing. I will have to wait until this afternoon when the temperature will probably go below 0°C again.

I will keep you updated if this fix works as it should.

**Comment by MirkoKas** [comment]
It has been way to warm in the last couple of days so I couldn‘t make a final test yet.

**Comment by MirkoKas** [comment]
„Finally“ it’s colder again, so I could test it. And: It works. Home app now shows -1 with the Tahoma temperature sensor. Thank you for this. You should integrate it with a new release.
