### ISSUE TITLE
[COZYTOUCH] chauffe eau atlantic

### ISSUE THREAD

**Issue by hitch3478** [dubocr/homebridge-tahoma#230]
bonsoir,
JE me suis connecte sur l'url https://dev.duboc.pro/tahoma
mais je n'ai pas de numero de setup a fournir .
ET je ne vois pas ce que je dois mettre dans le plugin 
Merci pour votre aide. La j'avoue je seche.

**Comment by hitch3478** [comment]
Voici ma config
{
    "bridge": {
        "name": "Cozytouch",
        "username": "xxxxx",
        "port": 51826,
        "pin": "xxxxxx"
    },
    "description": "This is an example configuration for the tahoma homebridge plugin",
    "platforms": [
        {
            "platform": "Cozytouch",
            "name": "Cozytouch",
            "user": "monadresse@com",
            "password": "monmotpasse",
            "service": "Cozytouch"
        }
    ],
    "accessories": [],
    "platform": "Tahoma"
}

voici la log que j'ai 


6/01/2021 à 20:53:34] Error: You must provide credentials ('user'/'password')
    at new OverkizApi (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:124:45)
    at new TahomaPlatform (/usr/local/lib/node_modules/homebridge-tahoma/index.js:33:13)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by hitch3478** [comment]
Bonjour remi
Merci pour le retour. Cependant je dispose de 2 thermostat. Le IO (15793876#2) faut-il qu'il soit mis dans le plugin ?
Et au demarrage du plugin j'ai surtout ca qui me gene
Error: You must provide credentials ('user'/'password')
Or mes credentials sont correctes à 200 %
Désolé de repondre que maintenant mais je suis a la maison que le week-end.
Et mon compte est bon vu que sur le site https://dev.duboc.pro/tahoma cela fonctionne.
Cdt

**Comment by Yodacoole** [comment]
Re Bonjour,

En lisant ton post, et si tu ne gères qu'un chauffeau eau atlantic, en ce qui me concerne je n'ai que ceci.

"platforms":[
		{
			"platform": "Tahoma",
			"name": "My TaHoma Box",

			"user": "user@me.com",
			"password": "MyPassw0rd",
		}
	]

Il n' y pas de d'object code pin ???? dans le source.

**Comment by hitch3478** [comment]
Merci pour ta réponse effectivement je viens de comprendre que je cassais
la config de homebridge en rajoutant trop de chose.
Maintenant cela fonctionne mais mes autres accessoires ne fonctionnes plus.
Il faut que je regarde comment on fait quand on a plusieurs plateformes
Merci pour ton aide
Cdt
Sebastien

Le sam. 23 janv. 2021 à 10:11, Yodacoole <notifications@github.com> a
écrit :

**Comment by Yodacoole** [comment]
il faut que tu dissocies correctement les plugins

Reprends correctement cette structure de cette façon :

{
	"bridge": {
		...
	},

	"description": "...",

	"accessories": [],

	"platforms":[
		{
			"platform": "Tahoma",
			"name": "My TaHoma Box",

			"user": "user@me.com",
			"password": "MyPassw0rd",
			"other:" "pas de virgule"
		}
	]
}

**Comment by Yodacoole** [comment]
si cela peut t'aider également : 

https://jsononline.net/json-checker

**Comment by hitch3478** [comment]
Merci pour ton aide ça y est tout fonctionne
Par contre j’ai des choses qui remontent.
Il faut que je regarde comment on peut les retirer. Je veux juste garder
mes thermostats le reste me sert à rien je pense



Le sam. 23 janv. 2021 à 10:18, Yodacoole <notifications@github.com> a
écrit :

**Comment by dubocr** [comment]
Bonjour @hitch3478 ,

Tu peux utiliser "exclude" dans ta config pour exclure des équipements :

ex: exclus tout les volets et l'appareil portant le nom "Chauffe-eau"

```
{
		"platform": "Tahoma",
		"name": "My TaHoma Box",

		"user": "user@me.com",
		"password": "MyPassw0rd",
		"exclude:" ["Chauffe-eau", "RollerShutter"]
	}
```
