### ISSUE TITLE
Callback already triggered

### ISSUE THREAD

**Issue by henkied** [dubocr/homebridge-tahoma#231]
Until recently I had no problems with the plugin!

Recently I get the message "Callback already triggered" so that the garage door does not open or close.

Is anyone familiar with this error?

**Comment by dubocr** [comment]
Hi,

Can you transmit the log.

Thank you.

**Comment by henkied** [comment]
Here the log homebridge:

[1/18/2021, 5:29:05 PM] [Tahoma] [Garagedeur] open[]
[1/18/2021, 5:29:28 PM] [Tahoma] [Garagedeur] open COMPLETED
[1/18/2021, 5:29:28 PM] [Tahoma] Callback already triggered
[1/18/2021, 5:42:23 PM] [Tahoma] [Garagedeur] open[]
[1/18/2021, 5:42:44 PM] [Tahoma] [Garagedeur] open COMPLETED
[1/18/2021, 5:42:44 PM] [Tahoma] Callback already triggered

setup:

{
    "platform": "Tahoma",
    "name": "Tahoma",
    "user": "*",
    "password": "*",
    "exclude": [
        "Alarm",
        "Tuin",
        "Sonos SUB",
        "Sonos PLAY:1"
    ],
    "defaultPosition": 0,
    "refreshPeriod": 300,
    "alwaysPoll": true,
    "initPosition": 0,
    "pollingPeriod": 60,
    "WindowCovering": {
        "reverse": false,
        "blindMode": false
    }
}

**Comment by dubocr** [comment]
The Callback already triggered is not the problem I think. You can ignore it.
As we can see the command is completed so for us TaHoma says "the door is open or opening"
Can you log there : https://dev.duboc.pro/tahoma and give me the last 4 digit of your bridge (SETUP-XXXX-XXXX-XXXX)

Thanks

**Comment by henkied** [comment]
5937

**Comment by dubocr** [comment]
Can you explain what you tried and what happen in Home and in reality.

For ex. there is multiple "open" command. Does your home app didn't react ? The Garage door widget display the spiner and "opening" word ?
```
Garagedeur - open - HomeKit (19/01/2021 21:13:26) COMPLETED
Garagedeur - open - HomeKit (19/01/2021 17:47:51) COMPLETED
Garagedeur - open - HomeKit (19/01/2021 17:23:23) COMPLETED
Garagedeur - open - HomeKit (19/01/2021 16:47:37) COMPLETED
Garagedeur - open - HomeKit (19/01/2021 15:21:45) COMPLETED
```

----

FYI
In your config, 
```
  "defaultPosition": 0,
  "initPosition": 0,
```
are ignored. You must put it in "WindowCovering"

**Comment by henkied** [comment]
True indeed, the status of garage is open. If I want to close it. He remains open status. and nothing happend

**Comment by dubocr** [comment]
Hi,

Could you please update to 2.x.x then give remaining issue feedback.
