### ISSUE TITLE
Connexion à Valve radiateur connectée Danfoss

### ISSUE THREAD

**Issue by louisendelicher** [dubocr/homebridge-tahoma#232]
Bonjour @dubocr et merci pour l'excellent travail que tu fais.
J'ai utilisé ton plugin pour connecter les différents objets fournis à la livraison de mon appartement (connecté par Somfy). Parmi ceux-ci figurent des vannes ZWave (de marque Danfoss que Somfy utilise) HeatingSystem. Celles-ci remontent bien dans Homekit mais je ne peux pas les contrôler et dans les log d'Homebridge il est indiqué "[1/18/2021, 8:38:57 PM] [My Tahoma] No target command for CHAMBRE" pour chacun des chauffages.
Sais-tu d'où cela pourrait venir et comment régler cette erreur ?
Merci énormément !
Louis

**Comment by dubocr** [comment]
Bonjour @louisendelicher,

Peux-tu te connecter sur la page https://dev.duboc.pro/tahoma et me transmettre les 4 derniers chiffres de ton bridge (SETUP-XXXX-XXXX-XXXX) afin que je puisse consulter ta config.

Merci

**Comment by louisendelicher** [comment]
Merci beaucoup pour ta réponse !
J’ai déjà essayé de m’y connecter tout à l’heure mais j’ai eu une erreur (voir PJ) peut-être une mauvaise manipulation de ma part ?
![C0B78DAB-A9DC-444E-8F85-7A91DC9809BD](https://user-images.githubusercontent.com/19635520/104961684-1c259d80-59d7-11eb-8bb2-397ff9703585.png)

**Comment by louisendelicher** [comment]
C’est bon cette fois ça a fonctionné !
Voici les 4 derniers chiffres : 6276.

Merci pour ton aide !

**Comment by dubocr** [comment]
Merci,

A priori le changement de T° devrait fonctionner. Peux-tu me confirmer ? Sinon peut-être que l'échec de la commande mode bloque l'ensemble. Dans ce cas peux-tu mettre à jour le plugin avec la dernière version et réessayer.

Eventuellement, tu peux également essayer de simplement modifier la consigne de T° avec l'application "Eve" pour confirmer que cette partie fonctionne. L'application Home envoie l'ensemble des état actuels lorsqu'on ouvre le widget ce qui peu poser problème tant que tout n'est pas fonctionnel.

Ensuite, pourras-tu réaliser les différents changements de mode possible avec l'application Somfy puis te reconnecter sur la page pour que je puisse ensuite les reproduire.
Il s'agirait de passer en mode AUTO (si existant), chauffage (confort), réduit (éco) et OFF (ou hors gel) sur l'application.

**Comment by louisendelicher** [comment]
Merci à toi.
Je n'ai pas réussi à modifier via HomeKit (Aucune réponse) et toujours le même message dans les logs Homebridge.
Avec l'app Eve je n'ai pas de message d'erreur et dans les logs : 
`[1/18/2021, 10:54:28 PM] [My Tahoma] [BUREAU] setTargetTemperature[20.5]
[1/18/2021, 10:54:28 PM] [My Tahoma] undefined
[1/18/2021, 10:54:28 PM] [My Tahoma] Listener registered 177dfc80-ac10-3401-7548-14e5cac6a83d`
Mais je ne sais pas si ça a réellement été pris en compte.

Dans l'application Somfy, je n'ai pas beaucoup d'options : uniquement le changement de température comme tu peux le voir sur la capture. Je vais faire quelques changement de température pour que tu puisses les voir de ton côté.
![IMG_0590](https://user-images.githubusercontent.com/19635520/104966357-fbfadc00-59e0-11eb-996f-e400a1fe7d3a.PNG)

**Comment by dubocr** [comment]
Si le message d'erreur est le meme dans les logs c'est que la mise à jour ne s'est pas faite.
Le changement de T° fonctionne à priori, une fois la mise à jour passée cela devrait donc fonctionner côté Homekit sauf si les modes sont refusés sur ce type de device mais vous auriez un message d'erreur différent.

**Comment by louisendelicher** [comment]
Effectivement, j'ai l'impression que le changement de température soit passé (soit via Eve soit via Home) malgré le message "Sans réponse" côté Home car c'est bien à la température que j'ai modifié tout à l'heure. Merci pour cela.
Je t'embête juste encore un tout petit peu pour te demander si il m'est possible de paramétrer dans Home pour qu'il n'y ait qu'un mode Chauffage (et non refroidir...), en effet les radiateurs apparaissent tout le temps "Éteint" sur Home alors qu'ils sont bel et biens allumés...
Je suis déjà très satisfait de pouvoir les contrôler via HomeKit et Siri.

Merci pour tout,
Bonne soirée

**Comment by dubocr** [comment]
Normalement avec la dernière version le pilotage depuis Home devrait être fonctionnel également.
Concernant les modes, peux-tu m'envoyer un screenshot du widget Thermostat sur l'app Home, je viens de vérifier et normalement aucun mode n'est configuré. Je voudrais vérifier commet cela apparait.
Par ailleurs, as-tu la possibilité d'éteindre/allumer les vanne ou uniquement de les piloter en T° sur l'app TaHoma ?

Merci.
