### ISSUE TITLE
Somfy Smoke detector does not present battery state

### ISSUE THREAD

**Issue by Bartus78** [dubocr/homebridge-tahoma#233]
I have got Somfy Smoke alarms installed in my home [https://boutique.somfy.fr/detecteur-de-fumee-io-pour-tahoma.html](https://boutique.somfy.fr/detecteur-de-fumee-io-pour-tahoma.html). Smoke alarm state is presented correctly both in armed and in alarm state. 

However, the battery state is not presented. Currently one alarm presents a low battery warning in the Tahoma Link, but this is not reported in Apple Home. Could this be added?

**Comment by Bartus78** [comment]
I see the smoke detectors actually have two batteries, one for the sensor (MaintenanceSensorPartBatteryState) and one for the radio (MaintenanceRadioPartBatteryState). Any of these low should lead to a HomeKit low battery state for the sensor (Homekit BatteryLowStatus). 

There is also a separate field giving the SensorDefectState, where every state not "NoDefect" should relate to HomeKit FaultStatus. 

Finally, StatusState (available) should be related to HomeKit  ActiveStatus enabled.

Thank you!

**Comment by dubocr** [comment]
Hi,

Battery and Fault will be reported in next major release 1.x.x currently in development. Should be available in the beta channel in the next days. (Be careful: this release breaks device identifiers, all your devices will be unlinked from automation)

However I don't have StatusState in the smoke sensor reported by users. Could you please log https://dev.duboc.pro/tahoma and give me your last 4 TaHoma digits to let me see your sensor.

Thank you.

**Comment by Bartus78** [comment]
Thank you. It is 8003.

Benno

Op 3 mrt. 2021 om 21:22 heeft Romain DUBOC <notifications@github.com> het volgende geschreven:

﻿

Hi,

Battery and Fault will be reported in next major release 1.x.x currently in development. Should be available in the beta channel in the next days. (Be careful: this release breaks device identifiers, all your devices will be unlinked from automation)

However I don't have StatusState in the smoke sensor reported by users. Could you please log https://dev.duboc.pro/tahoma<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.duboc.pro%2Ftahoma&data=04%7C01%7C%7C78ba27c3c83448d1f8da08d8de82209c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637503997754180852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U9i1%2B0nG8ZYy4XVyqYwaeNsyOymHJAtQdunhoICD3xU%3D&reserved=0> and give me your last 4 TaHoma digits to let me see your sensor.

Thank you.

**Comment by dubocr** [comment]
Thank you, ActiveStatus is implemented in 2.1.3.
