### ISSUE TITLE
Garage Door

### ISSUE THREAD

**Issue by mars-wolf** [dubocr/homebridge-tahoma#237]
Hi,
I have a very simple garage door opener connected to my tahoma.
If I press a button, the door opens. I have no control to press again to close it. After 120 seconds it closes automatically.
How can I setup this in homebridge-tahoma that it appears closed after 120 seconds? Currently I press twice the button in my home app, so it appears in correct state.
Any hints really welcome!

Current programmed plugin:

    "GarageDoorOpener": {
        "cyclic": true,
        "reverse": false,
        "stateless": true

Thanks!
Marcel

**Comment by qelanhari** [comment]
If it's the garage door that closes itself after 120 seconds, its a setup of the garage door (aka if no one crosses the security cells within 120s, it closes itself). If so, check the settings in somfy's manual.
Is it really a stateless Garage Door ?

**Comment by mars-wolf** [comment]
Yes, the 120 seconds are setup in the garage door and it closes itself. It is a "dumb" garage door opener. With a special somfy product connected to the "dumb" opener the somfy tahoma product sends a single signal to open the door. That's all. There is no second signal to close or something like that also no state that is transferred back. Only one signal in one direction.

**Comment by qelanhari** [comment]
Ok, after reading again I understood what is your goal. How does the virtual button behave in the tahoma's interface ?

From what I read of the plugin's code and the config you wrote above, the garagedoor button should be considered as closed 5 seconds after you hit the button once in the home app.

**Comment by mars-wolf** [comment]
It behaves as a button, a very simple one. Press it and thats it. The tahoma interface does not show if the garage door is open or closed. You just press the button and the door gets its signal to react. If you press the button again when the door is already open the door counts again backwards from 120 seconds until it closes again. You just reset the countdown.
My goal is just to have a simple button.

**Comment by qelanhari** [comment]
Ok, understood. There is no "stateless" button class in Homekit. The only thing we can do is reset the state after X milliseconds. This plugin, as you saw, allow you to set up the `cyclic` and `stateless` parameters. With both settings set to `true` the button should go back to "off/closed" after 5 seconds.
If this does not work, there is in fact a bug somewhere. If it works and you just want to increase the time to 120, it's not possible with this plugin for now. You may try to use an automation with another plugin https://github.com/nfarina/homebridge-dummy. Something like : when X turns on, then Y turns on for 120seconds, and when Y turns off turn X off.

**Comment by mars-wolf** [comment]
Thanks for the reply. I set it up like you said already:

    "GarageDoorOpener": {
        "cyclic": true,
        "reverse": false,
        "stateless": true

So there must be a bug because in home App the door keeps "open". It does not switch back to "closed" after 5 seconds. 5 seconds or 120 seconds don't bother me. So I will press twice the button for now and will speak to Siri twice. Thanks for your time and help so far.

**Comment by qelanhari** [comment]
Well, I just found out that the documentation has a typo. You should try to use `cycle` and not `cyclic`.

**Comment by qelanhari** [comment]
https://github.com/dubocr/homebridge-tahoma/blob/master/services/GarageDoorOpener.js#L12
https://github.com/dubocr/homebridge-tahoma/blob/master/services/GarageDoorOpener.js#L75
