### ISSUE TITLE
Add obstruction detection support for IO roller shutter motors

### ISSUE THREAD

**Issue by nitronl** [dubocr/homebridge-tahoma#239]
My high end IO roller shutter motors measure the amount of force while opening or closing. When a certain threshold relative to normal operation is exceeded they report obstruction. HomeKit apparently also supports the obstruction detection property as it is displayed in the Home app under settings for roller shutter devices. Currently the value is always false, even when I know it is true in the TaHoma app.

**Comment by qelanhari** [comment]
Did you check if your high end IO roller shutter aren't now natively compatible with homekit ?

**Comment by nitronl** [comment]
I have tested the Somfy HomeKit implementation with my RS100 IO motors and quickly went back to Homebridge. Homebrige + TaHoma plug-in stability was way better than Somfy's long awaited attempt. Somfy did not have the obstruction property at that time.

**Comment by qelanhari** [comment]
Somfy never disapoints 🥇 

Hope someone can check this obstruction feedback.

**Comment by dubocr** [comment]
Hi,

Plugin actually support obstruction when command execution failed with this error code.
Can you follow these steps to let me know if your shutters have additional states for obstruction.

Thanks

---

Please follow these step to obtain better support :
1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)
