### ISSUE TITLE
Lightsensor

### ISSUE THREAD

**Issue by MobiusOne91** [dubocr/homebridge-tahoma#24]
Hi Dubocr,

I would like to have to possibility to see the light value from my sensors. I tried to add following code in beneath line 34:
`this.log('['+this.name+'] Luminance value : ' + value);`

In syslog I get following error, when I try to restart Homebridge:
`Mar  4 12:11:38 Homebridge homebridge[1364]: [2018-3-4 12:11:38] Loaded plugin: homebridge-tahoma
Mar  4 12:11:38 Homebridge homebridge[1364]: homebridge-tahoma API version: 2.2
Mar  4 12:11:38 Homebridge homebridge[1364]: /usr/lib/node_modules/homebridge-tahoma/accessories/LightSensor.js:36
Mar  4 12:11:38 Homebridge homebridge[1364]:                 else
Mar  4 12:11:38 Homebridge homebridge[1364]:                 ^^^^
Mar  4 12:11:38 Homebridge homebridge[1364]: SyntaxError: Unexpected token else
Mar  4 12:11:38 Homebridge homebridge[1364]:     at createScript (vm.js:80:10)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Object.runInThisContext (vm.js:139:10)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Module._compile (module.js:607:28)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Object.Module._extensions..js (module.js:654:10)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Module.load (module.js:556:32)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at tryModuleLoad (module.js:499:12)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Function.Module._load (module.js:491:3)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Module.require (module.js:587:17)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at require (internal/module.js:11:18)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at /usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:37:39
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Array.forEach (<anonymous>)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at module.exports (/usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:33:36)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Plugin.module.exports [as initializer] (/usr/lib/node_modules/homebridge-tahoma/index.js:17:68)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:160:14)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Array.forEach (<anonymous>)
Mar  4 12:11:38 Homebridge homebridge[1364]:     at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:138:22)
Mar  4 12:11:38 Homebridge systemd[1]: homebridge-haussteuerung.service: Main process exited, code=exited, status=1/FAILURE`

Do you know what is wrong with that code?

Second, quite often HomeKit loses the connection to the light sensors. Tahoma has a connection. Do you know why, or is this a bug?

**Comment by dubocr** [comment]
Hi,
You want to see the light value in logs that’s right ?
Think you forgot the braces {} to group the line 34 + your new line.
´´
if(value >= 0.0001 && value <= 100000)
{
    this.lightState.updateValue(value);
    this.log('['+this.name+'] Luminance value : ' + value);
}
else
this.log('['+this.name+'] Outbound luminance value : ' + value);
´´
