### ISSUE TITLE
Sans la box tahoma

### ISSUE THREAD

**Issue by djrams10** [dubocr/homebridge-tahoma#241]
Bonjour, j’ai une question, est il possible de piloter mon chauffe eau connecté à l’application cozytouch sans passer par une box tahoma ? Je n’en possède pas et je ne prévoit pas l’acquisition de celle-ci. Merci d’avance pour votre aide.

**Comment by dubocr** [comment]
Bonjour,

La box TaHoma ne gère probablement pas votre chauffe-eau connecté. Pour cela vous devez acquérir un bridge Cozytouch.
