### ISSUE TITLE
Error 400 Too many asynchronous jobs

### ISSUE THREAD

**Issue by PatriceRobert** [dubocr/homebridge-tahoma#247]
Hi there,

Weird issue with this error:
`Error: Error 400 Too many asynchronous jobs, try again later (job was Full refresh all states) (TOO_MANY_OPERATIONS_IN_PROGRESS)`

This happens when trying to launch **only one** command from Homekit which is the start of an exported scenario.

Basically, when the blinds (velux) are opening/closing automatically with sunrise/sunset from a Homekit automation, it used to work fine and suddenly for the past few days, this error pops-up and nothing happens.

Then when manually doing it one-by-one from Homekit, the blinds are executing normally....

**Comment by PatriceRobert** [comment]
And tonight, another error, after upgrading to latest version, having it launched without any activities till this error:

`Feb 28 19:03:49 magneto homebridge[5867]: [Tahoma] Error 502
Feb 28 19:04:31 magneto homebridge[5867]: [Tahoma] Error 429 Server busy, please try again later. (Too many executions) (TOO_MANY_OPERATIONS_IN_PROGRESS)
`

Patrice.

**Comment by PatriceRobert** [comment]
Well, issue is on Somfy's cloud side.....
This morning, no commands have been sent at all, no actions but got another refresh error:
`Mar  2 07:01:04 magneto homebridge[441]: [Tahoma] Error 400 Too many asynchronous jobs, try again later (job was Full refresh all states) (TOO_MANY_OPERATIONS_IN_PROGRESS)
Mar  2 07:01:04 magneto homebridge[441]: [Tahoma] Error: Error 400 Too many asynchronous jobs, try again later (job was Full refresh all states) (TOO_MANY_OPERATIONS_IN_PROGRESS)
`
Went on opening just few minutes after and it worked:
`Mar  2 07:05:30 magneto homebridge[441]: [Tahoma] [Salle de Bains] setClosure[0]
Mar  2 07:05:30 magneto homebridge[441]: [Tahoma] [Dressing] setClosure[78]
Mar  2 07:05:30 magneto homebridge[441]: [Tahoma] undefined
Mar  2 07:05:30 magneto homebridge[441]: [Tahoma] Listener registered f18aa25b-ac10-3e01-0169-e7622d6b6a0e
Mar  2 07:06:07 magneto homebridge[441]: [Tahoma] [Salle de Bains] setClosure COMPLETED
Mar  2 07:06:07 magneto homebridge[441]: [Tahoma] [Dressing] setClosure COMPLETED
`

So nothing to do with the homebridge-tahoma plugin, but Somfy looks over busy on their cloud infrastructure....

Patrice.

**Comment by nscheffer** [comment]
Same for me !
Before working perfectly with most of the shutters used directly with HomeKit, only 2 garages doors and portal were controlled with Homebridge. How to reach too many requests for 3 devices ?

**Comment by nscheffer** [comment]
Hello Patrice -:)

**Comment by dubocr** [comment]
As 2.x.x release manage differently polling, please feedback any new occurence if any.

Thanks
