### ISSUE TITLE
fail to update version 2.0

### ISSUE THREAD

**Issue by henkied** [dubocr/homebridge-tahoma#250]
one 2 homebridge i cannot update to version 2

npm ERR! code 1
npm ERR! path /homebridge/node_modules/homebridge-tahoma/node_modules/event
npm ERR! command failed
npm ERR! command sh -c npm dedup
npm ERR! npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EACCES: EACCES: permission denied, open '/root/.npm/_cacache/tmp/9b7793b1'
npm ERR! npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! npm ERR! code EACCES
npm ERR! npm ERR! syscall open
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/2d6f7ed8
npm ERR! npm ERR! errno EACCES
npm ERR! npm ERR! 
npm ERR! npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! npm ERR! previous versions of npm which has since been addressed.
npm ERR! npm ERR! 
npm ERR! npm ERR! To permanently fix this problem, please run:
npm ERR! npm ERR!   sudo chown -R 1026:100 "/root/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-21T15_44_55_663Z-debug.log

Command failed. Please review log for details.

**Comment by nscheffer** [comment]
Same for me 👍 
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-tahoma@latest

npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/homebridge-tahoma/node_modules/event
npm ERR! command failed
npm ERR! command sh -c npm dedup
npm ERR! npm ERR! code EDEDUPEGLOBAL
npm ERR! npm ERR! `npm dedupe` does not work in global mode.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/pi/.npm/_logs/2021-03-21T16_11_14_295Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-03-21T16_11_14_788Z-debug.log

Command failed. Please review log for details.

**Comment by dubocr** [comment]
Hi,

As shown in logs please run `sudo chown -R 1026:100 "/root/.npm"` then try again without using **sudo**.

**Comment by staryga** [comment]
failed to update:

22 verbose stack Error: `npm dedupe` does not work in global mode.
22 verbose stack     at Dedupe.dedupe (/usr/local/lib/node_modules/npm/lib/dedupe.js:19:18)
22 verbose stack     at Dedupe.exec (/usr/local/lib/node_modules/npm/lib/dedupe.js:14:10)
22 verbose stack     at Object.[_runCmd] (/usr/local/lib/node_modules/npm/lib/npm.js:112:12)
22 verbose stack     at /usr/local/lib/node_modules/npm/lib/npm.js:28:35
22 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cli.js:58:7)
23 verbose cwd /usr/local/lib/node_modules/homebridge-tahoma/node_modules/event
24 verbose Darwin 19.6.0
25 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/.bin/npm" "dedup"
26 verbose node v15.11.0
27 verbose npm  v7.6.3
28 error code EDEDUPEGLOBAL
29 error `npm dedupe` does not work in global mode.
30 verbose exit 1

**Comment by nscheffer** [comment]
Hi,

Still have a problem 👍 
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-tahoma@latest

npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/homebridge-tahoma/node_modules/event
npm ERR! command failed
npm ERR! command sh -c npm dedup
npm ERR! npm ERR! code EDEDUPEGLOBAL
npm ERR! npm ERR! `npm dedupe` does not work in global mode.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/pi/.npm/_logs/2021-03-21T19_34_31_811Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-03-21T19_34_32_324Z-debug.log

Command failed. Please review log for details.

**Comment by danny1605** [comment]
failed to update

USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-tahoma@latest

npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-tahoma/node_modules/event
npm ERR! command failed
npm ERR! command sh -c npm dedup
npm ERR! npm ERR! code EDEDUPEGLOBAL
npm ERR! npm ERR! `npm dedupe` does not work in global mode.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/homebridge/.npm/_logs/2021-03-22T07_51_08_296Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-03-22T07_51_08_612Z-debug.log

Command failed. Please review log for details.

**Comment by alastairjardine** [comment]
Hi,

Receiving this error when updating to v2

`USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-tahoma@latest

npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-tahoma/node_modules/event
npm ERR! command failed
npm ERR! command sh -c npm dedup
npm ERR! npm ERR! code EDEDUPEGLOBAL
npm ERR! npm ERR! `npm dedupe` does not work in global mode.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/homebridge/.npm/_logs/2021-03-22T12_59_19_550Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-03-22T12_59_20_067Z-debug.log

Command failed. Please review log for details.`

**Comment by dubocr** [comment]
Hi all,

It seems you are all using software that generating command `sudo -E -n npm install -g homebridge-tahoma@latest`
And as you are all posting error with same syntax (USER: xx / DIR : xx / CMD : xx), from where these logs come from ?
Plugin install should normaly be made without `sudo` rights. But not sure it's what's wrong here.

Could you please provide more details about your installation.

**Comment by dubocr** [comment]
Re Hi,

Could you please retry with latest 2.1.4 release, hope it will solve.

Thanks

**Comment by staryga** [comment]
in my case it has updated but the plugin is keep on restaring. I am on macOs

[3/22/2021, 11:36:10 PM] [My TaHoma Box] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[3/22/2021, 11:36:10 PM] [My TaHoma Box] Launched child bridge with PID 35738
[3/22/2021, 11:36:10 PM] Registering platform 'homebridge-tahoma.Tahoma'
[3/22/2021, 11:36:10 PM] [My TaHoma Box] Loaded homebridge-tahoma v2.1.4 child bridge successfully
[3/22/2021, 11:36:10 PM] Loaded 0 cached accessories from cachedAccessories.0EA6B90FC91A.

/usr/local/lib/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:53
            throw new Error('Invalid service name \''+this.service+'\'');
                  ^
Error: Invalid service name 'TaHoma'
    at new OverkizClient (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/overkiz-client/src/Client.ts:53:19)
    at new Platform (/usr/local/lib/node_modules/homebridge-tahoma/src/Platform.ts:32:23)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:134:42)
[3/22/2021, 11:36:10 PM] [My TaHoma Box] Child bridge process ended
[3/22/2021, 11:36:10 PM] [My TaHoma Box] Process Ended. Code: 1, Signal: null

**Comment by dubocr** [comment]
You should set "tahoma" as service name in your config (or use homebridge-ui to configure it easily). I'll force lowercase to avoid this kind of mistakes.

Thanks

**Comment by staryga** [comment]
it helped. thanks, i appreciate your work!

**Comment by dubocr** [comment]
Will close this issue, @henkied @nscheffer @danny1605 @alastairjardine please reopen if latest release don't fix for you.

Thanks
