### ISSUE TITLE
Alarm > TSKAlarmController

### ISSUE THREAD

**Issue by koupus** [dubocr/homebridge-tahoma#251]
Bonsoir Romain,

Tout d'abord merci pour cette MAJ !
Cependant depuis celle ci, j'ai perdu mon alarme interne à Tahoma (Serenity) dans Homekit.

Une chance de pouvoir la retrouver ?

Je viens  de me log sur le dev. Devices SETUP-XXXX-XXXX-0976.

Merci !

Thomas

**Comment by dubocr** [comment]
Bonsoir Thomas,

Merci pour ton message et d'avoir bien suivi le process pour faciliter le diagnostic.
J'ai déployé une nouvelle version qui devrait corriger le problème.

N'ayant pas d'alarme dans mon installation les tests on été très limités sur cette nouvelles version, n'hésites pas à remonter les problème rencontrés.

Merci d'avance.

**Comment by koupus** [comment]
Merci Romain! Elle est désormais à nouveau accessible grâce à la MAJ.
Juste un « Active Button »  qui est apparu en même temps! Il est inutile et indiqué comme « non géré »! Je n’arrive pas à le cacher via homebridge...
![5AFE6A12-0501-49BE-B373-B8D25D66DB35](https://user-images.githubusercontent.com/50924184/111920025-fd9e5a00-8a8c-11eb-92e6-fb4c4dbb67d4.jpeg)

**Comment by dubocr** [comment]
Effectivement, je l'ai trouvé. Il sera masqué dans la prochaine version ce soir ou demain. Tu peux toujours le masquer en ajoutant `Pod` à la liste des device à exclure.

**Comment by koupus** [comment]
C’est parfait! Merci beaucoup !
