### ISSUE TITLE
Position volets par défaut

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#254]
Bonjour Romain et merci pour cette mise à jour.
Je n’ai pas de problème particulier.
Si tu pouvez juste apporter la possibilité de choisir la position par défaut au redémarrage d’homebridge des volets ou stores comme avec l’ancienne version: "initPosition": 0 directement dans les réglages du plugin.
Je les ai rajouté manuellement dans la config.
Par contre suite à la mise à jour, tous les volets avaient la position fermé au lieu du 50%. Ce n’est pas un problème, mais peut-être que certains appréciaient cela.

**Comment by dubocr** [comment]
Bonjour Patrick,

Effectivement il y a quelques changements à ce niveau. Cette nouvelle version restaure normalement la dernière position au redémarrage.
L'état devrait donc être généralement correct sauf en cas de changement par une commande locale. Dans ce cas, l'option "defaultPosition" reste toujours possible pour forcer une position par défaut après chaque modification.

A noter également que la configuration s'applique de façon différente avec cette version : idéalement utiliser l'éditeur homebridge-UI ou sur Hoobs.

Tiens moi au courant si cela ne répond pas au besoin.

**Comment by Tontonpat** [comment]
Merci pour ta réponse.
Je n’avais pas « capter » que ça garder la position en mémoire, c’est une très bonne idée !
Du coup pas besoin de configurer initPosition. C’est parfait. J’ai une autre requête. Mais je vais en ouvrir une autre.
Encore merci pour ce super travail.

**Comment by dubocr** [comment]
👍 impec, tiens moi au courant si pb.
Avec plaisir ;-)
