### ISSUE TITLE
Device to exclude

### ISSUE THREAD

**Issue by Konisan-K7** [dubocr/homebridge-tahoma#255]
Bonjour Romain,

Merci pour cette nouvelle mise à jour et globalement pour ton travail.

Je rencontre pour le moment un problème au niveau des éléments à ne pas afficher dans Maison. Tous les nouveaux que je veux exclure restent présents dans HomeKit alors que les anciens déjà ajoutés restent bien exclus.

Merci encore,
Nicolas

**Comment by dubocr** [comment]
Bonjour Nicolas,

Tu modifies directement ton fichier de config ? Peux-tu m'envoyer le paramètre exclude que tu utilises ?

Merci

**Comment by Konisan-K7** [comment]
Oui je modifie le fichier config et j’utilise
"exclude": ["hue", "DHW Set Point", ...],
Ceux que j’avais d’avant sont toujours bien exclus mais les nouveaux apparus avec la nouvelle mise à jour comme Serenity, Bouton sensitif ne disparaissent pas.

**Comment by dubocr** [comment]
Peux-tu te connecter sur https://dev.duboc.pro/tahoma et m’indiquer ton numéro de bridge.

merci

**Comment by Konisan-K7** [comment]
Salut, tu parles de mon numéro de bridge homebridge?
Sinon je sais pas si c’est lié mais depuis la mise à jour de ton plugin j’ai mon homebridge qui n’arrête pas de rebooter plusieurs fois par heure.

**Comment by Konisan-K7** [comment]
Pour le reboot de homebridge, j’ai redémarré mon raspberry Pi et le problème semble résolu.

**Comment by Tontonpat** [comment]
Bonjour Romain,
J’ai le même problème concernant les équipements à exclure.
Je me suis servi du réglage du plugin et non de la config.
Depuis la V2, ça m’a ajouté plein de boutons (correspondant aux télécommandes keygo et serenity) et le bouton sensitif (qui n’est pas géré par home) de la tahoma que je ne parviens pas à exclure.
![33C43DF5-7953-4253-BC76-A6C7C196E1E2](https://user-images.githubusercontent.com/49283285/111988695-18b2ad80-8b11-11eb-82bf-1edd50426b0d.jpeg)

**Comment by dubocr** [comment]
Pour les périphériques non gérés cela devrait être bon dans la dernière version.
Pour les télécommandes, si tu souhaites les masquer regarde le type de widget et ajoute le à la liste d'exclusion.
Envoi moi sinon la fin de ton N° de bridge après t'être connecté sur la page

**Comment by Tontonpat** [comment]
Le bouton sensitif (non géré) apparait toujours, que je l'exclu ou non.
Je ne sais pas ou trouver le type de widget.
Serait ce "RemoteController" ? Si oui, les télécommandes apparaissent toujours dans Home, mais plus au démarrage d'homebridge dans MAP Device qui liste tous les équipements.
Je suppose que çà n'efface pas les équipements déjà inclus lors de l'exclusion.
Mon n° de bridge : 9950

**Comment by dubocr** [comment]
Les widget sont accessible via https://dev.duboc.pro/tahoma dans les titres (voir photo sur  le second commentaire plus haut)

RemoteController effectivement pour les télécommande. Ils devrait en principe être supprimés si ils n'apparaissent plus dans le mapping de démarrage.

Le bouton c'est 'Pod' mais il est déjà exclus par défaut. Si ils persistent à rester sur Home même après un redémarrage il est possible de supprimer le fichier de cache mais je préfère comprendre pourquoi ils ne disparaissent pas.

Ca peut prendre quelque secondes après le démarrage si beaucoup de device.

**Comment by dubocr** [comment]
C'est bon j'ai trouvé, cela devrait être mieux avec la 2.1.7, effectivement les devices déjà présents n'était plus exclus.

Merci

**Comment by Tontonpat** [comment]
Je venais de les trouver, désolé.
J'ai donc mis RemoteControllerOneWay et AlarmRemoteController à exclure
![Capture d’écran 2021-03-23 à 15 21 10](https://user-images.githubusercontent.com/49283285/112161905-d9a55a80-8beb-11eb-9176-d229fad6891e.png)
Mais ils sont toujours présents dans home et homebridge , ainsi que le bouton sensitif, malgré qu'ils n'apparaissent pas dans map device
![Capture d’écran 2021-03-23 à 15 21 35](https://user-images.githubusercontent.com/49283285/112161969-ea55d080-8beb-11eb-9b2e-9d72b027293c.png)

**Comment by Konisan-K7** [comment]
Salut, super ça fonctionne en effet avec la toute dernière mise à jour.
Merci.
Sinon autre petite question, il y a les caméras somfy Protect qui apparaissent aussi mais qui ne sont gérées.
Est-ce que tu vas/pouvoir les inclure dans une prochaine mise à jour ou ce n’est pas possible avec les API de Somfy. Je sais que ça marche avec Ring mais peut-être pas ici.

Merci encore pour ton travail

**Comment by Tontonpat** [comment]
C'est tout bon, les boutons télécommandes ont bien disparu, ainsi que le bouton sensitif.
Merci

**Comment by dubocr** [comment]
> Salut, super ça fonctionne en effet avec la toute dernière mise à jour.
> Merci.
> Sinon autre petite question, il y a les caméras somfy Protect qui apparaissent aussi mais qui ne sont gérées.
> Est-ce que tu vas/pouvoir les inclure dans une prochaine mise à jour ou ce n’est pas possible avec les API de Somfy. Je sais que ça marche avec Ring mais peut-être pas ici.
> 
> Merci encore pour ton travail

Pour les caméras je pourrais effectivement me pencher dessus pour voir ce qui est faisable. Pour l’instant je ne sais pas dire mais c’est l’objectif de cette nouvelle version que de gérer d’éventuels nouveaux device sur une base plus stable.
