### ISSUE TITLE
Tahoma 2.1.3 + HOOBS 3.3.5 = CRASH

### ISSUE THREAD

**Issue by Ciarals84** [dubocr/homebridge-tahoma#256]
Hello. Tahoma 2.1.3 makes HOOBS to SIGINT. HOOBS service stops and remains stopped until the Tahoma 2.1.3 plugin is installed. I tried uninstalling all the plugins I had installed and HOOBS service restarts. Then I reinstall Tahoma 2.1.3 and HOOBS service stops again so it's clearly the Tahoma plugin or maybe both (HOOBS 3.3.5 + Tahoma 2.1.3). Here's the log:

```
22/3/2021, 01:17:46 HOOBS listening on port 80.
22/3/2021, 01:17:49 Initializing HAP-NodeJS v0.9.3...
22/3/2021, 01:17:51 No plugins installed.
22/3/2021, 01:17:51 Preparing Advertiser for 'Miller HOOBS 16B8' using bonjour-hap backend!
22/3/2021, 01:17:51 Starting to advertise 'Miller HOOBS 16B8' using bonjour-hap backend!
22/3/2021, 01:17:51 Bridge is running on port 51826.
22/3/2021, 07:40:18 
> event@1.0.0 postinstall /home/hoobs/.hoobs/node_modules/event
> npm dedup
22/3/2021, 07:40:23 npm
22/3/2021, 07:40:23  notice created a lockfile as package-lock.json. You should commit this file.
22/3/2021, 07:40:24 up to date in 1.574s
22/3/2021, 07:40:24 found 0 vulnerabilities
22/3/2021, 07:40:24 + homebridge-tahoma@2.1.3
added 22 packages from 18 contributors in 13.417s
22/3/2021, 07:40:24 
2 packages are looking for funding
  run `npm fund` for details
22/3/2021, 07:40:25 Plugin "homebridge-tahoma" installed.
22/3/2021, 07:40:25 Got SIGINT, shutting down Bridge...
22/3/2021, 07:40:33 Initializing HAP-NodeJS v0.9.3...
22/3/2021, 07:40:34 Loaded plugin 'homebridge-tahoma'
22/3/2021, 07:40:35 [3/22/2021, 12:40:34 AM] Registering platform 'homebridge-tahoma.Tahoma'
22/3/2021, 07:40:35 Loading 1 platforms...
22/3/2021, 07:40:35 [Tahoma] Initializing Tahoma platform...
22/3/2021, 07:47:14 connect ECONNREFUSED 127.0.0.1:51826
```

I will not send any config file because I have deleted the Tahoma plugin and re-installed from scratch, so the configuration is the default one and in HOOBS I don't have any other plugin installed. After removing Tahoma HOOBS service restarts correctly:

```
22/3/2021, 07:55:04 removed 22 packages and audited 3 packages in 3.296s
22/3/2021, 07:55:04 found 0 vulnerabilities
22/3/2021, 07:55:04 Plugin "homebridge-tahoma" removed.
22/3/2021, 07:55:07 Initializing HAP-NodeJS v0.9.3...
22/3/2021, 07:55:08 No plugins installed.
22/3/2021, 07:55:08 Preparing Advertiser for 'Miller HOOBS 16B8' using bonjour-hap backend!
22/3/2021, 07:55:08 Starting to advertise 'Miller HOOBS 16B8' using bonjour-hap backend!
22/3/2021, 07:55:08 Bridge is running on port 51826.
```

Just for your notice, I'm under a HOOBS in the box Raspberry Pi 3 Model B Rev 1.2 that I'm using since 1 year without any issue. I can't provide any error from https://dev.duboc.pro/tahoma because over there I have no errors since the plugin was functioning correctly before updating it. My bridge last 4 digits are 7686. Thank you very much.

**Comment by Ciarals84** [comment]
Any chance of solving this soon? I have 5 windows and 10 curtains controlled by your plugin. The latest update is totally unusable.

**Comment by dubocr** [comment]
Hi,

Hope 2.1.5 release should fix your issue.

Please feedback

**Comment by Ciarals84** [comment]
Unfortunately no, same issue. Service stopped.

```
23/3/2021, 00:37:32 HOOBS listening on port 80.
23/3/2021, 00:37:35 Initializing HAP-NodeJS v0.9.3...
23/3/2021, 00:37:36 No plugins installed.
23/3/2021, 00:37:36 Preparing Advertiser for 'Miller HOOBS 16B8' using bonjour-hap backend!
23/3/2021, 00:37:36 Starting to advertise 'Miller HOOBS 16B8' using bonjour-hap backend!
23/3/2021, 00:37:36 Bridge is running on port 51826.
23/3/2021, 00:41:32 + homebridge-tahoma@2.1.5
added 6 packages from 7 contributors in 8.562s
23/3/2021, 00:41:32 
2 packages are looking for funding
  run `npm fund` for details
23/3/2021, 00:41:32 Plugin "homebridge-tahoma" installed.
23/3/2021, 00:41:33 Got SIGINT, shutting down Bridge...
23/3/2021, 00:41:41 Initializing HAP-NodeJS v0.9.3...
23/3/2021, 00:41:42 Loaded plugin 'homebridge-tahoma'
23/3/2021, 00:41:42 [3/22/2021, 5:41:42 PM] Registering platform 'homebridge-tahoma.Tahoma'
23/3/2021, 00:41:42 Loading 1 platforms...
23/3/2021, 00:41:42 [Tahoma] Initializing Tahoma platform...
```

After another reboot:

```
23/3/2021, 00:44:01 HOOBS listening on port 80.
23/3/2021, 00:44:04 Initializing HAP-NodeJS v0.9.3...
23/3/2021, 00:44:06 Loaded plugin 'homebridge-tahoma'
23/3/2021, 00:44:06 [3/22/2021, 5:44:06 PM] Registering platform 'homebridge-tahoma.Tahoma'
23/3/2021, 00:44:06 Loading 1 platforms...
23/3/2021, 00:44:06 [Tahoma] Initializing Tahoma platform...
```

And that's it.

**Comment by dubocr** [comment]
You don’t notice any other error logs ? I will try to instal Hoobs to try debuging as it’s very difficult without any logs.

**Comment by Ciarals84** [comment]
No, I copied/pasted all the logs. Not so much, that’s because HOOBS is now empty due to this error as I wanted to avoid any other interference from other plugins to solve this issue. You will debug it easily: simply install latest HOOBS 3.3.5 and your plugin will make it crash/stop.

**Comment by Ciarals84** [comment]
Any chance of having this issue solved in short time? There are many HOOBS users out there and, since, this was an important release, maybe a little more testing would have been great, because there's no "standard" way to go back to previous versions and also all products are disappeared from Homekit.

I tried installing latest version 2.1.7 but still the same issue: after install is successfull, bridge stops:

<img width="905" alt="Schermata 2021-03-24 alle 14 53 58" src="https://user-images.githubusercontent.com/67325842/112322651-6108d180-8cb1-11eb-8643-af9373424b83.png">

After uninstalling plugin, bridge works as usual:

<img width="905" alt="Schermata 2021-03-24 alle 14 54 50" src="https://user-images.githubusercontent.com/67325842/112322735-72ea7480-8cb1-11eb-83c2-b6b4208235f0.png">

Thank you for your help.

**Comment by dubocr** [comment]
Hi,

This release was tested on homebridge. This is an open source plugin not a company software.
I don't know if updates are automatic on Hoobs, you are free to help improving it by testing latest release like you do.
After my main (true) work, I bought an SD card to install the system you are using (Hoobs).

Here are the logs, and yes everything is working fine in 3.3.3 and 3.3.5.

<img width="900" alt="Capture d’écran 2021-03-24 à 19 57 50" src="https://user-images.githubusercontent.com/5015156/112368362-49464300-8cdb-11eb-8589-3534996b20ee.png">

I think you are not telling me your config, it might come from here.
As I see that Hoobs don't support select box in config then your server name should be bad.

**Comment by Ciarals84** [comment]
Hello, I didn't wanted to mean that you had to help me or that your software had to work 100%, I know perfectly that this is open source and if this is the message that came out I'm really really sorry, it wasn't the meaning I wanted to give you. 

Besides from this, when you say "You're not telling me your config", I will if you just tell me what do I have to do. I can provide you my configuration. I'm under a "HOOBS in a Box": I bought it for 169,99 USD and that's it, I haven't configured anything a part from the usual things (name, admin, etc.). Everything worked fine until the 2.x.x update of Tahoma and all the other plugins work fine so there's something for sure in your pluing. I also see some other posts with people that can't install the plugin so there's surely something, not easily to find but there is. I will give you all I can. This is my configuration:

<img width="475" alt="Schermata 2021-03-24 alle 20 58 21" src="https://user-images.githubusercontent.com/67325842/112376271-86fb9980-8ce4-11eb-8b8f-f4906605e387.png">

This is my System:

<img width="814" alt="Schermata 2021-03-24 alle 20 58 45" src="https://user-images.githubusercontent.com/67325842/112376298-911d9800-8ce4-11eb-9713-472c3c8d03f2.png">

This is my Operative System:

<img width="831" alt="Schermata 2021-03-24 alle 20 58 56" src="https://user-images.githubusercontent.com/67325842/112376324-9bd82d00-8ce4-11eb-9a5f-7abf6c41d680.png">

Please tell me if I can provide you some other things that can be useful to solve this issue. Thank you very much for your effort. I will be glad to donate you what you have spent for the SD card since you did it just for me (and maybe for some other HOOBS in a Box user). Thank you again.

**Comment by dubocr** [comment]
Sorry for this misunderstanding.

Concerning your config, I just think of it after checking that everything works fine for me.
I didn't ask you before for this reason, but I said "You're not telling me your config" because it could be a pain to ask each user to give every infos that could help (like config, what they are trying to do, etc.).
You take the time to send logs (thanks for that) but as you see they don't provide any information and you ask twice "Any chance of having this issue solved in short time?" without trying to provide more information.

I understand you are buying your bridge and this price include tests for certified plugins. As mine is not certified it should be used "at you own risk" even if I will always try to make it working for most people.

As you said, I bought the SD card for you because you report this issue but even for other users so consider we are both helping the community and I'm not expecting anything more expected patience as I can't be fulltime on this project.

I understand it could be annoying as nothing is working for you but I think you can fix it "by yourself" (without new release). Maybe by searching hours and checking plugin readme, meaning using your time (instead of waiting mine).

To come back to the issue, it's the plugin config that I would like to check. I think there is something missing in it and Hoobs didn't show errors. Which service are you trying to use ? Tahoma, Cozytouch, ... ?

**Comment by dubocr** [comment]
I succeed reproducing behavior like your (no more logs after 24/03/2021, 21:48:32 [TaHoma] Initializing Tahoma platform...) by setting a bad service name in my config.
I try to understand why Hoobs isn't showing errors in logs but you can start to check the service name in your config.

**Comment by Ciarals84** [comment]
Hello and thank you again for your support.

> without trying to provide more information

This is just because I really don't know what do you need so I simply have sent you what I THINK that could help, but I'm not a developer, so I really don't know.

> I'm not expecting anything more expected patience as I can't be fulltime on this project

Understand perfectly and, again, sorry if my message had the impression of no patience, it wasn't what I intended.

> I think you can fix it "by yourself" (without new release).

The thing is: I don't know how to do that. In Homebridge it's easier but in HOOBS it's not, I don't know how can I do that but if you know, I can surely install the previous version and I will be fine :-)

> Maybe by searching hours and checking plugin readme, meaning using your time (instead of waiting mine).

Believe me, it's what I'm already doing: I've wrote also to HOOBS team, I'm searching in all Reddit and in Homebrdige forums to have some help. I'm not just waiting for you :-) I want to be helpful also for others that could have the same issue.

> To come back to the issue, it's the plugin config that I would like to check. I think there is something missing in it and Hoobs didn't show errors. Which service are you trying to use ? Tahoma, Cozytouch, ... ?

How can I provide it to you? I can't find a way in HOOBS, in Homebridge I knew how to do that but in HOOBS I can't and I can't find it in the guides. I'm trying to use Tahoma.

> I try to understand why Hoobs isn't showing errors in logs but you can start to check the service name in your config.

Just tell me how can I send you the log and I will be happy to do that :-)

**Comment by Ciarals84** [comment]
After installing the configuration and without modifying the default plugin configuration, this is the entire HOOBS configuration:

<img width="517" alt="Schermata 2021-03-24 alle 22 46 35" src="https://user-images.githubusercontent.com/67325842/112388068-e5c80f80-8cf2-11eb-96f3-79b7b60bcfec.png">

Did you need this?

**Comment by dubocr** [comment]
Thank you.
Can you confirm me you try to use Somfy "Tahoma" service ?
Now just add your user and password to the config and check "service", "user" and "password" fields are well set in your config.

**Comment by Ciarals84** [comment]
Yes, I'm using Tahoma service. I've added again user and password and this time it worked!! How could this be? Of course I already tried after updating and in these days but it never worked! Maybe in one of the latest updates something was changed? Because otherwise I really can't explain. When I updated to 2.1.3 the config was there and HOOBS crashed. So I reinstalled the plugin and added the Tahoma credentials but it didn't work. Is there a reason? Just to understand, you know :-)

**Comment by dubocr** [comment]
For the first update (from 0.x.x to <2.1.4) it is for sure the service name that was wrong as I had to change the names to match UI configuration schema.
After that, if your user and password were always set I can't explain it.
For sure there was an error that Hoobs didn't display (I add a workaround for that in 2.1.11) because I reproduce the same log behavior (Tahoma initializing then nothing more) when user, password or service is wrong.

Relieved to see that you will finally be able to reuse your devices.

**Comment by Ciarals84** [comment]
Ok, understand. For sure HOOBS doesn't like that the config file of your plugin is empty and this thing makes the service to stop. This is the only thing that we know for now.

Just one final question for you... In your update you said this:

> New plugin release 2.x.x will have many breaking changes. It will offer better stability for future development but this imply breaking devices identifiers from previous releases. After installing, this version, your devices will be removed from Homekit automation and you will have to configure them again. We appologize for that.

So we will have to reconfigure again all the devices in Homekit. No problem for this of course. But after having updated to version 2.x.x and having reconfigured everything, we will be done for some time, right? This 2.x.x update will be ok for a long time so we will not need to reconfigure everything again in the next months/years?

**Comment by dubocr** [comment]
> So we will have to reconfigure again all the devices in Homekit. No problem for this of course. But after having updated to version 2.x.x and having reconfigured everything, we will be done for some time, right? This 2.x.x update will be ok for a long time so we will not need to reconfigure everything again in the next months/years?

Yes, it's the goal. Device identifiers are now the Tahoma device identifiers so they will keep unchanged (except maybe if you delete and pair your device again in Tahoma).
This version let me separate clearly different kind of device to continue improving new devices without breaking olders.
So it will be a (more and more) stable version, hope forever.

**Comment by Ciarals84** [comment]
Perfect, really thank you so much. Just one final check. These below are now my actual log and config:

<img width="916" alt="Schermata 2021-03-25 alle 00 30 14" src="https://user-images.githubusercontent.com/67325842/112396887-51b17480-8d01-11eb-8e7b-af435665b84f.png">

<img width="513" alt="Schermata 2021-03-25 alle 00 34 11" src="https://user-images.githubusercontent.com/67325842/112397204-eb792180-8d01-11eb-8843-2cf8a06fa05b.png">

Can you please check them and see if everything seems to be fine and set correctly? Thank you!

**Comment by dubocr** [comment]
Yes that's perfect. As Hoobs hide debug logs you can't see device type at startupt but if you need some support because of bad device behaviour, just browse https://dev.duboc.pro/tahoma and give me your SETUP-XXXX-XXXX-XXXX id (visible on the page) to let me understand your device parameters.

**Comment by Ciarals84** [comment]
Perfect, really thank you so much :-) You're really doing a great job: I have bought HOOBS just to use your plugin so you can understand how much is important for me your plugin... Thank you again and have a good day/night (wherever you are).

**Comment by dubocr** [comment]
> Perfect, really thank you so much :-) You're really doing a great job: I have bought HOOBS just to use your plugin so you can understand how much is important for me your plugin... Thank you again and have a good day/night (wherever you are).

I understand that buying Hoobs only for my plugin could be annoying if it's not working properly.
Be sure I'll do my best to make it the more stable as possible in the next month.

Thank you to helping me solving this issue and so, improving it for everyone.

Have a nice day too.
