### ISSUE TITLE
Awning : open/close reversed

### ISSUE THREAD

**Issue by hoefs** [dubocr/homebridge-tahoma#259]
> Thank you for your feedback. I just deploy a new version, it should fix both issues. Can you check and confirm me.
> 
> Thanks

Yes!!! Seems to be fixed now! Thanks for your effort!!!!! Much appreciated

_Originally posted by @hoefs in https://github.com/dubocr/homebridge-tahoma/issues/234#issuecomment-770353151_

After updating to homebridge-tahoma v2.1.3 my awning shows correct status (closed = closed and open=open). However when requesting to close it opens, and when request to open, it closes. 
This was not the case with the latest 0.x version.

**Comment by dubocr** [comment]
Hi,

Effectively in case of stateless awning there were a mistake. If you are in this case (stateless Anwing), latest release 2.1.4 should solve. If not, please follow previous comment procedure to let me investigate.

Thanks.

**Comment by hoefs** [comment]
> Hi,
> 
> Effectively in case of stateless awning there were a mistake. If you are in this case (stateless Anwing), latest release 2.1.4 should solve. If not, please follow previous comment procedure to let me investigate.
> 
> Thanks.

Hi Romain,
My info: SETUP-0803-2123-6951

You had fixed this type of awning with the last plug-in on 0.x. 
Will test tomorrow with the 2.1.4.

**Comment by dubocr** [comment]
Update from @hoefs :

1) 
- Connexoon app works correct = opening is opening / closing is closing
- Homekit shows the correct open/close status. But the movement closing/opening is reversed.
As you can see in point 3 - I have to request 10% closed to get 10% open, but the end state after the request changes to 10% open.
2) done
3) 
Awning > PositionableHorizontalAwning
Devices click on a device to display current states
Zonnewering

States Zonnewering io://0803-2123-6951/4100875
core:DeploymentState 10
core:DiscreteRSSILevelState (good,low,normal,verylow) normal
core:Memorized1PositionState 66
core:MovingState (false,true)
core:NameState SUNEA io
core:OpenClosedState (closed,open) open
core:PriorityLockTimerState 0
core:RSSILevelState 46
core:SecuredPositionState
core:StatusState (available,unavailable) available
core:TargetClosureState 10
io:PriorityLockLevelState (comfortLevel1,comfortLevel2,comfortLevel3,comfortLevel4,environmentProtection,humanProtection,userLevel1,userLevel2)
io:PriorityLockOriginatorState (LSC,SAAC,SFC,UPS,externalGateway,localUser,myself,rain,security,temperature,timer,user,wind)

4) SETUP-0803-2123-6951

**Comment by dubocr** [comment]
@hoefs as I now understend you don't have stateless awning can you :
Send an "open" command from Connexxoon, then give me from https://dev.duboc.pro/tahoma :
- Latest command (in History) (eg: Zonnewering - setDeployment[0] - COMPLETED)
- core:DeploymentState at the end of movement
- core:TargetClosureState at the end of movement

Do the same for "close".

Thanks

**Comment by hoefs** [comment]
> @hoefs as I now understend you don't have stateless awning can you :
> Send an "open" command from Connexxoon, then give me from https://dev.duboc.pro/tahoma :
> 
> * Latest command (in History) (eg: Zonnewering - setDeployment[0] - COMPLETED)
> * core:DeploymentState at the end of movement
> * core:TargetClosureState at the end of movement
> 
> Do the same for "close".
> 
> Thanks

State was closed in homekit. Tapped it to open, only get spinner in the homekit screen. Nothing happens...

![IMG_1114](https://user-images.githubusercontent.com/7440522/112150636-98f41400-8be0-11eb-847b-1cdbce88b557.PNG)

This is homebridge:
```
[3/23/2021, 1:58:49 PM] [Connexoon] [Zonnewering] setClosure[100]
[3/23/2021, 1:58:49 PM] [Connexoon] undefined
[3/23/2021, 1:58:49 PM] [Connexoon] undefined
[3/23/2021, 1:58:49 PM] [Connexoon] [Zonnewering] setClosure Error undefined undefined (undefined)
[3/23/2021, 2:00:53 PM] [Connexoon] Event Polling - Error with listener 5dc1234a-ac10-3e01-0169-e7622ac63de6
[3/23/2021, 2:00:53 PM] [Connexoon] Error undefined undefined (undefined)
```

Your server gives a ERROR 500

**Comment by hoefs** [comment]
> @hoefs as I now understend you don't have stateless awning can you :
> Send an "open" command from Connexxoon, then give me from https://dev.duboc.pro/tahoma :
> 
> * Latest command (in History) (eg: Zonnewering - setDeployment[0] - COMPLETED)
> * core:DeploymentState at the end of movement
> * core:TargetClosureState at the end of movement
> 
> Do the same for "close".
> 
> Thanks

seems 2.1.6 fixed it... have you changed something?

**Comment by dubocr** [comment]
v2.1.6 now use "deployment", could you try to update then tell me what's ok or not.
Can you also said me what is "Open at 10%" with a screenshot of the homekit widget.

_Your server gives a ERROR 500_ : do you mean my server https://dev.duboc.pro/tahoma ?  How ?

**Comment by hoefs** [comment]
> v2.1.6 now use "deployment", could you try to update then tell me what's ok or not.
> Can you also said me what is "Open at 10%" with a screenshot of the homekit widget.
> 
> _Your server gives a ERROR 500_ : do you mean my server https://dev.duboc.pro/tahoma ? How ?

Your server seemed to be unreachable for some time, but is works now.

I requested in homekit to open 15% = correct:
`[3/23/2021, 3:07:10 PM] [Connexoon] [Zonnewering] setDeployment[15]`
```
Zonnewering - setDeployment - HomeKit (23/03/2021 15:07:10) COMPLETED
Zonnewering - setDeployment[15] - COMPLETED
```
```
States Zonnewering io://0803-2123-6951/4100875
core:DeploymentState 15
core:TargetClosureState 15

```

I just push it again in homekit (to close) = correct:
`[3/23/2021, 3:09:39 PM] [Connexoon] [Zonnewering] setDeployment[0]`
```
Zonnewering - setDeployment - HomeKit (23/03/2021 15:09:40) COMPLETED
Zonnewering - setDeployment[0] - COMPLETED
```
```
States Zonnewering io://0803-2123-6951/4100875
core:DeploymentState 0
core:TargetClosureState 0
```

Push it again in homekit (to completely open) - correct:
`[3/23/2021, 3:11:33 PM] [Connexoon] [Zonnewering] setDeployment[100]`
```
Zonnewering - setDeployment - HomeKit (23/03/2021 15:11:34) COMPLETED
Zonnewering - setDeployment[100] - COMPLETED
```
```
States Zonnewering io://0803-2123-6951/4100875
core:DeploymentState 100
core:TargetClosureState 100
```

Seems to be working fine now... Thanks again!!!!

**Comment by dubocr** [comment]
Great,

I hope your device is not "specific". Can you confirm me you have no "reverse": true anymore in your plugin config ?

Will wait for feedback from issue #206 regarding other kind of Awning.

**Comment by hoefs** [comment]
> Great,
> 
> I hope your device is not "specific". Can you confirm me you have no "reverse": true anymore in your plugin config ?
> 
> Will wait for feedback from issue #206 regarding other kind of Awning.

I think 206 was for the same issue. 

I dont have any reverse. Never had:
```
        {
            "name": "Connexoon",
            "service": "connexoon",
            "user": "xxxx@gmail.com",
            "password": "xxxxxxxx",
            "platform": "Tahoma"
        },
```

Seems to be working fine again (as it did before the 2.x.x upgrade)
