### ISSUE TITLE
Can't change the Temperature

### ISSUE THREAD

**Issue by groft389** [dubocr/homebridge-tahoma#26]
Hey,

First thank for this amazing Plugin,
but i can't change the Temeperature of my heater.
Every time i try to change the temperature it jumps back to the temperature before and this error message appears in the console:
```
[2018-4-2 00:32:30] [Tahoma] [Schlafzimmer Schrank] setHeatingTargetTemperature[24]
[2018-4-2 00:32:30] [Tahoma] Error 400 Managed action group is invalid : No such command : setHeatingTargetTemperature on device zwave://1202-5713-2283/19 (zwave:ProgrammableAndProtectableThermostatSetPointZWaveComponent) (UNSPECIFIED_ERROR)
```
And it doesn't show me what stands currently either:
![20180402_003808000_ios](https://user-images.githubusercontent.com/17033125/38179075-1f9514c0-361f-11e8-8d6e-fa001ebda8e8.png)

But if i open the Heater it shows me what it stands currently:
![20180402_003813000_ios](https://user-images.githubusercontent.com/17033125/38179087-318f4e0c-361f-11e8-9906-bc52968a4d74.png)

I don't know if iit's necessary but i use this device:
![20180402_003546804_ios](https://user-images.githubusercontent.com/17033125/38179050-b0105326-361e-11e8-83ea-f29987b41074.jpg)

I hope you can help me :)
(sorry for bad english ^^)

**Comment by groft389** [comment]
Fixed:

I just changed in HeatingSystem.js the Command from setHeatingTargetTemperature to  setTargetTemperature. Now it works :)

**Comment by dubocr** [comment]
Hey,

Nice to see you adapt the script to your device. I'll add your device type to adapt command name in the next release.

Enjoy.
