### ISSUE TITLE
homebridge-tahoma v2.1.5 - Awning > PositionableHorizontalAwning close/open move request reversed 

### ISSUE THREAD

**Issue by hoefs** [dubocr/homebridge-tahoma#260]
> Hi,
> 
> Effectively in case of stateless awning there were a mistake. If you are in this case (stateless Anwing), latest release 2.1.4 should solve. If not, please follow previous comment procedure to let me investigate.
> 
> Thanks.

Hi Romain,
My info: SETUP-0803-2123-6951

You had fixed this type of awning with the last plug-in on 0.x. 
Will test tomorrow with the 2.1.4.

_Originally posted by @hoefs in https://github.com/dubocr/homebridge-tahoma/issues/259#issuecomment-804440471_

Same issue as with 2.1.3 (was working before 2.x.x update). Closing = opening and opening is closing. End state is correct. It shows closed when it is closed and open when it is openend. Only the actual movement is reversed.

**Comment by hoefs** [comment]
1) 
- Connexoon app works correct = opening is opening / closing is closing
- Homekit shows the correct open/close status. But the movement closing/opening is reversed.
As you can see in point 3 - I have to request 10% closed to get 10% open, but the end state after the request changes to 10% open.
2) done
3) 
Awning > PositionableHorizontalAwning
Devices click on a device to display current states
Zonnewering

States Zonnewering io://0803-2123-6951/4100875
core:DeploymentState 10
core:DiscreteRSSILevelState (good,low,normal,verylow) normal
core:Memorized1PositionState 66
core:MovingState (false,true)
core:NameState SUNEA io
core:OpenClosedState (closed,open) open
core:PriorityLockTimerState 0
core:RSSILevelState 46
core:SecuredPositionState
core:StatusState (available,unavailable) available
core:TargetClosureState 10
io:PriorityLockLevelState (comfortLevel1,comfortLevel2,comfortLevel3,comfortLevel4,environmentProtection,humanProtection,userLevel1,userLevel2)
io:PriorityLockOriginatorState (LSC,SAAC,SFC,UPS,externalGateway,localUser,myself,rain,security,temperature,timer,user,wind)

4) SETUP-0803-2123-6951

**Comment by dubocr** [comment]
Hi hoefs,

Can you please keep update in the same topic to avoid duplicate. I move your comment in latest one.

Thanks.
