### ISSUE TITLE
Remove Alarm From Homekit

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#261]
Hi, I've added the name "Alarm" into the Config UI in your plugin for excluded it to appear in Homekit, but it still appears, how should I name it to remove the Alarm ? I have no alarm devices, it just appears as part of the plugin?

**Comment by dubocr** [comment]
Hi,

You should try with 2.1.7, must fix.

Thanks

**Comment by adavison007** [comment]
Perfect, that fixed removing the Alarm, many thanks….

I also managed to use it to remove the bogus Sonos device

Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 23 Mar 2021, at 14:27, Romain DUBOC ***@***.***> wrote:


Hi,

You should try with 2.1.7, must fix.

Thanks
