### ISSUE TITLE
Random Sonos Device appeared with updated plugin

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#262]
I've just updated your plugin and now have a Sonos device added... I have no sonos devices in Somfy?

<img width="499" alt="Screenshot 2021-03-23 at 13 26 41" src="https://user-images.githubusercontent.com/47482260/112153768-8deab500-8bdb-11eb-973d-10325c30c996.png">

**Comment by dubocr** [comment]
May your sonos are automaticaly added in your Tahoma. You can exclude them as you said in other issue.
