### ISSUE TITLE
Home Kit Blind Button Stays on opening or Closing too long for RTS blinds

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#263]
When you open a blind the switch stays on opening or Closing for about 1 minute... is it possible for us to manually change this time, or for you to reduce it?

**Comment by dubocr** [comment]
The switch stay in opening/closing state until end of execution.
Could you please send homebridge logs to check if COMPLETED is to late in your case.

Thanks

**Comment by adavison007** [comment]
For RTS Homekit/Bridge does not know when it has finished as it is a one way command…. so it won;t know when it is open or closed… only IO knows this??

Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 23 Mar 2021, at 21:17, Romain DUBOC ***@***.***> wrote:


The switch stay in opening/closing state until end of execution.
Could you please send homebridge logs to check if COMPLETED is to late in your case.

Thanks

**Comment by dubocr** [comment]
Yes we don’t have « feedback » of the position from the shutter but we have a feedback of the execution state (reported by the bridge). That’s what I want to check.
Normally you will see logs like « ... IN_PROGRESS », « ...COMPLETED ».

**Comment by adavison007** [comment]
Not sure this helps?

[23/03/2021, 22:30:34] [My TaHoma Box] [Bedroom Blind] open[]
INFO: [Device Event]: (Landing Motion) [MOTION] is inactive
INFO: [Device Event]: (Bedroom Motion) [MOTION] is inactive
INFO: [Device Event]: (Bedroom Motion) [MOTION] is active
[23/03/2021, 22:31:07] [My TaHoma Box] [Bedroom Blind] open COMPLETED

**Comment by dubocr** [comment]
Yes, thanks.
Then your widget stay in "opening" state during 33 seconds ? If yes, that's the good behaviour. If it stay to "opening" more than this 33 seconds please follow this procedure :

1. Execute failling operations from official app (TaHoma/Cozytouch/etc.) then execute same operation from Homekit
2. Report your config by browsing [https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma)
3. Search issues with title corresponding to your device widget name (see picture below). If no opened issue, rename your issue with this widget name.
4. Provide your bridge last 4 digits (number visible as SETUP-XXXX-XXXX-XXXX at step 2.)
![Widget](https://dev.duboc.pro/img/widgets.png)

Thank you.
