### ISSUE TITLE
Update to 2.x.x - is there a way back?

### ISSUE THREAD

**Issue by MirkoKas** [dubocr/homebridge-tahoma#264]
I‘m running the plugin for a long time. Since a couple of weeks I‘m having problems with closing some RTS shutters. Seems there could be a fix for this with the new release. 

But as I have quite a few automations configured for the shutters, I‘m afraid of having the shutters removed and re-added after the update to the 2.x.x. 
so, what’s the best way to update the plugin? Or is there a possibility to try the new version and in the case of problems to go back easily to the earlier version without the need to reconfigure every shutter?

**Comment by dubocr** [comment]
Hi @MirkoKas,

If you want to try the plugin but with the ability to rollback to a previous version it must be possible by copying both "accessories" and "persist" folders located in your homebridge directory (/var/lib/homebridge normally).
But if you migrate to 2.x.x be sure I'll do my best to fix major issues in the next days.
For RTS shutter, behavior is the same as previous version except I currently deploy new functionality to manage intermediate position (by setting movementDuration in your config).
