### ISSUE TITLE
time to Close from Open issue

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#266]
So if I set this (RTS blinds) it works for me setting a position of lets say 60% or 70% etc (awesome), but if I do a simple open or close, it does not open or close, it reverts to the last % position set... if I turn the timing off, then open and close works fine.

**Comment by adavison007** [comment]
Please ignore, I found the issue... I have door sensors on my blinds so that when I use a Somfy remote on the blind the position stays in sync with homekit.. :) It is this automation I use that causes the issue... need to re think my automation for partially open blind.

<img width="324" alt="Close Blind" src="https://user-images.githubusercontent.com/47482260/112323010-4a5e7c80-8ca9-11eb-8288-04e4ce06626d.png">
<img width="324" alt="Open Blind" src="https://user-images.githubusercontent.com/47482260/112323025-4cc0d680-8ca9-11eb-8e43-d9128484716c.png">

**Comment by dubocr** [comment]
Great, what is the app you're using to configure automation ?

Thanks

**Comment by adavison007** [comment]
Controller for Homekit, it’s available on MAC and IOS

Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 25 Mar 2021, at 12:01, Romain DUBOC ***@***.***> wrote:


Great, what is the app you're using to configure automation ?

Thanks

**Comment by dubocr** [comment]
> Controller for Homekit, it’s available on MAC and IOS

Thank you 🙏
