### ISSUE TITLE
WaterHeatingSystem > DomesticHotWaterProduction

### ISSUE THREAD

**Issue by Yodacoole** [dubocr/homebridge-tahoma#267]
Bonjour,

Romain, depuis la mise à jour tahoma 2.1.7, le plugins ne se connect plus....

Mon fichier de configuration json n'a pas été modifié.

Dans la configuration homebridge je me suis aperçu que vous avez modifié la structure de configuration.

Que faut il modifier ?

Merci de votre aide,

**Comment by Yodacoole** [comment]
Debug : 

[3/24/2021, 09:47:18] [core:OperatingModeState] [DHWP Actuator] off Error undefined No such command : off on device io://0824-6708-1433/14886293#1 (io:AtlanticDomesticHotWaterProductionV2_CE_FLAT_C2_IOComponent) (UNSUPPORTED_OPERATION)
[3/24/2021, 09:47:18] [homebridge-tahoma] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Error undefined No such command : off on device io://0824-6708-1433/14886293#1 (io:AtlanticDomesticHotWaterProductionV2_CE_FLAT_C2_IOComponent) (UNSUPPORTED_OPERATION). See https://git.io/JtMGR for more info.
[3/24/2021, 09:47:25] [core:OperatingModeState] [DHWP Actuator] heat[]
[3/24/2021, 09:47:25] [core:OperatingModeState] undefined

**Comment by Yodacoole** [comment]
Bonjour,

Suite aux erreurs du plugin, j'ai fait un rollback à la version homebridge-tahoma 0.3.72

La 2.1.7 n'est pas fonctionnelle pour moi.

**Comment by dubocr** [comment]
Bonjour,

J'ai corrigé le problème sur ce modèle de chauffe-eau (v2.1.8) j'aurai cependant besoin d'un référentiel pour aller plus loin.
Pourrez-vous faire les manipulations depuis l'appli cozytouch pour les différentes fonctionnalités puis vous connecter sur https://dev.duboc.pro/tahoma en m'indiquant les différentes opérations réalisée et l'ordre (ex: changement T°, mise en manuel, arrêt...).
En ce qui concerne la configuration si elle ne contenait rien de spécifique sur un device vous n'avez rien à changer.

Merci d'avance.

**Comment by Yodacoole** [comment]
Bonjour Romain,

Je viens de remettre à jour le plugins en 2.1.8 et je n'ai pas d'erreur de communication sauf.

Le comportement est déréglé façon de parlé.

Homekit mode Eteint
![image](https://user-images.githubusercontent.com/70021390/112321243-1a66a780-8cb0-11eb-80d1-86e478352541.png)

Homekit : Mode chauffe = Mode manuel 4 douches
![image](https://user-images.githubusercontent.com/70021390/112321422-44b86500-8cb0-11eb-8c9b-404156cf949f.png)

Homekit : Mode auto = mode auto
![image](https://user-images.githubusercontent.com/70021390/112321826-ad9fdd00-8cb0-11eb-9121-10267ded7420.png)

IOS 2.5 : Mode manuel 4 douche
![image](https://user-images.githubusercontent.com/70021390/112322004-d3c57d00-8cb0-11eb-9ca8-095ba64ac84a.png)

IOS 2.5 : Mode boost 
![image](https://user-images.githubusercontent.com/70021390/112322164-f48dd280-8cb0-11eb-88d2-6ba69d463105.png)

IOS 2.5 ; Mode Auto 
![image](https://user-images.githubusercontent.com/70021390/112322365-1dae6300-8cb1-11eb-81d6-2030f0adcef2.png)

Dans le choix depuis l'interface homekit le mode boost a été retiré de ce que j'avais vu sur la 2.1.7.

J'espère vous avoir aidé.

Cdlt

**Comment by Yodacoole** [comment]
En complément :  

De visu devant le chauffe eau avec l'application homekit 

Etat : 
- Eteint : NOK
- Chauffe : Manuel 4 douches et non le mode Boost
- Refroidir : NOK
- Auto : OK

**Comment by Yodacoole** [comment]
Bonjour Romain,

Pour info, la 2.1.11 n'a pas changé suite au maj de cette version

Le mode éteint est toujours inactif tant dis que les options chauffer et refroidir passe en mode manuel.
Le mode auto passe bien en mode auto.

Je repasse en 0.3.72

Je t'envoie pleins d'encouragements.

Courage,

**Comment by dubocr** [comment]
Merci,

Peux-tu me montrer à quoi ressemble l'interface sur Cozytouch pour piloter le chauffe-eau.
Et également me donner les commandes envoyées par Cozytouch pour :
- l'arrêt
- la fonction que tu attendrais comme action en choisissant "refroidir"

Pour le mode "chauffer" sur homekit, qu'est-ce qui serait le plus logique selon toi ? Le comportement actuel et je rajoute le bouton "boost" ou directement le mode boost ?

**Comment by Yodacoole** [comment]
Bonjour Romain,

![IMG_3879](https://user-images.githubusercontent.com/70021390/112601166-6893bc00-8e12-11eb-8396-9c5eade18188.PNG)
![IMG_3880](https://user-images.githubusercontent.com/70021390/112601174-69c4e900-8e12-11eb-9e9e-74604febe9c1.PNG)
![IMG_3881](https://user-images.githubusercontent.com/70021390/112601175-6a5d7f80-8e12-11eb-90d9-5fd1971cc166.PNG)

Tu as les 3 photos sur le mode de fonctionnement simple de cozitouch.
L'option programmation n'est pas disponible.

Pour les options:
Arrêt : Mode eteint = identique au mode absence
Refroidir : n'a pas de sens théorique pour moi
chauffer : au lieu de mettre le mode manuel 4 douches, j'aurais voulu le mode boost car celui-ci se désactivera automatiquement. (Comme avant avec la version 0.3.72)

Pour le mode chauffer si tu peux identifier le nombre de douche entre 1 a 4 serait un plus.

Par contre effectivement j'avais entre vu le bouton boost sur la 2.1.x, pourquoi pas a réinstaurer si cela ne perturbe pas d'autre matèriels.

J'attends une nouvelle build, je test et je te ferais un retour.

Merci,

**Comment by dubocr** [comment]
Merci,

- Comme il existe bien un mode "Eco" et un mode "Confort", je vais garder chauffer/refroidir pour ces deux modes pour rester cohérent avec ce qui est fait ailleurs (chauffage) et si d'autres modèles de chauffe-eau supporte par exemple une programmation.

- Je remets donc le boost dont la fonction est justement d'activer le boost.

- Je n'avais pas pris le bon paramètre pour la température actuelle de l'eau (demande remontée par @qelanhari et toi en février. Je corrige également.

- Pour le nombre de douche, je vais regarder pour l'ajouter dans un second temps sous forme de caractéristique additionnelle (qui sera visible sur les app comme Eve).

- Pour l'absence, peux-tu l'exécuter pour que je vois le format envoyé par Cozytouch. Le soucis avec l'absence c'est généralement qu'elle est associée à une durée (contrairement à un arrêt). J'espère pouvoir faire "sans limite".

**Comment by qelanhari** [comment]
Voici le miens pour info.
C'est un calypso split 270L.
Le mode éco n'allume jamais la résistance normalement.


![image](https://user-images.githubusercontent.com/4425771/112605813-fe7e1580-8e17-11eb-9f57-48b7d6c31d57.png)

**Comment by Yodacoole** [comment]
Pas de souci,

Pour le nombre de douche en ce qui me concerne n'a pas d'urgence effectivement.

Pour le mode absence, par ex: j'ai donc planifié une absence de chauffe du 27/03 au 04/04 

![image](https://user-images.githubusercontent.com/70021390/112605816-fe7e1580-8e17-11eb-99ae-bab06f0e1a6f.png)

**Comment by Yodacoole** [comment]
> Voici le miens pour info.
> C'est un calypso split 270L.
> Le mode éco n'allume jamais la résistance normalement.
> 
> ![image](https://user-images.githubusercontent.com/4425771/112605813-fe7e1580-8e17-11eb-9f57-48b7d6c31d57.png)

Cela ressemble à un mode autoconsomation, comme le linéo ou tu définis un nombre max de douche
Sur le linéo c'est manuel, de 1 a 4 par ex ou mode auto

**Comment by dubocr** [comment]
Super, on va pouvoir affiner tout ça. J'ai mis en ligne une version 2.1.13 avec le boost, le nombre de douche restantes (en lecture) et un correctif sur le mode absence qui n'apparaissait pas "en arrêt" sur homekit.

**Comment by Yodacoole** [comment]
Je viens de mettre à jour la 2.1.18.

Boost : Activation/Desactivation = OK
Eteint : NOK
Chauffer/refroidir : Active toujour le mode manuel +4 Douches
Auto : Ok

**Comment by Yodacoole** [comment]
Bonsoir Romain,

je viens de mettre à jour la 2.1.18 mais même problème le chauffe eau ne switch pas sur off lorsque je choisis eteint.
C'est bien ok pour moi... dans les logs du homebridge.
[core:OperatingModeState] [DHWP Actuator] setCurrentOperatingMode[{"relaunch":"off","absence":"on"}]

![image](https://user-images.githubusercontent.com/70021390/112733279-32078f80-8f3f-11eb-919f-b852e75c597a.png)

La seule différence pour que le mode off s'active, il faut valider une date du jour par ex. (voire option)

Merci

**Comment by Yodacoole** [comment]
En complément,

Sur homekit lorsque je creer une automatisation, le bouton boost n'existe pas.

**Comment by qelanhari** [comment]
Peut-être demander des vignette séparée pour faire l'automatisation et rejoin après. Sinon via Eve maybe ?

**Comment by dubocr** [comment]
> En complément,
> 
> Sur homekit lorsque je creer une automatisation, le bouton boost n'existe pas.

Il devrait apparaitre à côté du sèche-serviette dans la même pièce. Pour moi avec une automatisation "Un accessoire est sous contrôle" il apparait bien au même titre qu'un accessoire "à part".
J'ai modifié la commande off sur la dernière version 2.1.19. Peux-tu me dire si tu sors d'absence en repassant à AUTO/CHAUFFAGE/RAFRAICHISSEMENT ?

J'en profite pour une petite question, pour vous la fonction HomeKit "AUTO" doit-elle passer en mode Cozytouch "MANU" (et les fonction chauffage/rafraichissement disparaitre), ou cette possibilité d'activer la prog est-elle nécessaire sur Homekit ?

Merci.

**Comment by qelanhari** [comment]
Pour les chauffe eaux ?

**Comment by dubocr** [comment]
Ha oui pardon c'est également le cas sur mon chauffe-eau même si ce n'est pas le même. Si le switch boost apparait sur le widget de contrôle il devrait apparaitre dans les automatisation également.

**Comment by qelanhari** [comment]
Pardon, ma question se référait au sujet des réglages vis à vis du Cozytouch.

**Comment by qelanhari** [comment]
Bon, alors, ici aussi j'vais tenter un lobbying pour que le chauffe eau ne soit pas un Thermostat. Je me suis fait avoir ce matin :
qui a eu la bonne idée de lancer la commande "Dis Siri, éteint tous les chauffages" hier ? 😭. 
Se laver à 20° c'est encore pas la saison.
Bon, c'est contournable par un simple scénario qui exclus le chauffe eau, mais j'vais voir si j'ai mieux à proposer

**Comment by Yodacoole** [comment]
Bonjour,

Test avec la v: 2.1.20 :
Dans automatisation : le mode boost n'est toujours pas présent.

Avec homekit : 
Le mode eteint : ok mais si je choisis d'autre mode il ne revient pas en mode normal (auto/manuel).
Pour interragir, j'utilise donc l'application cozitouch pour définir un mode "je suis absent avec une date de retour" puis de cliquer sur je suis de retour pour annuler le mode absence. (dingue)

![image](https://user-images.githubusercontent.com/70021390/112803296-6d0adf80-9073-11eb-8ceb-517ca63d3e1b.png)

Mode chauffer / refroidir = Mode manuel 4 douches : OK
Mode auto : OK
Mode boost On / Off : OK

Ya que le mode eteint qui est perturbant.

Merci

**Comment by qelanhari** [comment]
Ah oui, voilà, ça explique pourquoi je n'ai pas vu le mode absence sur cozytouch non plus; c'est en allant voir l'écran du chauffe eau que je m'en suis rendu compte.

**Comment by qelanhari** [comment]
```
{
                "name": "core:OperatingModeState",
                "type": 11,
                "value": {
                    "relaunch": "off",
                    "absence": "on"
                }
            },
```

**Comment by qelanhari** [comment]
Et je me rend compte que le plugin utilise : `core:DHWOnOffState` et `io:PassAPCDHWModeState`, hors mon chauffe eau ne dispose pas de ces états.

Voici mon log : 

```
{
        "creationTime": 1561543163000,
        "lastUpdateTime": 1561543163000,
        "label": "IO (7666296#9)",
        "deviceURL": "io://0814-0166-3977/7666296#9",
        "shortcut": false,
        "controllableName": "io:AtlanticPassAPCZoneTemperatureSensor",
        "definition": {
            "commands": [],
            "states": [
                {
                    "type": "DiscreteState",
                    "values": [
                        "available",
                        "unavailable"
                    ],
                    "qualifiedName": "core:StatusState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:TemperatureState"
                }
            ],
            "dataProperties": [],
            "widgetName": "TemperatureSensor",
            "uiProfiles": [
                "Temperature"
            ],
            "uiClass": "TemperatureSensor",
            "qualifiedName": "io:AtlanticPassAPCZoneTemperatureSensor",
            "type": "SENSOR"
        },
        "states": [
            {
                "name": "core:StatusState",
                "type": 3,
                "value": "available"
            },
            {
                "name": "core:TemperatureState",
                "type": 2,
                "value": 23.6
            }
        ],
        "attributes": [
            {
                "name": "core:MeasuredValueType",
                "type": 3,
                "value": "core:TemperatureInCelcius"
            },
            {
                "name": "core:PowerSourceType",
                "type": 3,
                "value": "mainSupply"
            },
            {
                "name": "core:MaxSensedValue",
                "type": 2,
                "value": 30.0
            },
            {
                "name": "core:MinSensedValue",
                "type": 2,
                "value": 5.0
            }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "47fecf16-c2ae-4f7d-be41-83418280cc8d",
        "widget": "TemperatureSensor",
        "type": 2,
        "oid": "c109656d-dd40-4f1b-9bbd-c9e6aec342a3",
        "uiClass": "TemperatureSensor"
    },
    {
        "creationTime": 1609317136000,
        "lastUpdateTime": 1609317136000,
        "label": "DHWP Actuator",
        "deviceURL": "io://0814-0166-3977/9140803#1",
        "shortcut": false,
        "controllableName": "io:AtlanticDomesticHotWaterProductionV2_SPLIT_IOComponent",
        "definition": {
            "commands": [
                {
                    "commandName": "advancedRefresh",
                    "nparams": 1
                },
                {
                    "commandName": "delayedStopIdentify",
                    "nparams": 1
                },
                {
                    "commandName": "getName",
                    "nparams": 0
                },
                {
                    "commandName": "identify",
                    "nparams": 0
                },
                {
                    "commandName": "refreshManufacturerName",
                    "nparams": 0
                },
                {
                    "commandName": "refreshTargetTemperature",
                    "nparams": 0
                },
                {
                    "commandName": "refreshWaterConsumption",
                    "nparams": 0
                },
                {
                    "commandName": "setComfortTargetTemperature",
                    "nparams": 1
                },
                {
                    "commandName": "setDateTime",
                    "nparams": 1
                },
                {
                    "commandName": "setEcoTargetTemperature",
                    "nparams": 1
                },
                {
                    "commandName": "setFrostProtectionTargetTemperature",
                    "nparams": 1
                },
                {
                    "commandName": "setName",
                    "nparams": 1
                },
                {
                    "commandName": "setTargetTemperature",
                    "nparams": 1
                },
                {
                    "commandName": "startIdentify",
                    "nparams": 0
                },
                {
                    "commandName": "stopIdentify",
                    "nparams": 0
                },
                {
                    "commandName": "wink",
                    "nparams": 1
                },
                {
                    "commandName": "pairOneWayController",
                    "nparams": 2
                },
                {
                    "commandName": "refreshAntiLegionellosis",
                    "nparams": 0
                },
                {
                    "commandName": "refreshAwayModeDuration",
                    "nparams": 0
                },
                {
                    "commandName": "refreshBoilerInstallationOption",
                    "nparams": 0
                },
                {
                    "commandName": "refreshBoostModeDuration",
                    "nparams": 0
                },
                {
                    "commandName": "refreshCurrentOperatingMode",
                    "nparams": 0
                },
                {
                    "commandName": "refreshDHWCapacity",
                    "nparams": 0
                },
                {
                    "commandName": "refreshDHWError",
                    "nparams": 0
                },
                {
                    "commandName": "refreshDHWMode",
                    "nparams": 0
                },
                {
                    "commandName": "refreshElectricalExtraManagement",
                    "nparams": 0
                },
                {
                    "commandName": "refreshExtractionOption",
                    "nparams": 0
                },
                {
                    "commandName": "refreshInstallation",
                    "nparams": 0
                },
                {
                    "commandName": "refreshMiddleWaterTemperature",
                    "nparams": 0
                },
                {
                    "commandName": "refreshOperatingModeCapabilities",
                    "nparams": 0
                },
                {
                    "commandName": "refreshOperatingRange",
                    "nparams": 0
                },
                {
                    "commandName": "refreshOperatingTime",
                    "nparams": 0
                },
                {
                    "commandName": "refreshProgrammingSlots",
                    "nparams": 0
                },
                {
                    "commandName": "refreshRateManagement",
                    "nparams": 0
                },
                {
                    "commandName": "refreshSmartGridOption",
                    "nparams": 0
                },
                {
                    "commandName": "setAntiLegionellosis",
                    "nparams": 1
                },
                {
                    "commandName": "setAwayModeDuration",
                    "nparams": 1
                },
                {
                    "commandName": "setBoilerInstallationOption",
                    "nparams": 1
                },
                {
                    "commandName": "setBoostModeDuration",
                    "nparams": 1
                },
                {
                    "commandName": "setCurrentOperatingMode",
                    "nparams": 1
                },
                {
                    "commandName": "setDHWMode",
                    "nparams": 1
                },
                {
                    "commandName": "setElectricalExtraManagement",
                    "nparams": 1
                },
                {
                    "commandName": "setExtractionOption",
                    "nparams": 1
                },
                {
                    "commandName": "setHaltedTargetTemperature",
                    "nparams": 1
                },
                {
                    "commandName": "setInstallation",
                    "nparams": 1
                },
                {
                    "commandName": "setOperatingRange",
                    "nparams": 1
                },
                {
                    "commandName": "setProgrammingSlots",
                    "nparams": 1
                },
                {
                    "commandName": "setRateManagement",
                    "nparams": 1
                },
                {
                    "commandName": "setSmartGridOption",
                    "nparams": 1
                },
                {
                    "commandName": "unpairAllOneWayControllers",
                    "nparams": 0
                },
                {
                    "commandName": "unpairOneWayController",
                    "nparams": 2
                }
            ],
            "states": [
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:BoostModeDurationState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:ComfortTargetTemperatureState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:DHWPSoftwareVersionState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "core:DateTimeState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "good",
                        "low",
                        "normal",
                        "verylow"
                    ],
                    "qualifiedName": "core:DiscreteRSSILevelState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:EcoTargetTemperatureState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:FrostProtectionTargetTemperatureState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:HaltedTargetTemperatureState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "core:ManufacturerNameState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:MaximalShowerManualModeState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:MaximalTemperatureManualModeState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:MinimalShowerManualModeState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:MinimalTemperatureManualModeState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "core:NameState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:NumberOfTankState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "antifreeze",
                        "auto",
                        "away",
                        "eco",
                        "frostprotection",
                        "manual",
                        "max",
                        "normal",
                        "off",
                        "on",
                        "prog",
                        "program",
                        "boost"
                    ],
                    "qualifiedName": "core:OperatingModeState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:PriorityLockTimerState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:RSSILevelState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:SecuredPositionTemperatureState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "available",
                        "unavailable"
                    ],
                    "qualifiedName": "core:StatusState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:TargetTemperatureState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:TemperatureState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:VersionState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "core:WaterConsumptionState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "io:AntiLegionellosisState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "io:AwayModeDurationState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "boilerOptimising",
                        "boilerPriority",
                        "heatPumpOptimising",
                        "heatPumpPriority"
                    ],
                    "qualifiedName": "io:BoilerInstallationOptionState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "io:DHWCapacityState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "io:DHWErrorState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "autoMode",
                        "manualEcoActive",
                        "manualEcoInactive"
                    ],
                    "qualifiedName": "io:DHWModeState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "io:ElectricBoosterOperatingTimeState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "auto",
                        "deactive"
                    ],
                    "qualifiedName": "io:ElectricalExtraManagementState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "fastExtractionSpeed",
                        "lowExtractionSpeed",
                        "noExtraction"
                    ],
                    "qualifiedName": "io:ExtractionOptionState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "io:HeatPumpOperatingTimeState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "extraBoiler",
                        "extraSolar",
                        "onlyThermodynamic"
                    ],
                    "qualifiedName": "io:InstallationState"
                },
                {
                    "type": "ContinuousState",
                    "qualifiedName": "io:MiddleWaterTemperatureState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "io:OperatingModeCapabilitiesState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "pac24h_elec24h",
                        "pacProg_elecProg"
                    ],
                    "qualifiedName": "io:OperatingRangeState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "io:PowerConsumptionFanState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "io:PowerHeatElectricalState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "io:PowerHeatPumpState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "comfortLevel1",
                        "comfortLevel2",
                        "comfortLevel3",
                        "comfortLevel4",
                        "environmentProtection",
                        "humanProtection",
                        "userLevel1",
                        "userLevel2"
                    ],
                    "qualifiedName": "io:PriorityLockLevelState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "LSC",
                        "SAAC",
                        "SFC",
                        "UPS",
                        "externalGateway",
                        "localUser",
                        "myself",
                        "rain",
                        "security",
                        "temperature",
                        "timer",
                        "user",
                        "wind"
                    ],
                    "qualifiedName": "io:PriorityLockOriginatorState"
                },
                {
                    "type": "DataState",
                    "qualifiedName": "io:ProgrammingSlotsState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "forbidden",
                        "no",
                        "recommended",
                        "unsuitable",
                        "wanted"
                    ],
                    "qualifiedName": "io:RateManagementState"
                },
                {
                    "type": "DiscreteState",
                    "values": [
                        "active",
                        "deactive"
                    ],
                    "qualifiedName": "io:SmartGridOptionState"
                }
            ],
            "dataProperties": [
                {
                    "value": "500",
                    "qualifiedName": "core:identifyInterval"
                }
            ],
            "widgetName": "DomesticHotWaterProduction",
            "uiProfiles": [
                "StatefulThermostatWithSensor",
                "StatefulThermostat",
                "Thermostat",
                "WaterConsumption"
            ],
            "uiClass": "WaterHeatingSystem",
            "uiClassifiers": [
                "generator"
            ],
            "qualifiedName": "io:AtlanticDomesticHotWaterProductionV2_SPLIT_IOComponent",
            "type": "ACTUATOR"
        },
        "states": [
            {
                "name": "core:NameState",
                "type": 3,
                "value": "DHWP Actuator"
            },
            {
                "name": "core:VersionState",
                "type": 3,
                "value": "45373232383031202020"
            },
            {
                "name": "core:PriorityLockTimerState",
                "type": 1,
                "value": 0
            },
            {
                "name": "core:StatusState",
                "type": 3,
                "value": "available"
            },
            {
                "name": "core:DiscreteRSSILevelState",
                "type": 3,
                "value": "normal"
            },
            {
                "name": "core:RSSILevelState",
                "type": 2,
                "value": 52.0
            },
            {
                "name": "io:RateManagementState",
                "type": 3,
                "value": "?"
            },
            {
                "name": "io:OperatingModeCapabilitiesState",
                "type": 11,
                "value": {
                    "relaunch": 1,
                    "absence": 1,
                    "rateManagement": 0,
                    "energyDemandStatus": 0
                }
            },
            {
                "name": "core:OperatingModeState",
                "type": 11,
                "value": {
                    "relaunch": "off",
                    "absence": "off"
                }
            },
            {
                "name": "io:DHWErrorState",
                "type": 11,
                "value": {
                    "code": 255,
                    "minor": 255,
                    "family": "W",
                    "type": 0
                }
            },
            {
                "name": "io:HeatPumpOperatingTimeState",
                "type": 1,
                "value": 2883
            },
            {
                "name": "io:ElectricBoosterOperatingTimeState",
                "type": 1,
                "value": 34
            },
            {
                "name": "io:DHWModeState",
                "type": 3,
                "value": "manualEcoActive"
            },
            {
                "name": "core:TemperatureState",
                "type": 2,
                "value": 54.5
            },
            {
                "name": "core:TargetTemperatureState",
                "type": 2,
                "value": 54.5
            },
            {
                "name": "io:ProgrammingSlotsState",
                "type": 11,
                "value": {
                    "slot2": {
                        "start": "12:00",
                        "end": "12:00"
                    },
                    "slot1": {
                        "start": "22:00",
                        "end": "06:00"
                    }
                }
            },
            {
                "name": "io:AntiLegionellosisState",
                "type": 1,
                "value": 1
            },
            {
                "name": "io:ElectricalExtraManagementState",
                "type": 3,
                "value": "deactive"
            },
            {
                "name": "io:MiddleWaterTemperatureState",
                "type": 2,
                "value": 54.1
            },
            {
                "name": "io:PowerHeatElectricalState",
                "type": 1,
                "value": 0
            },
            {
                "name": "io:PowerHeatPumpState",
                "type": 1,
                "value": 9
            },
            {
                "name": "core:DateTimeState",
                "type": 11,
                "value": {
                    "month": 3,
                    "hour": 20,
                    "year": 2021,
                    "weekday": 6,
                    "day": 28,
                    "minute": 26,
                    "second": 54
                }
            },
            {
                "name": "core:BoostModeDurationState",
                "type": 1,
                "value": 0
            },
            {
                "name": "io:AwayModeDurationState",
                "type": 3,
                "value": "0"
            },
            {
                "name": "core:ManufacturerNameState",
                "type": 3,
                "value": "Atlantic"
            },
            {
                "name": "io:DHWCapacityState",
                "type": 1,
                "value": 270
            }
        ],
        "available": true,
        "enabled": true,
        "placeOID": "47fecf16-c2ae-4f7d-be41-83418280cc8d",
        "widget": "DomesticHotWaterProduction",
        "type": 1,
        "oid": "adf7e561-fbd2-4bea-8b13-6f72c0166659",
        "uiClass": "WaterHeatingSystem"
    },
```

**Comment by Yodacoole** [comment]
Le mode eteint s'active correctement, mais pas le rollback.
Je suis obligé d'aller directement sur le chauffe eau pour déverrouiller le mode eteint = vacances. pour le mettre en mode auto.

**Comment by qelanhari** [comment]
> Le mode eteint s'active correctement, mais pas le rollback.
> Je suis obligé d'aller directement sur le chauffe eau pour déverrouiller le mode eteint = vacances. pour le mettre en mode auto.

Doit falloir modifier la commande 
[core:OperatingModeState] [DHWP Actuator] setCurrentOperatingMode[{"relaunch":"off","absence":"on"}]

Pour 

[core:OperatingModeState] [DHWP Actuator] setCurrentOperatingMode[{"relaunch":**"on",**"absence":"on"}]

**Comment by Yodacoole** [comment]
T inquiète, fais comme moi une pause, en plus il fait beau

**Comment by dubocr** [comment]
> Edit : Je dis n'importe quoi pardon, je regarde le code du plugin au milieu du code du boulot, j'ai plus les yeux en face des trous

Ou alors c'est à cause de la douche froide de ce matin... Gloups.
Effectivement les thermostats pour le chauffe eau c'est jolie mais avec Siri ca l'est moins. J'espère quand même qu'Apple va nous sortir des nouveaux accessoires pour ça.

Pour la sortie d'absence la prochaine maj devrait corriger.
Pour le boost je ne comprends pas, il apparait bien chez moi avec ta config :

![45264](https://user-images.githubusercontent.com/5015156/112876643-0b279580-90c6-11eb-855c-6449db3bbb9b.jpeg)

**Comment by Yodacoole** [comment]
Romain,

Pour le boost il apparait bien sur le widget seul mais pas dans automation.

Par contre il y a une option qui s 'intitule affichage en mode séparé sur homekit permettant de dissocier les fonctionnalités.

![IMG_3892](https://user-images.githubusercontent.com/70021390/112889669-3b773000-90d6-11eb-82cf-1969746db93c.jpg)

En cliquant sur l'option tu as afficher les vignettes séparées et la oui je retrouve l'option boost sur automation. (moins pratique).

ex:
![IMG_3891](https://user-images.githubusercontent.com/70021390/112889880-82652580-90d6-11eb-8f40-e6ca642c1536.jpg)

Par contre en vignette unique, l'option boost est présente mais pas en mode automation.

![IMG_3890](https://user-images.githubusercontent.com/70021390/112889922-8d1fba80-90d6-11eb-9f99-5e65c29d09cb.PNG)

Je test la v2.1.22 et je vous redit

**Comment by Yodacoole** [comment]
Bon, je ravis je ne sais pas si @qelanhari a donner de son temps pour la correction  mais merci, car le mode eteint puis switch sur le mode auto/chauffer/refroidir par ex fonctionne correctement.

@dubocr  Y a plus qu'a ajuster la partie selection des douches de 1 a x selon le type de chauffe eau.

Grand merci à vous 2

**Comment by Yodacoole** [comment]
Bonjour Romain,

Oui pour le mode boost il faut afficher les widgets en mode séparer sinon coté automatisation cela n'apparait pas.

Pour le mode manuel sur le choix des douches c'était une suggestion si cela était différent avec d'autres chauffe eau.

**Comment by dubocr** [comment]
Salut @Yodacoole 

> Bonjour Romain,
> 
> Oui pour le mode boost il faut afficher les widgets en mode séparer sinon coté automatisation cela n'apparait pas.

Non non j'ai bien dit en vignet unique comme en vignette séparée. Dans les deux cas le boost s'affiche chez moi (voir copie d'écran je suis en vignette unique)

> 
> Pour le mode manuel sur le choix des douches c'était une suggestion si cela était différent avec d'autres chauffe eau.

OK, voilà ce que ca donne en tout cas sur ta dernière config :

![IMG_36DCA8EBE760-1](https://user-images.githubusercontent.com/5015156/113135705-b77e8e80-9222-11eb-8101-dfeeebc9750b.jpeg)

**Comment by Yodacoole** [comment]
ok bon je viens de retesté en mode widget simple, et effectivement il apparait avec le mode automatisation.

Sur eves également.

Méaculpa..... ;)

Merci

**Comment by dubocr** [comment]
Pas de problème ;-).
J'ai ajouté le changement du nombre de douche dans la version 2.1.27

**Comment by phis5533** [comment]
Bonjour @dubocr ,

bravo et merci pour ton travail, c'est magnifique !

J'ai de mon côté un Lineo dernière version avec le panneau avant comme celui-là : 
<img width="276" alt="panneau" src="https://user-images.githubusercontent.com/37141288/120328533-30fe3000-c2eb-11eb-941c-f70aac6bce42.png">

Il fonctionne très bien avec l'appli Cozytouch, mais ne remonte rien dans HomeKit : 

Application Home :

![Image PNG 2](https://user-images.githubusercontent.com/37141288/120328758-6f93ea80-c2eb-11eb-8469-b07fa2f1e61a.png)

Application Eve : 

![Image PNG](https://user-images.githubusercontent.com/37141288/120328818-7f133380-c2eb-11eb-83d7-e4efa54e0b19.png)

Comment puis-je faire pour avancer ?? 

Quelques idées ? 

Merci
Philippe

**Comment by phis5533** [comment]
Bonjour,

en fait je crois que ça fonctionne, mais je ne connais pas les correspondances des modes.... 😊 

Merci
A+

**Comment by Jeepmg** [comment]
Bonjour,

Je possède aussi un Lineo dernière génération. Je le vois dans Homebridge mais je n'ai pas trouvé comment l'intégrer à l'application Homekit. J'ai tapé le code à 12 digits du setup mais il n'en veut pas.

Merci pour votre aide.

**Comment by Yodacoole** [comment]
Bonjour,

Normalement, il faut ajouter un accessoire depuis le homekit et scanner le QR Code du homebridge ou taper le code d'identification.
Homekit le verra comme un concentrateur de pont complémentaire.

**Comment by Jeepmg** [comment]
Bonjour,

J'ai redémarré mon Iphone et mon Lineo est apparu dans Homekit lié avec le Boost que j'ai séparé.

Nickel
