### ISSUE TITLE
Tahoma plug-in 2.1.7 does not install

### ISSUE THREAD

**Issue by dibimuc** [dubocr/homebridge-tahoma#268]
I installed the latest version of Tahoma plug-in in Hoobs. The installation failed.
Hint: I installed the previous version which occurs a massive error in Hoobs (stalling). I de-installed it but the accessories are still there (plug-in de-installedI). 
I cannot access the log-file (permission denied)

24.3.2021, 09:45:53 npm
24.3.2021, 09:45:53 
24.3.2021, 09:45:53 ERR!
24.3.2021, 09:45:53  code ETARGET
24.3.2021, 09:45:53 npm
24.3.2021, 09:45:53 
24.3.2021, 09:45:53 ERR! notarget No matching version found for homebridge-tahoma@2.1.7.
npm
24.3.2021, 09:45:53  ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
24.3.2021, 09:45:54 
24.3.2021, 09:45:54 npm
24.3.2021, 09:45:54  ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-03-24T08_45_53_260Z-debug.log

**Comment by Yodacoole** [comment]
Hi,

How rollback version

**Comment by dibimuc** [comment]
Not an expert and don’t know how to roll-back. Using the previous version of Tahoma I had to update the node version 14.16.0 because Hoobs service crashed because of Tahoma plug-in.

**Comment by Yodacoole** [comment]
Hi,
How use previous version, because i don't see him.
The last list version is 
https://github.com/dubocr/homebridge-tahoma/releases

Thanks,

**Comment by Yodacoole** [comment]
Hi,

I found,
Since homebridge of dashboard, i schédule backup and restore, and choice yesterday version package tahoma at version 0.3.72.

It's comeback normaly.

it's ok for me
