### ISSUE TITLE
RollerShutter > PositionableRollerShutter

### ISSUE THREAD

**Issue by eledrich** [dubocr/homebridge-tahoma#269]
Bridge last 4 digits : 1557

I'm trying the 'blindMode' option which is a brilliant idea but can't get it to work.

            "devicesConfig": [
                {
                    "key": "BSO Façade",
                    "blindMode": true
                }

I've tried with the device name as well as its serial number - no luck.
Whenever I do change the open / close ratio, things work just as if the option was set to 'false'.
Shall the device be removed and reimported again ?
Is the 'ç' in the device name causing the problem ?
Thanks a lot 

Emmanuel

**Comment by dubocr** [comment]
Bonjour Emmanuel,

Tout à l'air correct effectivement. Par contre ce mode s'applique au BSO (ce qui est ton cas d'après le nom) mais ce qui n'est pas le cas du widget PositionableRollerShutter.
Peux tu m'indiquer les 4 derniers chiffres de ton N° de bridge (et suivre la procédure précédente si ce n'est pas fait), pour que je m'assure que le type de BSO applique bien ce mode.

Merci

**Comment by eledrich** [comment]
Bonjour
Donc les 4 derniers chiffres :  1557
La particularité vient peut être du fait que mes BSO ont des moteurs Somfy Oximo qui sont des moteurs... de volets!
Merci !
![Screenshot 2021-03-25 at 08 50 20](https://user-images.githubusercontent.com/81315776/112437370-2baec300-8d47-11eb-8810-01214da0bb70.png)

**Comment by dubocr** [comment]
Effectivement, et malheureusement ils n'ont pas de commande pour l'orientation des lames.
Comment fais-tu pour orienter les lames avec l'application Tahoma ?

**Comment by eledrich** [comment]
En faisant une combinaison (raccourci Apple qui enchaine des scènes Homekit):
Fermeture à 100% puis attendre 35 secondes puis Fermeture à 98%
Si on pouvait trouver le moyen de scripter ça dans Homebridge ça serait magique!
Merci !
Manu

**Comment by dubocr** [comment]
OK parce que les lames se mettent à l'horizontale lorsque le BSO monte ?

**Comment by eledrich** [comment]
Exactement !

**Comment by dubocr** [comment]
Tu pourras essayer le paramètre `blindsOnRollerShutter` dans la version 2.1.22 (ce soir ou demain).
