### ISSUE TITLE
Somfy Protect Alarm

### ISSUE THREAD

**Issue by RienduPre** [dubocr/homebridge-tahoma#27]
Hi,

I have a Somfy Protect Alarm, which is visible in Tahoma (see picture) , but the plugin does not expose this alarm in homeKit.

I used the config item:
            "Alarm": {
                "STAY_ARM": "A,C",
                "NIGHT_ARM": "B"
           },
But this does not work with the Somfy protect.

Can you please help me get this working ?

<img width="1289" alt="2018-04-30_1240" src="https://user-images.githubusercontent.com/9009949/39423806-f4a36314-4c73-11e8-9e78-43903b9c787b.png">

**Comment by dubocr** [comment]
Hi,

Could you try to log there : [http://home.dubocr.fr/tools/setup](http://home.dubocr.fr/tools/setup) to obtain your configuration.

Thanks

**Comment by RienduPre** [comment]
Do you mean this info ?

<img width="547" alt="2018-05-01_1057" src="https://user-images.githubusercontent.com/9009949/39467454-7882093c-4d2e-11e8-897b-4e59355b66c2.png">

**Comment by dubocr** [comment]
Yes thanks.
Non of your alarm appears in Homekit ? Alarm neither Binnensirene ?
Can you access en send me startup logs of homebridge ?

Thanks

**Comment by dubocr** [comment]
Think your alarm is displayed but just not controllable.
Can you try replace the Alarm.js file from accessories plugin folder by this one an retry : [Alarm.js.zip](https://github.com/dubocr/homebridge-tahoma/files/1964336/Alarm.js.zip)
Alarm configuration isn't necessary as your alarm doesn't support zone configuration.

**Comment by RienduPre** [comment]
Sorry !!

Yes it does work. Thank you

**Comment by MirkoKas** [comment]
Thx for the reply. Do you also have additional components connected to the Somfy One, like an outdoor alarm or so? Do these also work?
