### ISSUE TITLE
HeatingSystem > AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint

### ISSUE THREAD

**Issue by Killator** [dubocr/homebridge-tahoma#270]
Bonjour Romain.

Ca bouge beaucoup par ici... Besoin d'un petit coup de main ?
J'ai quelques régressions depuis le passage en V2... Je me permets de t'en faire une petit liste.

Pour rappel, j'ai 5 radiateurs Atlantics / CozyTouch et j'ai complètement supprimé les anciens devices en cache HomeBridge.

1/ L'ensemble des radiateurs sont tjs vu "Eteins" dans HomeKit, avec la T° consigne dans la tuile (alors qu'ils sont bien en mode PRGM).
2/ L'ouverture de la tuile déclenche instantannément le "setOperatingMode["standby"]", et l'appareil s'éteint vraiment... Ce qui n'arrivait plus depuis lgt.
3/ Le n° de série présent dans les infos de l'appareils est maintenant un UID qui ne permet plus de faire de correspondance avec le retour de l'API... C'est dommage (mais tu sembles avoir complètement changer le mapping des devices).
4/ On ne peut plus faire de détails dans les capteurs (ouverture de fenêtre/présence/wattmetre). Le wattmètre était perfectible mais j'appréciais voir les états des ouvertures fenêtre et présence (même à 10min de refresh prêt). D'ailleurs, je me servais du capteur de présence pour piloter autre chose, et je ne peux plus le faire...
5/ Je ne vois plus le refresh de l'API OverKiz dans les logs Homebridge.

Voilà, c'est du vrac "rapide mais précis" enfin, j'espère ^^

N'hésite pas à me demander des infos/des tests. Je ferais le max pour t'aider.

Cordialement,
Mathieu.

**Comment by dubocr** [comment]
Bonjour Mathieu,

Effectivement pas mal de changement pour assainir au maximum l'implémentation des différents appareils car les spécificités étaient de plus en plus nombreuses et compliquées à gérées. L'objectif de cette version est de pouvoir dissocier au maximum  les types d'appareil.

Pour les chauffages, ca reste effectivement le gros point noir car j'ai bien l'impression qu'aucun chauffage n'est identique alors même que les définitions les sont.
Je vais donc effectivement avoir besoin de vos retours pour implémenter au mieux les commandes.

Pourras-tu te connecter et me transmettre ton N° de bridge comme indiqué ci-dessus et réaliser les commandes possible sur Cozytouch ainsi qu'une capture d'écran de l'écran de contrôle de tes chauffages.

> Bonjour Romain.
> 
> Ca bouge beaucoup par ici... Besoin d'un petit coup de main ?
> J'ai quelques régressions depuis le passage en V2... Je me permets de t'en faire une petit liste.
> 
> Pour rappel, j'ai 5 radiateurs Atlantics / CozyTouch et j'ai complètement supprimé les anciens devices en cache HomeBridge.
> 
> 1/ L'ensemble des radiateurs sont tjs vu "Eteins" dans HomeKit, avec la T° consigne dans la tuile (alors qu'ils sont bien en mode PRGM).
> 2/ L'ouverture de la tuile déclenche instantannément le "setOperatingMode["standby"]", et l'appareil s'éteint vraiment... Ce qui n'arrivait plus depuis lgt.
On va corriger cela avec tes retours

> 3/ Le n° de série présent dans les infos de l'appareils est maintenant un UID qui ne permet plus de faire de correspondance avec le retour de l'API... C'est dommage (mais tu sembles avoir complètement changer le mapping des devices).
Quelle information y avait-il avant ? L'UUID n'est effectivement pas le plus utile pour debbuger je peux changer ça.

> 4/ On ne peut plus faire de détails dans les capteurs (ouverture de fenêtre/présence/wattmetre). Le wattmètre était perfectible mais j'appréciais voir les états des ouvertures fenêtre et présence (même à 10min de refresh prêt). D'ailleurs, je me servais du capteur de présence pour piloter autre chose, et je ne peux plus le faire...
Je ne comprend pas de quoi tu parles par "détails dans les capteurs". Peux-tu me préciser stp ?

> 5/ Je ne vois plus le refresh de l'API OverKiz dans les logs Homebridge.
Je prend note pour le rajouter, tu utilises Homebridge nu ou Hoobs ? Car sur Hoobs les logs debug sont masqués.

> 
> Voilà, c'est du vrac "rapide mais précis" enfin, j'espère ^^
> 
> N'hésite pas à me demander des infos/des tests. Je ferais le max pour t'aider.
> 
> Cordialement,
> Mathieu.

Merci pour tes retours en tout cas.

**Comment by Killator** [comment]
Alors,

J'utilise un HomeBridge dockerisé (https://github.com/oznu/docker-homebridge), sous Raspbian buster, tout est up-to-date, j'ai bien accès à tous les logs avec les autres plugins.

Avant le UUID, il y avait l'identifiant #IO de chaque devices du type:
- 7288378#1 - HeatingSystem (HeaterWithAdjustableTemperatureSetpoint)
- 7288378#2 - TemperatureSensor
- 7288378#3 - ContactSensor
- 7288378#4 - OccupancySensor
- 7288378#5 - ElectricitySensor
 
Ce qui était top pour refaire mapping ou ignorer un device particulier dans le config.json.
`           "exclude": [
                "IO (7288378#5)"
            ]
 `
 
Mon setup >> SETUP-0809-5997-0285
 
J'ai, dans l'ordre:
- ouvert une tuile, ce qui a éteint réellement mon appareil (setOperatingMode["standby"]/COMPLETED)
- Mis en "chauffage" l'appareil ce qui a généré une erreur et remis l'appareil à "Eteint"
`[3/25/2021, 1:52:33 PM] [Cozytouch] [Radiateur] setOperatingMode["normal"]
[3/25/2021, 1:52:33 PM] [Cozytouch] undefined
[3/25/2021, 1:52:33 PM] [Cozytouch] undefined
[3/25/2021, 1:52:33 PM] [Cozytouch] [Radiateur] setOperatingMode Error undefined Managed action group is invalid : IO protocol driver could not convert command setOperatingMode : invalid parameters ? (UNSPECIFIED_ERROR)
[3/25/2021, 1:52:33 PM] [homebridge-tahoma] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Error undefined Managed action group is invalid : IO protocol driver could not convert command setOperatingMode : invalid parameters ? (UNSPECIFIED_ERROR). See https://git.io/JtMGR for more info.
[3/25/2021, 1:52:33 PM] [Cozytouch] [Radiateur] setOperatingMode["standby"]
[3/25/2021, 1:52:36 PM] [Cozytouch] [Radiateur] setOperatingMode COMPLETED`
- Mis en auto (setOperatingMode["auto"]/COMPLETED)
- changer le set point à 16° (setTargetTemperature[19]/COMPLETED)
- mis en climatisation, ce qui a généré une erreur et remis l'appareil à "Auto".
`[3/25/2021, 1:56:44 PM] [Cozytouch] [Radiateur] setOperatingMode["eco"]
[3/25/2021, 1:56:44 PM] [Cozytouch] undefined
[3/25/2021, 1:56:44 PM] [Cozytouch] undefined
[3/25/2021, 1:56:44 PM] [Cozytouch] [Radiateur] setOperatingMode Error undefined Managed action group is invalid : IO protocol driver could not convert command setOperatingMode : invalid parameters ? (UNSPECIFIED_ERROR)
[3/25/2021, 1:56:44 PM] [homebridge-tahoma] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: Error undefined Managed action group is invalid : IO protocol driver could not convert command setOperatingMode : invalid parameters ? (UNSPECIFIED_ERROR). See https://git.io/JtMGR for more info.
[3/25/2021, 1:56:44 PM] [Cozytouch] [Radiateur] setOperatingMode["auto"]
[3/25/2021, 1:56:47 PM] [Cozytouch] [Radiateur] setOperatingMode COMPLETED`
- Eteint l'appareil.

Voilà voilà, j'espère que je n'ai rien oublié...

**Comment by dubocr** [comment]
OK pour les identifiants. Pour info l'UID peut aussi être utilisé pour exclure les devices mais je vais remettre le type de widget.
Pour les commandes, merci mais je souhaitait les commandes avec Cozytouch (depuis l'application Cozytouch). Pour savoir quelles commandes je dois utiliser.

Merci d'avance.

**Comment by dubocr** [comment]
J'ai mis en ligne une version qui devrait apporter quelques amélioration en attendant de pouvoir voir les commandes cozytouch.
Je serai également intéressé par une copie de l'écran de contrôle sur Cozytouch.

Petite question également, utilises-tu la programmation de ton chauffage et HomeKit pour y déroger ou préférerais-tu un mode de fonctionnement simple et manuel sur HomeKit et réaliser les programmation via des automatisations Homekit ?

Merci.

**Comment by Killator** [comment]
Merci Romain, je mets à jour de suite et je teste.

Je n'étais pas trop dispo ce WE, mais je reboucle toutes tes demandes dès demain !

**Comment by Killator** [comment]
Hello,

Quelques tests rapides ce matin avec ta v2.1.20... Je ne vois pas trop ce que tu as changé:
> Les radiateurs sont toujours vu éteins (alors que par défaut les miens sont tous en PRGM)...
> C'est toujours l'UUID présent dans les infos.
> Le mode refroidir/ECO plante toujours.
> Le mode chaufage plante toujours.

Bon, le mode Eteint/StandBy fonctionne toujours, le mode Autom./Auto aussi (même si le radiateur en question ne le prends pas en charge... C'est un peu con mais si l'API ne fait pas le check...).

Dans tous les cas, l'usage que je destine à ton plugin, c'est juste un contrôle rapide de mon installation... Appareil en chauffe ou pas... Les températures consignes... Donc surtout du "display" car l'apps classique mets plusieurs secondes a se charger alors que HomeKit est instantané... Et que je peux demander le status "vocalement" avec SIRI y compris dans ma voiture avec CarPlay. Il y **a mon avis** trop de différence de philosophie entre Cozytouch et Homekit pour mapper correctement toutes les fonctions, surtout si on rentre dans les détails du genre: appareils jumelés dans Cozytouch (2 radiateurs dans la même pièce)... Appareils qui supportent le mode AUTO (avec le capteur de présence) et d'autres non...

J'ajoute 2 captures d'écran de la vision classique de mon installation dans cozytouch & HomeKit. J'enchaine avec un autre post sur les commandes API.
![IMG_3965](https://user-images.githubusercontent.com/31735023/112795928-873fc000-9069-11eb-8870-ebc92d9bf2ea.PNG)
![IMG_3966](https://user-images.githubusercontent.com/31735023/112795940-8b6bdd80-9069-11eb-8acf-03fc0dd1e67c.PNG)

**Comment by Killator** [comment]
Mise à OFF > Atlantic iOS: 2.5 (206) (29/03/2021 08:40:22)
`Radiateur - setOperatingMode["standby"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED
Radiateur - setOperatingMode["standby"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED`

Mise à BASIC > Atlantic iOS: 2.5 (206) (29/03/2021 08:41:48)
`Radiateur - setOperatingMode["basic"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED
Radiateur - setOperatingMode["basic"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED`

Mise à PRGM > Atlantic iOS: 2.5 (206) (29/03/2021 08:42:36)
`Radiateur - setOperatingMode["internal"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED
Radiateur - setOperatingMode["internal"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED`

Mise à AUTO > Atlantic iOS: 2.5 (206) (29/03/2021 08:43:16)
`Radiateur - setOperatingMode["auto"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED
Radiateur - setOperatingMode["auto"] - COMPLETED
Radiateur - refreshDerogatedTargetTemperature[] - COMPLETED`

Il y a toujours 2 commandes qui partent car j'ai fait ça avec la tuile Salon... Où j'ai 2 radiateurs jumelés... Mais c'est les seuls qui supportent le mode AUTO...

**Comment by Killator** [comment]
Pour le fun, voici ce qu'on voit dans Cozytouch quand on met un radiateur en mode AUTO avec ton plugins/API alors qu'il ne le supporte pas (pas de capteur de présence): le "trait souligné" apparait en vrac sur l'écran, alors qu'il devrait être sous OFF / BASIC / PRGM...

![IMG_81B18A7779C0-1](https://user-images.githubusercontent.com/31735023/112797505-c66f1080-906b-11eb-821b-1e1a0e763718.jpeg)

**Comment by dubocr** [comment]
Il doit effectivement y avoir un problème, j'ai supprimé refroidir, changer l'uuid et modifié le mode chauffage.
Je fais une nouvelle mis à jour ce soir tu pourras mettre à jour normalement tu devrais voir au moins quelques changements.
J'ai utilisé `io:NativeFunctionalLevelState` pour savoir si le chauffage supporte le mode auto. Je suis pas sur à 100% mais de mémoire c'est ce qui distingue les gammes.

Question quelle est la différence entre tes tuiles grise et celles en violets dans ta copie d'écran.

Merci.

**Comment by qelanhari** [comment]
Programmé mais en période totalement off je dirais.

**Comment by Killator** [comment]
Le 4 tuiles Cozytouch = 5 tuiles HomeKit car "Salon" représente 2 appareils jumelés (les 2 tuiles "radiateur" à 20°C dans HK).
C'est pour ça qu'une action sur la tuile Cozytouch, provoque 2 appels API automatiquement (1 pour chaque radiateur).

Pour le reste, je confirme qu'il y a de beaux progrès avec ta dernière MàJ ! Merci !
J'ai vidé le cache concernant les radiateurs: l'UUID est bien remplacé par le code IO de l'appareil.
Je vois les appareils allumés (pastille orange) et les appareils éteints (pastille bleu), c'est beaucoup mieux !

![IMG_A050C17DA228-1](https://user-images.githubusercontent.com/31735023/112886431-3adc9a80-90d2-11eb-8b99-69040eb1fbe1.jpeg)

**Comment by Killator** [comment]
Par contre... Il devrait y avoir une différence entre la "bulle" et la légende, non ?
> Dans la bulle la t° mesurée par l'appareil
> Dans la légende la t° consigne (SetPoint)

**Comment by dubocr** [comment]
Exact je n'avais pas vu les capteur de température.
Ce sera bon dans la 2.1.24

**Comment by Killator** [comment]
Bjr Romain !

Alors maintenant j'ai le "setPoint max" (core:ComfortRoomTemperatureState / T° Confort) et le "setPoint min" (io:EffectiveTemperatureSetpointState / T° ECO). C'est pas encore toutafay ça (cf. capture). 

J'ai refais un tour dans l'API, la température est remontée par le "TemperatureSensor" / "core:TemperatureState" (avec 1 décimale).

Dans l'idéal:
> La bulle affiche toujours le "core:TemperatureState".
> La consigne affiche le "io:EffectiveTemperatureSetpointState" quand le radiateur est ECO (la bulle est bleue).
> La consigne affiche le "core:ComfortRoomTemperatureState" quand le radiateur est CONFORT (la bulle est orange).
(consigne = texte en bas de la tuile pour moi).

Je ne sais pas si l'affichage peut être conditionné de la sorte...

![IMG_882C636F443A-1](https://user-images.githubusercontent.com/31735023/112952660-07832580-913d-11eb-80bb-1363eebeae7e.jpeg)

**Comment by Killator** [comment]
Wow... Je viens de passer de la 2.1.24 (ce matin) à la 2.1.26 tout fraiche... Ya du changement mais j'ai un truc bizarre... J'ai à nouveau vidé les caches... Redémarrer complètement mon homebridge sous docker... Je regarde si ça "décante" et te fait un retour demain.

**Comment by Killator** [comment]
SETUP-0809-5997-0285

Bon, j'ai beau rafraichir dans tous les sens, le constat reste... Et c'est assez surprenant:
- Dans l'Apps Cozytouch, toutes mes pièces sont vues à 21 ou 22° """mesuré"" par les radiateurs (super journée ^^)
- Dans l'API, aucune des "core:TemperatureState" ne correspond à ce qui est affiché dans Cozytouch.
- Dans Homebridge Web (Config-UI-X): bien les "core:TemperatureState" avec les décimales x,3°C par exemple.
- Dans Homekit iOS, j'ai les "core:TemperatureState" MAIS avec des arrondis différents (avec des x,5°C)

Après recherche, et comparaison avec ma station Netamo, l'arrondi à x,0° ou x,5° est un nouveau comportement de Homekit... Je n'avais pas ça avant... Merci Apple de prévenir...

Par contre, ça n'explique pas la "core:TemperatureState" dans la bulle complètement différent... Je sèche...
J'ai l'impression que l'Apps Cozytouch y va aussi de son petit arrondi à 1 ou 2° supérieure... Car souvent, le capteur du radiateur situé sous le corps de chauffe, au niveau du sol, enregistre une température inférieure à celle de la pièce...

Du coup... Si on mets de coté les écarts/arrondi de température, on dirait que tout fonctionne bien niveau display !
Y compris la consigne haute ou basse selon le mode Confort ou ECO... J'ai bon ?

![IMG_3980](https://user-images.githubusercontent.com/31735023/113062184-a5193c00-91b3-11eb-99a7-dd49ef7297a7.PNG)
![IMG_3981](https://user-images.githubusercontent.com/31735023/113062211-aea2a400-91b3-11eb-92bc-578f39dd6569.PNG)
<img width="606" alt="Capture d’écran 2021-03-30 à 23 48 23" src="https://user-images.githubusercontent.com/31735023/113062235-b82c0c00-91b3-11eb-88e6-92e4e1f4ad45.png">
<img width="1178" alt="Capture d’écran 2021-03-30 à 23 38 13" src="https://user-images.githubusercontent.com/31735023/113062240-bb26fc80-91b3-11eb-99b3-c25ef30d3cf3.png">

**Comment by Killator** [comment]
Putain le con: c'est bien mentionné (cf. capture ci dessous).

Donc entre la t° mesurée radiateur... La t° affichée Cozytouch... La t° affichée Homekit...
La t° mesurée Netatmo... La t° affiché Netatmo iOS... La t° affichée Netatmo Homekit...

J'ai que des valeurs et des arrondis différents... Vive l'IoT 😅

![IMG_3982](https://user-images.githubusercontent.com/31735023/113064466-54a3dd80-91b7-11eb-8f12-583c0f9f926e.jpg)

**Comment by dubocr** [comment]
Sur Homekit j'avais effectivement constaté cet arrondi à 0,5. C'était peut-être différent avant mais pour moi c'est comme cela depuis un moment quand même.
Sur Cozytouch, sur ma chaudière c'est encore différent. Sur la tuile de l'écran d'accueil, j'ai la T° exact au 10eme près. Si je rentre dans la tuile j'ai "Température relevée" arrondie au degrés près.
Tout est fait pour masque l'imprecision des capteurs on dirait bien :-).

**Comment by Killator** [comment]
Du coup... Pour un usage juste de "Display" dans HomeKit, tout est OK pour moi.

Mais veux-tu qu'on passe du temps sur l'ensemble des fonctions/modes ?
Verifier le mapping des états Cozytouch avec les états Homekit ?
Le mode absence / hors gel / les spécificités de radiateurs appairés ?

Si tu veux t'investir là dessus... Et que tu as du temps devant toi, on peux poursuivre ensemble les ajustements...
De même, as-tu la volonté de remettre à dispo les capteurs de présence... D'ouverture... Le log de "refresh" dans HomeBridge ?

Comment tu vois ça ? ;-)

**Comment by dubocr** [comment]
Bonjour,

Au niveau des commandes tu avais des choses qui n'allaient pas ?
N'hésites pas à les exécuter puis à te connecter à la page pour que je puisse corriger au fur et à mesure.
Les capteurs ont été ajoutés mais ils sont majoritairement "inertes" chez moi. Tiens moi au courant.
Les logs refresh sont en debug pour ne pas polluer inutilement, tu peux activer le debug homebridge ou ajouter la config `"debug": true` au plugin.

**Comment by Killator** [comment]
Salut Romain,

Je te confirme le retour des capteurs d'ouverture et de présence ! Merci bcp. Les premiers sont actifs que très rarement, je te l'accorde (porte/fenetre ouverte un moment avec l'appareil en chauffe). Mais les capteurs de présence fonctionnent bien chez moi (sur un pas de 10min, évidemment).

Pour les commandes/états, en regardant rapidement, j'avais vu des petits soucis... Je peux essayer de qualifier ça du mieux possible mais avant tout: comment tu mappes l'ensemble des mode possibles avec seulement 3 états dans HomeKit ?

**Mode Cozytouch**: antifreeze,auto,away,eco,frostprotection,manual,max,normal,off,on,prog,program,boost
**Mode HomeKit**: Eteint / Chauffer / Auto (ce qui fait parfaitement sens avec un radiateur "classique" dans l'interface Cozytouch Off / BASIC / PRGM)

**Comment by dubocr** [comment]
Jusqu'à présent sur des chauffage électrique le mapping était le suivant :
- AUTO <-> PROG
- Chauffage <-> Manuel (Basic) confort
- Rafraichissement <-> Manuel (Basic) eco
- Arrêt <-> Off

Mais je vais effectivement faire évoluer suite au différents échanges.

Deux alternatives sont en réflexion.

La première :
- AUTO <-> PROG (orange: confort, bleu: eco)
- Chauffage <-> Manuel (Basic)
- Arrêt <-> Off

L'autre alternative, supprimer complement la prog et ne conserver qu'une usage manuel sur le principe qu'HomeKit permet de programmer des automatisations pouvant remplacer la prog.
L'affichage ne montrerait alors qu'un bouton pour allumer/éteindre en plus  du réglage T° :
- Marche <-> Basic
- Arrêt <-> Off

Vos avis sont les bienvenus

**Comment by Killator** [comment]
Alors pour moi, on est déjà sur le mode:
- AUTO <-> PROG (orange: confort, bleu: eco)
- Chauffage <-> Manuel (Basic)
- Arrêt <-> Off

Et ça marche bien pour moi qui utilise ton plugin comme un "display" dans HomeKit de mon installation où tous les radiateurs sont en PRGM...

Changer pour du ON/OFF (mode basic) à du sens mais c'est un changement limite "structurant"... Ciao l'apps Cozytouch, ses limitations et ses bugs (en ce moment, c'est vraiment pas top) et on fait tout avec HomeKit, les scènes et Siri... J'avoue, je me lancerai bien dans l'aventure... Mais attention, ça veut dire que ton plugins (et toute ma chaine Homebridge) devient "vital" pour la gestion de mon installation...

Suggestion: ya p'têt un intérêt de laisser les 2 modes accessibles si une option, histoire que les utilisateurs choisissent...

Bref, si tu es partant, je suis partant ;-)

**Comment by dubocr** [comment]
Oui j'avais commencé un message que je n'ai pas du envoyé :-). J'ai effectivement vu que sur ce type de chauffage on était déjà dans cette configuration.
On est d'accord qu'en supprimant la prod via Cozytouch, l'ensemble du pilotage programmé devient dépendant d'Homebridge. En cas de problème le chauffage pourrait ne pas démarrer à l'heure prévue.

Il me semble aussi que ce mapping des modes est cohérent. Il implique néanmoins de bien gérer la dérogation en fonction des appareils. J'ai d'ailleurs mis en ligne une version dans ce sens (passage en dérogation pour les produits en prog au changement de T°).

Dans tout les cas, la suppression de la prog revient à supprimer le mode "AUTO". Donc on peut avancer indépendant sur les modes "Chauffage" et "AUTO" en fonction des usages de chacun.

Le tiens actuellement étant "AUTO", pourras-tu me faire un retour sur la gestion de la T° sur des chauffages avec mode auto et ceux avec mode prog uniquement.

Merci

**Comment by dubocr** [comment]
Merci, pour le 1er problème cel rejoint effectivement la problématique de @qelanhari. Par contre j'avais testé, Siri remet dans le dernier mode utilisé donc en principe si il était en HEAT (Basic), il devrait se rallumer en HEAT (Basic).
Je m'oriente effectivement sur une option de configuration (ou une caractéristique supplémentaire) pour choisir d'utiliser la prog et n'utiliser que le mode basic par défaut.

Pour le 2nd soucis, tout dépend. Homekit limite à 16°C par défaut mais si tu peux descendre davantage sur Cozytouch avec le réglage de T° on peut mettre cette limite en cohérence. Par contre si ces T° ne sont appliquées qu'en utilisant les modes absence/Hors gel elles ne seront peut-être pas applicables dans une commande T°
