### ISSUE TITLE
HeatingSystem > AtlanticPassAPCZoneControl

### ISSUE THREAD

**Issue by fabien2b** [dubocr/homebridge-tahoma#271]
Depuis la mise à jour 2.0 je rencontre beaucoup de problèmes avec cozytouch et zone contrôle 2 suis je le seul ? Y a t'il une configuration spéciale ?
Merci

**Comment by dubocr** [comment]
Bonjour Fabien,

Je te laisse suivre la procédure précédente pour me permettre de corriger les problèmes rencontrés.

Merci par avance.

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112485452-3edb8600-8d7b-11eb-9b31-5c834638581a.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112485516-531f8300-8d7b-11eb-8411-2a5c13395a52.jpeg)

**Comment by fabien2b** [comment]
Je n'ai plus la température dans le salon

**Comment by fabien2b** [comment]
Et zone contrôle est apparut mais il est non gérer lui a une température je pense que c'est celle du salon

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112486917-9af2da00-8d7c-11eb-83c0-aa5457368580.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487396-f4f39f80-8d7c-11eb-96c2-bf4aa4baf65e.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487450-0046cb00-8d7d-11eb-8da9-32ca60b37367.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487500-0c328d00-8d7d-11eb-8e9d-c12688524a29.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487528-13599b00-8d7d-11eb-8123-743b411a0386.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487551-19e81280-8d7d-11eb-8079-fb0b4918fa3c.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487579-21a7b700-8d7d-11eb-9362-000051835e33.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487620-29675b80-8d7d-11eb-9979-f2e06c59881d.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487651-2ff5d300-8d7d-11eb-82bb-27ad0c7d1536.png)

**Comment by qelanhari** [comment]
@fabien2b Je ne suis pas certain qu'il ai besoin de toutes ces captures

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112487690-371ce100-8d7d-11eb-80a7-95f4d95bfe10.png)

**Comment by qelanhari** [comment]
@dubocr Hello, je t'avais poussé la PR pour le ZoneControl sur la version précédente du plugin. Je peux essayer de jeter un coup d'oeil pour corriger la 2.X. Avant que je me lance, je voulais vérifier que tu n'avais pas de travail en cours sur le sujet ou des consignes/infos pour que je reste cohérent avec ton refactor.
J'avais commencé à faire un composant spécifique pour le ZoneControl, mais ça supprimait complètement le concept d'abstraction.

**Comment by fabien2b** [comment]
J'ai aussi les zones qui démarre en automatique alors que je n'ai rien demandé

**Comment by fabien2b** [comment]
Non aucun travail en cour

**Comment by qelanhari** [comment]
La question était pour l'auteur du plugin ;)

**Comment by fabien2b** [comment]
😅

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112523575-3137f780-8d9f-11eb-91c3-8f2a7d066372.png)

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112523606-39903280-8d9f-11eb-897e-c6d40df96bb1.jpeg)

**Comment by fabien2b** [comment]
Les deux télécommande entoures son enfaite qu'une seul c'est la centrale du coup j'ai la température relevé sur une et je dois me servir de l'autre pour réglé la température voulu

**Comment by dubocr** [comment]
Merci @fabien2b , effectivement toutes les captures n'étaient pas nécessaire mais merci.

@qelanhari, effectivement je suis en train de regarder ce que tu avais fait. Le problème c'est qu'Atlantic utilise les même composant pour le zone control, pour une PAC, etc...
Nous avons remis à plat les commandes avec un autre utilisateur qui avait une PAC, en principe elles doivent être cohérentes aussi sur le ZoneControl.

Je regarde le problème du capteur de T°, au niveau des commandes y à t'il des soucis ?
Si une action ne fonctionne pas ou n'est pas cohérente, il faudrait simplement me dire laquelle et executer la commande attendu avec Cozytouch puis se connecter à nouveau à la page.

Merci

**Comment by fabien2b** [comment]
Ok je te tiens au courant demain

**Comment by qelanhari** [comment]
Pour info sur zonecontrol il n’y a pas de dérogation time ou temperature. Si on est en mode prog, on est régie par un planning qui passe de éco à confort ou off, et la seule commande dispo est off ou déroger de éco à confort ou vice versa, jusqu’à la prochaine consigne planifiée contraire ou jusqu’à ce qu’on l’annule.
Je ne pense pas que ce soit une bonne chose que de manipuler le mode programme via HomeKit, il faut se contenter du mode Manuel et faire son planning via HomeKit. C’est d’autant plus vrai que HomeKit n’a pas ces notions de confort et éco. 
a noter également qu’on ne peux pas à priori savoir si une zone est actuellement active (si elle ne souffle plus parce que la consigne est atteinte), on ne peux que savoir comment elle est réglée a priori.

**Comment by qelanhari** [comment]
Du coup normalement impossible d’avoir une file verte. Je peux te fournir mon json actuel ou toutes mes zones sont allumée mais inactive (merci la journée ensoleillée)

**Comment by qelanhari** [comment]
Faudra que je re essai mais la x.17 me renvoyais Bad credentials sur mon cozytouch et faisait des erreurs sur mon connexoon pour mon portail ou mon garage, je regarde plus en détail demain.

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112609750-338c6700-8e1c-11eb-96ec-5a188697373a.png)

**Comment by fabien2b** [comment]
Au démarrage de maison j'ai des zone qui se mettent en climatisation d'autre en chauffage et d'autre en programmation 😓

**Comment by qelanhari** [comment]
```
[26/03/2021 à 10:44:53] [Cozytouch] Map device Chambre Malo
[26/03/2021 à 10:44:53] [Cozytouch]   HeatingSystem > AtlanticPassAPCHeatingAndCoolingZone
[26/03/2021 à 10:44:53] [Cozytouch] TypeError: _a.onSet is not a function
    at AtlanticPassAPCHeatingAndCoolingZone.registerThermostatService (/usr/local/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem.ts:32:27)
    at AtlanticPassAPCHeatingAndCoolingZone.registerServices (/usr/local/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem/AtlanticPassAPCHeatingAndCoolingZone.ts:7:14)
    at new Mapper (/usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:38:14)
    at new HeatingSystem (/usr/local/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem.ts:6:1)
    at new AtlanticPassAPCHeatingAndCoolingZone (/usr/local/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem/AtlanticPassAPCHeatingAndCoolingZone.ts:5:1)
    at Platform.discoverDevices (/usr/local/lib/node_modules/homebridge-tahoma/src/Platform.ts:125:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[26/03/2021 à 10:44:53] [Cozytouch] Retry in 60 sec...
```

**Comment by dubocr** [comment]
@fabien2b peux tu te reconnecter sur la page pour que je teste ta config avec ces statuts demain matin.
@qelanhari cela ressemble à un problème de version d’homebridge. Essaie de mettre à jour homebridge.

**Comment by fabien2b** [comment]
![image](https://user-images.githubusercontent.com/76244189/112695686-cfea5400-8e84-11eb-9c46-5a3885ad036c.png)

**Comment by qelanhari** [comment]
@dubocr en effet, mon homrbridge de dev n'était pas à jour. J'ai pu init, et tenté de lancer une ou deux commandes. Comme l'indique à priori le code que j'avais lu, on balance des commandes du mode "prog" (eco/confort/derogation).
J'aurai normalement un peu de temps ce soir pour m'y plonger et tenter de te faire une PR.
Par contre, le fonctionnement actuel est clairement "inutile" pour moi. Je chercherai à le faire tourner en mode manuel et non jouer avec le mode eco/confort via les modes chauffage/refroidissement. Je verrais pour peut être proposer un settings qui permet de choisir le comportement attendu.

**Comment by qelanhari** [comment]
Ah, et du coup tu exclu le composant `AtlanticPassAPCZoneControl` pourtant c'est lui qui décide du mode de fonctionnement des zones (chauffage/refroidissement/déshumidification/off total)

**Comment by qelanhari** [comment]
``` 
switch(value) {
            case Characteristics.TargetHeatingCoolingState.AUTO:
                commands.push(new Command('set' + heatingCooling + 'OnOffState', 'on'));
                commands.push(new Command('setPassAPC' + heatingCooling + 'Mode', 'internalScheduling'));
                break;

            case Characteristics.TargetHeatingCoolingState.HEAT:
                commands.push(new Command('setDerogationOnOffState', 'off'));
                commands.push(new Command('set' + heatingCooling + 'OnOffState', 'on'));
                commands.push(new Command('setPassAPC' + heatingCooling + 'Mode', 'comfort'));
                break;

            case Characteristics.TargetHeatingCoolingState.COOL:
                commands.push(new Command('setDerogationOnOffState', 'off'));
                commands.push(new Command('set' + heatingCooling + 'OnOffState', 'on'));
                commands.push(new Command('setPassAPC' + heatingCooling + 'Mode', 'eco'));
                break;

            case Characteristics.TargetHeatingCoolingState.OFF:
                commands.push(new Command('set' + heatingCooling + 'OnOffState', 'off'));
                //commands.push(new Command('setHeatingOnOffState', 'on'));
                //commands.push(new Command('setPassAPCHeatingMode', 'absence'));
                break;
        }
        return commands;
    }
```

Ici en mode prog les commande sont inversée : 
En cas de choix "auto", il faudrait envoyer Derogation Off, et lorsqu'on passe sur eco/confort forcé, c'est derogation on.
Normalement pas besoin d'envoyer la commande eco/confort en parallèle (en tout cas l'app cozytouch ne le fait pas).

**Comment by qelanhari** [comment]
`setDerogatedTargetTemperature`

cette commande n'existe pas sur ZoneControl, en mode prog il faut envoyer des commandes du type : 
`setComfortHeatingTargetTemperature` et ses variantes.

**Comment by qelanhari** [comment]
```
private getHeatingCooling() {
        if(
            this.device.get('io:PassAPCHeatingProfileState') === 'stop' &&
            this.device.get('io:PassAPCCoolingProfileState') !== 'stop'
        ) {
            return 'Cooling';
        } else {
            return 'Heating';
        }
    }
```

Il faut que je vérifie en mode prog, mais en mode manuel ce n'est pas un moyen fiable d'avoir le mode actuel de fonctionnement. En effet, comme dis plus haut, c'est la zone principale qui régie le fonctionnement chaud/froid, et étonnamment `io:PassAPCHeatingProfileState` et `io:PassAPCCoolingProfileState` peuvent être à `on` en même temps... il faut donc lire `io:PassAPCOperatingModeState` sur le composant "parent" qui est le `AtlanticPassAPCZoneControl `.

**Comment by dubocr** [comment]
@fabien2b quelle étaient les configuration des zones lors de la connexion à ma page ? Il semblerait qu'elle ait changé entre temps je n'ai pas la même chose.

@qelanhari oui pour l'instant je masque le module principal, le changement chauffage/rafraichissement n'était pas ma priorité comme il n'intervient que deux fois l'an. Mais je suis dessus.

Au niveau de la dérogation, il s'agit de la derog de T° (lorsqu'on est en mode auto, en changeant de T° cela passe en dérogation en général sur les systèmes Atlantic, ce n'est pas le cas sur le ZC ?.
En mode manuel (eco/comfort), il faut alors quitter une éventuelle dérogation en cours d'où le `off`.
Effectivement le `setDerogatedTemperature` n'existe pas sur vos zones. Par contre chez @fabien2b c'est `setHeatingTargetTemperature` qui est utilisé par Cozytouch à priori.

Au niveau des modes de fonctionnement sur les zones, je ne cherche pas à avoir les modes auto/chauffage/rafraichissement/off (puisque redondant avec le contrôleur principal) mais auto/comfort/eco/off pour conserver la même logique sur tous les chauffages.

En ce qui concerne `io:PassAPCHeatingProfileState`, @fabien2b il est à stop sur presque toutes tes zones du coup je m'interroge sur l'état actuel. Serait-il possible de mettre en mode prog une zone, de changer le consigne, de se connecter a ma page et de faire une capture des states pour cette zone, puis de la mettre en manuel et faire de même et enfin à l'arrêt et faire de même.

Merci d'avance.

**Comment by fabien2b** [comment]
Honnêtement je suis nul je comprends la moitié des choses si tu veux je te donne mes code en privé et je te laisse regarder dis moi juste ce quil te faut si tu veux

**Comment by dubocr** [comment]
Non non c'est très bien ce que tu m'as envoyé c'est juste qu'il y a tellement de paramètres que ca devient difficile d'y voir clair. Je suis même pas sur qu'ils s'en sortent chez Atlantic avec tout ça.

Si ca ne te dérange pas on peut faire ça oui, j'en aurai pas pour long simplement je devrais changer de mode et de T° pour comprendre la logique, je remettrait dans l'état initial au mieux que je peux.

Tu peux m'envoyer ça sur mon mail perso dubocr[arobase]gmail.com

Merci.

**Comment by qelanhari** [comment]
@dubocr 

> lorsqu'on est en mode auto, en changeant de T° cela passe en dérogation en général sur les systèmes Atlantic, ce n'est pas le cas sur le ZC ?.

Non, on ne peux déroger que sur le mode eco/confort. La commande de dérogation de température n'existe pas et renvoie une erreur. On ne peux pas changer la température lorsqu'on est en auto. Si on la change (via `setComfortHeatingTargetTemperature` par exemple, c'est définitif sur la zone pour le mode programmé concerné).
`setHeatingTargetTemperature ` est une commande qui n'est utilisé qu'en mode manuel (que j'avais implémenté sur le plugin, et que probablement tout le monde utilisait avec le Zone Control)

**Comment by qelanhari** [comment]
> Au niveau des modes de fonctionnement sur les zones, je ne cherche pas à avoir les modes auto/chauffage/rafraichissement/off 

Ça tombe bien, c'est pas controllable depuis les zones.
Une zone c'est un capteur de température +
- mode Prog qui permet de choisir eco ou confort ou off. La température est définie dans le planning. On peu déroger au mode actuel via une dérogation de mode, mais pas de température. 
- mode manuel qui permet de choisir la température et on et off et c'est tout.. La commande de température sera a choisir selon le mode actuel de la commande principale.

**Comment by qelanhari** [comment]
> En ce qui concerne io:PassAPCHeatingProfileState, @fabien2b il est à stop sur presque toutes tes zones du coup je m'interroge sur l'état actuel. Serait-il possible de mettre en mode prog une zone, de changer le consigne, de se connecter a ma page et de faire une capture des states pour cette zone, puis de la mettre en manuel et faire de même et enfin à l'arrêt et faire de même.

Cf ce que j'ai dit plus haut, ce ProfileState n'est pas fiable. Je n'ai pas réussi a en percer les mystères. Il faut utiliser l'état de la commande principale.

**Comment by fabien2b** [comment]
Dans la soirée là pas possible

**Comment by dubocr** [comment]
Merci à tout les deux pour votre aide, j'ai déployé une nouvelle version qui devrait correspondre à ce que tu m'indiquait @qelanhari, j'ai repris tes infos, ce que tu avais fait sur la précédente version et j'ai essayé que ca fonctionne également pour les PAC qui utilisent ce même composant.

Pour le ZoneControl ca devrait marcher correctement, je vous laisse me remonter d'éventuels soucis.

Bonne soirée.

**Comment by fabien2b** [comment]
Super je regarde quand je rentre👍🏼merci

**Comment by qelanhari** [comment]
Merci pour ton investissement.
Je pense que tu as fait une typo ici : 
https://github.com/dubocr/homebridge-tahoma/blob/master/src/mappers/HeatingSystem/AtlanticPassAPCZoneControl.ts#L6

Aussi, c'est dommage d'utiliser le service thermostat pour ce composant vu qu'on ne peux pas regler de température. J'avais utilisé le service HeaterCooler qui me semblait plus approprié. Il faut cependant, comme le Thermostat, lui donner une température courante, je m'étais "amusé" à prendre la plus haute/plus basse de toutes les zones selon le mode.

En l'état les modifs que tu as faite permettent de controler mon zone control en manuel. Le seul truc un peu perturbant si je lis bien le code, c'est qu'en allumant la zone je peux choisir "auto" qui enverra le mode "prog", ou "heat" qui allumera selon la saison le mode manuel de chauffe ou de refroidissement.

La classe `AtlanticPassAPCHeatingAndCoolingZone` est utilisée pour d'autres types de PAC que le ZoneControl ?

**Comment by qelanhari** [comment]
Je suis tombé là dessus pour info : 

```
[27/03/2021 à 21:19:10] [homebridge-tahoma] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 27 exceeded maximum of 26. See https://git.io/JtMGR for more info.
[27/03/2021 à 21:19:10] [homebridge-tahoma] Error:
    at TargetTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at TargetTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1950:16)
    at TargetTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at AtlanticPassAPCHeatingAndCoolingZone.onStateChanged (/usr/local/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem/AtlanticPassAPCHeatingAndCoolingZone.ts:77:41)
    at /usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:205:18
    at Array.forEach (<anonymous>)
    at AtlanticPassAPCHeatingAndCoolingZone.onStatesChanged (/usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:203:16)
    at new Mapper (/usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:47:18)
    at new HeatingSystem (/usr/local/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem.ts:6:1)
    at new AtlanticPassAPCHeatingAndCoolingZone (/usr/local/lib/node_modules/homebridge-tahoma/src/mappers/HeatingSystem/AtlanticPassAPCHeatingAndCoolingZone.ts:5:1)
    at Platform.discoverDevices (/usr/local/lib/node_modules/homebridge-tahoma/src/Platform.ts:123:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by dubocr** [comment]
Merci pour l'erreur de typo. Je vais regarder le HeaterCooler, l'avantage du Thermostat c'était la selection AUTO/chauffage/refroidissement/off qui pour le coup correspond exactement à ce qu'il faut. Mais effectivement les infos de T° s'affichent.

Pour les zones, oui c'est l'idée : avoir accès aux mêmes fonctions que l'app Cozytouch (AUTO=PROD / CHAUFFAGE=MANU / OFF=OFF). Je vais regarder pour que le libellé change entre chauffage et refroidissement en fonction du mode actuel du ZC. Ca peut ne pas être très intuitif je l'entends mais c'est le seul moyen d'avoir les fonctions dispos.

J'ai augmenté la limite par défaut de la T° (mais là tu n'es pas très écolo lol :-))

**Comment by qelanhari** [comment]
Justement j'étais écolo, j'étais réglé sur 27 en mode refroidissement, mais homekit me croyais en mode chauffe :p
Du coup, même si c'est hors sujet, j'avais participé à une autre issue concernant l'ouverture piétonne pour le portail. Je viens de voir que c'est devenu méga simple d'ajouter un switch en plus sur le portail. Je te ferai une PR sous peu :)

**Comment by dubocr** [comment]
Ha oui exact :-), elle était pas prête de se mettre en route alors.
Exact je me souviens de cette histoire d'ouverture piétonne, c'est effectivement l'objectif de cette nouvelle version que de pouvoir ajouter ces fonctions en plus.
Avec plaisir pour la PR. Tu as tout ce qu'il faut comme exemple pour voir si la commande existe et ajouter le switch effectivement.

**Comment by fabien2b** [comment]
Après la mise à jour 😅j'ai une erreur![image](https://user-images.githubusercontent.com/76244189/112744052-e84d9200-8f9c-11eb-8513-16dea5e8df5a.png)
Pour tt est bien configuré

**Comment by qelanhari** [comment]
@dubocr Que pense tu de l'idée d'un settings global au niveau du plugin pour choisir si on veux utiliser le mode manuel ou prog pour éviter de mélanger les deux et que les utilisateurs aient à deviner les mappings ? Si ça t'intéresse, j'essai de te faire une proposition de PR à discuter au plus vite.

**Comment by dubocr** [comment]
Le problème de mettre en settings un mode de fonctionnement c’est qu’il n’y aura plus de synchro entre Cozytouch et Homekit.
Si le ZoneControl est en « prog », il n’y aura pas de mode en face sur homekit donc ce sera « auto » ou « off » et du coup pour repasser en manu l’utilisateur devra passer à off puis passer à « auto ».
Et il faudra aussi savoir qu’il y a un setting possible.
Alors que là l’utilisateur va changer les premières fois et rapidement comprendre quoi correspond à quoi non ?

**Comment by dubocr** [comment]
@fabien2b le nom du service est correct dans ta config ? Arrête peut-être 5/10 min (voir plus) homebridge puis relance si c’est un problème d’identifiants incorrects a la base Cozytouch peut t’avoir temporairement bloqué j’ai déjà eu ça sur l’appli après plusieurs échecs d’authentification.

Sinon question, quelle version d’homebridge as tu ? Je vois que chaque accessoire doit être ajouté avec son propre code comme si ils étaient indépendants. Ça attire ma curiosité je n’ai jamais vu ça.

**Comment by qelanhari** [comment]
Je pense que passer de auto à Manuel n'est pas quelque chose qu'on fait tous les jours, généralement jamais, mais je comprend ton point de vue.
Un warning au runtime et une doc claire pourrais suffire à mon sens.
Il faut que les user gardent en tête que les api HomeKit et somfy divergent trop pour être iso. J'avoue que je préfère être carré sur les specs avec des restrictions plutôt que de tout mélanger mais c'est un avis perso et je ne suis pas l'auteur ^^.
Je réfléchi voir si je trouve un meilleur truc.

**Comment by dubocr** [comment]
Je comprends aussi la logique (qui semble être celle qui ressort de ce que tu me dis) de dire « si on utilise HomeKit, c’est pas pour utiliser Cozytouch à côté » donc on rentre dans la logique HomeKit, On/Off et changement de T° et on fait des automatisations pour les programmes.

Un autre utilisateur lui voulait utiliser sa prog et simplement déroger (mais également avec des automatisations donc j’avoue que peut-être le mode manu lui conviendrait quand même).
Je vais interroger les utilisateurs avec ces équipements pour voir ce qui en resort.

Merci en tout cas pour ton point de vu, utilisant Cozytouch + HomeKit j’essayais toujours d’avoir un lien entre les deux et de satisfaire le plus de monde en proposant les modes disponibles sur Cozytouch mais il est vrai que dans les faits je suis en manu depuis le début (même si j’avais prévu de tester la prog + dérogation suite aux échanges avec l’utilisateur en question pour voir l’intérêt)

**Comment by qelanhari** [comment]
Oui, comme tu dis, je part du principe que si Homekit fait le boulot correctement je n'utilise plus Cozytouch. C'était le cas depuis que j'avais refacto le ZoneControl, mais je pensais pas que le widget était utilisé pour d'autres PAC...j'avais du casser des usages.
J'attend ton retour de sondage du coup.

Autre point en la faveur de ne pas mélanger le mode prog et manuel : les commandes Siri. Aujourd'hui j'utilise assez régulièrement les commandes d'allumage ou extinction via Siri. Ça va être bizarre cet été de lui demander de faire chauffer le salon 😂

**Comment by dubocr** [comment]
Je comprend également le point de vue de dire

> Ça va être bizarre cet été de lui demander de faire chauffer le salon 😂

Pas faux :-) 👍

**Comment by fabien2b** [comment]
> > Ça va être bizarre cet été de lui demander de faire chauffer le salon 😂
> 
> 
> 
> Pas faux :-) 👍 
> 
> 
> 
> 

Rien à voir mais depuis l'autre jour impossible de me connecter à mon compte cozytouch en wifi que en 4G c'est pour cela que homebridge se mets en erreur. Une idée cela peu venir du pluging?

**Comment by qelanhari** [comment]
Ton IP est temporairement bannie probablement à cause des essai constant du plugin pour se connecter. Coupe homebridge / le plugin et retente ce soir.

**Comment by fabien2b** [comment]
👍🏼super

**Comment by qelanhari** [comment]
@dubocr aurais-tu le JSON d'un `AtlanticPassAPCHeatPump` pour que je vois les commandes et états dispo, afin de double checker de ne pas casser le comportement que tu as établis sur ma proposition de PR.

**Comment by dubocr** [comment]
Voici.

[ZoneControl.txt](https://github.com/dubocr/homebridge-tahoma/files/6251046/ZoneControl.txt)
