### ISSUE TITLE
Plus possible d'avoir deux instances du plugin

### ISSUE THREAD

**Issue by qelanhari** [dubocr/homebridge-tahoma#273]
J'ai deux bridges IO (merci somfy...), un Cozytouch & un Connexoon. 
Lorsque les deux instance du plugin sont configurées dans une même instance de homebridge, les credentials du second viennent à priori écraser ceux du premier.

**Comment by dubocr** [comment]
Effectivement, j'ai fait une modification sur le client mais pas sur que ca fonctionne totalement. De toute façon Homebridge n'accepte(ra) plus les instance multiple des Platform. Il faut donc que je gère moi-même les bridges multiples.
Je te tiens au courant quand j'ai quelque chose à te faire tester.

**Comment by Killator** [comment]
Hello,

Depuis sa [version 1.3.0](https://github.com/homebridge/homebridge/releases/tag/v1.3.0), Homebridge gère la notion de "Child Bridge".

C'est p'têt une notion à creuser pour faire tourner plusieurs instances d'un même plugin, même si c'est pas noté explicitement comme use-case dans le change log...

**Comment by dubocr** [comment]
Merci @Killator, je confirme que c'est l'option à privilégié.
L'utilisation simultanée de plusieurs bridges étant, de plus, exceptionnel puisqu'un bridge peut supporter tout type d'équipement.
Pour gérer plusieurs bridges et donc plusieurs instances du plugin il faudra le passer en [Child Bridge](https://github.com/homebridge/homebridge/wiki/Child-Bridges).
