### ISSUE TITLE
GarageDoor > UpDownGarageDoor4T

### ISSUE THREAD

**Issue by koupus** [dubocr/homebridge-tahoma#274]
Bonjour Romain,

depuis la MAJ, je n'arrive plus a configurer l'état de ma porte de garage afin d'émuler un cycle.

La différence dans la config porte sur la mention "cycle" devenue "cyclic".

**Avant:**
"GarageDoorOpener": {
                "cycle": true
            },

**Désormais:**
 "devicesConfig": [
                {
                    "key": "GarageDoorOpener",
                    "cyclic": true
                }
            ],

tu peux résoudre cela ? Je n'ose pas le modifier directement dans l'éditeur de config vu la possibilité de réglage dans le plugin.

Je viens de me log sur le dev. Devices SETUP-XXXX-XXXX-0976.

Merci, Thomas

**Comment by dubocr** [comment]
Merci Thomas,

Décidément cette erreur me suivra jusqu'à la fin. J'ai fait une correction dans la version 2.1.16

**Comment by dubocr** [comment]
Ceci dit je suis étonné je viens de voir que j'avais mis en place une détection des porte cycliques. Normalement elle aurait du automatiquement être détectée comme telle et le widget revenir à la position initiale sans même définir la configuration.
Peux-tu me confirmer que le mode fonctionne bien en tout cas.

Merci.

**Comment by Pconde2A** [comment]
Bonsoir,
J’ai le même problème avec un portail coulissant, identifié comme Gâté donc.
Est-ce que le correctif le de la 2.1.16 fonctionnera ?
Merci et bravo pour votre travail.
Pierre

**Comment by dubocr** [comment]
Je l'espère même si techniquement cela devait fonctionner également avant dont il doit y avoir quelque chose qui reste à corriger. Serait-il également possible de te connecter sur https://dev.duboc.pro/tahoma et de me donner les derniers chiffre de ton bridge pour voir la configuration de ton portail (qui dispose peut-être d'ailleurs d'un mode piéton, je pourrais l'implémenter comme ça).

**Comment by Pconde2A** [comment]
C’est fait. Les derniers numéros du bridge sont 0123. Le portail est défini dans Tahoma comme 2 équipements : un pour l’ouverture totale et un pour le mode piéton. J’ai domotisé un portail CAME avec la commande universelle Somfy 1841022. 
Cdt
Pierre

**Comment by koupus** [comment]
> Ceci dit je suis étonné je viens de voir que j'avais mis en place une détection des porte cycliques. Normalement elle aurait du automatiquement être détectée comme telle et le widget revenir à la position initiale sans même définir la configuration.
> Peux-tu me confirmer que le mode fonctionne bien en tout cas.
> 
> Merci.

Bonjour Romain, ma porte n’est de base pas cyclique. Malgré les MAJ, je n’arrive cependant toujours pas a émuler un cycle comme avant.

L’idée est que mon interrupteur porte de garage dans homekit reviennent à l’état off après l’avoir actionné car j’utilise un capteur d’ouverture à côté.

Ce n’est peut-être plus possible avec la nouvelle version ?

**Comment by qelanhari** [comment]
@dubocr 

Peut être que ces lignes devraient être sortie du switch case

```
if(this.cyclic && this.currentState) {
    const current = this.currentState.value;
    setTimeout(() => {
        this.currentState?.updateValue(current);
        this.targetState?.updateValue(current);
    }, this.cycleDuration);
}
```

Aussi, sauf erreur de ma part, tu update avec la même valeur -> `const current = this.currentState.value;` + `this.currentState?.updateValue(current);` et non son opposé

**Comment by dubocr** [comment]
> Aussi et surtout, sauf erreur de ma part, tu update avec la même valeur -> `const current = this.currentState.value;` + `this.currentState?.updateValue(current);` et non son opposé

Ha merci, c'est surtout que j'update avec la valeur que je viens d'update. Ce qui ne sert... à rien ! Pas les yeux en face des trous.

@koupus @Pconde2A cela devrait être mieux dans la prochaine version.

**Comment by Pconde2A** [comment]
Merci pour votre retour. Petite question complémentaire néanmoins en attendant la prochaine version, faut-il utiliser :

"devicesConfig": [
{
"key": "GarageDoorOpener",
"cyclic": true
}
],
comme l'écrit Koupos dans son premier message 

ou 

"devicesConfig": [
{
"key": "GarageDoor",
"cyclic": true
}
],

comme dans le README.md ?

**Comment by Pconde2A** [comment]
Tout fonctionne.

**Comment by dubocr** [comment]
La `key` doit correspondre à l’une des infos suivantes :
- Nom du device
- Widget type
- UiClass type

C’est infos sont visibles au démarrage du plugin 
Configure device [Nom du device]
 UiClass > Widget

GarageDoor fonctionnera donc et s’appliquera à tous les device de type GarageDoor.

GarageDoorOpener était le type Homekit dans la version précédente.

**Comment by koupus** [comment]
Hello Romain, c’est parfait pour moi également. Merci!
