### ISSUE TITLE
Does this plugin already support Tahoma V2?

### ISSUE THREAD

**Issue by PhilippKarstedtHrs** [dubocr/homebridge-tahoma#28]
I upgraded from Tahoma Box V1 to Tahoma Box V2, also selled as Tahoma Premium.
Does this plugin support also this newer Box?

Thanks in advance,
Phill

**Comment by loggoi** [comment]
the Tahoma Box v2 is not sooo new, it has some years by now.

And yes this plugin supports this box.

**Comment by PhilippKarstedtHrs** [comment]
Thanks for you fast response!
Is there anything else to do to get it working again?
Maybe restart the homebridge service again, after shifting to the new TahomaV2? 
Actually it is quite clear to me that homebridge talks anyway over the tahoma account to the specific box, so i also think there should not be a problem in supporting Tahoma V2.

Best,
Phill
