### ISSUE TITLE
Hitachi Temperature Illegal value

### ISSUE THREAD

**Issue by fafoulon** [dubocr/homebridge-tahoma#280]
Hi,
I've got this message with the new versions of homebridge-tahoma. I think it's with decimal.

[homebridge-tahoma] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 231 exceeded maximum of 26. See https://git.io/JtMGR for more info.

**Comment by fafoulon** [comment]
Last 4 digits : 0570
HitachiAirToAirPump

**Comment by dubocr** [comment]
Hi,

I will change something in next release, please update and test. If you always have error, please send logs just before the error.

thanks

**Comment by fafoulon** [comment]
Hi,

It's weird, I have it like this :

[homebridge-tahoma] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 28 exceeded maximum of 26. See https://git.io/JtMGR for more info.

**Comment by dubocr** [comment]
Hi,

Thank you for testing. I increased the default Homekit target T° value to 30°C. It must fix this new warning.

**Comment by fafoulon** [comment]
Thanks!!
