### ISSUE TITLE
Homebridge crashes after plugin update 

### ISSUE THREAD

**Issue by DerDirsch** [dubocr/homebridge-tahoma#283]
After update to v 2.x.x  my whole Homebridge crashed and I had to rebuild the complete Homebridge. 
After having set up the the clean Homebridge installation I did install the latest version of the plugin straight from the beginning and an error occurred. 
thus I had to step back to v 0.3.58. 

Any thoughts on this?

**Comment by qelanhari** [comment]
>an error occurred.

A stacktrace or log from this error would be useful
