### ISSUE TITLE
Buggy plugin. Major incident with 2.1.30 

### ISSUE THREAD

**Issue by dibimuc** [dubocr/homebridge-tahoma#284]
I installed Version 2.1.30 on the latest Hoobs version. The following issue happens which I experienced earlier as well. 

1) Hoobs does not start after installing the version 2.1.30 
2) You have to de-install this plug-in in order to go run Hoobs again. Then the accessories remain visible in Hoobs although the plug-in has been successfully been removed. 

Thank you for taking care and let me know if you need more information.

**Comment by iMicknl** [comment]
>Please fix this issue. You delivered multiple Tahoma updates within the last weeks. That shows me that this plug-in in general is extremely buggy. Do you test you plug-ins?

@dibimuc, do you really think that this is the best way to deliver feedback? I believe that you should be grateful for open source software, especially when it receives many updates like this integration. Updates do not equal buggy releases. Especially if you think about the Somfy ecosystem, there is no way for a developer to own all different devices.

p.s. have a look at the [GitHub Community Guidelines
](https://docs.github.com/en/github/site-policy/github-community-guidelines)

**Comment by dibimuc** [comment]
Okay, you are right and I am sorry about that. I am absolutely grateful for the ecosystem of Homebridge and Hoobs. No doubt. Since I had issues and issues again with this plug-in my feedback was a bit rude. And you are right: Somfy is not the best ecosystem for digitalisation and therefore hard to deliver stable software based on Tahoma. So please sorry and thank you for your open words.

**Comment by qelanhari** [comment]
> Okay, you are right and I am sorry about that. I am absolutely grateful for the ecosystem of Homebridge and Hoobs. No doubt. Since I had issues and issues again with this plug-in my feedback was a bit rude. And you are right: Somfy is not the best ecosystem for digitalisation and therefore hard to deliver stable software based on Tahoma. So please sorry and thank you for your open words.

There is no documentation on the Somfy's API (aka states and commands) for each devices. As @iMicknl said, there is no way for the dev to own each devices. Moreover, even when some devices seems to have similar behavior they do not. @dubocr started to refactor the plugin almost from scratch to have more consistant behavior, cleaner code and this has to come with bugs but this is for the greater good. Proper feedbacks and logs helps improve what has gone under the radar.

You did not provide any logs or stacktrace to help figuring out why your homebridge isn't running, nor what your config is.

**Comment by dubocr** [comment]
Hi @dibimuc,

If I had issue like your **major** one, be certain it'll be solved before publishing
So your issue seems not to be a global one, and your first reflex should be to post your logs as we can't guess what you see

As @iMicknl says, I don't own every 140 kind of devices (only 3 of them !). I know this period could be frustrating and I'll do my best to fix every blocking issue.

For your information, there are many TaHoma updates in the last days mainly for minor fix or new features as I deliver them as soon as possible and because we sometime need many tries as I can't test with real devices.
