### ISSUE TITLE
Impossible to exclude 1 alarm over 2 when using Protexial

### ISSUE THREAD

**Issue by Jeffish25** [dubocr/homebridge-tahoma#285]
Hi,

My Tahoma box is connected to a Protexial Alarm.
Therefore, homebridge-tahoma recognizes 2 Alarm systems: the one from the Tahoma and the Protexial.
For some reason, I would like to keep only the Protexial one, which I simply called "Protexial".
So I did put "Alarm" in the equipment to exclude but then it excludes both alarms. I also tried by mentionning the serial number but it doesn't work.

Any idea ?

Thanks !

**Comment by dubocr** [comment]
Hi @Jeffish25,

You could put the more specific "widget" name of one of the 2 alarms in the exclude list.
Widget name is the name after the ">" in startup log.

Other possibility, more simple but less "reliable" as it's based on device name is to add "Protexial" device name in the exclude list.

**Comment by Jeffish25** [comment]
Hi @dubocr ,

Solution number 1 you suggested is working perfectly, thank you !

And congratulations for the great job !
