### ISSUE TITLE
AtlanticPassAPCHeatPump - Target température 

### ISSUE THREAD

**Issue by Loudu44** [dubocr/homebridge-tahoma#289]
Bonjour,

Suite à la mise à jour du plugin cette semaine, je rencontre un souci dans les logs de Homebridge (Voir ci-dessous)

Extrait logs Homebridge : 
[4/10/2021, 10:17:49 AM] [homebridge-tahoma] This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

Ma config: 
SETUP-xxxx-xxxx-6516

Extrait sur mon iPhone :
![IMG_C00723D77E9C-1](https://user-images.githubusercontent.com/82260426/114263789-dda4eb00-99e7-11eb-897d-7485ba9f0754.jpeg)
![IMG_383D7A28CE0F-1](https://user-images.githubusercontent.com/82260426/114263792-e09fdb80-99e7-11eb-939e-77c874fccc8e.jpeg)

Aussi, est-il possible d'associer HP_Actuator avec Heating système afin d'avoir un bouton poussoir comme WaterHeatingSystem

**Comment by dubocr** [comment]
Bonjour,

Cette erreur ne devrait plus apparaitre sur la prochaine version.
Pour le HP_Actuator, il s'agit de la commande principale pour activer la fonction chauffage/rafraichissement/off qu'un simple interrupteur ne permet pas de gérer. Néanmoins il permet de passer de ON (auto/chauffage/refroidissement) ou OFF (éteint) également. Quel est votre besoin ?
Par ailleurs pour le WaterHeatingSystem il s'agit d'un interrupteur pour le BOOST.

**Comment by Loudu44** [comment]
Merci pour ton retour, c’est noté pour la réponse à la problématique.

Pour le HP_actuator l’idée est d’avoir la même commande que ci dessous 
![0AF1B3CF-539D-4D12-AC36-73FB803681BF](https://user-images.githubusercontent.com/82260426/114314919-f81cb880-9afc-11eb-951f-e7e6278a9e71.jpeg)

**Comment by dubocr** [comment]
Mais la commande ON/OFF en question correspond au boost. Il n'y a pas d'équivalent sur le chauffage.

**Comment by Loudu44** [comment]
Si non, est-il possible d’associer sur le même icône HP_Actuator et Heating système ? L’objectif est de gérer le chauffage/rafraîchissement sur le même icône dans la maison 

Nota : avant cette mise à jour HP_Actuator était  un interrupteur on/off pour le chauffage/rafraîchissement

**Comment by dubocr** [comment]
Vous n'avez qu'une seule zone du coup je comprend le besoin de rassembler les deux accessoires en un seul mais malheureusement il est possible d'avoir plusieurs zones et la gestion du chauffage/rafraichissement ne se fait que sur le composant principal (comme sur Cozytouch, vous avez d'un côté la gestion de la Zone et de l'autre la gestion de la PAC).

Avant l'interrupteur ne permettait que de faire ON/OFF justement et pas chauffage/rafraîchissement/off, c'est donc une évolution qui permet de gérer ces 3 modes au lieu de 2 seulement.

Vous pouvez masquer le composant HP_Actuator dans la config si vous le souhaitez, puisqu'avec une seule zone, la passer à OFF revient à couper la totalité du système.

Si il y a un besoin particulier que je ne vois pas n'hésitez pas à me le dire.

**Comment by Loudu44** [comment]
C’est parfait dans l’explication, je n’avais pas pris en compte le cas avec plusieurs zones.

Merci beaucoup, je reviens vers vous après la prochaine mise à jour.

**Comment by Loudu44** [comment]
Bonsoir,

Ça fonctionne très bien depuis la mise à jour, cependant je n’ai plus la température extérieure.

bonne soirée

**Comment by dubocr** [comment]
Merci pour l'information, ce sera corrigé dans la version 2.1.29.

Bonne soirée.
