### ISSUE TITLE
Tahoma and Protexial alarm

### ISSUE THREAD

**Issue by Jeffish25** [dubocr/homebridge-tahoma#290]
Hello,

Just a small issue, nothing dramatic.

When using Tahoma and a Protexial alarm, it seems not to be possible to link the homebridge alarm modes to other zones.

For example, I would like the Night Zone to be 'A'. I have used this script:
"key": "Alarme",
"nightZones": "A"

But the Night Zone remains 'B'.

Is it possible to do something ?

Thanks,

JF

**Comment by dubocr** [comment]
Bonjour,

Votre config est correcte il y a effectivement une erreur, la prochaine version 2.1.34 devrait corriger le problème.

Merci.

**Comment by Jeffish25** [comment]
Ca fonctionne parfaitement maintenant !

Merci !
