### ISSUE TITLE
Open fails with CMDCANCELLED

### ISSUE THREAD

**Issue by mhalttu** [dubocr/homebridge-tahoma#293]
My version is 2.1.31. Recently my blinds have stopped opening in the morning. This is how the log looks like:

```
17/04/2021, 05:57:18 [My TaHoma Box] [Office] my[]
17/04/2021, 05:57:18 [My TaHoma Box] [Kitchen] my[]
17/04/2021, 05:57:26 [My TaHoma Box] [Office] my CMDCANCELLED
17/04/2021, 05:57:26 [My TaHoma Box] [Kitchen] my CMDCANCELLED
```

One reason I can think of is that the time is very close to the exact hour and the Tahoma service may be flooded with requests. Is there a way I can enable more logging to confirm this theory?

**Comment by dubocr** [comment]
Hi,

Command should be canceled if the is 1 order sent while previous isn't finished. Do you have any log before or after the one you send me ?

**Comment by mhalttu** [comment]
Here are more complete logs from today. I don't think there is anything helpful there. I'm happy to enable extra logging if you can tell me how.

```
[there is nothing logged by Tahoma for hours before this point]
20/04/2021, 20:51:57 [My TaHoma Box] [Bedroom (Right)] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [VR Room 1] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [Stairs (1st Floor)] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [VR Room 2] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [Living Room 1] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [VR Room 3] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [Kitchen] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [Stairs (2nd Floor)] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [Living Room 2] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [Office] close[]
20/04/2021, 20:51:57 [My TaHoma Box] [VR Room 4 (Door)] close[]
20/04/2021, 20:52:05 [My TaHoma Box] [Bedroom (Right)] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [VR Room 1] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [Stairs (1st Floor)] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [VR Room 2] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [Living Room 1] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [VR Room 3] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [Kitchen] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [Stairs (2nd Floor)] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [Living Room 2] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [Office] close CMDCANCELLED
20/04/2021, 20:52:05 [My TaHoma Box] [VR Room 4 (Door)] close CMDCANCELLED
20/04/2021, 20:52:08 [My TaHoma Box] [Bedroom (Left)] close[]
20/04/2021, 20:52:40 [My TaHoma Box] [Bedroom (Left)] close COMPLETED
[there is nothing logged by Tahoma after this point]
```

**Comment by mhalttu** [comment]
Here is another one that happened just now with fewer devices:

```
[nothing Tahoma related before this point]
20/04/2021, 21:36:56 [My TaHoma Box] [Living Room 3] close[]
20/04/2021, 21:36:56 [My TaHoma Box] [Living Room 4 (Door)] close[]
20/04/2021, 21:36:56 [My TaHoma Box] [Living Room 5] close[]
20/04/2021, 21:36:57 [AutomationSwitches] Change target state of Bedroom Left Curtains Open to false
20/04/2021, 21:36:57 [AutomationSwitches] Change target state of Bedroom Left Curtains Open to false
20/04/2021, 21:37:05 [My TaHoma Box] [Living Room 3] close CMDCANCELLED
20/04/2021, 21:37:05 [My TaHoma Box] [Living Room 4 (Door)] close CMDCANCELLED
20/04/2021, 21:37:05 [My TaHoma Box] [Living Room 5] close CMDCANCELLED
[nothing Tahoma after this this point]
```

These problems have started after I upgraded to the 2.x version

**Comment by mhalttu** [comment]
And here is me triggering the scene manually after the previous failure:

```
20/04/2021, 21:49:21 [My TaHoma Box] [Living Room 4 (Door)] close[]
20/04/2021, 21:49:21 [My TaHoma Box] [Living Room 3] close[]
20/04/2021, 21:49:21 [My TaHoma Box] [Living Room 5] close[]
20/04/2021, 21:49:55 [My TaHoma Box] [Living Room 4 (Door)] close COMPLETED
20/04/2021, 21:49:55 [My TaHoma Box] [Living Room 3] close COMPLETED
20/04/2021, 21:49:55 [My TaHoma Box] [Living Room 5] close COMPLETED
```

**Comment by mhalttu** [comment]
It happened again this morning. If it helps, some of the blinds had already started to open when everything was cancelled. The cancellation happened 9 seconds after the open command had been sent this morning.

**Comment by bkehoe00** [comment]
I'm getting the same with a Homekit automation event to open some blinds 30 mins after sunrise. CMDCANCELLED showing shortly after the desired commands have been initiated and a relatively recent occurrence as well - guessing since v2.

**Comment by mhalttu** [comment]
@dubocr I updated to the latest version and can confirm that the problem has not been resolved.

**Comment by mhalttu** [comment]
@dubocr Is there any debug information I could provide to you to get this issue resolved?

**Comment by mhalttu** [comment]
@dubocr Could this be a regression of this issue https://github.com/dubocr/homebridge-tahoma/issues/50? I am sending the command to 13 devices at once.

The weird thing is that everything works if I trigger the scene manually. It's only the automation that is broken.

**Comment by dubocr** [comment]
Hi @mhalttu,

Sorry for this delay. Can you please log at https://dev.duboc.pro/tahoma and give me the last 4 digit of your bridge number (displayed after you login as `SETUP-XXXX-XXXX-1234`.
You can also activate some more debug by setting `"debug": true` in the plugin config.

Thanks

**Comment by mhalttu** [comment]
I've tried enabling `"debug": true` but unfortunately I did not see anything helpful in the logs. The last 4 digits of my bridge number are 6188. Thanks!

**Comment by dubocr** [comment]
I made a special version 2.1.36 with one more log and without a cancel command when there is already a command in progress. Could you please upgrade then tell me if something change.

Otherwise could you please give me your plugin config to check it.

Thanks

**Comment by bkehoe00** [comment]
As I'm having the same issue, if it helps my number is 3617. Upgraded to the new version last night but both my automation events this morning still had CMDCANCELLED. 

I've also just had a look in the Somfy app, and in the History section of the dashboard it has the following message beside the events in which this happens: "Device Name : An error has occurred. Please try again. If the error persists, please contact Customer Support. RTS"

**Comment by mhalttu** [comment]
I installed the new version, and at least today the shades opened as expected. There is some randomness involved, so this might not "prove" anything. I'll monitor the situation over the weekend, and get back to you.

**Comment by mhalttu** [comment]
Another 24 hours and still working! 

I do see these in the logs:
```
07/05/2021, 05:01:19 [My TaHoma Box] [Living Room 5] open[]
07/05/2021, 05:01:22 [My TaHoma Box] [Living Room 5] open NOT_TRANSMITTED
07/05/2021, 05:01:22 [My TaHoma Box] [Living Room 5] open TRANSMITTED
07/05/2021, 05:01:22 [My TaHoma Box] [Living Room 5] open IN_PROGRESS
07/05/2021, 05:01:25 [My TaHoma Box] [Living Room 5] Try to set new position while already executing commands
07/05/2021, 05:01:25 [My TaHoma Box] [Living Room 5] open[]
07/05/2021, 05:01:27 [My TaHoma Box] [Living Room 5] open QUEUED_SERVER_SIDE
07/05/2021, 05:02:07 [My TaHoma Box] [Living Room 5] open COMPLETED
07/05/2021, 05:02:07 [My TaHoma Box] [Living Room 5] open NOT_TRANSMITTED
07/05/2021, 05:02:07 [My TaHoma Box] [Living Room 5] open TRANSMITTED
07/05/2021, 05:02:09 [My TaHoma Box] [Living Room 5] open IN_PROGRESS
07/05/2021, 05:02:55 [My TaHoma Box] [Living Room 5] open COMPLETED
```

**Comment by dubocr** [comment]
Hi,

Yes, this log confirms that in that case the command were canceled before this version.
This command is sent by an automation isn't it ?

Thanks

**Comment by mhalttu** [comment]
Yes, it is an automation based on sunrise.

**Comment by mhalttu** [comment]
The new version seems to be working. From my perspective, this issue can be closed unless you want to dig deeper. Thank you for fixing!

**Comment by bkehoe00** [comment]
Just to provide some further feedback - since the update that came out around 2 weeks ago I haven't seen a single reoccurrence of this problem. Finally my blinds open in the morning again. Thanks very much for fixing. :) 

I do occasionally see the following in the log but it doesn't seem to affect the blinds;
[10/06/2021, 05:41:56] [Tahoma] [Hallway Blind] Try to set new position while already executing commands
