### ISSUE TITLE
Status de l'alarme

### ISSUE THREAD

**Issue by Jeffish25** [dubocr/homebridge-tahoma#294]
Bonjour,

Avec ceci dans mon fichier de configuration: 

"devicesConfig": [
                {
                    "key": "Alarme",
                    "nightZones": "A"
                }
            ],

Lorsqu'avec mon iPhone j'active la zone "Nuit" de mon alarme (donc A), le curseur "saute" sur "Domicile". Si ensuite je reviens sur "Nuit", la mention "Activation" (avec la roue qui tourne) tourne sans fin.

Cordialement,

JF

**Comment by Jeffish25** [comment]
(ça ne le fait pas avec l'UI Homebridge)

**Comment by dubocr** [comment]
Bonjour,

La zone "Domicile" est par défaut la "A". En ne changeant que la zone nuit cela crée un conflit.
Essayez d'ajouter `"stayZones": "B"` si cela ne pose pas de problème par rapport à ce que vous souhaitez configurer.

```
"devicesConfig": [
{
"key": "Alarme",
"nightZones": "A",
"stayZones": "B"
}
],
```

**Comment by Jeffish25** [comment]
Parfait, ça fonctionne, merci
