### ISSUE TITLE
Erreur à l'init

### ISSUE THREAD

**Issue by qelanhari** [dubocr/homebridge-tahoma#295]
[4/22/2021, 2:11:08 PM] [Cozytouch] Create accessory: Zone Control
[4/22/2021, 2:11:09 PM] [Cozytouch] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: c889ed75-648e-499c-bd51-be7f5b32c41d

J'ai pas encore trouvé la raison de ceci. Je suis reparti d'une fresh install, mes accessoires ne se mettaient pas à jour.

**Comment by qelanhari** [comment]
Ça peut être lié à mon bridge de dev, même si le plugin n’est plus dans la configuration ?

**Comment by dubocr** [comment]
Salut,

Si ton bridge de dev est(était) sur le même hombridge, oui c’est fort probable car les identifiants sont désormais liés à ceux du service.
Il faudrait que je recherche mais je crois avoir vu quelque part une option pour supprimer  les accessoires en cache d’un plugin supprimé de la config.
Par contre si le plugin n’est plus dans la config qu’est-ce qui le lance ? Une config avec le plugin sous un autre non ?

Peux-tu regarder à quel accessoire cela correspond dans ton fichier de définition ?

**Comment by qelanhari** [comment]
Je clos, j'ai supprimé mon bridge de dev et autres, à priori j'ai plus l'erreur.
merci pour ton retour ;)
