### ISSUE TITLE
Actualisation dans home

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#296]
Bonjour Romain,
Depuis quelques temps le plugin a du mal à s’actualiser dans home.
Voici mes paramètres : 
```
"pollingPeriod": 30,
"refreshPeriod": 300,
```
Des fois le garage est fermé physiquement et ouvert dans home, alors je le ferme dans home et ça reste sur fermeture.

Pour rappel ce sont des IO

**Comment by dubocr** [comment]
Bonsoir Patrick,

Quand tu observes l’écart comment est l’application TaHoma au même moment ? Ou éventuellement depuis ma page si tu peux t’y connecter quand tu observes l’écart pour voir les états.

**Comment by dubocr** [comment]
Dans ce cas c'est que l'état local de l'équipement n'est pas remonté à TaHoma. Quand tu lances TaHoma cela force un rafraichissement de tout les devices je pense ce qui explique pourquoi l'état se met à jour peu après.
Une fois à jour sur TaHoma me confirmes tu que l'état dans Home devient alors correct ?

Avec ta config, les équipements IO qui remontent spontanément leur état (volets, capteurs par ex) sont pris en compte dans les 30 secondes (`pollingPeriod`) lors d'une action locale (via une télécommande / ne passant pas par TaHoma).
Pour les équipements qui ne remontent pas spontanément leur état (porte de garage et portail par ex), l'info peu ne remonter qu'après 30 min (`refreshPeriod`) si ils sont piloté en local.

Lorsque tu lances l'appli TaHoma, c'est l'équivalent du `refreshPeriod` qui est réalisé.

Pour une action lancée via TaHoma, les états seront quoi qu'il arrive remonté dans les 10 secondes.

Par contre ce qui m'intrique c'est que tu m'indiques "depuis quelques temps" comme si ce n'était pas le cas avant. Hors à ce niveau là rien n'a changé. Peux-tu me préciser ce qui était "mieux avant" ?

**Comment by Tontonpat** [comment]
Bonjour Romain, je te confirme qu’une fois à jour dans tahoma, cela devient à jour dans home. Je penses plus à un problème avec ma porte de garage.
Le « depuis quelques temps » me fait penser depuis la V2 mais je penses que ma porte bug depuis ce même période. 
J’avais déjà changer la carte de cette motorisation il y a 2 ans.
Coïncidence.
Je vais investiguer

**Comment by nscheffer** [comment]
Bonjour Romain,
J'ai aussi une Tahoma v2 avec Homebridge sur un Raspberry avec l'image dédié Homebridge et seulement le plugin Tahoma.
J'ai que du IO comme appareils Somfy (17 volets io, 2 garage io, un portail io et les izymo io), je remarques les points suivants:
- j'utilise beaucoup l'Apple Watch et ensuite l'iPhone pour piloter la maison
- toutes les commandes Somfy via son App iPhone ou Watch sont instantanées et avec un retour immédiat sur le statut 
- quand je commande via la voix (Siri) ou l'app Maison sur l'iPhone le temps de réaction est plus long mais ca marche et par contre l'état n'était pas toujours à jours
- quand je commande via la voix (Siri) ou l'app Maison sur l'Apple Watch le temps de réaction est parfois très long ou même ca ne marche pas et le retour sur le statut aléatoire

Ces derniers les logs du Homebridge sont "tout rouge" avec des erreurs de partout... je redémarre et ca remarche...
Régulièrement, je remets une image plus récente de Homebridge sur mon Raspberry et suivant la motivation je restaure une sauvegarde ou je refais tout à la main pour être sur d'avoir quelque chose de propre.. en moyenne cela une fois tous les 4 mois max !!

Voila pour mon cas. Je suis prêt à aide plus s'il le faut, à ta disposition 
Nicolas

**Comment by dubocr** [comment]
Bonjour à tous les deux,

@Tontonpat : de mon côté ma porte de garage ne remonte pas son statut si piloté avec la télécommande. C'est "normal" et c'est la raison pour laquelle Somfy n'a pas intégré ces portes avec HomeKit natif je pense. C'est le `refreshPeriod` qui permettra de récupérer le statut, malheureusement on ne peu pas le lancer trop souvent car il rafraîchit tout les appareils et donc bonjour le traffic radio dans la maison.

@nscheffer : concernant l'état du portail c'est identique. En ce qui concerne le pilotage via Siri je suis étonné car c'est plutôt dans ce cas de figure que c'est le plus rapide chez moi car sinon via Home il faut d'abord attendre que les widget se mettent à jour avant de les commander.
Pourras-tu m'envoyer les logs que tu observes la prochaine fois que cela ce produit ?

Merci

**Comment by nscheffer** [comment]
Bonjour Romain,
Siri sur l'iPhone marche très bien et tout le temps.
C'est Siri sur l'Apple Watch qui me pose des problèmes, mais je pense avoir identifier en partie le problème qui est que je suis en limite de portée Bluetooth mais sous couverture Wifi (J'ai une borne Pro Outdoor). J'ai remarqué que si je mets l'iPhone en mode Avion c'est pratiquement en permanence nickel !!
J'essaye lors d'une prochaine fois de collecter un maximum d'infos et de logs puis de les poster ici...
Merci du retour.

**Comment by Tontonpat** [comment]
Bonjour Romain, mon refreshperiod est à 300 donc 5 min. Malgré cela, si je ferme mon garage IO par le bouton mural alors qu’il est ouvert dans Home, il ne se rafraichit pas dans Home, même après 5 ou 30 minutes. Sauf si je redémarre homebridge ou que j’ouvre l’appli tahoma. Il y a peut-être un problème avec le refreshperiod?

**Comment by dubocr** [comment]
Bonjour Patrick,

`refreshPeriod` est à renseigner en minutes. Je n'avais pas fait attention dans la config que tu avais envoyé. Si tu le passe à 5 tu devrais voir la valeur se rafraichir plus rapidement. Même si je ne te recommande pas cette valeur sur la durée, seulement pour confirmer le test.

**Comment by Tontonpat** [comment]
Bonjour Romain, ah c’est pour ça! J’étais persuadé que c’était en seconde. Je test et je te dis.
Quelle valeur me conseilles-tu ?

**Comment by dubocr** [comment]
Oui c'est volontaire que l'un soit en secondes et l'autre en minutes car on est sur des type d'actualisation très différentes.
La valeur par défaut est 30 (minutes), tu peux raisonnablement passer à 10 (minutes) en dessous je trouve que c'est beaucoup de traffic radio pour récupérer un potentiel changement d'état.

En gros il faut imaginer que toutes les 10 minutes tout tes équipements IO vont être interrogés pour renvoyer tous leurs états et donc générer un important traffic radio dans la maison mais que dans le lot seuls quelques un (voir aucun) n'aura changé.
