### ISSUE TITLE
SomfyHeatingTemperatureInterface n'apparait pas dans la liste des équipements

### ISSUE THREAD

**Issue by Aeosium** [dubocr/homebridge-tahoma#297]
Hello,

J'ai un soucis avec des thermostats Somfy connectés via TaHoma qui ne veulent pas s'afficher, de la catégorie HeatingSystem > SomfyHeatingTemperatureInterface ([ce modèle](https://www.somfypro.fr/produits/-/e-cat/2401243/THERMOSTAT_PROGRAMMABLE_FILAIRE_-_CONTACT_SEC), modèle comparable à celui rencontré ici je crois https://github.com/dubocr/homebridge-tahoma/issues/12)

Ils s'initialisent dans le log de homebridge et je peux les voir sur https://dev.duboc.pro/ , mais impossible de les trouver ensuite dans la page accessories. Pas de problème avec les autres équipements connectés.

Une idée?

Merci d'avance!

PS: bridge last 4 digits 7451

**Comment by dubocr** [comment]
Bonjour,

J'ai mis en ligne une nouvelle version qui devrait prendre en charge vos équipements. Si vous rencontrez des soucis, pouvez-vous executer les commandes problématique depuis l'application TaHoma officielle puis vous reconnecter à la page https://dev.duboc.pro/tahoma afin que je puisse connaitre les commandes à utiliser.

Merci d'avance.

**Comment by Aeosium** [comment]
Hello,

Je vois bien les thermostats et j'arrive bien à ajuster les paramètres! Il manque juste un swtich pour passer des modes Confort/Eco/Auto/Hors-gel, mais personnellement ce n'est pas un problème (je recherchais surtout à avoir la lecture de température, le reste c'est bonus :) ).

![HB](https://user-images.githubusercontent.com/84744362/119893077-3a7a4780-bf3b-11eb-887d-ca8c72f88643.png)

![Tahoma](https://user-images.githubusercontent.com/84744362/119893180-5aaa0680-bf3b-11eb-86eb-f836ac0baeb2.png)

Merci!

**Comment by Aeosium** [comment]
En regardant le code source je vois qu'il n'est peut être pas évident de rajouter un switch supplémentaire comme je le pensais dans mon précédent commentaire. Si je comprends bien le sélecteur "Chauffer/Refroidir/Auto" est géré par la fonction `getTargetStateCommands`, mais je ne vois pas de fonction dans la classe de base pour sélectionner les modes "Confort/Eco/Auto".

Peut être qu'il est plus adapté d'utiliser `getTargetStateCommands` pour faire passer des `SetPointMode` "Confort/Eco/Auto", à la place des `OperatingMode` Chauffage/Refroidissement, s'il n'y a pas d'autre choix que de choisir l'un ou l'autre?

**Comment by dubocr** [comment]
Bonjour,

Effectivement il n'est pas possible de personnaliser l'interface Home à volonté.
Sur la dernière version, 2 boutons `prog` et `eco` sont disponibles (uniquement via des app tierces comme Eve) pour réaliser ce genre de changements
