### ISSUE TITLE
RTS blinds - "my position" 

### ISSUE THREAD

**Issue by Plexitar** [dubocr/homebridge-tahoma#298]
Hi All! 
at the beginning - great work with the plugin. 

I have a following issue: My setup is 5 somfy internal blinds operate by one pilot somfy rts telis 1 var (you are controlling all 5 blinds at the same time and can also control the blinds angle) and one external anti burglar blind/gate (up and down only). 

With the pilots I could also stop the closing/opening process midway - i miss the functionality in the plugin. If i set the % value in the homekit the following happens:
1. the external blinds goes all the way up/down and do not stop midway
2. internal - 2/5 go full down/up and the rest remains open. 

Any way to have functionality where i could stop the process midway?

Kind regards,
P

**Comment by Plexitar** [comment]
I have logged in to the requested site but do not see any errors. 

The action was logged correctly as "my" but not courtain did not move from the starting position. 
![gateProblem](https://user-images.githubusercontent.com/85678591/121534136-3b15e200-ca01-11eb-8aa5-bc65d8d7d06a.JPG)

the gate and the blinds looks as follows:
![rol](https://user-images.githubusercontent.com/85678591/121534208-4ec14880-ca01-11eb-8a39-88a3822a534a.JPG)
![rol2](https://user-images.githubusercontent.com/85678591/121534217-508b0c00-ca01-11eb-8852-f2a05d10a868.JPG)

I am using the latest version of everything.

**Comment by Plexitar** [comment]
The "stop command - would also solve my problem but unfortunately when I press a button midway it just completes the full cycle and start the next full cycle. 

I have seen this issue but unfortunately is does not work the same for me. 
Here is also my config:
{
            "name": "My TaHoma Box",
            "service": "tahoma",
            "user": "XXXXXX",
            "password": "XXXXXXXXXXXX",
            "platform": "Tahoma"
        }

**Comment by dubocr** [comment]
Hi,

You can try to add this configuration

```
{
	"key": "RollerShutter",
	"movementDuration": "30"
}
```
(Replace 30 by the duration of open to close movement).

This will allow you to set intermediate position other than "My".

Stopping the shutter is not possible as HomeKit has not button like that.
