### ISSUE TITLE
TaHoma Switch

### ISSUE THREAD

**Issue by IngmarStein** [dubocr/homebridge-tahoma#299]
Does this plugin support the new 3rd generation TaHoma Switch box?

**Comment by dubocr** [comment]
Hi,

It would as the backend system is probably the same but I've actually no feedback about user using it.

**Comment by iMicknl** [comment]
@dubocr apparently you will need `https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/` for the TaHoma Switch, since they use a different Overkiz platform.

TaHoma Switch users don't have access to tahomalink.com.

**Comment by IngmarStein** [comment]
I can confirm that TaHoma Switch users don't have access to tahomalink.com and can help test the API.

**Comment by nscheffer** [comment]
Hi Romain,
Just got a new Tahoma Switch and remove the Tahoma Box v2 and bad news for me :
- no more Apple Watch App
- no more Homebridge support with your great plugin
- no more Garage door access from the Apple Watch or SIRI
- no more Gate access from the Apple Watch or SIRI

Let me know how to help you to suppor this new Somfy Switch ?
Somfy concède Ron their Web site the Tahoma Box v2 as obsolete !!!!

**Comment by PatriceRobert** [comment]
> Hi @dubocr ,
> Just got a new Tahoma Switch and remove the Tahoma Box v2 and bad news for me :
> 
> * no more Apple Watch App
> * no more Homebridge support with your great plugin
> * no more Garage door access from the Apple Watch or SIRI
> * no more Gate access from the Apple Watch or SIRI
> 
> Let me know how to help you to support this new Box Somfy Switch ?
> For info, Somfy consider on their Web site the Tahoma Box v2 as obsolete !!!!

I told you Nicolas ;-)

**Comment by dubocr** [comment]
Hi @iMicknl,

Thanks for your help. Hope it will change something because ha101 was the historic Somfy server so the same one used by tahomalink.

@nscheffer, release 2.1.43 add TaHoma Switch service option (`tahoma_switch` is used directly in config file). Keep us informed.

Thanks

**Comment by IngmarStein** [comment]
Wow, thanks. The basic functionality seems to be working. There's one warning in the log for me:
```
[7/10/2021, 8:23:36 PM] [TaHoma] Create accessory: Flur
[7/10/2021, 8:23:36 PM] [TaHoma] Configure device Flur
[7/10/2021, 8:23:36 PM] [TaHoma]   ExteriorVenetianBlind > UpDownExteriorVenetianBlind
[7/10/2021, 8:23:36 PM] [homebridge-tahoma] This plugin generated a warning from the characteristic 'My': Characteristic not in required or optional characteristic section for service WindowCovering. Adding anyway.. See https://git.io/JtMGR for more info.
```

**Comment by dubocr** [comment]
Super, the warning is "normal", it will only appears once when registers "My" characteristic at first startup.

**Comment by nscheffer** [comment]
@dubocr
You rock ! I got all my Somfy devices back with my new Tahoma Switch....

**Comment by dubocr** [comment]
As the server is the same, I change config naming to group all TaHoma services (TaHoma, TaHoma Switch, Conexoon) in the same config name 'tahoma'.
