### ISSUE TITLE
Quiet mode roller shutter within defined time period

### ISSUE THREAD

**Issue by Bartus78** [dubocr/homebridge-tahoma#303]
Dear Dubocr,

Thank you for this feature, it is very helpful. May I ask if it would be possible to define an optional user defined time periode each day where the window covering uses low speed mode and uses normal speed mode during the other times of day. In defining a wake up period, say between 6:30-10:30hrs, the window covering would then go up slow. But when you lower your window covering during the night it would then go down more rapid.

Thanks in advance, best regards,

Benno

__Originally posted by @Bartus78 in https://github.com/dubocr/homebridge-tahoma/issues/173#issuecomment-860866675__

**Comment by dubocr** [comment]
Hi,

An idea I had but never take time to implements it. It's now done ;-). Thank you.
