### ISSUE TITLE
WindowHandle Enocean - no state update > OpenClosedState

### ISSUE THREAD

**Issue by aDabbelju** [dubocr/homebridge-tahoma#304]
I am using iobroker with this plugin and the window handles are not refreshing his status. In the tahoma app is everything fine. 
How i can support to fix this issue with data?

**Comment by aDabbelju** [comment]
1. Windowhandle supports three states (close, tilt, open) and they are visible at the official tahoma app 
2.  done
3. nothing found
4. SETUP-XXXX-XXXX-2011

I´m stll hoping for help.

**Comment by dubocr** [comment]
Hi,

An update was deployed, you can try to update the plugin it must fix your issue.

**Comment by aDabbelju** [comment]
Thanks @dubocr! I updated the plugin and it works.

**Comment by aDabbelju** [comment]
@dubocr There are only two states now (open,close). The state tilt is missing. It‘s possible to add this state for the window Handels? 

0 - closed
1 - opened 
2 - tilted

**Comment by dubocr** [comment]
Unfortunately, HomeKit doesn’t have a `tilt` state for sensors. I mapped tilted to opened.
I can change to closed if better.

**Comment by aDabbelju** [comment]
Sorry for the late answer. I think that this plugin handled the tilt state in the past. 
Maybe it's possible with the following homekit state.

https://developer.apple.com/documentation/homekit/hmcharacteristictypecurrentposition
