### ISSUE TITLE
PergolaHorizontalAwningUno - 1564

### ISSUE THREAD

**Issue by freten** [dubocr/homebridge-tahoma#305]
Forgive me if I didnt get the title quite right.... unsure of the request. Anyway, I have a Pergola, IO-controlled. It is visible in Homekit and responding to commands. Siri works, if I say "close Roof" she closes the roof. So far everything perfect. The problem I am having is that in the Homekit app it says the opposite. I say "Close" to Siri, she closes, and when done Homekit says roof is "Open". Also, when I use Homekit to e.g. set the roof to 75% open, it works, but during the process Homekit turns it around and when done Homekit says 25% open. 

I have tried a lot of combinations with reverse, orientation, false, true etc but cant seem to get Siri and Homekit to "agree". I dont know what I am doing wrong or if there is a fix needed.

Apart from this, thanks for a great plugin!

**Comment by freten** [comment]
PergolaHorizontalAwningUno - 1564

**Comment by dubocr** [comment]
Hi,

Can you confirm me that :
- Asking Siri to any position works as expected
- Setting any position from Home app works as expected
- Only Home widget indicate bad % position after execution ?

So can you try to move your Pergola to intermediate position (except 50%), then connect again to https://dev.duboc.pro/tahoma

Thank you.

**Comment by freten** [comment]
Hi, 

    Asking Siri to any position works as expected        **Yes**
    Setting any position from Home app works as expected   **Yes, but Home app "reverses" my %-setting (25% changes to 75%).**
    Only Home widget indicate bad % position after execution ? **I am not sure what you mean with Home Widget...**

I have re-uploaded my config. 
Note that in Homebridge log it says "SetClosure 21" and "SetClosure completed" it is actually opening the roof. 

Thanks, and Regards,
Fredrik

**Comment by dubocr** [comment]
Hi,

You fully close it after the 21% closure and before uploading your config.
Can you retry to close/open partially, wait end of movement then re-connect but without any other command after.
;
Thanks

**Comment by freten** [comment]
Done. Sorry. Thanks. :)

**Comment by dubocr** [comment]
Thank you,
Did you already try to remove and add again your Pergola from TaHoma ?
Your model has only one state to indicate the target position and it is reversed. I can fix it to `PergolaHorizontalAwningUno` kind of device but I want to be sure this is the case for everyone so make sure your installation is up to date.

Thanks you

**Comment by freten** [comment]
Hi, removed  and re-added the pergola from Thoma app/box and now it is working correct. Thank you, I should have thought of this before. Thanks for your support.

**Comment by dubocr** [comment]
Great,
Can you re upload your config one more time just by curiosity to check the new config ?

Thank you.

**Comment by freten** [comment]
Sure, thanks for your commitment! :) . Done.
