### ISSUE TITLE
Somfy Connectivity Kit

### ISSUE THREAD

**Issue by cjournet** [dubocr/homebridge-tahoma#306]
Hello,

Do you know is the Connectivity Kit is working with your plugin?
This sounds to be the new connexoon, and I may buy it if I can integrate it to Homekit.

you can find it here:
https://boutique.orange.fr/accessoires/kit-de-connectivit-somfy
(only buyable thought Orange and Professional for the moment).

Thanks
Regards

**Comment by dubocr** [comment]
Hi,

I've no feedback about this product but as Somfy manage a common cloud technology for every services it should be. May there will be some investigation to find the good server URL to reach.
So I can't affirm you it will be but normal it will.

**Comment by cjournet** [comment]
Hi,
I have buy the product and pair my shutter with it. Working well. When I add the plugin in home bridge, my login working and it seems to add the shutter and the led of the connectivity box in homebridge. But the shutter are not configure well (see screen  attached)
<img width="668" alt="Capture d’écran 2021-07-12 à 20 40 40" src="https://user-images.githubusercontent.com/16878058/125339307-77ff2c80-e351-11eb-9363-c024e6a61ff7.png">

In the home bridge log:
[7/12/2021, 8:32:41 PM] [TaHoma] Configure device Connectivity kit-ledBox
[7/12/2021, 8:32:41 PM] [TaHoma]   Light > DynamicLight
[7/12/2021, 8:32:41 PM] [TaHoma] Configure device Porte Fenetre Cuisine
[7/12/2021, 8:32:41 PM] [TaHoma]   Shutter > DynamicShutter
[7/12/2021, 8:32:41 PM] [TaHoma] Configure device Verrière Cuisine
[7/12/2021, 8:32:41 PM] [TaHoma]   Shutter > DynamicShutter
[7/12/2021, 8:32:41 PM] [TaHoma] Configure device S&SO-RS100 io
[7/12/2021, 8:32:41 PM] [TaHoma]   Shutter > DynamicShutter

My setup ID: 8891

Thanks
<img width="812" alt="Capture d’écran 2021-07-12 à 20 41 45" src="https://user-images.githubusercontent.com/16878058/125339455-98c78200-e351-11eb-84fd-516094e1edc3.png">

**Comment by cjournet** [comment]
I find a work around for the moment:
- For my IO shutter, I add it directly through HomeKit (native)
- For RTS shutter, I added a scenario and it's working (I don't this the shutter directly but I have a scenario to open, and one to close)

Thanks for your support

**Comment by dubocr** [comment]
Bonjour,

J'ai publié la version 2.1.54 pour gérer les Shutter. A voir comment cela réagit car l'historique fait apparaitre l'utilisation de la commande `setClosure` alors qu'elle n'apparait pas dans la liste des commandes.

Pour information quelle type de service avez vous utilisé pour la connexion ? `tahoma` ?

Merci.

**Comment by cjournet** [comment]
Bonjour,

Alors depuis la mise à jour, cela apparait bien comme des volets dans Homekit. Par contre le retour d'état (sur le IO uniquement les RTS n'en ayant pas) ne fonctionne pas, et les commandes non plus.

Je suis pas sur de comprendre le type de service? J'utilise l'application Tahoma (la nouvelle qui fonctionne pour la switch et le kit de connectivité).

Je suis dispo pour aider sans soucis (avec mes faibles compétences)
merci encore de votre réactivité

Bonne journée

**Comment by dubocr** [comment]
Les volets IO n'ont pas d'état d'après ce que je vois ce qui expliquerait pourquoi rien ne remonte. Sur l'appli TaHoma vous avez bien le retour ?
Pouvez-vous vous reconnecter à la page https://dev.duboc.pro/tahoma après avoir essayé une commande depuis l'appli Home afin que je vois la commande et l'erreur.
Avez-vous des choses dans les logs homebridge ?

Concernant le service c'était pour savoir si vous utilisiez 'tahoma' ou autre chose mais je comprends de votre réponse que vous passez par tahoma.

**Comment by Murphy1084** [comment]
Bonjour , j ai le même problème . Avez vous trouver une solution ? Merci d avance

**Comment by cjournet** [comment]
Après avoir comme conseillé reinclus les volets dans l’application TaHoma fa fonctionnait nickel. Depuis une mise à jour plus du tout :( il faut que je renvoi quelque chose?

**Comment by davidXire** [comment]
Le ticket devient un fouillis de problèmes différents, tout ce qui concerne ERROR 400 UNSUPPORTED_OPERATION -> https://github.com/dubocr/homebridge-tahoma/issues/342

**Comment by zakrabdea** [comment]
Salut cjournet,
Je rencontre les problèmes tu as rencontré il y a 1 an et je voulais savoir si tu as résolu le problème depuis. 
Merci pour ton aide. 
Cordialement.
