### ISSUE TITLE
ExteriorHeatingSystem > DimmerExteriorHeating

### ISSUE THREAD

**Issue by gongevangen** [dubocr/homebridge-tahoma#308]
bridge last 4 digits 4305

This device shows as a on/off switch, but it can be regulated as a dimmer.

I used to use this workaround https://github.com/dubocr/homebridge-tahoma/issues/209, but I cannot get it to work with the new version of this plugin.

Is it possible that you could change it to a dimmer so the heat can be set fro 0 -100% ?

**Comment by dubocr** [comment]
Hi,

This is implemented in latest release 2.1.53.
