### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#309]
Bonjour Romain, depuis ta dernière mise à jour, j’ai le droit au « bad credentials » dans les log.
Toutes les 30 secondes il retente de se connecter.
J’ai démarré homebridge, mais pareil.

**Comment by MirkoKas** [comment]
This has nothing to do with the latest updates of the plugin as far as I know. 
I have the very same problem with an earlier version. 
i also found that I can‘t login on tahomalink.com while the iOS app login works just fine. 
There are reports on Twitter that there was/is an outage on TaHoma a couple of hours ago. Maybe not all systems are up yet again.

**Comment by Tontonpat** [comment]
Effectivement j’avais le même souci sur tahomalink.
J’ai fait la mise à jour de ce plugin et j’ai vu les log.
Mais je n’ai pas pensé que ça venait du serveur tahoma.
C’est résolu.
