### ISSUE TITLE
[Somfy Connexoon] Gestion des erreurs / périphérique  'Window operator'

### ISSUE THREAD

**Issue by lboue** [dubocr/homebridge-tahoma#31]
Bonjour,

Tout d'abord merci pour ce plugin génial qui me permet de commander les appareils suivants depuis ma box Somfy Connexoon :
- Fenêtre de toit Velux Integra
- Volet fenêtre de toit roulant électrique (VELUX Sml)

Voici le log de démarrage:
```
pi@raspberrypi:~/.homebridge $ homebridge -D 2>&1 |egrep "Connexoon|tahoma"
Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.2  
[2018-6-4 22:09:12] [Connexoon] Initializing Tahoma platform...
[2018-6-4 22:09:12] [Connexoon] Connecting TaHoma server...
[2018-6-4 22:09:12] [Connexoon] Connecting TaHoma server...
[2018-6-4 22:09:14] [Connexoon] Device type Pod unknown
[2018-6-4 22:09:14] [Connexoon] Device WaterHeatingSystem ignored
[2018-6-4 22:09:14] [Connexoon] Device ElectricitySensor ignored
[2018-6-4 22:09:14] [Connexoon] Initializing platform accessory 'Shutter'...
[2018-6-4 22:09:14] [Connexoon] Initializing platform accessory 'Window operator'...
```

Je rencontre un souci sur le retour d'état dans un cas d'erreur. En effet, lorsque la fenêtre à été ouverte manuellement (débrayée), une tentative remonter une erreur dans les logs mais rien dans l'application HomeKit "Maison", la fenêtre repasse alors grisée car l'ouverture à échouée.

Voici ce que remontent les logs à ce moment précis:
```
[2018-6-4 22:29:28] [Connexoon] [Window operator] setClosure[0]
[2018-6-4 22:29:33] [Connexoon] [Window operator] setClosure WHILEEXEC_MANUALLY_CONTROLLED
```

Serait-il possible de remonter une notification pour signaler ce défaut dans HomeKit ?
Eventuellement ça : [HMError.Code.actionSetExecutionFailed](https://developer.apple.com/documentation/homekit/hmerror/code/actionsetexecutionfailed)
 

Cordialement,
Ludovic

**Comment by dubocr** [comment]
Bonjour,

Pour des raisons de performances, le retour vers Homekit est effectué dès la prise en compte de la commande sur Tahoma et il est possible que l'erreur ne soit pas connue à ce moment. Pour vérifier, peux-tu remplacer les lignes 109 à 112 du fichier 'accessories/AbstractAccessory.js' par les suivantes :
```
if(status == ExecutionState.FAILED || status == ExecutionState.COMPLETED)
that.log('[' + that.name + '] ' + cmdName + ' ' + (error == null ? status : (status + ' - ' + error)));
else
that.log.debug('[' + that.name + '] ' + cmdName + ' ' + (error == null ? status : (status + ' - ' + error)));
```

Dans tous les cas, dans le fichier 'accessories/Awning.js' tu peux modifier les lignes 59 à 74 pour déplacer la ligne `callback(error);` afin d'arriver au code ci-dessous. Cependant, le widget HomeKit restera "bloqué" durant tout le mouvement du device :

```
switch (status) {
	case ExecutionState.INITIALIZED:
		
		break;
	case ExecutionState.IN_PROGRESS:
		var newValue = (value == 100 || value > that.currentPosition.value) ? Characteristic.PositionState.INCREASING : Characteristic.PositionState.DECREASING;
		that.positionState.updateValue(newValue);
		break;
	case ExecutionState.COMPLETED:
	case ExecutionState.FAILED:
                callback(error);
		that.positionState.updateValue(Characteristic.PositionState.STOPPED);
		that.targetPosition.updateValue(that.currentPosition.value); // Update target position in case of cancellation
		break;
	default:
		break;
}
```

**Comment by lboue** [comment]
J'ai modifié les 2 fichiers:
- accessories/AbstractAccessory.js
- accessories/Awning.js

J'ai refait un autre test "coupure de courant" et voici le résultat du test:

```
[2018-6-5 22:08:34] [Connexoon] [FenÃªtre toit cha] setClosure[0]
[2018-6-5 22:08:34] [Connexoon] [FenÃªtre toit cha] setClosure INITIALIZED
[2018-6-5 22:08:34] [Connexoon] Register listener
[2018-6-5 22:08:36] [Connexoon] [FenÃªtre toit cha] setClosure IN_PROGRESS
[2018-6-5 22:08:38] [Connexoon] [FenÃªtre toit cha] setClosure FAILED - ACTUATORNOANSWER
[2018-6-5 22:08:38] [Connexoon] Unregister listener
```

Ludovic

**Comment by dubocr** [comment]
Et lorsque la fenêtre est "débrayée" ?

**Comment by dubocr** [comment]
C'est bien ça. En décalant le callback comme indiqué tu auras le message d'erreur mais le widget sera "bloquant" tant que le mouvement du volet n'est pas terminé.

**Comment by lboue** [comment]
J'ai trouvé un moyen de lever des erreurs et générer une alerte avec la Characteristic ObstructionDetected : 

> HMCharacteristicTypeObstructionDetected
> Indicates whether the accessory has detected an obstruction—for example, an automatic garage door opener may have the ability to tell if something is blocking the door. The value is a boolean indicating whether an obstruction was detected.

J'ai fait un [premier test ](https://github.com/lboue/homebridge-tahoma/commit/b02fb2e2b74d2728e81016ffe3041e0e9d22668a
)en publiant le service et cela apparaît dans HomeKit

J'ai pris exemple sur un contrôleur "GarageDoor".

Ludovic
