### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by zilnik1234** [dubocr/homebridge-tahoma#310]
I have 6 rollerblinds with connexoon hub
i/am using the plugin since 2 years with hoobs with no issues. today my blinds stopped working from homekit. i checked the logs in hoobs and it says 14/07/2021, 22:38:25 [Tahoma] Bad credentials
14/07/2021, 22:38:25 [Tahoma] Retry in 120 sec...
14/07/2021, 22:42:25 [Tahoma] Bad credentials
14/07/2021, 22:42:25 [Tahoma] Retry in 240 sec...

i updated the plugin, the connexoon hub and hoobs and it/s still the same error. 
in connexoon app everything is working fine.

**Comment by Pharaoas** [comment]
Hi, it seems Tahoma changed it's api. 
Got the same problems here - and cannot login on tahomalink.com...
Tahoma App works...
Problem is after latest update of Tahoma box.

best regards

**Comment by zilnik1234** [comment]
I updated the hub after i got the bad credentials log...
and i can login here https://dev.duboc.pro/tahoma with my credentials if that helps

**Comment by mhalttu** [comment]
I'm seeing the same problem.

**Comment by pelo76** [comment]
#metoo - same Problem here

**Comment by robcalcroft** [comment]
Same here

**Comment by henkied** [comment]
same here

**Comment by dubocr** [comment]
Hi,

Can you give your homebridge-tahoma plugin version ?
If you all have access to the https://dev.duboc.pro/tahoma page with « TaHoma / Connexoon » service selected it should work in the plugin with `tahoma` service name in the latests versions (2.2.x).

**Comment by pelo76** [comment]
This Morning, everything works again…

**Comment by iMicknl** [comment]
@dubocr this is caused by an outage on Somfy's side and probably your HomeBridge integration keeps retrying? (which will extend / invoke a temporary account ban). During an outage they throw a BadCredentials error, after which you should stop retrying and ask the user to reauthenticate. This should be successful if the service is restored.

See https://github.com/iMicknl/ha-tahoma/issues/466 for more context. Feel free to hit me up on Discord to discuss. (iMick#1903)

**Comment by robcalcroft** [comment]
Does anyone know the exact length of time that the "temporary ban" happens for? Sounds like Somfy services are back online today but im still locked out of the account, trying a different IP is not really do-able for me

**Comment by iMicknl** [comment]
@robcalcroft my understanding is every time you do a login during this period, you 'temporary ban' will be extended. Best would be to stop hitting the service (probably by disabling the homebridge integration). And try to login again in a day or so.

**Comment by robcalcroft** [comment]
👍 ok cool thanks

**Comment by dubocr** [comment]
> @dubocr this is caused by an outage on Somfy's side and probably your HomeBridge integration keeps retrying? (which will extend / invoke a temporary account ban). During an outage they throw a BadCredentials error, after which you should stop retrying and ask the user to reauthenticate. This should be successful if the service is restored.
> 
> See [iMicknl/ha-tahoma#466](https://github.com/iMicknl/ha-tahoma/issues/466) for more context. Feel free to hit me up on Discord to discuss. (iMick#1903)

Thanks @iMicknl, exact I managed this case at startup but not when occurring at runtime.
I'll implements locker when Bad credentials occurs.

**Comment by snookerap** [comment]
Selbiges Problem bei mir.

[7/15/2021, 11:23:12 PM] [Tahoma] API client locked. Please check your credentials then restart.
[7/15/2021, 11:23:12 PM] [Tahoma] Retry in 120 sec...
[7/15/2021, 11:25:12 PM] [Tahoma] API client locked. Please check your credentials then restart.
[7/15/2021, 11:25:12 PM] [Tahoma] Retry in 240 sec...

**Comment by dubocr** [comment]
> Selbiges Problem bei mir.
> 
> [7/15/2021, 11:23:12 PM] [Tahoma] API client locked. Please check your credentials then restart.
> [7/15/2021, 11:23:12 PM] [Tahoma] Retry in 120 sec...
> [7/15/2021, 11:25:12 PM] [Tahoma] API client locked. Please check your credentials then restart.
> [7/15/2021, 11:25:12 PM] [Tahoma] Retry in 240 sec...

You now have to wait. If you are always locked tomorow please let me know and stop manualy homebridge for some hours.

**Comment by snookerap** [comment]
Sadly it still does not work.
I can log into the Tahoma app, but not online at tahomalink.com.
I have a Tahoma Box V1.

![image](https://user-images.githubusercontent.com/50512041/125959439-ff910d78-43c0-4524-b956-fb8afac239fc.png)

**Comment by vniehues** [comment]
I actually have the same problem where the plugin is unable to log me in and I also can't log in on https://www.tahomalink.com. 
But I was able to log in on https://somfy-connect.com without any problem! I was then redirected to tahomalink but I was already logged in.

**Comment by robcalcroft** [comment]
Hey all im still getting bad credentials issue after leaving the account for 24hrs, is there any way to contact somfy to get them to unban me?

**Comment by dubocr** [comment]
What did you mean by 

> leaving account for 24hrs ?

Do you have access to TaHoma app ?

**Comment by ollero** [comment]
Hi, 
I had the same “bad credentials” problem. I couldn’t login to tahomalink, but I could use the somfy app. However, I could access Tahomalink from other computers out of home, so I thought it had to do with my IP. I solved it **restarting my router**. I have dynamic IP, and it seems that the Tahoma service had too many calls from my IP and banned it. Restarting my router supposedly assigned me a new public IP, then I restarted Homebridge and it worked like a charm again. Hope this helps

**Comment by volantynys** [comment]
I think this is longer than 24
![C534AD42-D7CF-4394-AE7A-D9646B7BDE5B](https://user-images.githubusercontent.com/30656490/126083041-f027b88f-6850-475c-9e05-2345d1d35aeb.jpeg)

**Comment by snookerap** [comment]
It works again for me.
I waited 48 hours.
I have a fixed IP.

**Comment by bakman2** [comment]
My fix was; 
- go to https://www.tahomalink.com
- forgot password
- set new password
- removed connexoon app (+delete all data) 
- reinstalled new app, login with new password
- update homebridge config with new password
- restart homebridge, all working.

Could this be caused by the oauth2 authentication they use in the app(s) perhaps ?
