### ISSUE TITLE
Refresh rate

### ISSUE THREAD

**Issue by iChris5** [dubocr/homebridge-tahoma#311]
Hello,

is it possible to reduce the refresh rate for showing the actual status of sensors in HomeKit?

I would like to see the window sensors immediately or shortly after opening/closing the windows. Actually, it needs up to one minute until showing the status. 

Best regards
Chris

**Comment by dubocr** [comment]
Hi,

You can reduce the `pollingPeriod` but it's already at 30 sec by default (so normally you should see updates after 30 sec or less).
