### ISSUE TITLE
Error Unhandled promise rejection

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#314]
Bonjour @dubocr 
Depuis la dernière mise à jour de ton plugin, j'ai cette erreur dans les logs:
`(node:5505) UnhandledPromiseRejectionWarning: Error 405 Request method 'POST' not supported (INVALID_API_CALL)
(node:5505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)
(node:5505) UnhandledPromiseRejectionWarning: Error 405 Request method 'POST' not supported (INVALID_API_CALL)
(node:5505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)`

Je n'ai rien changé, ou mis à jour d'autre que ton plugin.

As tu une idée du problème?

**Comment by Tontonpat** [comment]
A priori, ce message apparaît lorsque j’ouvre home

**Comment by Tontonpat** [comment]
Bonjour Romain, t’as une idée sur ce problème ?

**Comment by Tontonpat** [comment]
Bonjour Romain, je viens d'installer la version 2.2.8 et je n'ai plus ce message.

**Comment by Pharaoas** [comment]
Same problem on my side, I also switched back to 2.2.8...

**Comment by jerem916** [comment]
Même soucis également. Je suis aussi repassé sur la 2.2.8

**Comment by dubocr** [comment]
Bonjour,

Avez-vous tous une porte de garage ou un portail RTS ?
Il semble que l'API retourne une erreur sur une demande de refresh sur les périphériques RTS (ce qui est cohérent en soit).
J'ai déployé une mise à jour pour ne pas réaliser ce refresh, pourrez-vous m'indiquer si cela corrige le problème.

Merci d'avance.

**Comment by Tontonpat** [comment]
Salut Romain, chez moi ces deux équipements sont en IO

**Comment by Tontonpat** [comment]
Suite à la mise à jour :
![2172CD2B-B68B-4D82-BC77-B86525E7DD2F](https://user-images.githubusercontent.com/49283285/128595544-aa88257a-0f47-4226-8d15-f9b0c396a767.jpeg)

**Comment by jerem916** [comment]
Oui je vous confirme que j’ai bien une porte de garage en RTS.

merci à vous !! Bonne journée !

**Comment by Tontonpat** [comment]
@dubocr pourquoi as tu fermé ce ticket? J’ai le message d’erreur 405 à chaque fois que j’ouvre home

**Comment by Tontonpat** [comment]
![B69DEDFB-9321-4188-92FB-FE4DB381EA23](https://user-images.githubusercontent.com/49283285/128597284-20737cbd-a0a7-444d-8825-d17e7d266711.jpeg)

**Comment by nscheffer** [comment]
J'ai que du IO partout (volets, portail, garage, etc...).
Mise à jour du plugin et même erreur 👍 [07/08/2021, 15:24:03] [TaHoma] [Portail] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
[07/08/2021, 15:24:03] [TaHoma] [Garage Bleu] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
[07/08/2021, 15:24:03] [TaHoma] [Garage Rouge] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
[07/08/2021, 15:24:18] [TaHoma] [Portail] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
[07/08/2021, 15:24:18] [TaHoma] [Garage Rouge] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
[07/08/2021, 15:24:19] [TaHoma] [Garage Bleu] Error 405 Request method 'POST' not supported (INVALID_API_CALL)

Retour en 2.2.8 en attendant un fix.
