### ISSUE TITLE
UpDownRollerShutter

### ISSUE THREAD

**Issue by pzim-devdata** [dubocr/homebridge-tahoma#315]
bridge last 4 digits : 2819

When I use a _remote control_ (not the app Tahoma) for opening or closing the "UpDownRollerShutter" the status of the accessory in Homebridge doesn't change.
For exemple, when I'm opening the "UpDownRollerShutter" the state of the accessory "UpDownRollerShutter" in Homebridge stay "Close".
It's the same for "UpDownSwingingShutter".
I think it would be great if the state (open or close) of this accessories ("UpDownRollerShutter" and "UpDownSwingingShutter")  not been showed on Homebridge, as in the Tahoma app.

**Comment by Tontonpat** [comment]
Hi, RTS or IO ?

**Comment by pzim-devdata** [comment]
Hi, thank you for your reply. It’s RTS

**Comment by Tontonpat** [comment]
It’s normal.
RTS didn’t send the position to tahoma (IO does) so homebridge doesn’t have the position.
Using a remote control or the tahoma app will have no effect to homebridge.

The « my » position in tahoma is the set of 50% in Home.
Also, you can configure the time like this: [Exemple](https://github.com/dubocr/homebridge-tahoma/issues/298#issuecomment-864392794) 

I’ll hope you understand because I’m French 😅

**Comment by Tontonpat** [comment]
Salut, si je ne dis pas bêtises, les volets dans home n’existe pas avec 3 boutons.
Pour le retour d’état, comme je te l’ai dis, les équipements rts ne renvoient leurs états à tahoma donc homebridge ne peut pas le savoir.
Pour que l’état soit juste dans home, utilise home ou Siri 😅
As tu essayé la config de temps?

**Comment by pzim-devdata** [comment]
`salut. Merci pour ta réponse. J’ai essayé les paramètres de temps mais ca n’a rien changé du coup j’ai retiré ce paramètre. Par contre lorsque je demande à siri “entrouve les volets” ca fonctionne. ` Dans Tahoma il y a un bouton my donc ce bouton doit bien exister dans les commandes. Il n’y a pas d’interrupteur à 3 positions mais on pourrait mettre un switch “my” un switch up et un switch down dans les paramètres du volet au lieu d’un variateur.

**Comment by Tontonpat** [comment]
@dubocr: je te laisse répondre

**Comment by dubocr** [comment]
Bonjour @pzim-devdata,

Par défaut sur les volets RTS, la commande "my" s'execute pour toute les positions intermédiaires (entre 1 et 99%) :
- 0% => Fermé
- 100% => Ouvert
- Autre % => My

Il est possible comme indiqué par @Tontonpat d'avoir un positionnement approximatif pour les positions intermédiaires en ajoutant le paramètre `movementDuration` correspondant au temps en seconde que met le volet pour passer de 100% à 0% (**un redémarrage d'homebridge est nécessaire**)

```
{
	"key": "RollerShutter",
	"movementDuration": "30"
}
```

Ou depuis Homebridge UI
<img width="736" alt="Capture d’écran 2021-08-07 à 11 24 39" src="https://user-images.githubusercontent.com/5015156/128595653-2c0725a4-75b7-4996-bc7c-01fd41ae4c53.png">

Dans tous les cas, la commande `My` reste disponible sur les applications tierces (comme Eve). Si vous souhaitez la retrouver dans Home vous pouvez l'ajouter dans une Scene par exemple.

Concernant les commandes en local via la télécommande. Vos équipements étant en RTS il est impossible de faire quoi que ce soit, c'est pour cette raison que ce type de volet ne sera jamais compatible Homekit avec TaHoma et que le comportement que vous évoquez n'est pas non plus possible sur l'app TaHoma.

**Comment by Alwiz79** [comment]
The my button also works as „stop” command (which doesn’t have to at 50%).
Is there a „real“ stop at at any given time possible?

**Comment by pzim-devdata** [comment]
Merci @dubocr Je vais créer une scène pour la position My à défaut d’avoir le même comportement que dans Tahoma.
