### ISSUE TITLE
[Stateless][RollerShutter] Offset duration for accurate position

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#316]
Bonjour Romain,
Je rencontre un problème avec le réglage des volets roulants depuis quelques jours.(je n´ai pas fait attention si c’est lié à une maj de ton plugin)
Il y a un délai entre le moment où je règle le volet et le moment où la commande cancel est envoyée.
Donc le temps de latence + le délai de cancel = beaucoup trop 😅
Du coup les volets ne sont pas positionnés comme il faut.
Exemple pour un réglage à 50% (5s latence + 7,5s avant le cancel qui a mis 10s) :
![C65BE063-47A0-40F9-BBC0-1ADC614496A9](https://user-images.githubusercontent.com/49283285/128006028-f17eceb7-ac15-4fea-8f55-8488f264ca94.jpeg)

**Comment by Tontonpat** [comment]
Je viens de me connecter et je vois 14s:
![CC9FB92A-5B96-4A2A-938D-AC820987E3C3](https://user-images.githubusercontent.com/49283285/128006935-9ac589a7-680f-4a8e-880d-48e046b40e74.jpeg)

**Comment by dubocr** [comment]
Bonjour Patrick,

Peux-tu essayer d'ajouter le paramètre `"execPollingPeriod": 2` pour réduire la fréquence de refresh lors d'une execution et me dire si ça améliore ?

Merci.

**Comment by Tontonpat** [comment]
Bonjour Romain, 1er essai concluant.
A suivre

**Comment by Tontonpat** [comment]
Bonjour Romain, après plusieurs tests, ça fonctionne mieux avec ce paramètre.
Penses tu ajouter un correctif?

**Comment by dubocr** [comment]
Bonjour Patrick,

Je vais probablement le re-passer à 2 secondes même si j'y vais doucement sur ce genre de choses car je ne souhaites pas froisser Somfy qui pourrait décider de blacklister le plugin si ils le voulaient.

J'ai fait des améliorations ces derniers temps sur la gestion des polling notamment sur les executions donc je pense que ca se tente. Le problème c'est qu'avant, l'API pouvait ne pas retourner la fin d'une execution et donc le plugin continuait d'interroger toutes les 2 secondes l'API sans limite de temps.

**Comment by Tontonpat** [comment]
@dubocr je penses que le ticket #319 vient de là

**Comment by Tontonpat** [comment]
Bonjour Romain, ta dernière version du plugin (2.2.14) fonctionne très bien.
Je re-tente donc : "execPollingPeriod": 2
Je te tiens au courant

**Comment by Tontonpat** [comment]
Bonjour Romain,
Le paramètre execPollingPeriod ne règle plus le problème de délai.

**Comment by SaruManiac** [comment]
Bonjour,

Je me permets de rebondir sur cette issue car j'ai fait le même constat de ces +5s sur mon installation (v2.2.15) et je venais chercher des infos. :)

Pour ne pas risquer le blacklist du plugin en augmentant la fréquence des exécutions, serait-il possible de mettre en place un offset d'ajustement paramétrable comme workaround ?

Je m'explique : 
Si mon volet mets 20s par ouverture/fermeture et que je demande une ouverture à 50%, l'appli va envoyer la commande d'ouverture, attendre 5s ,et demander un stop après 10s (50% de mes 20s). Si au lieu de ces 10s l'appli demandait 10s - 5s (offset), on arriverait à un valeur d'ouverture plus proche de la demande.
On aurait toujours un comportement bizarre pour toute demande qui nécessiterait <5s de temps d'ouverture/fermeture, mais pour toutes les demandes >= 5s ça pourrait régler le soucis.

Je ne sais pas si on est beaucoup à rencontrer ce problème mais je me dis que ça pourrait être utile à d'autres.
En tout cas merci beaucoup pour ce super plugin que j'utilise quotidiennement et tout le travail déjà réalisé ! :)

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous essayer de jouer avec le paramètre non documenté `offsetMovementDuration` (en seconde pour l'instant).
Il ajoute un délais fixe au délais variable (selon la position) sur la dernière version.

Pour information, je crois avoir lu (source non officielle) qu'une valeur jusqu'à 1 seconde pour les poll lors des execution était "acceptable".
