### ISSUE TITLE
Garage door issue with radio set IO

### ISSUE THREAD

**Issue by RiS84** [dubocr/homebridge-tahoma#321]
Hello!

Again, thank you for this great homebridge plugin. Much apprecicated!
Unfortunately, I have for some time again problems with the garage control. The status does not change and is blocked. 
Therefore, the garage is always open or in "close" mode after execution.

Hombridge log shows: [TaHoma] [Garage] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
I reported my config at https://dev.duboc.pro/tahoma --> SETUP-XXXX-XXXX-2780

I would be very happy if this problem can be solved. As always, thanks for your great work.

**Comment by qelanhari** [comment]
Hello @dubocr, même erreur de mon côté : 

```
[8/13/2021, 7:25:07 AM] [Connexoon] [Portail] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
[8/13/2021, 7:25:07 AM] [Connexoon] [Porte Garage] Error 405 Request method 'POST' not supported (INVALID_API_CALL)
```

Je suis retourné en 2.2.8 mais j'ai ça en échange : 

```
[8/13/2021, 6:30:35 AM] [Connexoon] [Portail] open COMPLETED
(node:1904) UnhandledPromiseRejectionWarning: TypeError: this.platform.client.requestState is not a function
    at Gate.requestStateUpdate (/usr/local/lib/node_modules/homebridge-tahoma/src/Mapper.ts:196:54)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:1904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by dubocr** [comment]
Bonjour,

Avez-vous toujours le problème avec la >2.2.12 ?

Merci.

**Comment by qelanhari** [comment]
Problème toujours présent :(

**Comment by qelanhari** [comment]
Au passage, il me semble que j'ai le souci avec la > 2.2.12 autant qu'avec la 2.2.1, mais que je n'avait pas avant (genre avant la release qui transforme la fonction piéton en Lock au lieu d'un Switch) : 
Lorsqu'une automatisation essai de fermer mon portail / garage alors qu'il est déjà fermé (et marqué comme fermé dans homekit), la tuile passe de "closed" à "closing" et bloque pendant plusieurs secondes/minutes.

**Comment by nscheffer** [comment]
Je confirme pareil pour moi, retour en 2.2.8 pour que tout fonctionne correctement.

**Comment by qelanhari** [comment]
J'ai fait la MAJ hier soir et je n'ai pas revu d'erreurs dans les logs pour le moment non plus.
J'ai encore le souci des tuiles qui continuent de mouliner si l'état état déjà le même, mais moins longtemps il me semble.
