### ISSUE TITLE
Blinds do not go up all the way

### ISSUE THREAD

**Issue by Reckziegel182** [dubocr/homebridge-tahoma#322]
Hi

thank you for your great work! When i open my shutters all the way up in Homebridge, it goes up maybe 95%. When i then open it 100% in Tahoma app, it goes all the way. Any way to adjust the max open value in Homebridge plugin? The not fully opened shutters are blocking my mosquito door :-D 
Thank you

**Comment by dubocr** [comment]
Hi @Reckziegel182,

Do you follow the previous message to let me investigate ?

Thanks.

**Comment by Reckziegel182** [comment]
Hello sorry for not following up. Not sure i understand the instrucitons however the results seem to be mixed. Right now tested and all works. I will try to find a pattern and provide more info once / if it happens. Until then - pleas eclose :-)
