### ISSUE TITLE
Control the "my" command ?

### ISSUE THREAD

**Issue by Alwiz79** [dubocr/homebridge-tahoma#323]
Is there a way to send the "my" command via homekit?
My original remote control (wireless) has an up, down and my button, which also stops the blind.
I'd like to use some other nice homekit button, but I don't want to lose the "my"/stop control.
Up and down will be easy with the homekit automation tools, but I see no way to send "my"/stop

**Comment by Alwiz79** [comment]
I did the above. Pressing the "my" button does not show up explicetly in the config browser.
The ony thing I see is, that the "close 100%" command was cancelled

**Comment by dubocr** [comment]
Hi,

you can find answer to your questions here :

https://github.com/dubocr/homebridge-tahoma/issues/315#issuecomment-894630463

Best
