### ISSUE TITLE
[PositionableHorizontalAwning] Problems Push Notification

### ISSUE THREAD

**Issue by Jemeins** [dubocr/homebridge-tahoma#324]
Hello, when I close my awning after a few seconds, I get the message "awning open".
I use a sunea io drive

**Comment by dubocr** [comment]
Hi,

Before following the previous process, please put your awning in "close" state (Not deployed).

Thanks.

**Comment by Jemeins** [comment]
PositionableHorizontalAwning
SETUP-XXXX-XXXX-4676
