### ISSUE TITLE
initPosition does not work anymore for UpDownRollerShutter

### ISSUE THREAD

**Issue by exzz** [dubocr/homebridge-tahoma#326]
Hello,

Just update this wondurful plugin from an old version. Since, the initPosition for my RTS roller shutter is not evaluated : When I start homebridge, all my shutter are shown as closed.

Here is my current configuration:
```
{
            "platform": "Tahoma",
            "name": "Tahoma",
            "user": "YYY",
            "password": "XXX",
            "refreshPeriod": 60,
            "exclude": [
                "Escalier",
                "Salle de bain",
                "TSKAlarmController"
            ],
            "devicesConfig": [
                {
                    "key": "UpDownRollerShutter",
                    "defaultPosition": 50,
                    "initPosition": 50
                }
            ]
}
```

The defaultPosition still seems to work as expected. If I interact with any roller shutter, it appears as 50% open once command is ended.

I understand this changed since my last update:
```
 if (this.stateless) {
            //this.currentPosition.updateValue(this.initPosition);
            //this.targetPosition.updateValue(this.initPosition);
            if (this.device.hasCommand('my')) {
                this.my = service.getCharacteristic(MyPositionCharacteristic);
                this.my.onSet(this.setMyPosition.bind(this));
            }
```
Does this means the initPosition is configured to "my" position ?

Thanks.

**Comment by dubocr** [comment]
Hi @exzz 

In latests plugin version, position are saved in case of restart. So init position is the last position.
If you would like to restore widget in specific position, please use `defaultPosition` option.
