### ISSUE TITLE
Update Cozitouch : Bad Connexion Erreur API Client locked

### ISSUE THREAD

**Issue by Yodacoole** [dubocr/homebridge-tahoma#328]
Bonjour,

Suite à la mise à jour Cozitouch ce week end, l'authentification ne passe plus.
J'ai appelé Atlantic pour vérifier avec eux et il semblerait qu'il aurait changé le niveau d'authentification.

Cela fait 3 fois que je réinitialise mon mot de passe. Même avec l'application cozytouch il y a eux des problèmes de réauthentification et niveau de sécurité.

Après plusieurs essaie, cela semble être résolu coté apps cozytouch, par contre coté homebridge impossible.

[9/28/2021, 13:53:59] [core:OperatingModeState] API client locked. Please check your credentials then restart.
If your credentials are valid, please wait some hours to be unbanned
[9/28/2021, 13:53:59] [core:OperatingModeState] Retry in 120 sec...

Avez vous eux un retour ?

Merci de votre aide,

**Comment by Yodacoole** [comment]
J'ai testé la connexion depuis le site https://dev.duboc.pro/tahoma

**Comment by Yodacoole** [comment]
En complément :

(node:16904) UnhandledPromiseRejectionWarning: Bad credentials
(node:16904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:16904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Yodacoole** [comment]
Atlantic, on modifiait leur apps par une mise à jour ce week end et plus moyen de se connecter depuis homebridge.
L'apps cozytouch ayant eu quelques soucis a pu être corrigé et tout est rentré dans l'ordre, par contre depuis ton lien pour le mode debug est impossible d'accès.

Merci Romain de ton aide,

**Comment by dubocr** [comment]
Corrigé sur la 2.2.14
