### ISSUE TITLE
Somfy protect alarm

### ISSUE THREAD

**Issue by just808b** [dubocr/homebridge-tahoma#329]
I’m a newbie to Homebridge.  I currently have Hoobs and looking to add my Somfy one to HomeKit.  Is this the right plug-in.  Can someone help? I’m willing to pay.

**Comment by dubocr** [comment]
Hi @just808b 

Is somfy protect alarm using gateway like TaHoma or something like that ?
You can try to log with your account at [http://dev.duboc.pro/homebridge-tahoma/](http://dev.duboc.pro/homebridge-tahoma/).
If you can connect to one of the services, then you could try to install the homebridge-tahoma plugin to hoops and configure it with your credential and the good service.
