### ISSUE TITLE
This plugin generated a warning from the characteristic 'Current Position': 

### ISSUE THREAD

**Issue by kurt-thu** [dubocr/homebridge-tahoma#339]
I get the warning:

This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 124 exceeded maximum of 100.

Any idea what's wrong?

Thx a lot for your help!!

**Comment by dubocr** [comment]
Hi,

This issue is generated because your device as invalid position value. What kind of device it is ?
As this message is a warning, you should simply ignore it.

**Comment by dubocr** [comment]
Please follow #341
