### ISSUE TITLE
[SomfyThermostat] Gestion affichage des modes

### ISSUE THREAD

**Issue by NicolasBoulanger** [dubocr/homebridge-tahoma#340]
Hello,
je viens de mettre en place homebridge, jai un souci concernant l'etat du thermostat radio v2

il affiche toujours qu'il est en chauffe en mode automatique, alors que non
l'icon ne change jamais, j'ai l'impression que l'app thermostat et votre plugin n'est pas synchro avec tous les mode (chauffe, refroidir, eteint et auto)

[https://imgur.com/a/iFeLRw8](url)

SETUP-2003-1017-9714

merci :)

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous placer votre thermostat dans un mode qui pose problème puis renvoyer votre config sur http://dev.duboc.pro/homebridge-tahoma

Merci

**Comment by dubocr** [comment]
Please follow #393
