### ISSUE TITLE
Error 400 - UNSUPPORTED_OPERATION 

### ISSUE THREAD

**Issue by davidXire** [dubocr/homebridge-tahoma#342]
Bonjour,

J'ai l'erreur suivante : 
`setClosure Error 400 No such command : setClosure on device ogp://xxxx-xxxx-xxxx/xxxxxxxx (ogp:Shutter) (UNSUPPORTED_OPERATION)`

Fonctionnement parfaitement normal avant cette erreur

**Comment by davidXire** [comment]
1) Quand j'exécute la commande depuis l'app officiel aucun problème. Depuis Homebridge, l'historique ne se met pas à jours
2) 
![image](https://user-images.githubusercontent.com/1581073/142909066-2d600e56-90aa-4411-b59c-047153f3ad63.png)
3) Shutter 
4) cf photo ci dessus

**Comment by davidXire** [comment]
`    protected getTargetCommands(value) {
        if (this.stateless) {
            if (value === 100) {
                return new Command('open');
            } else if (value === 0) {
                return new Command('close');
            } else {
                if (this.movementDuration > 0) {
                    const delta = value - Number(this.currentPosition!.value);
                    return new Command(delta > 0 ? 'open' : 'close');
                } else {
                    return new Command('my');
                }
            }
        } else {
            return new Command('setClosure', this.reversedValue(value));
        }
    }`

On arrive dans le dernier cas, sauf que la commande SetCloure n'existe pas pour les volets RTS

**Comment by neverwalkerwan** [comment]
Hi, I have the same problem with somfy connectivity kit bought from Orange (only affordable and not out of stock somfy hub in France currently) and my 2 rts curtains, smoove wall remote. Window covering activated for both. 
Works perfectly and suddenly error 400 command not supported. Still works in tahoma app, solved by deleting 2 curtains from tahoma and reinstall it, restarting homebridge, quiet annoying. I suspect that it happens after using the physical remote button. Just reinitialized it, I won’t touch my wall remotes from now and see if it still finishes in error 400 at one moment. 
any corrective update though?

**Comment by davidXire** [comment]
https://github.com/dubocr/homebridge-tahoma/blob/97bd290ff9cb466ca6095c694518e9a931b93f60/src/mappers/RollerShutter.ts#L57
En supprimant la condition, ça marche sans aucun problème. 

@neverwalkerwan Je faisais comme toi avant, et j'en ai eu marre. J'ai bidouillé un peu le code pour que ça marche en attendant une solution pérenne. D'ou mes premiers éléments de diagnostique

**Comment by neverwalkerwan** [comment]
Ok cool merci comment est-ce que je fais ça sur homebridge installé sur un raspberry en réseau local? Désolé un peu noob la dessus! Merci!

**Comment by davidXire** [comment]
> Ok cool merci comment est-ce que je fais ça sur homebridge installé sur un raspberry en réseau local? Désolé un peu noob la dessus! Merci!

Tu installes ton éditeur texte préféré et tu vas dans :
/usr/local/lib/node_modules/homebridge-tahoma/dist/mappers

Tu remplaces le contenu de RollerShutter.js par celui ci : https://pastebin.com/Ww2E8LWt

**Comment by neverwalkerwan** [comment]
Merci mec!

**Comment by neverwalkerwan** [comment]
up?

**Comment by Pilou103** [comment]
Bonjour, J’ai également le même problème, pour le résoudre, je suis obligé de désinstallé mes volets sur connectivity box, et de tous réinstaller. 
Serait il possible de résoudre ce problème?

**Comment by neverwalkerwan** [comment]
@davidXire J’ai bien compris d’où venait le problème (setclosure) et comment éditer rollershutter.ts en revanche j’ai du pas comprendre quoi changer. Quand tu dis supprimer la condition ça veut dire quoi? Pcq j’ai essayer en copiant collant tout le script, ça marchait pas mes volet était « non géré » et quand j’y vais manuellement en supprimant toute la ligne « else {
return new Command(‘setClosure’, this.reversedValue(value)); » les volets sont géré mais quand je tente de fermer ou s’ouvrir il ne se passe rien et dans le log j’ai « no command for this device » ou un truc dans le genre. Ce que j’ai pas encore testé c’est faire ça et les supprimer-réinstaller dans tahoma. Besoin de ton aide stp!

**Comment by dubocr** [comment]
Bonjour à tous,

Désolé pour ce silence je suis actuellement loin de tout pour quelques mois. J'ai tout de même fait quelques corrections ce qui devrait corriger également ce problème.

**Comment by neverwalkerwan** [comment]
@dubocr merci beaucoup, je te fais un feedback dans quelques jours semaine si ça marche ou dès qu’il y a un bug 🙂🙂🙂
