### ISSUE TITLE
MyFoxSecurityCamera not supported

### ISSUE THREAD

**Issue by MMMMikael** [dubocr/homebridge-tahoma#345]
Hi,

While MyFoxSecurityCamera is well found by the plugin, it is shown as a "not supported" device in Apple Homekit.
The message in the Apple Home App is  "This accessory is not currently supported by the Home App".

Any advice ?

Thanks in advance,
Mickael.

**Comment by dubocr** [comment]
Hi,

If always required, please follow process at [http://dev.duboc.pro/homebridge-tahoma](http://dev.duboc.pro/homebridge-tahoma) to reopen integration request.

Thanks
