### ISSUE TITLE
Blinds go all the way up and then down

### ISSUE THREAD

**Issue by fox-on-tour** [dubocr/homebridge-tahoma#346]
Hey,

thank you for this plugin. I posted this behavior  a couple of months ago but I have forget about it. Anyway it’s still present. When I open my blinds in HomeKit to 100% the blind goes all the way up and then finally it hits the end position it then goes a title bit down (nearly 2-3%). What kind of informations do you need to investigate?
Thank you in advance.

**Comment by dubocr** [comment]
Hi,

Do you have the option "blindsOnRollerShutter" active in your plugin config ?
