### ISSUE TITLE
Cozytouch thermor problem

### ISSUE THREAD

**Issue by granborja** [dubocr/homebridge-tahoma#347]
Hi! 
I have one of this cozytouch wifi and I was able to control it with homekit through homebridge, but It doesn´t show the temperature.
It is always in 0.0ºC...

Is it any solution?

Thanks!

**Comment by granborja** [comment]
sorry but im not able to sing in in the report config web...

**Comment by dubocr** [comment]
Hi,

[https://dev.duboc.pro/tahoma](https://dev.duboc.pro/tahoma) is updated with Cozytouch new sign in process.
