### ISSUE TITLE
Cozytouch Error 429 Too many requests, try again later (QUOTA_EXCEEDED)

### ISSUE THREAD

**Issue by OSS1117** [dubocr/homebridge-tahoma#349]
Since a few days, (corresponding to some updates on some Atlantic Cozytouch maintenance, reported as stability issue due to increasing sollicitation of the servers, I get the Error 429 Too many requests, try again later (QUOTA_EXCEEDED) message. 
It does correspond to the refresh time, thus I increased the refresh time step by step up to 360 minutes (6 hours).

It looks like to have disappeared now (at 5 hours refresh time it was still occurring). Consequence ; the changes into the settings are reported with a longer period.

**Comment by anthonyplaisir** [comment]
dear all I have the same since some days, do you have any issu?

**Comment by Valmorefr** [comment]
Hi all. I'm having the same issue for a few weeks. I've tried extending the poling interval, to no avail. Looks like a server-side issue? Is there any way around that? I have a water heater as well, connected through cozytouch platform.

**Comment by Xenon341** [comment]
Hi there !

Same problem but when this happen, homebridge restarts and it reset the room setting on all of my Cozytouch devices in the Apple Home app. Seems like the cache is not working in case of an exception followed by homebridge restart.
Works well if I restart manually homebridge though.

Anyway, Is there a way to avoid a homebridge crash when this happen and just try again later ?

thanks !

**Comment by dubocr** [comment]
Hi,

Homebridge restarts on error should be improved in latest version.
Please update and reopen this issue if reappear.

Thanks
