### ISSUE TITLE
Shutter not place in "room"

### ISSUE THREAD

**Issue by chrisman59000** [dubocr/homebridge-tahoma#351]
In my TAHOMA, I placed all my shutters in their correct room. The name of the room are the same as the ones in my home (HomeKit).

Rooms are not saved in HomeKit. There is no link between rooms in TAHOMA and in HOMEKIT.

Each time I restart my homebridge, all the shutters are place in favorite et and a same room in HomeKit.

I s there a solution ? 

By the way I don't pullaway because it is always lost at a restart.

**Comment by chrisman59000** [comment]
Bonjour,
En Français, ce sera mieux :-) 
J'ai suivi le process mais en fait, je ne vois pas ce que je dois faire car dans les devices ne figurent pas le nom des pièces.
Je n'ai pas de problème de pilotage, ce qui se passe, c'est que les volets, capteurs et autres accessoires ne sont pas mis  dans leur "pièce" sur HomeKit.  Pourtant, dans ma TAHOMA, j'ai bien créé les pièces dans lesquelles j'ai placé mes volets.
Pour les autres accessoires comme mes détecteurs de fumée ou mes détecteurs d'ouvertures, TAHOMA ne propose pas des les affecter à une pièce.
De ce fait dès lors que je dois redémarrer mon homebrige (notamment après ajout ou motif. d'un plugin), tous les éléments perdent leur pièce d'affectation HomeKit. C'est comme si je n'avais rien fait et il faut recommencer à remettre les devices dans leur pièce correcte. HomeKit n'a pas gardé en mémoire ce qui avait été fait précédemment. Vu la quantité d'accessoires que j'ai, c'est ingérable (14 volets - 5 capteurs d'ouverture - 10 détecteurs incendie)

**Comment by dubocr** [comment]
Bonjour,

Il n'existe malheureusement pas de "synchronisation" entre les pièces TaHoma et celle d'Homekit via ce plugin (ou plus exactement via Homebridge). Néanmoins, une fois les pièces configurées dans HomeKit (et les devices positionnés dans chaque pièce) cette configuration est normalement conservée (même lors d'un redémarrage d'Homebridge).

Il est peut-être possible que les devices homebridge ne soit pas sauvegardés, utilises tu d'autres plugins et rencontre tu le même problème sur ces autres plugins ?

Normalement, homebridge utilise un répertoire sur le Raspberry pour stocker les informations des périphériques : https://github.com/homebridge/homebridge/issues/1614

**Comment by chrisman59000** [comment]
Bonjour,

Merci pour cette réponse. Je comprends bien. J'utilise d'autres plugin et je ne rencontre ce problème qu'avec le plugin TAHOMA. Je viens encore de vérifier. A priori, cela signifie donc que mes Devices SOMFY ne seraient pas sauvegardés par Homebridge. C'est d'autant plus dommage que j'en ai en nombre : volets RTS, détecteurs de fumée, détecteurs d'ouverture, caméra et alarme. Pour le COZYTOUCH en revanche, pas de problème, il a bien gardé en mémoire les pièces.
Je vais lire le lien pour voir.

Merci en tous les cas, c'est un super plugin
