### ISSUE TITLE
[Stateless][RollerShutter] Invalid target position after multiples executions

### ISSUE THREAD

**Issue by morkjt** [dubocr/homebridge-tahoma#353]
Hi,

I have identified a small issue with RollerShutter.js; I have four blinds all with a set movement duration that enables me to set a percentage target position in HomeKit and move the blinds approximately as per your implementation.  This has worked well since you put the functionality in, but at some point in the last 6 months, a problem has occurred and I've only just figured out what was happening.

If HomeKit sets a blind to 80% open, the plug in moves it to 80%.  If HomeKit sends a repeat of that instruction, the plug moves the blind again even though it is already at 80%.   The problem I found is I have multiple automation rules calling "scenes" with fixed % for each blind, and if a scene is called multiple times instead of finding my blinds at 80% they are 3/4 closed - as the scene was called 4 times.   In realty surely the plugin should realise that the currentPosition is 80%, the target position is 80% and do-nothing.

This seemed like a simple fix and I've given it a few tries, not really knowing enough about the plugin - every attempt I've made results in the blind moving to "unsupported mode".  Wondered if you could fix it?

**Comment by dubocr** [comment]
Normally, as the target position is known and maintained between execution, next one must take it into account.
Can you check that the HomeKit position is good after an execution and transmit your log.
You cas also follow #316.
