### ISSUE TITLE
Error 400 Too many asynchronous jobs

### ISSUE THREAD

**Issue by fox-on-tour** [dubocr/homebridge-tahoma#355]
There all,

i have several times the following error code in my Homebridge protocoll:
Error 400 Too many asynchronous jobs, try again later (job was Full refresh all states) (TOO_MANY_OPERATIONS_IN_PROGRESS)

- I use Hoobs in the newest version
- as well as this plugin in the newest version

This also happens when i want to execute a scenario with the result that the scenario doesn't execute.
When i restart the homebridge everything works well for a short time until the error pops up again.

**Comment by fox-on-tour** [comment]
Now I also got the following error after a couple of 400 errors:

HOOBSTaHomaWARNUNGAPI client will be locked for 6 hours because of bad credentials or temporary service outage. You can restart plugin to force login retry.

only rebooting of hoobs helped.
By the way the Tahoma box glowed red during that moment.

**Comment by bsoener** [comment]
Have already tried reboot. no success

**Comment by fox-on-tour** [comment]
Seems to work fine since a couple of days ago. It might be a problem wir the Somfy cloud?

**Comment by bsoener** [comment]
For me, it is always these two that cause problems.
```
Bad - setClosureAndLinearSpeed[0,"lowspeed"] - COMPLETED
Büro - setClosureAndLinearSpeed[0,"lowspeed"] - COMPLETED
Esszimmer - setClosureAndLinearSpeed[0,"lowspeed"] - COMPLETED
Küche - setClosureAndLinearSpeed[0,"lowspeed"] - COMPLETED
Wohnzimmer1 - setClosureAndLinearSpeed[0,"lowspeed"] - TIME_OUT_ON_COMMAND_PROGRESS
Wohnzimmer2 - setClosureAndLinearSpeed[0,"lowspeed"] - TIME_OUT_ON_COMMAND_PROGRESS 
```
