### ISSUE TITLE
Invalid Credentials Error

### ISSUE THREAD

**Issue by sprihar** [dubocr/homebridge-tahoma#357]
Hello,

Im trying to connect to this plugin for the first time and I am getting the below error, however the very same credentials work for me in the Somfy Tahoma NorthAmerica app. Are Tahoma users in NorthAmerica supported by this plugin? Is there any advice on how to get this setup to work? Thank you.

1/25/2022, 3:44:33 PMTahoma BridgeTaHomaWARNINGAPI client will be locked for 60 hours because of bad credentials or temporary service outage. You can restart plugin to force login retry.
1/25/2022, 3:44:33 PMTahoma BridgeTaHomaWARNINGAPI client will be locked for 60 hours because of bad credentials or temporary service outage. You can restart plugin to force login retry.
1/25/2022, 3:44:33 PMTahoma BridgeTaHomaERRORBad credentials
1/25/2022, 3:44:33 PMTahoma BridgeTaHomaERRORRetry in 60 sec...
1/25/2022, 3:44:33 PMTahoma BridgeWARNINGunhandled rejection: Bad credentials
1/25/2022, 3:45:35 PMTahoma BridgeTaHomaWARNINGAPI client will be locked for 240 hours because of bad credentials or temporary service outage. You can restart plugin to force login retry.
1/25/2022, 3:45:35 PMTahoma BridgeTaHomaERRORBad credentials
1/25/2022, 3:45:35 PMTahoma BridgeTaHomaERRORRetry in 120 sec...
1/25/2022, 3:47:35 PMTahoma BridgeTaHomaERRORAPI client locked. Please check your credentials then restart.
If your credentials are valid, please wait some hours to be unbanned
1/25/2022, 3:47:35 PMTahoma BridgeTaHomaERRORRetry in 240 sec.

**Comment by dubocr** [comment]
Hi,

North America endpoint was added in latest release 2.2.26.
You could connect by selecting Somfy North America service (or in JSON config `"service": "somfy_north_america"`).

**Comment by dubocr** [comment]
Thank you @PabloZaiden I see your PR (too late and with long delay).
