### ISSUE TITLE
[DynamicShutter] "Reverse" option not working

### ISSUE THREAD

**Issue by charliebird** [dubocr/homebridge-tahoma#359]
Hi,
I have a "Kit de connectivité" Somfy with 4 shutters connected. When I set them up in the app, only one was properly done (with Closing > Close and Opening > Open), the other 3 are inverted (I have to Open them to Close). Unfortunately there's no option to change that in the TaHoma app.
I've used the "reverse" parameter in HB for these 3 but that doesn't do anything.
Any idea why?

**Comment by davidXire** [comment]
Problème similaire, quand on couple avec une durée, option reverse ou non, « ouvert à 80% » ca ferme le volet de 80%

**Comment by dubocr** [comment]
Pouvez-vous vérifier dans l'historique de vos commandes [http://dev.duboc.pro/homebridge-tahoma](http://dev.duboc.pro/homebridge-tahoma) les commandes qui sont envoyées lors de l'utilisation avec l'app officielle puis avec HomeKit.

1. Executer les 4 commandes (2 avec l'app et 2 avec HomeKit) et notez les heures / l'ordre d'execution
2. Vous connecter http://dev.duboc.pro/homebridge-tahoma](http://dev.duboc.pro/homebridge-tahoma) puis cliquer sur `browse your config`
3. Sur la partie inférieure de la page (historique), déplier chaque execution pour consulter la commande

Merci.

**Comment by dubocr** [comment]
Est-ce mieux avec la dernière version 2.2.40 ?

Sur l'application officielle, rencontrez-vous des problème également ?
Je n'arrive pas à comprendre pourquoi sur 4 équipements identiques, 3 sur 4 réagissent différement.
