### ISSUE TITLE
Stop rolling Shutter

### ISSUE THREAD

**Issue by pelo76** [dubocr/homebridge-tahoma#361]
Hi,

I'm using a HomePod for steering my smart home - for the blinds I have a Tahoma Box. I can use the command "bathroom shutter 50%" to roll down the IO shutter/blind to my position.

A few month ago, I could use the command "bathroom stop shutter" to stop the blind in any position... This doesn't' work anymore... 

Is it possible to reactivate this function?

**Comment by pelo76** [comment]
SETUP-XXXX-XXXX-4549

**Comment by piejanssens** [comment]
@dubocr Could you add a dummy button for Somfy IO/RTS shutters/awnings to send the STOP command?
This would be optional and can be disabled per device. If enabled, the shutter has two buttons in HomeKit:
a shutter (the current one) and a Switch (that never turns on) to STOP the opening/closing motion.
