### ISSUE TITLE
[DynamicVenetianBlind] No such command setClosureAndOrientation 

### ISSUE THREAD

**Issue by MSCHNOBER** [dubocr/homebridge-tahoma#362]
Hello!

I'm using version 2.2.16 and my sun blinds ("SUNEA io") work perfectly fine 👌

However I can't control my venetian blinds ("My EVB Pro io") with homekit. Remote and official Tahoma App work fine.

![image](https://user-images.githubusercontent.com/101925296/159116158-4e5a2903-f86c-46a0-a6db-0312d2e4a5c9.png)

![image](https://user-images.githubusercontent.com/101925296/159116162-0dccdaa8-6dc0-44ea-93fa-88b6f1c0dd2b.png)

**Comment by MSCHNOBER** [comment]
Hmmm I'm a newbie but it seems like the "DynamicVenetianBlind" doesn't support the command "SetClosureAndOrientation". 

![image](https://user-images.githubusercontent.com/101925296/159117189-2411e318-af49-46e8-80e8-c8ece7f3828d.png)

**Comment by dubocr** [comment]
Hi @MSCHNOBER,

Sorry for this delay, I've no devices/gateway anymore and are less implied on this project.
This should be fixed in next release 2.2.23 which will be available until end of day.
