### ISSUE TITLE
RFX Shutter: Can the Tahoma bridge receive and report on commands send by the original remotes?

### ISSUE THREAD

**Issue by piejanssens** [dubocr/homebridge-tahoma#370]
I'm trying to find a solution to make my shutter report in the correct state.
Some people in the house use the remote to operate the rolling shutters and by doing so cause the rolling shutter state to be incorrect in the Home app.

Is there any way from the integration with Tahoma of the state through commands being send by other remotes?

**Comment by dubocr** [comment]
This must be managed by refreshing states. If your shutters are sending their states in real time, the value must be updated on HomeKit in the 30 secs.

You can enable Local API to refresh more frequently.

If your shutters don't send their state (eg, if state is not updated in TaHoma app without relaunching the app), there is nothing to do.
