### ISSUE TITLE
Sensor values not visible in Homekit

### ISSUE THREAD

**Issue by Zoltanvajt** [dubocr/homebridge-tahoma#371]
Hi,
Since yesterday 2022.06.22. The values of Somfy Sunis IO Wireless Light sensor (Fenyerzekelo) and Zigbee Temperature (24582/1#1) and Humidity sensor (24582/1#2) are not visible in Homekit. This week my Tahoma Switch received an FW ugrade (this enabled the Zigbee 3.0 devices to connect) not sure if this is related. Sorry Labels are in Hungarian.

So devices are sending values to Tahoma Switch and I can see this in the Tahoma App
![image](https://user-images.githubusercontent.com/101664429/175313991-d4d58078-cda0-481c-9f29-85a8be6c426e.png)

I have set-up the Thoma Plugin in Hoobs and devices are showing up is Hoobs and Homekit. I can see Values for the Zigbee temperature sensor and the Humidity (Light level did never show up here so thats not an issue)
![image](https://user-images.githubusercontent.com/101664429/175314824-abb4e323-a01d-4838-9aad-8082eefa00bb.png)

When I open the Homekit App I can see the devices but there are no values.
![image](https://user-images.githubusercontent.com/101664429/175315277-79c84245-21ab-4716-bac9-473a5b1b9c7c.png)
![image](https://user-images.githubusercontent.com/101664429/175315399-a63386c4-4214-4908-8ea8-1f914c786e1c.png)
This says "current light level" "Unknown"

![image](https://user-images.githubusercontent.com/101664429/175315503-138c876d-1e50-4b12-9b36-69ca4fe7b841.png)
![image](https://user-images.githubusercontent.com/101664429/175315530-05415d31-7c67-4c37-800c-fd640b7d105e.png)
Second photo says devices are updating, but they never get a velue.

Is this an issue maybe my config are not good?
Thanks,
Zoltan

**Comment by Zoltanvajt** [comment]
Any plans for the Local API Support?
thx

**Comment by OverSoft** [comment]
I don't know, it's not my project.
I hastily patched it at home (it's not a big change), but this is anything but production code.

**Comment by Zoltanvajt** [comment]
Any help you can send so i can do that maybe as well? Or contact to a project member?
Thx!

**Comment by OverSoft** [comment]
Not me, sorry. I've hacked together something that works for me real quick.
The reason I'm not forking this and releasing it myself is:
A) I generated a working token manually, this would be very hard to do for someone that doesn't have in depth knowledge of the Somfy API.
B) I don't want to handle housekeeping, development or support, sorry. I'm busy enough as is.

**Comment by gurtjun** [comment]
> Not me, sorry. I've hacked together something that works for me real quick.
> The reason I'm not forking this and releasing it myself is:
> A) I generated a working token manually, this would be very hard to do for someone that doesn't have in depth knowledge of the Somfy API.
> B) I don't want to handle housekeeping, development or support, sorry. I'm busy enough as is.

Hi! I was trying to tweak the plugin to be able to communicate with the local API.However I get some "socket hang up" errors. I also generated my token manually and I'm able to call the local API via curl or postman but no luck via homebridge. Is there no way you can share your "hacked" code?

**Comment by dubocr** [comment]
Hi guys,

Local API is currently in development. You can start to try it on latest plugin version 2.2.20.
You will have to: 
1. Activate `developer mode` ([somfy.com](https://www.somfy.com) > My Account > Activate developer mode) 
2. Generate API credentials at [https://dev.duboc.pro/homebridge-tahoma](https://dev.duboc.pro/homebridge-tahoma)
3. Select `Local API` service with gateway IP or PIN number as Username and previously generated token as Password

Tests are always in progress by users as I have no gateway anymore (TaHoma nor Cozytouch or other).

**Comment by Zoltanvajt** [comment]
Thanks for the update!
How can I get the latest plugin to my Hoobs?

**Comment by dubocr** [comment]
> Thanks for the update! How can I get the latest plugin to my Hoobs?
> […](#)

It's sometime longer than on Homebridge but the update must appear in plugin tab.

**Comment by Zoltanvajt** [comment]
OK will check! Thanks once again!

**Comment by Zoltanvajt** [comment]
Hi,
After downloded 2.2.21, I added "service": "local", to the config, but I
receive errors on Hoobs. User and PW were generated as advised before and
also dev mode is enabed on Tahoma Switch (just added different vlues here).
[image: image.png]

[image: image.png]

Am I missing something?

Regrads,
Zoltan

**Comment by dubocr** [comment]
Hi,

Images are not attached in mail reply. Could you please copy error or post image on GitHub.

Thanks

**Comment by Zoltanvajt** [comment]
Hi Romain,
It was my fault. Ugrade was not perfect. Now I fixed that and installed 2.2.22.

Plugin found my devices but I am getting such "Polling errors" and values still does not appear in homekit
![image](https://user-images.githubusercontent.com/101664429/188074364-af097696-81c3-4296-845c-f6a3c70359dc.png)

![image](https://user-images.githubusercontent.com/101664429/188074419-b96b3260-6e4c-4cda-9b2f-a52ec74d70cc.png)


Regrads,
Zoltan

**Comment by dubocr** [comment]
> Hi Romain, It was my fault. Ugrade was not perfect. Now I fixed that and installed 2.2.22.
> 
> Plugin found my devices but I am getting such "Polling errors" and values still does not appear in homekit ![image](https://user-images.githubusercontent.com/101664429/188074364-af097696-81c3-4296-845c-f6a3c70359dc.png)
> 
> ![image](https://user-images.githubusercontent.com/101664429/188074419-b96b3260-6e4c-4cda-9b2f-a52ec74d70cc.png)
> 
> Regrads, Zoltan

Try to add « .local » after your gateway pin as username : 2008-5424-6552.local
Or put the gateway ip adress instead.

**Comment by dubocr** [comment]
> > Hi Romain, It was my fault. Ugrade was not perfect. Now I fixed that and installed 2.2.22.
> > Plugin found my devices but I am getting such "Polling errors" and values still does not appear in homekit ![image](https://user-images.githubusercontent.com/101664429/188074364-af097696-81c3-4296-845c-f6a3c70359dc.png)
> > ![image](https://user-images.githubusercontent.com/101664429/188074419-b96b3260-6e4c-4cda-9b2f-a52ec74d70cc.png)
> > Regrads, Zoltan
> 
> Try to add « .local » after your gateway pin as username : 2008-5424-6552.local Or put the gateway ip adress instead.

Adding ".local" will not be necessary (nor acceptable) after release 2.2.23.
You will just need to set your gateway PIN as username, plugin will manage to resolve gateway IP with mDNS service. I'll be interested by your log feedback.

Thanks

**Comment by Zoltanvajt** [comment]
Hi Romain,
I can now connect to the box with either the .local and the local IP. Now the configuration of the first device connected to the Tahoma Switch fails "4-HaloErkelyAjto" is a Roller shutter.
![image](https://user-images.githubusercontent.com/101664429/188137713-5cb88806-d16a-40b8-9cde-9c6764e27e3e.png)

It was similar with a Zigbee Temperature/Humidity sensor earlier today (since that I disconnected that device), thats how not the roller sutter popped up.
![image](https://user-images.githubusercontent.com/101664429/188137834-82293c10-8b85-483d-88dc-24c085b2887e.png)

It looks like when the first device is there to cinfig there is an issue

Regards,
Zoltan

**Comment by dubocr** [comment]
Thanks for your feedbacks. Device definitions are reduced in local API.
I just release v2.2.24 it should fix that.

**Comment by dubocr** [comment]
Thank you @Zoltanvajt, regarding Local API, if any issues can you please continue on topic #367.
For your sensor values, can you please open a new `Device Integration` issue. It will let you selecting device to integrate.

Thank you.

**Comment by Zoltanvajt** [comment]
Thanks Romain! All devices with value issues added to the Device
Integration.
By the way, great portal created for this!
