### ISSUE TITLE
Status rollershutter in Homekit

### ISSUE THREAD

**Issue by Teclini** [dubocr/homebridge-tahoma#372]
For a few weeks now, the status of my RTS roller shutters has been displayed in homekit with is open. In homebride it seems correct. just not home kit.
![D42BAAA9-013D-4FAC-86C4-3C9E20E78BE4](https://user-images.githubusercontent.com/69106704/175801631-51ac6d19-72fb-4482-9672-75fcba5b96d4.jpeg)
![7E530053-D227-4ECD-ADFA-C96C53A40AF4](https://user-images.githubusercontent.com/69106704/175801633-2990be2d-cacb-45b9-bd1b-e3e0448b1de6.jpeg)

**Comment by Teclini** [comment]
xxxx-xxxx-5984

**Comment by tahomauser123** [comment]
@dubocr
First of all I would like to thank you for your work providing Homebridge TaHoma Plugin.

I have the same issue.
I have shutters from Somfy of type IO (not RTS). However all 16 of the show either in status closed or opening. They never reach the status Opened.

I am using Homebridge UI (homebridge-config-ui-x v4.50.1) and Homebridge TaHoma (homebridge-tahoma v2.2.18) on a Synology NAS with lastest operation system version (7.x).

Tahoma Plugin is running as own Homebridge.

Status in Homebridge on NAS is correct as mentioned by teclini.
However status in home kit is not correct - to be precise not correct only if you opend the shutter when closing status is correctly updated to closed.

In native Tahoma App it is working fine.

The configuration has already been reported XXXX-XXXX-4010

**Comment by dubocr** [comment]
Hi @tahomauser123 ,

Could you please use the config page to check the `core:ClosureState` and `core:TargetClosureState` value when your shutters are fully opened and fully closed.
It should be between 0 and 100 but the current value is 124.

@Teclini, your shutters seems to be IO not RTS. Can you confirm me ?

Thanks

**Comment by Teclini** [comment]
@tahomauser123 
I use an RTS Motor with A Somfy io Controller 
![8A526101-A521-4AAD-BB75-9F553F0CF457](https://user-images.githubusercontent.com/69106704/188263569-e13d0840-0f75-4494-85a1-a6c543639f0a.jpeg)

with Service restart i see this:

![F89C0526-DB49-40B9-8860-ED0AE1CC92BB](https://user-images.githubusercontent.com/69106704/188263695-94f9428b-7a08-49c8-8f10-de084af575ba.jpeg)

**Comment by dubocr** [comment]
Release 2.2.28 add evolution to PositionableRollerShutterUno. Could you please update and give feedback in issue #341 

Thank you.

**Comment by tahomauser123** [comment]
> @tahomauser123 I use an RTS Motor with A Somfy io Controller ![8A526101-A521-4AAD-BB75-9F553F0CF457](https://user-images.githubusercontent.com/69106704/188263569-e13d0840-0f75-4494-85a1-a6c543639f0a.jpeg)
> 
> with Service restart i see this:
> 
> ![F89C0526-DB49-40B9-8860-ED0AE1CC92BB](https://user-images.githubusercontent.com/69106704/188263695-94f9428b-7a08-49c8-8f10-de084af575ba.jpeg)

@Teclini: I am sorry. You are right. Some setup for me. I use also Somfy io Controller. Therefore I thought it is IO. Not very familiar with this technic.

**Comment by tahomauser123** [comment]
@dubocr: sorry for my late reply. I am on vacation currently. So I can not provide any feedback on your question. 
I will test it again with the new version and provide feedback.

Thank you very much for taking care of this issue so fast!!!

> Hi @tahomauser123 ,
> 
> Could you please use the config page to check the `core:ClosureState` and `core:TargetClosureState` value when your shutters are fully opened and fully closed. It should be between 0 and 100 but the current value is 124.
> 
> @Teclini, your shutters seems to be IO not RTS. Can you confirm me ?
> 
> Thanks

**Comment by tahomauser123** [comment]
@dubocr just updated yesterday und did some testing. Till now it seems to work fine. Shutters are opened completely now.
Thank you for your support.
