### ISSUE TITLE
Tahoma Homebridge Configuration

### ISSUE THREAD

**Issue by Jimbojingle** [dubocr/homebridge-tahoma#374]
Hi, I have just configured a Homebridge Server on a Raspberry Pi 4. I have installed your Tahoma plugin but have really no idea how to configure it. Is there a simple procedure that I can follow from beginning to end?

Thanks in advance.

**Comment by dubocr** [comment]
Hi,

If you are not familiar with homebridge configuration, you could install [homebridge UI ](https://github.com/oznu/homebridge-config-ui-x) or [Hoobs](https://hoobs.com).

The only other steps are :

1. Choosing the appropriate service `Somfy Europe (TaHoma)` in homebridge-tahoma config.
2. Set your username and password
