### ISSUE TITLE
Atlantic Lineo depuis fev 2021

### ISSUE THREAD

**Issue by Jeepmg** [dubocr/homebridge-tahoma#376]
Bonjour,

Les Appareils Lineo ont changé depuis fev 2021 en particulier leur gestion à distance. 

Ton plugin ne fonctionne pas avec ces nouveaux appareils.

La doc : https://www.atlantic.fr/gaatlanticerp/download/lineo-connecte-notice-simplifiee-2021-atlanticpdf

Peut on espérer une mise  à jour de ta part ? en particulier sur le mode absence.

Merci

**Comment by dubocr** [comment]
Bonjour,

Merci d'ouvrir une demande **Device integration and bug** [ici](https://github.com/dubocr/homebridge-tahoma/issues/new/choose) pour ce problème qui concerne la prise en charge des équipements.

Merci.

**Comment by Jeepmg** [comment]
Bonjour,

j'ai installé le plugin. Je vois mon Lineo dans Homebridge mais je ne parviens pas à l'intégrer à Homekit. J'ai tapé les 12 digits du setup mais il n'en veut pas.

Merci pour votre aide.
