### ISSUE TITLE
DynamicScreen / DynamicVenetianBlind

### ISSUE THREAD

**Issue by brennan247** [dubocr/homebridge-tahoma#378]
I'm aware of the limitations of RTS with HomeKit, but I was of the understanding that this plugin still exposed the devices nevertheless, is that correct?  I can see my RTS devices in HomeBridge, but not in the HomeKit app - please could you assist?  Many thanks

**Comment by brennan247** [comment]
0951

**Comment by dubocr** [comment]
Hi,

Seem other user has your kind of device : #362 
You device `Bedroom Blinds` should be visible in HomeKit. Does your homebridge bridge well linked to HomeKit ?
