### ISSUE TITLE
Tahoma + Alarme somfy

### ISSUE THREAD

**Issue by MXCZK** [dubocr/homebridge-tahoma#379]
Bonjour,

J'ai installé le plugin et dans homebridge, je vois deux badges : virtual alarm et alarm.

Savez-vous à quoi cela correspond svp ?

Merci

**Comment by dubocr** [comment]
Bonjour,

Certain modèles d'alarme remontent plusieurs objets qui ne sont pas toujours utiles. Si l'un d'eux ne semble servir à rien, vous pouvez le masquer dans la configuration (soit par ajout du nom, du type ou de l'identifiant unique).

Utiliser `"exclude" : ["Nom du badge inutile"]` dans la config.
