### ISSUE TITLE
[Volet] Implémentation du retour d'erreur "ObstructionDetected"

### ISSUE THREAD

**Issue by lboue** [dubocr/homebridge-tahoma#38]
Bonjour,

Je rencontre assez souvent le cas de mon volet qui se bloque lorsque la fenêtre Velux est ouverte entièrement.
J'aimerais être averti dans Homebridge comme c'est le cas si je lance l'application Connexoon. Il faut ouvrir l'application pour remarquer l'erreur, ce n'est pas pratique.

Voici ce que retourne l'API Tahoma au moment du blocage :

```
[{
	"execution": {
		"eventTime": 1530354922928,
		"owner": "user@domain.com",
		"source": "mobile:connexoon",
		"endTime": 1530354937044,
		"effectiveStartTime": 1530354922928,
		"duration": 14116,
		"id": "5042f5ae-2e69-7448-5ca5-6448a99715f8",
		"label": "Volet Velux - Fermer - user",
		"executionType": "Immediate execution",
		"executionSubType": "MANUAL_CONTROL",
		"type": "Immediate execution - MANUAL_CONTROL",
		"failureType": "WHILEEXEC_BLOCKED_BY_HAZARD",
		"state": "FAILED",
		"commands": [{
			"deviceURL": "io://0808-0476-7160/12852936",
			"command": "close",
			"parameters": [],
			"rank": 0,
			"dynamic": false,
			"failureType": "WHILEEXEC_BLOCKED_BY_HAZARD",
			"state": "FAILED"
		}]
	}
```

1) On remarque qu'une erreur est bien retournée **"failureType": "WHILEEXEC_BLOCKED_BY_HAZARD"**,
2) J'ai trouvé un moyen de lever des erreurs dans HomeKit et générer une alerte avec la Characteristic ObstructionDetected : 
> HMCharacteristicTypeObstructionDetected
> Indicates whether the accessory has detected an obstruction—for example, an automatic garage door opener may have the ability to tell if something is blocking the door. The value is a boolean indicating whether an obstruction was detected.

J'ai fait un [premier test ](https://github.com/lboue/homebridge-tahoma/commit/b02fb2e2b74d2728e81016ffe3041e0e9d22668a
)en publiant le service et cela apparaît dans HomeKit
![obstructiondetectedservice](https://user-images.githubusercontent.com/938089/42080290-7659cf0a-7b82-11e8-980e-55d6ad684cc6.jpg)

Voici un exemple 
```
volet
        .getService(Service.WindowCovering)
        .setCharacteristic(Characteristic.ObstructionDetected, true);
```

Serait-il possible de vérifier le retour de l'API et lever une alerte ?

Cordialement
Ludovic

**Comment by dubocr** [comment]
Salut,

[Awning.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2152905/Awning.js.zip)
Peux-tu essayer le fichier suivant. J'ai ajouté la caractéristique pour les volets non RTS et update le status à la fin de l'execution en fonction de l'erreur.

**Comment by lboue** [comment]
Bonjour,

Merci d'avoir pris le temps de me répondre. 
Je viens de faire un test et j'ai bien l'erreur remontée par la console qui apparait désormais;

```
[2018-7-1 23:09:59] [Connexoon] [Volet Velux] setClosure[29]
[2018-7-1 23:10:16] [Connexoon] [Volet Velux] setClosure COMPLETED
[2018-7-1 23:10:25] [Connexoon] [Volet Velux] setClosure[98]
[2018-7-1 23:10:28] [Connexoon] [Volet Velux] setClosure[100]
[2018-7-1 23:10:30] [Connexoon] [Volet Velux] setClosure CMDCANCELLED
[2018-7-1 23:11:02] [Connexoon] [Volet Velux] setClosure WHILEEXEC_BLOCKED_BY_HAZARD
```

Par contre pas d'erreur signalée dans HomeBridge
`this.obstruction = service.addCharacteristic(Characteristic.ObstructionDetected);
 `
Ludovic

**Comment by lboue** [comment]
En fait on ne passe pas le test **if(this.obtruction != null)**. J'ai donc essayé de le mettre plus haut pour voir : 
```
case ExecutionState.FAILED:
	that.positionState.updateValue(Characteristic.PositionState.STOPPED);
	that.targetPosition.updateValue(that.currentPosition.value); // Update target position in case of cancellation
	that.log.info('Before');
	this.obtruction.updateValue(error == 'WHILEEXEC_BLOCKED_BY_HAZARD');
	if(this.obtruction != null) {
		this.obtruction.updateValue(error == 'WHILEEXEC_BLOCKED_BY_HAZARD');
		//this.obtruction.service.setCharacteristic(Characteristic.ObstructionDetected, true);
		that.log.info('this.obtruction != null');
		this.getService(Service.WindowCovering).setCharacteristic(Characteristic.ObstructionDetected, Characteristic.ObstructionDetected.YES)
	}
```
Et j’obtiens cette erreur : 
```
[2018-7-1 23:44:40] [Connexoon] [Volet Velux] setClosure[100]
[2018-7-1 23:44:40] [Connexoon] [Volet Velux] setClosure INITIALIZED
[2018-7-1 23:44:40] [Connexoon] Register listener
[2018-7-1 23:44:41] [Connexoon] [Volet Velux] setClosure IN_PROGRESS
[2018-7-1 23:44:53] [Connexoon] [Volet Velux] setClosure WHILEEXEC_BLOCKED_BY_HAZARD
[2018-7-1 23:44:53] [Connexoon] Before
/usr/lib/node_modules/homebridge-tahoma/accessories/Awning.js:78
                                        this.obtruction.updateValue(error == 'WHILEEXEC_BLOCKED_BY_HAZARD');
                                                        ^

TypeError: Cannot read property 'updateValue' of undefined
    at /usr/lib/node_modules/homebridge-tahoma/accessories/Awning.js:78:22
    at /usr/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:113:5
    at pollingtoevent.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:104:21)
    at pollingtoevent.emit (events.js:182:13)
    at done (/usr/lib/node_modules/homebridge-tahoma/node_modules/polling-to-event/index.js:63:20)
    at /usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:86:14
    at Request.authCallback [as _callback] (/usr/lib/node_modules/homebridge-tahoma/overkiz-api.js:207:17)
    at Request.self.callback (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1157:10)
```
Il faudrait peut etre quelque chose du style 
`that.getService(Service.WindowCovering).setCharacteristic(Characteristic.ObstructionDetected, Characteristic.ObstructionDetected.YES)`

Mais j'obtiens ça : 
`TypeError: that.getService is not a function`

Ludovic

**Comment by lboue** [comment]
J'ai fait un[ commit sur mon repo](https://github.com/lboue/homebridge-tahoma/commit/9af97e0a4d6fd00e939dc6f1c3408fdd1063f11f#diff-9dff61d63477f831060348b6c649501cR44) pour montrer qu'en forçant au tout début (ligne 44) avec la commande suivante l'alerte apparait bien dans HomeKit: 
`this.getService(Service.WindowCovering).setCharacteristic(Characteristic.ObstructionDetected, Characteristic.ObstructionDetected.YES)`

Je ne sais pas comment faire la même chose depuis la méthode setClosure.

**Comment by dubocr** [comment]
Peux-tu déjà remplacer le bloc par 
```
if(that.obtruction != null) {
    that.obtruction.updateValue(error == 'WHILEEXEC_BLOCKED_BY_HAZARD');
}
```

**Comment by lboue** [comment]
Par contre si je comprend bien ça veut dire que tout les cas d'erreurs (case ExecutionState.FAILED), cette alerte va être levée ?

**Comment by lboue** [comment]
J'ai également l'impression qu'au polling suivant de l'API (device states refresh), l'alarme est effacée.

**Comment by dubocr** [comment]
Non l'alerte sera levée si l'execution échoue et si le retour de l'API est`error == 'WHILEEXEC_BLOCKED_BY_HAZARD'`
La valeur n'est normalement réinitialisée qu'à la prochaine commande envoyée au volet et correctement exécutée ou au redémarrage d'homebridge.

**Comment by lboue** [comment]
Effectivement je pensais que c'était la valeur à écrire lors de l'update alors qu'`error == 'WHILEEXEC_BLOCKED_BY_HAZARD_'` est un test. J'avais mal compris :-)
