### ISSUE TITLE
Error 401 Bad credentials (AUTHENTICATION_ERROR)

### ISSUE THREAD

**Issue by thierrydesixfours** [dubocr/homebridge-tahoma#381]
Bonjour,

depuis quelques temps, j'obtiens une erreur au login. Ma box est une Rexel

en vérifiant -> https://dev.duboc.pro/homebridge-tahoma c'est l'erreur 401 qui m'est retournée.

Je ne trouve pas la cause de mon soucis ! ?

Merci pour votre aide

**Comment by dubocr** [comment]
Bonjour,

Malheureusement Rexel a mis en place une authentification déportée (authentification sur leurs infrastructures permettant ensuite de se connecter sur les serveurs applicatifs d'Overkiz).
Et je n'ai pas connaissance du serveur d'authentification ni des clés.

Problèmes remonté ici : #344 et [#591](https://github.com/iMicknl/ha-tahoma/issues/591)
