### ISSUE TITLE
Garage / Portail

### ISSUE THREAD

**Issue by pwnz0r69** [dubocr/homebridge-tahoma#383]
Bonjour.

Tout d'abord merci pour votre plugin.

Pouvez vous m'indiquez ce que je dois régler car mon portail ainsi que ma porte de garage Somfy RTS sont toujours avec un affichage "ouverture en cours" ou "fermeture en cours".

Cordialement

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous passer par [cette page](https://dev.duboc.pro/homebridge-tahoma) pour ouvrir une demande plus complète qui permettra d'analyser.

Merci.
