### ISSUE TITLE
[DynamicGarageDoor]

### ISSUE THREAD

**Issue by pwnz0r69** [dubocr/homebridge-tahoma#385]
Gateway: 9145
Device: GarageDoor > DynamicGarageDoor

Bonjour Monsieur.

Comme dis précédemment, j'arrive a contrôler mon portail ainsi que ma porte de garage en ouverture et fermeture. Ce sont 2 appareils Somfy RTS.
Par contre Homekit m'affiche tjrs une information Ouverture en cours ou Fermeture en cours. Comme si il était toujours entrain d'ouvrir ou de fermer le portail ou la porte de garage. L'information est aussi présente sur Homebridge.

J'utilise un kit de connectivité Somfy et l'application Tahoma ainsi que votre votre plug in dans Homebridge.

Merci d'avance de votre aide.

Bien Cordialement

![image](https://user-images.githubusercontent.com/107087151/188334379-70d8f6fe-a7db-4e44-a153-afcf920a936d.png)

**Comment by dubocr** [comment]
Bonjour,

Merci pour ces informations. En effet votre équipement comporte des _états_ mais non utiles.
Ce qui le faisait passer dans la catégorie des équipements _avec état_ qui attend alors un changement d'état.

J'ai mis en place un correctif. Vous pouvez mettre à jour le plugin ce qui devrait corriger le problème.

Merci.

**Comment by pwnz0r69** [comment]
Merci pour la modification. C'est parfaitement fonctionnel maintenant.
