### ISSUE TITLE
Document how the "local" API integration is authenticated

### ISSUE THREAD

**Issue by WTell** [dubocr/homebridge-tahoma#388]
Hi devs,

Thanks for putting in the time and effort to maintain this library!

Consider updating the _Configuration_ section of README.md to indicate that when using `"service" : "local"`, `user` and `password` should be set to the gateway IP and the access token, respectively.

Thanks!

**Comment by dubocr** [comment]
Hi,

There is a full section for Local API 

### (*) Local API configuration
Local API service is available on TaHoma and TaHoma switch gateways.

To use Local API you will have to:
1. Activate `developer mode` ([www.somfy.com](https://www.somfy.com) > My Account > Activate developer mode) 
2. Generate API credentials at [https://dev.duboc.pro/homebridge-tahoma](https://dev.duboc.pro/homebridge-tahoma)

For more information, browse [https://developer.somfy.com/developer-mode](https://developer.somfy.com/developer-mode)

I'll add some link to force people read it.

Thks

**Comment by WTell** [comment]
Hi,

Thanks for the feedback. Yes, I saw the mentioned part of the documentation – my point is that this part of the documentation should mention that user = IP and password = token.

Cheers!
