### ISSUE TITLE
[Information] Official Homekit with Tahoma

### ISSUE THREAD

**Issue by fafoulon** [dubocr/homebridge-tahoma#39]
Bonne nouvelle,

ils parlent de Homekit pour mi-2018
https://service.somfy.com/downloads/fr_v4/somfy-cp_ces2018.pdf

**Comment by lboue** [comment]
Suivant les pages,  l'information n'est pas la même 
[Ici ](https://www.somfy.fr/produits/domotique/maison-connectee-tahoma
)
> Avec TaHoma, pilotez vos équipements Somfy** et créez vos scénarios depuis l'application Home d'Apple.
> 
> Par exemple, éteignez la lumière, activez votre caméra, verrouillez vos portes et réglez le thermostat sur éco en un seul clic.
> 
> * Toute la gamme Somfy Protect, excepté Home Alarm.
> 
> ** Produits IO (protections de fenêtre, portails, terrasse, auvents et pergolas, prises et lumières, capteurs). Liste indicative. 
> 
> **Disponibilité : second semestre 2018**

Et plus de précision [ici](https://www.somfy.fr/produits/domotique/upgrade-tahoma). C'est seulement pour la V2 : 
> Les box de première génération bénéficieront des mises à jour sur un périmètre restreint uniquement :
> - Les actions correctives (corrections de bug, maintenance…) seront intégrées.
> - Les nouvelles compatibilités Somfy et partenaires existants (Atlantic, Philips hue, Sonos…) seront intégrées jusqu’à la fin de l’année 2018.
> 
> - **Les nouveaux partenaires (Legrand, HomeKit…) ne seront pas intégrés.**

**Comment by fafoulon** [comment]
Merci pour les précisions! ;-)
