### ISSUE TITLE
Cozytouch - Can't get current temperature, occupancy, opening sensors values

### ISSUE THREAD

**Issue by JTex92** [dubocr/homebridge-tahoma#390]
Congratulations for your plugin which would be very useful for me!
I integrated 3 Atlantic radiators successfully, however I can't get current temperature, occupancy & opening sensors values.
It looks like information is going only in one way: Home application to radiators but not radiators to Home app.
Thank for your help.

**Comment by dubocr** [comment]
Hi,

As you request concerns devices, please open **Device integration or bug** [here](https://github.com/dubocr/homebridge-tahoma/issues/new/choose)

Thank you.
