### ISSUE TITLE
[AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint]

### ISSUE THREAD

**Issue by JTex92** [dubocr/homebridge-tahoma#392]
***Gateway:*** 6473
***Device:*** HeatingSystem > AtlanticElectricalHeaterWithAdjustableTemperatureSetpoint

***States***
**Consigne à 19°c** 
core:TargetTemperatureState=19.0

Dans l'application Cozytouch
![image](https://user-images.githubusercontent.com/113131925/189409417-1de7d998-ceb0-40b4-9225-d70225693f49.png)

Dans HomeBridge
<img width="514" alt="image" src="https://user-images.githubusercontent.com/113131925/189409734-7162fb28-2116-4878-8cf8-b9e30da6ea35.png">

Dans HomeKit
![image](https://user-images.githubusercontent.com/113131925/189410489-200a94fc-b97a-4248-b09f-ea55f8c21cb3.png)

**Comment by JTex92** [comment]
Je peux commander mon radiateur depuis HomeBridge / HomeKit mais les modifications faites dans l'appli Cozytouch n'impactent pas HomeBridge / HomeKit.
La température effective ne remonte pas non plus dans HomeBridge / HomeKit.

**Comment by dubocr** [comment]
Bonjour,

Quelle est votre version du plugin ?
Sur la config transmise, les chauffages sont à l'arrêt ce qui n'est pas le cas sur la copie d'écran de l'appli cozytouch. Est-ce qu'ils venaient d'être mis en route ?

**Comment by JTex92** [comment]
Bonjour,
Je viens de les allumer.
J'ai fait la mise à jour du plugin il y a quelques minutes, ça a l'air de fonctionner maintenant.
Mes trois radiateurs se mettent à jours dans HomeBridge & HomeKit.
Merci pour votre réactivité !
Je vais analyser un peu plus en détail le comportement dans HomeKit et vous fais un retour au plus tôt.

**Comment by JTex92** [comment]
Bonjour Romain,
Je vous confirme que tout fonctionne parfaitement bien depuis la mise à jour. L'ensemble des radiateurs et capteurs remontent leurs informations dans HomeKit.
Merci beaucoup pour ce plugin qui me sera vraiment super utile pour piloter au mieux mon chauffage.
N'hésitez pas à me solliciter si vous avez besoin de retour sur l'utilisation du plugin ou pour tester de nouvelles versions.
Bonne journée à vous.
