### ISSUE TITLE
[UpDownHorizontalAwning] Reverse not working for RTS device

### ISSUE THREAD

**Issue by underbarnet2** [dubocr/homebridge-tahoma#394]
I'm using a Tahoma Switch with 2 IO rolling shutters and 6 RTS blinds, curtains and awnings.

I am having an issue with one of the devices, an older RTS Somfy motorized awning where the open and close states are reversed.

For the IO devices, the reverse function in the device config works, however not for the RTS devices, luckily all RTS devices are showing up correctly regarding open / closed except for the awning. 

For some reason the device config I do (engaging reverse mode) doesn't stick. I've tried removing and re-adding the awning on the Tahoma App, renaming it, rebooting the hoobs box, my iPhone, my Apple Tv, I've also tried clearing the whole cache in the bridge, and the cache in the plug in, I've tried removing the awning from the bridge, and uninstalling the plug-in and reinstalling. 

I'm getting the sense that the plug-in isn't registering the device config against the correct hardware, even if the names are identical. I've checked so the names are identical across: Tahoma App, Homebridge Device list, Log, and Homekit app on iPhone but still no dice. The name is: "Terrass"

I'm running hoobs version 4.2.8  and the latest plug in version.

I've completely run out of ideas and this is driving me nuts. Any help would be much appreciated.

Thanks

**Comment by dubocr** [comment]
Hi,

Could you please submit your config there [https://dev.duboc.pro/homebridge-tahoma](https://dev.duboc.pro/homebridge-tahoma)

Thank you.

**Comment by dubocr** [comment]
You can try to update the plugin it should improve.
