### ISSUE TITLE
[LuminanceSensor] Somfy Sunis io Luminance sensor shows 0 Lux in HomeKit, values should be between 50-100K Lux

### ISSUE THREAD

**Issue by Zoltanvajt** [dubocr/homebridge-tahoma#398]
***Gateway:*** 6551
***Device:*** LightSensor > LuminanceSensor

***States***
**advancedRefresh**
![image0](https://user-images.githubusercontent.com/101664429/190847460-b26c5713-2f7f-406a-afb7-cde92bd8a798.png)
![image1](https://user-images.githubusercontent.com/101664429/190847466-cb68192f-aef7-4f78-be83-205503e54281.png)

**Comment by Zoltanvajt** [comment]
Product page on Somfy UK site
https://www.somfy.co.uk/products/2401219/sunis-sun-sensor-io

**Comment by Zoltanvajt** [comment]
Command to get LUX values 
**core:LuminanceState 5193**

**Comment by dubocr** [comment]
I think you could be on an old plugin version (<2.2.38).
Please check you plugin version to make sure you are running 2.2.41.

Thank you.

**Comment by Zoltanvajt** [comment]
Hi,
Trying to update from 2.2.37 to 2.2.42 but I always got the follwing warning "Plugin site unavailable"
![image](https://user-images.githubusercontent.com/101664429/190996225-23f7ede0-3107-4324-a3dd-149d99586cc7.png)

**Comment by dubocr** [comment]
You should retry (now or later) as it seem your DNS fails to resolve yarnpkg wesite.

**Comment by Zoltanvajt** [comment]
Managed to update the plugin to the latest version. All values are fine! Issue can be closed. Thank you Romain for the updates!
