### ISSUE TITLE
[TemperatureSensor] Zigbee device shows 0 celsius in Homekit 

### ISSUE THREAD

**Issue by Zoltanvajt** [dubocr/homebridge-tahoma#399]
***Gateway:*** 6551
***Device:*** TemperatureSensor > TemperatureSensor

***States***
**advancedRefresh **

https://sonoff.tech/product/smart-home-security/snzb-02/

![image](https://user-images.githubusercontent.com/101664429/190847865-287a7163-f7c3-4f01-8202-233852f74f1d.png)
![image](https://user-images.githubusercontent.com/101664429/190847871-360ba66e-c53b-42ec-83a3-0c4d7ae795ae.png)

**Comment by Zoltanvajt** [comment]
This device is also a Humidity sensor that also shows 0% in Homekit, tested with same command
![image](https://user-images.githubusercontent.com/101664429/190847944-02a775e1-aa4b-423a-8705-6ef4b84eaca6.png)
![image](https://user-images.githubusercontent.com/101664429/190847948-52245513-2580-46ef-bde0-539daef14155.png)

**Comment by Zoltanvajt** [comment]
Values with states
Temperature: core:TemperatureState 23,27
Humidity: core:RelativeHumidityState 66,03

**Comment by dubocr** [comment]
Hi,

What is you homebridge-tahoma plugin version ?
Could you please upgrade and test again.

Thank you.
