### ISSUE TITLE
Fenêtres de toit Velux et Stores SOMFY - RTS not showing

### ISSUE THREAD

**Issue by LaurentCole** [dubocr/homebridge-tahoma#4]
Hi Romain
I guess you speak french so it would be easier to communicate but the problem is I have 2 roof windows registered with rts and 3 rollers still registered in rts in my Tahoma box and they don't appear.
Any help would be greatly appreciated.

Thx

Laurent
![capture d ecran 2017-05-12 a 17 13 39](https://cloud.githubusercontent.com/assets/28627515/26004514/6c692a90-3736-11e7-8219-31ec86c0c270.png)

**Comment by gregmoseley** [comment]
Same problems here. 11 devices (7 Somfy Window blinds and 4 Velux) and get 11 Device Screen Ignored errors on startup and no sign of the devices in Homebridge. Scenarios do appear but would rather use Homekit to create these as they only appear as switches.

**Comment by LaurentCole** [comment]
Checked again and windows are Velux io protocol. 
Any chance you could Write something and make them work. 
Idem with Somfy RTS protocol. 
Thanks anyway for what you' be already done.

**Comment by dubocr** [comment]
Hi Guys,

Could you please browse http://home.dubocr.fr/tools/setup this will send me your device configuration to implement missing devices.
Concerning Scenarios, unfortunately homebridge don't support HomeKit scene so exposing them as on/off switches is the best solution we found.

Thanks

**Comment by dubocr** [comment]
Hi,

Can you try this file (copy this js file in /usr/lib/node_modules/homebridge-tahoma/accessories/)[Screen.js.zip](https://github.com/dubocr/homebridge-tahoma/files/999520/Screen.js.zip).
Laurent, j'attends votre config pour pouvoir implémenter les devices de type 'window'

**Comment by LaurentCole** [comment]
Bonjour,
je vous ai fait parvenir ma configuration Tahoma.
Je vais tester votre script.

Merci pour votre aide.

**Comment by LaurentCole** [comment]
Pour les stores, c'est bien mieux. Ils apparaissent dans Maison et fonctionnent en ouverture et fermeture totale. Je ne peux pas régler le % d'ouverture ou fermeture en revanche.
Merci pour cette avancée déjà.

**Comment by dubocr** [comment]
Voici le fichier pour les devices 'Window'.
[Window.js.zip](https://github.com/dubocr/homebridge-tahoma/files/999625/Window.js.zip)

Concernant vos stores, il n'est pas possible de régler le % sur les périphériques sans retour d'état (RTS). Sur ces produit, définir un réglage intermédiaire (quelque soit celui-ci) place le store en position 'my'.

**Comment by LaurentCole** [comment]
C'est parfait pour les Velux.
Pour les stores, n'y a-t-il pas moyen de par exemple lancer l'ouverture et ensuite appuyer sur le bouton d'activation pour arrêter le store quand on veut. C'est possible avec l'application Tahoma en appuyant sur "Stop".
J'y connais rien mais je demande tout de même.
En tout cas ce que vous avez fait me facilite déjà grandement la gestion de mes accessoires en regroupant tout dans "Maison".
Merci infiniment.

**Comment by gregmoseley** [comment]
Hi,
We have copied screen.js.zip and this have now exposed all the Blinds individually.
The Velux Blinds work a treat (even returning the correct position after a restart of homebridge) but the somfy Blinds are still having a problem.
The grouped Blinds within Tahoma don't work at all, and the individual Blinds don't return the correct current position, also I can't group either the Velux or Somfy Blinds??
Loving the work though, please let me know where I can make a donation.
Thanks, Greg

**Comment by dubocr** [comment]
@LaurentCole techniquement il serait possible d'arrêter le mouvement mais l'interface Home ne permet que l'ouverture/fermeture. Rappuyer sur le bouton provoque le mouvement inverse. Sur TaHoma le bouton "Stop" est-il affiché en permanence ou apparait-il après avoir enclenché le mouvement ? Dans le second cas, disparait-il après ?

@gregmoseley grouped devices in TaHoma can't be programatically exposed in HomeKit. You have to use HomeKit groups or create scene but not sure Home or HomeKit allows grouping blinds at the moment (for me only lights can be grouped in Home). Velux and Somfy Blinds are same kind of device in HomeKit so behavior is the same and is dependent of HomeKit.
I'm not expecting donation for this work but feel free to donate another of my [project](http://www.change4time.org/nous-soutenir/) or another non lucrative organisation.

Romain

**Comment by LaurentCole** [comment]
En effet, le bouton "stop" apparait une fois l'action lancée et disparait ensuite.

**Comment by LaurentCole** [comment]
Greg, you can make a group with Velux windows. 
That's what I did with two of them.

**Comment by gregmoseley** [comment]
@LaurentCole The option to group Velux for me isn't there? I can group lights ok though? 

@dubocr ok thanks, I'll keep playing with the window blinds to work out where I'm going wrong.

**Comment by LaurentCole** [comment]
Within 'Home' you can make a scene and group your Windows. I managed that way.

**Comment by dubocr** [comment]
You can group using 'Eve' app but Home will not merge. Maybe we can expect good behavior in future Home release.
Your Blinds are RTS components so don't reports their position. Every Homebridge restart will loose it.

**Comment by dubocr** [comment]
Grouping blinds is now supported by Home in iOS 11.

**Comment by Prohability** [comment]
I’m having some issues on the similar topic. My 3 somfy protocoll devices works great, but I can’t seem to get homebridge to find my outdoor awnings (RTS in somfy), Any idea what to do?

**Comment by dubocr** [comment]
Hi,

Can you browse this page and log with your Tahoma credential to let me know your config as I can see what kind of devices you have.

Thanks.

**Comment by Prohability** [comment]
Hi!

Config bellow:
Devices
2 Screen > PositionableTiltedScreen
<http://home.dubocr.fr/tools/setup#8d0fe6f1c8d9849c414f056bb6062078>
Devices click on a device to display current statesPersienn II Persienner

States Persienner

   - core:ClosureState 0
   - core:Memorized1PositionState
   - core:NameState Persienner
   - core:OpenClosedState (closed,open) open
   - core:PriorityLockTimerState 0
   - core:RSSILevelState 84
   - core:SecuredPositionState
   - core:StatusState (available,unavailable) available
   - io:PriorityLockLevelState
   (comfortLevel1,comfortLevel2,comfortLevel3,comfortLevel4,environmentProtection,humanProtection,userLevel1,userLevel2)
   - io:PriorityLockOriginatorState
   (LSC,SAAC,SFC,UPS,externalGateway,localUser,myself,rain,security,timer,user,wind)

Commands

   - close
   - delayedStopIdentify + 1 parameter
   - down
   - getName
   - identify
   - my
   - open
   - refreshMemorized1Position
   - setClosure + 1 parameter
   - setMemorized1Position + 1 parameter
   - setName + 1 parameter
   - setPosition + 1 parameter
   - setSecuredPosition + 1 parameter
   - startIdentify
   - stopIdentify
   - up
   - wink + 1 parameter

1 Alarm > TSKAlarmController
<http://home.dubocr.fr/tools/setup#a87f482473105c71b73653cf9faf623a>
Devices click on a device to display current statesAlarm

States Alarm

   - core:NameState alarm name
   - internal:AlarmDelayState 60
   - internal:CurrentAlarmModeState (off,partial1,partial2,total) off
   - internal:IntrusionDetectedState (detected,notDetected,pending,sos)
   notDetected
   - internal:TargetAlarmModeState (off,partial1,partial2,sos,total) off

Commands

   - alarmOff
   - alarmOn
   - getName
   - off
   - on
   - setName + 1 parameter
   - refreshAlarmDelay
   - refreshCurrentAlarmMode
   - refreshIntrusionDetected
   - setAlarmDelay + 1 parameter
   - alarmPartial1
   - alarmPartial2
   - setIntrusionDetected + 1 parameter
   - setTargetAlarmMode + 1 parameter

1 Window > PositionableTiltedWindow
<http://home.dubocr.fr/tools/setup#ee16eba64a276d0c60f79193fbd8ee37>
Devices click on a device to display current statesTakfönster

States Takfönster

   - core:ClosureState 100
   - core:NameState Takfönster
   - core:OpenClosedState (closed,open) closed
   - core:PriorityLockTimerState 0
   - core:RSSILevelState 96
   - core:StatusState (available,unavailable) available
   - io:PriorityLockLevelState
   (comfortLevel1,comfortLevel2,comfortLevel3,comfortLevel4,environmentProtection,humanProtection,userLevel1,userLevel2)
   - io:PriorityLockOriginatorState
   (LSC,SAAC,SFC,UPS,externalGateway,localUser,myself,rain,security,timer,user,wind)

Commands

   - close
   - delayedStopIdentify + 1 parameter
   - getName
   - identify
   - open
   - setClosure + 1 parameter
   - setName + 1 parameter
   - startIdentify
   - stopIdentify
   - wink + 1 parameter

1 VenetianBlind > UpDownVenetianBlind
<http://home.dubocr.fr/tools/setup#8615ed8e3e09a1e525f31c423f3e649d>
Devices click on a device to display current statesMarkis

Commands

   - close
   - down
   - identify
   - my
   - open
   - rest
   - stop
   - test
   - up
   - moveOf + 1 parameter
   - tiltNegative + 2 parameter
   - tiltPositive + 2 parameter


Scenes
2 Ljus <http://home.dubocr.fr/tools/setup#cb80fc12e9064cdef1a52bfc5203bf41>

   - io://0204-8929-0974/8093007 open
   - io://0204-8929-0974/2201193 open

2 Mörkläggning
<http://home.dubocr.fr/tools/setup#3edad9653696b7db0210541064349c94>

   - io://0204-8929-0974/8093007 close
   - io://0204-8929-0974/2201193 close


History
undefined Persienn II <http://home.dubocr.fr/tools/setup#1506664916573>

   - setPosition 0

undefined Persienner <http://home.dubocr.fr/tools/setup#1506664895061>

   - setPosition 0

undefined Persienner <http://home.dubocr.fr/tools/setup#1506633436769>

   - setPosition 100

undefined Persienn II <http://home.dubocr.fr/tools/setup#1506633435764>

   - setPosition 100

undefined Takfönster <http://home.dubocr.fr/tools/setup#1506632361940>

   - setClosure 100


Best regards

2017-09-30 11:10 GMT+02:00 Romain DUBOC <notifications@github.com>:

**Comment by dubocr** [comment]
You can try to copy (after extract) this file in the 'accessories' folder of the plugin.
[VenetianBlind.js.zip](https://github.com/dubocr/homebridge-tahoma/files/1346389/VenetianBlind.js.zip)

**Comment by Prohability** [comment]
Thanks so much for your help, your script got it to be recognized. Only
minor issue is that the icon/switch in homekit is always at 50% and there
seems to be the other way around with opening and closing, any idea what
could be done to mitigate that?


2017-09-30 14:23 GMT+02:00 Romain DUBOC <notifications@github.com>:

**Comment by dubocr** [comment]
[VenetianBlind.js.zip](https://github.com/dubocr/homebridge-tahoma/files/1346581/VenetianBlind.js.zip)

Tel me if this one open/close correctly. Regarding 50%, it's the default value at startup as RTS devices don't give their position. When you change position the state is normally saved. Tell me if it's not the case. If you want to change the default value add following line in your homebridge config file
`"VenetianBlind" : { "defaultPosition" : 100 }`

**Comment by Prohability** [comment]
Under the tahoma platform configuration or as an accessory?

**Comment by dubocr** [comment]
In the plugin config object :
Name: TaHoma
User:...
Password:...
VenetianBlind:...

**Comment by Prohability** [comment]
Hmm, it doesn't really respond well at all. I can make them roll out, but any command (open/close/percentage) doesn't seem to have any effect.

**Comment by dubocr** [comment]
Only 0% and 100% commands normaly respond as your device model doesn’t support position order. Any other percentage order have no effect.
So normaly using the widget as a switch (not as a slider with opening percentage) must operate properly.

**Comment by dubocr** [comment]
Please report any issue from this new version : 
[TaHoma.zip](https://github.com/dubocr/homebridge-tahoma/files/1347123/TaHoma.zip)

**Comment by Prohability** [comment]
YES! It works, it finally works! You are awesome, thank you so much for all help! Please let me know if you have a donate-button somewhere :)

**Comment by dubocr** [comment]
Great,
Hope you'll enjoy your new automated home ;-).
I'm not expecting anything for this development but as you and @gregmoseley request it, here it is [![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=L4X489MG7FUCN)

**Comment by Shana611** [comment]
Can you tell me how can I copy this TaHoma.zip file to Accessory folder I'm login to Rpi using PUTTY from Windows Computer. i have no idea how to copy from computer to Rpi. Pls help me.Thanks

**Comment by Prohability** [comment]
Hi again! Just updated homebridge and installed the plugin again. The file you added does not seem to work anymore in the updated version, any idea how to solve it?
