### ISSUE TITLE
Automatisation chauffage ios16

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#401]
Bonjour Romain,
Depuis iOS 16 (je penses), j’ai un soucis avec mon automatisation de coupure du chauffage lors de l’ouverture de la fenêtre.
Dans les réglages de l’automatisation, j’ai mis le chauffage sur éteint (7 degrés), mais il passe en mode eco sur tahoma et en chauffage (7 degrés) sur home…
![AD0DA346-2623-4B1B-ABAB-E7D14D42A124](https://user-images.githubusercontent.com/49283285/190870812-9a668a5d-652f-47eb-b4db-73e378135631.png)

![B5219766-C1F2-4E78-A514-B8B1FE4EE87D](https://user-images.githubusercontent.com/49283285/190870825-d45a69a7-bf26-4cfe-bd7c-bd65cd9f925b.png)

une fois l’automatisation lancée :
![D61548C9-13AF-4CD3-9D4C-AB8D3EDDF3E8](https://user-images.githubusercontent.com/49283285/190870879-62631cc2-b503-41c3-a6db-9c72ea4d75c8.png)

Voici les logs sur ta page:
***Gateway:*** 9950
***Device:*** HeatingSystem > AtlanticElectricalHeater

***States***
****
core:AbsenceModeState=true
core:OnOffState=on
io:TargetHeatingLevelState=frostprotection
core:TargetHeatingLevelState=frostprotection
core:AbsenceModeState=true
core:AbsenceModeState=undefined
core:OnOffState=off
io:TargetHeatingLevelState=off
core:TargetHeatingLevelState=off
core:AbsenceModeState=true
core:OnOffState=on
io:TargetHeatingLevelState=frostprotection
core:TargetHeatingLevelState=frostprotection
core:AbsenceModeState=undefined
core:OnOffState=off
io:TargetHeatingLevelState=off
core:TargetHeatingLevelState=off

**Comment by dubocr** [comment]
(Re)Bonjour Patrick,

Lorsque l'automatisation est créée depuis Home, elle contient deux ordres : changement de mode + T° consigne.
Du coup pour un arrêt, je pense que cela envoi arrêt + T° consigne 7°C dans ton cas (tu peux vérifier sur l'application Eve par exemple, l'automatisation devrait faire apparaitre un scénario avec "2 actions".

La T° de consigne à 7°C correspondant au mode hors gel, cela correspond à un mode différent de arrêt donc il y à conflit.

C'était déjà le cas avant iOS16 mais peut-être dans l'autre ordre.

J'ai fait une mise à jour qui devrait normalement permettre d'ignorer la commande de T° si on est à l'arrêt.

**Comment by Tontonpat** [comment]
Merci Romain, j’ai fait la mise à jour et c’est bon 👍
En revanche, ça garde affiché la température de consigne avant le passage en off.
Mais c’est pas bien grave

**Comment by dubocr** [comment]
Je pense que ce dont tu parles n’est pas la consigne mais la température ambiante (la consigne est masquée en arrêt).
Pour ne pas afficher 0°C, l’utilisateur qui avait retouché le code avait choisi de mettre la T° de consigne comme température ambiante. Quand on est a l’arrêt c’est vrai que c’est perturbant.
Je vais voir si on peut afficher des - - a la place.

**Comment by Tontonpat** [comment]
Ne te prends pas la tête avec ça, c’est « esthétique ».
Merci encore
