### ISSUE TITLE
[SomfyThermostat] Tahoma + LocalAPI = missing Thermostat

### ISSUE THREAD

**Issue by luk4s** [dubocr/homebridge-tahoma#403]
***Gateway:*** AgPhXTn8qvEeZgn4EfjBYtTFdlecH393
***Device:*** HeatingSystem > SomfyThermostat

I try switch my homebridge connection with tahoma to local API. I followed https://github.com/dubocr/homebridge-tahoma#configure-local-api, connection works fine, but in accessories missing Thermostat (so temperature and humidity)

Is it feature or bug?

(I switched back to somfy_europe service, and thermostat works)

thx

**Comment by dubocr** [comment]
Hi,

It's a [known issue](https://github.com/dubocr/homebridge-tahoma/issues/367#issuecomment-1233075015_).
Please follow [https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/20](https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/20)
