### ISSUE TITLE
Tahoma & LocalAPI - long request time

### ISSUE THREAD

**Issue by dawidstolarski** [dubocr/homebridge-tahoma#404]
Hello, 
I've switched to the localAPI and i've noticed that time from changing accessory state in homebridge to sending a request  is about 2.6 ~ 3 seconds - in my case `setClosureAndOrientation` - i've searched a repo and VenetianBlind class is responsible for that request.

I was expecting a way better time improvement when it communicates locally to the tahoma.  Is any way to improve the time of response to the local API? 🤔

**Comment by dawidstolarski** [comment]
I don't see any errors in the homebridge logs.
`Does it appear for shutters only or other kind of device ?` - It's case of all of the Somfy integratation. Metro IO garage doors also takes about 2-3 second to "react" on the user action from the homebridge accessory status change. ( I am trying to change the accessory status from there because I want to be sure that's not a problem with Homekit/Homebridge communication) 

To be honest - I have Hue and Tuya local integrations and it reacts instantly ( about 0.2s max )

`Is it longer than the cloud API ?` - No. It's almost same as the cloud API. It behaves like it was sending some requests to the cloud, and then making a local API call.

**Comment by dawidstolarski** [comment]
Here are the logs:
```
[19/09/2022, 13:37:46] [TaHoma]  POST /events/33df75f5-65cc-4f81-8426-1439ae3fc0c8/fetch
[19/09/2022, 13:38:46] [TaHoma]  POST /events/33df75f5-65cc-4f81-8426-1439ae3fc0c8/fetch
[19/09/2022, 13:39:05] [TaHoma] [Gabinet] setClosureAndOrientation[0,0]
[19/09/2022, 13:39:05] [TaHoma]  POST /exec/apply
[19/09/2022, 13:39:05] [TaHoma]  Change event polling period to 5 sec
[19/09/2022, 13:39:10] [TaHoma]  POST /events/33df75f5-65cc-4f81-8426-1439ae3fc0c8/fetch
[19/09/2022, 13:39:10] [TaHoma] [Gabinet] setClosureAndOrientation IN_PROGRESS
[19/09/2022, 13:39:10] [TaHoma] [Gabinet] core:TargetClosureState => 0
[19/09/2022, 13:39:10] [TaHoma] [Gabinet] core:MovingState => true
[19/09/2022, 13:39:15] [TaHoma]  POST /events/33df75f5-65cc-4f81-8426-1439ae3fc0c8/fetch
[19/09/2022, 13:39:18] [TaHoma] [Gabinet] setClosureAndOrientation[100,0]
[19/09/2022, 13:39:18] [TaHoma]  POST /exec/apply
```

**Comment by dawidstolarski** [comment]
Here's the video of the lag between interaction and Command
https://user-images.githubusercontent.com/20901841/191010780-480daecd-fa78-4166-87f8-1ab165a32f3f.mov

**Comment by dawidstolarski** [comment]
Here's with be better quality and trimmed to get down with 10MB attachment's file size. You can see the lag
![](https://user-images.githubusercontent.com/20901841/191011338-48b8bfbe-d69a-4a7d-a0f2-c157f43496bc.mov)
https://user-images.githubusercontent.com/20901841/191011338-48b8bfbe-d69a-4a7d-a0f2-c157f43496bc.mov

**Comment by dubocr** [comment]
This delay is only for characteristics with range values (position for shutter/blind, temperature for heater or luminosity for light). This is to avoid multiple command to be sent when user moves the cursor on HomeKit UI.
You should not notice it on garage door.

I published new plugin version to reduce a little the delay and exclude it for 0/100 values (when user is not using the cursor but only the switch on/off, open/close).

**Comment by dawidstolarski** [comment]
The lag is fixed for 0/100 - thanks! But could you add also 99%?- i am using my Blinds in blindsMode

**Comment by dubocr** [comment]
I can't do that because when user slide from 100% to X% (80% for eg.), the cursor will pass on 99% causing one command at 99% + another at 80%.
Not sure this delay is a big embarrassment on device that takes seconds to operate ?

**Comment by dubocr** [comment]
I can't do that because when user slide from 100% to X% (80% for eg.), the cursor will pass on 99% causing one command at 99% + another at 80%.
Not sure this delay is a big embarrassment on device that takes seconds to operate ?

**Comment by dubocr** [comment]
I reduced a bit more the delay, this is the best compromise I can do between UI slider experience and "speed".

**Comment by dawidstolarski** [comment]
@dubocr everything's working excellently now!
