### ISSUE TITLE
Status update after opening blinds with remote control

### ISSUE THREAD

**Issue by JHPWBN** [dubocr/homebridge-tahoma#409]
Hi, I am new to Homebridge and GitHub but have managed to install your plug-in using the Homemanager App. Everything works fine, so many thanks for that, except one thing which I discovered so far:
I have a number of blinds upstairs and a number of blinds downstairs, for each level I have a separate remote control which I use to open the blinds.
The blinds downstairs show up in the HomeApp as open, however the ones upstairs remain shown as closed. I have even re-opened them with the Tahoma App, no change.
If you have a solution I would be much obliged as that seems to be the only issue with this fantastic tool.

The blinds are powered by RTS motors.

Many thanks in advance!

**Comment by dubocr** [comment]
Hi,

RTS device are stateless so the state can't be syncronized. You should encounter the same issue on TaHoma when moving blind with the remote control : TaHoma can't tell you if the blind is open or close.
