### ISSUE TITLE
Somfy One support?

### ISSUE THREAD

**Issue by MirkoKas** [dubocr/homebridge-tahoma#41]
I‘m thinking about buying that Somfy One camera and alarm system and was wondering, if this device is supported by this plugin when I integrate it with my Tahoma setup. And if yes, what functions are supported, e.g. camera live feed, Alarm activation/deactivation.

**Comment by dubocr** [comment]
Hi,

Alarm system may be supported if it's the same system as Tahoma but Camera won't.
For the Alarm, activation/deactivation and zone are supported.
