### ISSUE TITLE
Tahoma Metro false positive status

### ISSUE THREAD

**Issue by dawidstolarski** [dubocr/homebridge-tahoma#410]
When I am closing the garage doors I always get notification "garage doors opened" when the doors are half way to the end and after few seconds proper "garage doors closed". So I cannot pair status with the switch, because it will generate a loop - switch turned on will open the garage, closed garage doors should turn off the switch - but it can't, because it will firstly turn it on, and reopen the door.

Zamkniete - means closed
Otwarte - means opened

![image](https://user-images.githubusercontent.com/20901841/191248336-4a4f1e53-b7d8-4a29-8403-e0c724e2a4b5.jpeg)

**Comment by dubocr** [comment]
Hi,

As your request is about devices, please follow `Device integration and bug` link when opening issue.

Thank you.
