### ISSUE TITLE
[PositionableGarageDoorWithPartialPosition]

### ISSUE THREAD

**Issue by dawidstolarski** [dubocr/homebridge-tahoma#413]
***Gateway:*** 4639
***Device:*** GarageDoor > PositionableGarageDoorWithPartialPosition

***States***

***Description***
When I am closing the garage doors I always get notification "garage doors opened" when the doors are half way to the end and after few seconds proper "garage doors closed". So I cannot pair status with the switch, because it will generate a loop - switch turned on will open the garage, closed garage doors should turn off the switch - but it can't, because it will firstly turn it on, and reopen the door.

**Comment by dubocr** [comment]
Hi,

What do you mean by `the switch` and `pair status` ?

It seems you miss some steps while opening the issue as the `States` part is empty.
Please read and execute carefully the process below.
In you case, you can execute the command with the tool (app, switch,...) you used when you says `When I am closing the garage doors`

> 1. Enter the name of a command to execute
2. Execute the command with official application
3. Wait (aprox. 10-20 seconds) for event states (if any)
4. Repeat for each command
5. Click 'Open GitHub issue' to create the report
