### ISSUE TITLE
Error "plugin site unavailable" after 2.2.48 update

### ISSUE THREAD

**Issue by Ciarals84** [dubocr/homebridge-tahoma#414]
Hello. After latest 2.2.48 update my Tahoma plugin has become unresponsible. On the log, the error is the same:

<img width="787" alt="Schermata 2022-09-22 alle 08 00 35" src="https://user-images.githubusercontent.com/67325842/191669746-9cd107ea-e392-4848-b6ef-af0c012a6a91.png">

Of course I've tried rebooting HOOBS and/or just the bridge but nothing. How can I solve this? My Tahoma is currently functioning and accessible. I haven't changed anything in the configuration since years. Thank you for your help.

**Comment by dubocr** [comment]
Hi,

This issue is not related to TaHoma plugin. It's a connectivity issue impacting both Hoobs `22/9/2022, 07:24:18 WARNING plugin site unavailable` and all plugin which need connectivity.

`getaddrinfo EAI_AGAIN` meens the TaHoma server can't be resolved. It is a DNS issue on your system.

**Comment by dubocr** [comment]
Find some information could help you : [https://support.hoobs.org/topics/connectivity/plugin-site-unavailable](https://support.hoobs.org/topics/connectivity/plugin-site-unavailable)
