### ISSUE TITLE
[UpDownScreen]

### ISSUE THREAD

**Issue by philask** [dubocr/homebridge-tahoma#418]
***Gateway:*** 7877
***Device:*** Screen > UpDownScreen

***States***
**close**

No devices work anymore, very command produces:

[9/30/2022, 7:11:11 AM] [TaHoma] [Living Room 4] close[]
[9/30/2022, 7:11:17 AM] [TaHoma] [Living Room 4] close APPLICATION_ERROR

**Comment by dubocr** [comment]
Hi,

Is you issue always in progress ?
As I can see you also have this error with Tahoma PC application so this is not related to the plugin.
