### ISSUE TITLE
LocalAPI vs Standard API advice?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [dubocr/homebridge-tahoma#419]
Hi, during setup, I've never chosen the service, and I am now wondering what option I am using?

![image](https://user-images.githubusercontent.com/15063294/193477457-49223997-2f77-44c7-83a7-a02d47f77398.png)

I guess SomfyEurope? I had my fair share of issues with Tahoma API stopping to work and banning you for minutes randomly that you are aware of, and I was wondering if using LocalAPI is subject to the same issues. Would I be able to configure 5-10 seconds check for state changes so that when I open my gate manually (using pilot or button) I would get faster updates in homekit or will it behave the same as with the API I am currently using where the polling/refresh rate is 60/30.

**Comment by dubocr** [comment]
Hi,

If you don't choose service, you are using the somfy_europe default one.
Local API is not rate limited so you will be able to configure lower polling/refresh rates.

There is some limitation with local api like missing devices and all you automation will break, you'll have to recreate it. Somfy is working on these limitations so we could expect improvements.
