### ISSUE TITLE
[HomekitStack] : [10/17/2022, 10:14:05 AM] [TaHomaLocal] Error 400 Unknown object. (UNSPECIFIED_ERROR)

### ISSUE THREAD

**Issue by grunchy99** [dubocr/homebridge-tahoma#424]
When using Local API I have this error in log : Error 400 Unknown object. (UNSPECIFIED_ERROR)

***Gateway:*** 1cVVzYYJCWy3XhjHgQenzP52JUWbk7jR
***Device:*** ProtocolGateway > HomekitStack

***States***

**Comment by PatriceRobert** [comment]
Hey @dubocr , same thing here, many messages like this one using local API:


`Oct 26 09:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 10:25:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 10:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 11:25:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 11:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 12:25:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 12:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 13:25:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 13:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 14:25:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 14:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 15:25:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 15:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 16:25:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
Oct 26 16:55:58 chups homebridge[17766]: [TaHoma] Error 400 Unknown object. (UNSPECIFIED_ERROR)
`

But all seems to work fine. Even tried to block the TaHoma switch from internet access and it's all good, just got this error message.
-- Patrice.

**Comment by dubocr** [comment]
Duplicate #405
