### ISSUE TITLE
[My TaHoma Box] Error 400 invalid_grant

### ISSUE THREAD

**Issue by jonasophie** [dubocr/homebridge-tahoma#437]
Bonjour,

j'ai une box CozyTouch avec une clim réversible Shogun
j'arrive bien à me servir de l'application Cozytouch/Atlantic, par contre  malheureusement je n'arrive  pas à l'intégrer à HomeKit  avec le plugin.

**Voici les messages d'erreur:**
[16/11/2022 21:17:41] [My TaHoma Box] Error 400 invalid_grant
[16/11/2022 21:17:41] [My TaHoma Box] Retry in 120 sec...

**Ma config:**
            "platform": "Tahoma",
            "name": "My TaHoma Box",
            "service": "cozytouch",
            "user": "_e-mail idem appli iPhone_",
            "password": "_idem appli iPhone_"

j'ai le message suivant quand j'essaye de me logger sur le site -> https://dev.duboc.pro/tahoma
_AxiosError: Request failed with status code 400_
avec le service "Cozytouch"

Est-ce que j'ai raté quelque chose dans la configuration ? ou pas compris un truc ?

merci d'avance

**Comment by nscheffer** [comment]
J'ai le même soucis, j'ai fait un changement du mot de passe et pareil...

**Comment by nscheffer** [comment]
Il semble que depuis quelques semaines plus d'API Overkiz pour les box CozyTouch, ce sont les mêmes constants partout (HA, Homebridge, Jeedom, etc...) par contre la box Tahoma Switch n'est pas impacté.

**Comment by jonasophie** [comment]
bonjour,
merci pour ton retour. ça veut dire que pour le moment, pas de solution ? il faut attendre ? une mise à jour ?
merci

**Comment by nscheffer** [comment]
Effectivement je pense que l'on va devoir attendre une mise à jour quelque part...

**Comment by jonasophie** [comment]
Bonjou @dubocr merci pour la mise à jour, ça règle le soucis. 👍🏼
