### ISSUE TITLE
[Cozytouch] Gestion mode "Prog"

### ISSUE THREAD

**Issue by Flavien06** [dubocr/homebridge-tahoma#438]
Bonjour,

Sur le Cozytouch il y a le mode "Arrêt", "Basic", "Prog" et "Auto"
Et les consigne "Eco"  (Climatisation) et le mode  le mode "Confort" (Chauffage)

J'ai fait mes test sur 2 radiateurs (Un Radiateur Thermor (Salon) et une Interface fil pilote Thermor (SdB)
<img src="https://user-images.githubusercontent.com/1915755/202510592-eaf7e4b9-342e-4c44-bb02-513f401e4b90.jpg" width=20% height=20%>   <img src="https://user-images.githubusercontent.com/1915755/202510615-f4ff4b08-2e67-4ed7-9f6e-c5b24a127321.jpg" width=20% height=20%>

Via Homebridge "Arret" et "Auto" fonctionne bien. (Sauf le mode "Auto" qui ne sert à rien sur l'interface fil pilote" car il n'existe pas)
"Climatisation" et "Chauffage" outrepasse les consigne si en auto.

Par contre le mode "Prog" ne peut pas être activer.

Est-ce possible d'ajouter ce mode Prog? 
- Sur l'interface fil pilote il pourrait êtres activer via le mode "Auto"
- Par contre sur le Radiateur comment l'ajouter (je veux garder le mode Auto) Est-il soit possible d'ajouter un autre menu? Ou envisageable d'échanger les menu pour que le mode "Refroidir" active le mode "Prog" du radiateur (pour ma config uniquement)?

```
**Arret**
core:OperatingModeState=standby
**Basic**
core:OperatingModeState=basic
**Prog**  #(mode suivant un planing horraire dans l'appli)
core:OperatingModeState=internal
core:OnOffState=on
io:TargetHeatingLevelState=eco   #<= Mode eco actif sans doute car mode eco en cours dans la prog horraire.
**Auto**
core:OperatingModeState=auto

**Basic selection température**
core:TargetTemperatureState=22.0
```

**Comment by jonasophie** [comment]
Bonjour

Tu pourrais stp partager ta configuration, j'arrive pas à intégrer ce plugin ?

Merci

**Comment by Flavien06** [comment]
> Bonjour
> 
> Tu pourrais stp partager ta configuration, j'arrive pas à intégrer ce plugin ?
> 
> Merci

Bonjour,
C'est une autre demande, peut tu crée un autre "issues" avec ta config et ce que tu a fait, cela plus simple.
Merci

**Comment by nscheffer** [comment]
Je suis dans le même ca avec une config similaire une CozyTouch box V2 avec des radiateurs Sauter Connectés IO et des radiateurs Atlantic ancien avec le module Fil Pilote.
L'interface HomeKit pour la gestion des module Fil Pilote est pas intuitive et peut être amélioré.

Par contre depuis qq temps le plugin Tahoma pour gérer une CozyTouch box est en erreur 400/401 !!!
