### ISSUE TITLE
Rts Awning accepts only 0% or 100%

### ISSUE THREAD

**Issue by padman74** [dubocr/homebridge-tahoma#44]
Today I installed the TaHoma Premium and configured my awning on the terrace to work with Homebridge. It’s an older Somfy motor with Rts control. Unfortunately it reacts only on fully open (100%) or on close (0%). If I select another value HomeKit shows the value but the awning is not doing anything.

**Comment by dubocr** [comment]
Normaly, any other value than 0 or 100 put the device in « my » position. May your awning doesn’t have configured or existing « my » position.

**Comment by dubocr** [comment]
Normaly, any other value than 0 or 100 put the device in « my » position. May your awning doesn’t have configured or existing « my » position.
