### ISSUE TITLE
Local API won't connect.... been working fine... now it won't connect, codes and user codes and api codes all correct...

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#441]
***Gateway:*** 2006
***Device:*** ProtocolGateway > HomekitStack

***States***
**down**

<img width="869" alt="Screenshot 2022-12-09 at 19 44 47" src="https://user-images.githubusercontent.com/47482260/206789042-882ba517-ee80-4a4b-a75b-8347a94cf102.png">

**Comment by adavison007** [comment]
Is this normal? 

<img width="1293" alt="Screenshot 2022-12-09 at 20 54 27" src="https://user-images.githubusercontent.com/47482260/206804969-9299121d-977b-4dd4-a164-eb177916748c.png">

**Comment by adavison007** [comment]
FIXED! Looks like Somfy deleted my API key.... Generated a new one and then rebooted the Tahoma hub and now it works

**Comment by yyzpeekay** [comment]
How did you generate a new API key?

**Comment by adavison007** [comment]
> How did you generate a new API key?

https://dev.duboc.pro/overkiz

**Comment by adavison007** [comment]
The issue occurred again today, when using the API tool from yourself I noticed no APIs had been generated, so basically the same as before the API code gets deleted after a period of time and you have to make a new one and put it in the code to work again
