### ISSUE TITLE
[PositionableRollerShutterWithLowSpeedManagement]

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#444]
***Gateway:*** 9950
***Device:*** RollerShutter > PositionableRollerShutterWithLowSpeedManagement

***States***
Bonjour Romain,
J’ai un souci avec 3 volets Somfy IO que je viens d’installer.
Ils sont reconnus dans homebridge mais n’apparaissent pas dans home.
J’ai vu ces messages d’erreur dans les logs a l’heure où j’ai connecté mes volets à Tahoma:
`[12/17/2022,
11:54:42 AMI [Tahomal Pol
ling error - TypeError: Cannot read pr
operties of undefined (reading
'update
States')
at OverkizClient.fetchEvents (/hom
ebridge/node_modules/homebridge-tahoma
/node modules/overkiz-client/src/Clien tats:247:32)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node
:internal/process/task queues:96:5)
at OverkizClient.pollingTask (/hom
ebridge/node modules/homebridge-tahoma
/node modules/overkiz-client/src/Clien t.ts:233:13)
[12/17/2022, 11:54:42 AM] [Tahoma] Typ
eError: error.includes is not a functi
ON
at OverkizClient.fetchEvents (/hom
ebridge/node modules/homebridge-tahoma
/node modules/overkiz-client/src/Clien t.ts:266:27)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node
:internal/process/task_queues:96:5)
at OverkizClient.pollingTask (/ hom
ebridge/node_modules/homebridge-tahoma
/node modules/overkiz-client/src/Clien t.ts:233:13) `

Après avoir redémarré homebridge, on voit bien les VR Mathys, VR Raphaël et VR salle de jeux dans les équipements de homebridge pourtant:
![431ACE5B-4958-4B3F-835C-51272D85B75A](https://user-images.githubusercontent.com/49283285/208289311-b54c9cda-b394-40d6-bd1a-8ef88ef2b366.jpeg)

![07F25170-C58A-4897-B6F9-A223DE2F0BD9](https://user-images.githubusercontent.com/49283285/208289256-7ac631a5-767f-4f35-aaf1-95699dfe8edb.jpeg)

Merci pour ton aide.

**Comment by dubocr** [comment]
Bonjour Patrick,

J'ai corrigé l'erreur. Pas sur que cela change quelque chose au problème d'affichage mais à voir déjà.
As-tu fais la mise à jour iOS 16.2 ? Apple à changé son moteur HomeKit à partir d'iOS 16.2. C'est désormais le concentrated qui centralise tout. La mise à jour des concentrateurs + mise à niveau d'homkit (réglage du domicile > mise à jour) peut peut-être aider.

**Comment by Tontonpat** [comment]
Oui je suis bien à jour partout, j’ai également mis à jour ton plugin mais toujours pas de Vr dans home.
Dois-je les supprimer de tahoma, puis les re-appairer afin qu’ils soient chargés dans home?

**Comment by Tontonpat** [comment]
Merci Romain, tout fonctionne👍
