### ISSUE TITLE
Local API scenes

### ISSUE THREAD

**Issue by IngmarStein** [dubocr/homebridge-tahoma#445]
Hi,

I'm using the local API somewhat successfully (https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/64 is still open with Somfy), but I noticed that I can't trigger scenes. They are mapped correctly (example: `[TaHoma] Map scene Rollladen runter`), but when I execute one from Home, I get errors like this:

```
[TaHoma] [Scene] Rollladen runter undefined
```

**Comment by dubocr** [comment]
Please follow #412

**Comment by IngmarStein** [comment]
Ah, I didn't spot the closed issue. Thanks and sorry for the noise!
