### ISSUE TITLE
Refresh Period Error

### ISSUE THREAD

**Issue by adavison007** [dubocr/homebridge-tahoma#448]
***Gateway:*** 2006
***Device:*** ProtocolGateway > HomekitStack

I have the refresh period set to 30 minutes, every 30 minutes when refresh occurs I get the following message.... If I change the refresh period to 10 then the issues happens every 10 minutes... what's interesting in the JSON It only shows Polling Period and not the refresh period I change in the UI?

### **[22/12/2022, 10:59:23] [My TaHoma Box] Error 400 Unknown object. (UNSPECIFIED_ERROR)**

  {
            "name": "My TaHoma Box",
            "service": "local",
            "user": "XXXXXXXXXX",
            "password": "XXXXXXXXXX",
            "pollingPeriod": 30,
            "exposeScenarios": false,
            "exclude": [
                "Alarm",
                "MusicPlayer"
            ],
            "_bridge": {
                "username": "XXXXXXXXXX",
                "port": 35475
            },
            "platform": "Tahoma"
        },

**Comment by Tontonpat** [comment]
Bonjour Romain, idem pour moi
