### ISSUE TITLE
Somfy Connectivity Box - error 401

### ISSUE THREAD

**Issue by Manu-1989** [dubocr/homebridge-tahoma#450]
Hello,
First of all, thank you for your hard work on keeping this plugin, 
I noticed since couple weeks back that my Homebridge is returning error 401.
It was working flawlessly before.
Also, i noticed that i can now login to my connectivity box via IP, which was not a thing before, so not sure if the issue regarding credentials is coming from the plugin side or from Somfy themselves.
Other thing, this box was bought and installed as being in France but i live in Switzerland (the connectivity box was not available here at the time), does the "Somfy europe" database use our location to retrieve the country? if it's the case, that might explain the issue (when i was installing the connectivity box, i had to create the account in FR as it seems the box is sort of geofenced and don't accept being installed in CH site)
In future, i will replace this with the tahoma switch but until then, it would be great if i can figure what's happening.
Regards and keep the good work!
<img width="1091" alt="Capture d’écran 2022-12-28 à 09 38 10" src="https://user-images.githubusercontent.com/103191063/209784161-647defd1-b6c4-4fda-99df-d5bfea9ef57f.png">

**Comment by Thibaultclm** [comment]
Hi,
Yes, thank you for your work! 
Just for the record, I have the same problem. If it can help you.
PS: I am from France and my box was bought in France.

<img width="1261" alt="Capture d’écran 2023-01-05 à 21 23 10" src="https://user-images.githubusercontent.com/26966117/210873060-72ba225b-b39c-49e4-bd0c-0163a5412b64.png">

**Comment by Manu-1989** [comment]
well, as far as i can see, this error really is very random.
On the other hand, I noticed that my scenarios regarding the devices connected to the box are not being executed as their schedule.
I've some windows/blinds to open/close at specific hours but none are being executed. when I try to manage said scenarios via homekit, i also receive a error as homekit was not able to update the scenario.
Really weird, I reseted the box, went through all configuration but still not 100% working.
hope the issue can be found and fixed..

**Comment by ragingbowels** [comment]
I am also getting the polling error.  I am not using the developer mode local API and get get this reapeated.


![1Capture](https://user-images.githubusercontent.com/29823104/211130313-ac0992f0-7ef7-45fc-a575-235c91e622b8.JPG)

**Comment by jcbr247** [comment]
Same here as well

**Comment by Manu-1989** [comment]
I really don't get it...
For almost 1 entire wee, it worked flawlessly, I reseted my automations on homekit side and all windows and blinds worked as they were supposed according to schedules. Today for some reason I'm getting again the same 401 error...at this point i don't really know what's going on.

**Comment by luk4s** [comment]
I have same problem , via local api on Tahoma, also via Europe API too. Start failing yesterday. Today same error start appear with Somfy Protect too...

I think its somfy-related issue... :/

**Comment by adavison007** [comment]
I've had this issue a few times now. Basically Somfy or the API creation tool keeps deleting my API after a period of time. If you use this tool https://dev.duboc.pro/overkiz and create a new API code and paste that into the settings on homebridge everything will work again.

**Comment by luk4s** [comment]
> I've had this issue a few times now. Basically Somfy or the API creation tool keeps deleting my API after a period of time. If you use this tool https://dev.duboc.pro/overkiz and create a new API code and paste that into the settings on homebridge everything will work again.

It helped! Thank you.

**Comment by Manu-1989** [comment]
> I've had this issue a few times now. Basically Somfy or the API creation tool keeps deleting my API after a period of time. If you use this tool https://dev.duboc.pro/overkiz and create a new API code and paste that into the settings on homebridge everything will work again.

I’m using the connectivity box which do not support local API.

**Comment by adavison007** [comment]
The issue still occurs, it happened to me yesterday and I logged it under the original post #441
