### ISSUE TITLE
Tahoma plugin not recognizing blind position when it has been altered by the remote or Tahoma app

### ISSUE THREAD

**Issue by yyzpeekay** [dubocr/homebridge-tahoma#453]
Is the plugin supposed to poll the blind or Tahoma site to determine blind position. My issue is that if I alter the blind position with the Somfy remote the plugin does not recognize and show the current blind position.

**Comment by julien94800** [comment]
Hello, I see that this issue is old but I get same issue. Is it same for everyone? Or is there any setting available that could improve this?
Thanks in advance
