### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MarkP63** [dubocr/homebridge-tahoma#457]
Please advise if this plug-in requires and radio hardware device?  I am trying to integrate Brustor Louvred Pergola (rotating roof, side blinds and lights) which I believe uses Somfy technology.  Brustor recommends the Tahoma Switch for IO & RTS. I use Apple Homekit and Homebridge and was looking for a plugin to bridge Brustor to HK via Homebridge. Will this plugin work or do I need additional hardware (radio/contoller) or a different plugin? I was trying to avoid the expensive somfy 1870600/1870594 TaHoma Switches.  Thanks

**Comment by Manu-1989** [comment]
Hello.
You do need to have the gateway that communicate with said devices.
not sure how many you have but you can always get the tahoma connectivity box, it's around 60€ which is way less comparing to their switch.
The major downside is it's limit to 20 devices and not able to do any automation, you need to set any automation directly on HK.
It's my current setup, I've 5 devices connected to it.
I regularly have some authentication errors on HB but usually it figures itself out and my scenarios are executed as they should
