### ISSUE TITLE
Polling error - not authenticated access denied

### ISSUE THREAD

**Issue by Ln12345678910** [dubocr/homebridge-tahoma#460]
Hi, the plug-in works when setup in a child bridge but I get multiple polling error messages. 

I can’t help but think that’s leading to instability. 

Any help would be gratefully appreciated.

**Comment by artik** [comment]
Hi !

Did you try to add `"pollingPeriod": 30` in your configuration?

**Comment by LionelPKX64** [comment]
https://github.com/dubocr/homebridge-tahoma/issues/481#issuecomment-1605293919
