### ISSUE TITLE
Support for Connectivity kit?  Somfy blind works only 100% down or 100% up, and doesnt respons to my MY button via Homekit (works fine via Tahoma app)

### ISSUE THREAD

**Issue by phattrance** [dubocr/homebridge-tahoma#462]
So im using the somfy connectivity kit with this plugin to use my somfy blinds with homekit, and i noticed that in homekit, i ONLY have the option to have the blinds 100% up or 100% down, and nothing in between.  

On my Sony remote ( https://shop.somfy.se/media/catalog/product/cache/e576c2d73384ece72d3ff6a2c4412693/s/o/somfy-telis-1-rts-pure.jpg ) i have a MY button where i have set the blind to stop at 50%, but this option doesnt seem to be avalible via this plugin at all.  

In the Tahoma app, the MY button works as it should, so it stops the blinds at 50%, but in homekit, when i put the "slider" to 50%, nothing happens, the blinds wont even move. 

I am connected to the Tahoma Europe server ( https://imgur.com/a/L560Cac ) and the version of the plugin: homebridge-tahoma v2.2.54

is this a bug or just not supported by this plugin?

**Comment by romontei** [comment]
Hey ! 

If your roller shutter motor is RTS and not IO Homecontrol, it cannot communicate its status because RTS is monodirectional. You can only send open or close order.

You need IO Homecontrol motor to set a % state.

**Comment by romontei** [comment]
Btw, if you have a motor with IO Homecontrol, you don't need this plugin as the shutter is natively supported to HomeKit from TaHoma App ☺️

**Comment by marn06** [comment]
For rts you can have the plug-in calculate the position with this config, it is not perfect but better than nothing imo.
{
  "name": "TaHoma",
  "service": "somfy_europe",
  "user": "",
  "password": "",
  "devicesConfig": [
    {
      "key": "Screen",
      "movementDuration": 23
    }
  ]
}

**Comment by phattrance** [comment]
> For rts you can have the plug-in calculate the position with this config, it is not perfect but better than nothing imo. { "name": "TaHoma", "service": "somfy_europe", "user": "", "password": "", "devicesConfig": [ { "key": "Screen", "movementDuration": 23 } ] }

I just tried this (replaced the json config with this one and added my user and password. the plugin went offline in homebridge and didnt even go live until i switched back to the old json config.

**Comment by marn06** [comment]
> > For rts you can have the plug-in calculate the position with this config, it is not perfect but better than nothing imo. { "name": "TaHoma", "service": "somfy_europe", "user": "", "password": "", "devicesConfig": [ { "key": "Screen", "movementDuration": 23 } ] }
> 
> I just tried this (replaced the json config with this one and added my user and password. the plugin went offline in homebridge and didnt even go live until i switched back to the old json config.

Are you using somfy_europe with your own json config? The part of the config handling the calculate of position is this:
"devicesConfig": [ { "key": "Screen", "movementDuration": 23 } ]

Where it calculates position based on a movement duration of 23 seconds 0% - 100%.

**Comment by phattrance** [comment]
> > > For rts you can have the plug-in calculate the position with this config, it is not perfect but better than nothing imo. { "name": "TaHoma", "service": "somfy_europe", "user": "", "password": "", "devicesConfig": [ { "key": "Screen", "movementDuration": 23 } ] }
> > 
> > 
> > I just tried this (replaced the json config with this one and added my user and password. the plugin went offline in homebridge and didnt even go live until i switched back to the old json config.
> 
> Are you using somfy_europe with your own json config? The part of the config handling the calculate of position is this: "devicesConfig": [ { "key": "Screen", "movementDuration": 23 } ]
> 
> Where it calculates position based on a movement duration of 23 seconds 0% - 100%. So that is the only line you need to add.


This is the json code im using. Are you able to edit it for me?  (i have removed my password etc)

`{
    "name": "TaHoma",
    "service": "somfy_europe",
    "user": "user",
    "password": "password",
    "pollingPeriod": 60,
    "refreshPeriod": 60,
    "exposeScenarios": false,
    "_bridge": {
        "username": "bla",
        "port": 36414
    },
    "platform": "Tahoma"
}`

**Comment by marn06** [comment]
Sure @phattrance 
{
  "name": "TaHoma",
  "service": "somfy_europe",
  "user": "user",
  "password": "password",
  "devicesConfig": [ { "key": "Screen", "movementDuration": 23 } ],
  "pollingPeriod": 60,
  "refreshPeriod": 60,
  "exposeScenarios": false,
  "_bridge": { "username": "bla", "port": 36414 },
  "platform": "Tahoma"
}

**Comment by marn06** [comment]
Hi @phattrance 
You are correct in your assumptions, but I see different possible issues:
1. It seems that settings position to 50% and then afterwards 40% while blinds moving, will cause it to calculate duration between 50% and 40% and then stop, and in homekit it is easy to set multiple positions while trying to set position. You can check the logs to see if this happens.
2. Response lag is variable hence the calculations will never be 100% correct, and I would suggest you go with a trial/error approach to come up with the best number, which for me is 23.

**Comment by romontei** [comment]
Nice I was not aware of this feature ! How this is working ? When I add : 
```
"devicesConfig": [ { "key": "Screen", "movementDuration": 31 } ],
```

The plugin fails the operation with the following error : 
```
[19/04/2023, 19:06:13] [TaHoma] [Volet Cuisine] my[]
[19/04/2023, 19:06:13] [TaHoma] [Volet Cuisine] my Error 400 No such command : my on device ogp://XXXX (ogp:Shutter) (UNSUPPORTED_OPERATION)
```

**Comment by Plexitar** [comment]
Hi, 
Would it be possible to also check my code - I cannot get this to work in json. 

I have 5 rts blinds (group together in HomeKit) and 1 anti theft metal gate. Not sure if need to somehow separate the devices ? (23 sec should be correct for all of the open/close)

{
            "name": "My TaHoma Box",
            "service": "tahoma",
            "user": "xxxx",
            "password": "xxxxx",
            "platform": "Tahoma"
        },
