### ISSUE TITLE
Error: ...same SSID

### ISSUE THREAD

**Issue by mahuch** [dubocr/homebridge-tahoma#47]
Hello,
I have the Homebridge installed on my Mac server. As the only plugin I wanted to use the plugin for TaHoma. I think the installation was successful.

When I start the Homegridge with the plugin installed I get the following error message:
````

> /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
>       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
>       ^
> 
> Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 866498a5-0cc7-4f3a-8307-a375efcecf16
>     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
>     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:399:24)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
>     at /usr/local/lib/node_modules/homebridge-tahoma/index.js:67:16
>     at /usr/local/lib/node_modules/homebridge-tahoma/index.js:125:5
>     at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:176:5
>     at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:208:17)
>     at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:182:13)
>     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)

````

I searched TaHoma for duplicate names. A room had the same name as a window blind. I have adapted these names. After that I still get the error.

Also, I tried it to delete the folder "accessories" and "persist". Without success.

Can you help me to find the mistake?

Thank you, mahuch.

**Comment by dubocr** [comment]
Hello,

Try to stop homebridge completely before removing both folders then start again. Data are persisted when homebridge stop.
Also, you can try to replace line 85 of the `AbstractAccessory.js` file located in 'accessories' tahoma plugin folder by this code :
`this.UUID = UUIDGen.generate(serial);`

This will use unique radio address as UUID.

Hope it will solve.

**Comment by mahuch** [comment]
First, I restarted the Mac. In the processes, the homebridge process was not visible. Then I edited the file AbstractAccessory.js

Line 85 changed from:
    this.UUID = UUIDGen.generate(this.displayName); // serial
to
    this.UUID = UUIDGen.generate(serial);

Then I removing both folders and start Homebridge. 
Unfortunately, I received the same error message.

**Comment by mahuch** [comment]
I found the mistake. A window had the same name as a roller blind. Soory and thank you for your help.

**Comment by dubocr** [comment]
👍
