### ISSUE TITLE
RTS position

### ISSUE THREAD

**Issue by xeonxxxx** [dubocr/homebridge-tahoma#471]
Hi, 

thanks for your plugin, works great.
I want place you a question.
If we use RTS motor we cannot know position, ok.

So, if we use application tahoma (app or tahoma box) there isn't a signal from tahoma that you can intercept to sync position on homebridge?

Thank you so much.

**Comment by marn06** [comment]
Hi @xeonxxxx 
The RTS motors does not have the functionality of informing what their position is, so you will never know. If you go to the issue:
https://github.com/dubocr/homebridge-tahoma/issues/462
You will see how you can use this plugin to calculate the position and get a solution that isn't perfect, but better than nothing in my opinion.

**Comment by Plexitar** [comment]
Hi as topic 462 closed - maybe somebody could help me here:
Hi,
Would it be possible to also check my code - I cannot get this to work in json.

I have 5 rts blinds (group together in HomeKit) and 1 anti theft metal gate. Not sure if need to somehow separate the devices ? (23 sec should be correct for all of the open/close)

{
            "name": "My TaHoma Box",
            "service": "tahoma",
            "user": "xxxx",
            "password": "xxxxx",
            "platform": "Tahoma"
        },

**Comment by marn06** [comment]
Hi @Plexitar 
Is your problem that the calculation of positions based on time does not work?

**Comment by Plexitar** [comment]
Well with the code as it is now - i can just close it or open fully. Can't stop it midway e.g.

**Comment by Plexitar** [comment]
If i press the button mid-movemenet it will go down 100% and then after a few seconds open 100%.
