### ISSUE TITLE
[ERROR] - Connectivity kit-ledbox Error 400 : (UNSUPPORTED_OPERATION)

### ISSUE THREAD

**Issue by romontei** [dubocr/homebridge-tahoma#472]
Bonjour !

Il semblerait que la requête qui pilote la led du Kit de Connectivité ne fonctionne pas / plus : 
```
[18/04/2023, 19:25:55] [TaHoma] [Connectivity kit-ledBox] on Error 400 No such command : on on device ogp://XXXX (ogp:Light) (UNSUPPORTED_OPERATION)
```

Serait-il possible par ailleurs de rendre optionnel la gestion de la led du Kit ?

Merci par avance et bonne continuation !

**Comment by romontei** [comment]
Just disabled the Light device and everything is now ok

**Comment by achlyss-8** [comment]
> Just disabled the Light device and everything is now ok

Hello, how did you deactivate the light please?

**Comment by dpamping** [comment]
How did you disable it?
