### ISSUE TITLE
Problème Erreurs 401 récurentes

### ISSUE THREAD

**Issue by ludokess** [dubocr/homebridge-tahoma#474]
***Gateway:*** 0541
***Device:*** Gate > OpenCloseSlidingGate

***States***
**Open**

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/131894163/234624585-a5467e8b-8745-4b44-b198-7aa71cd0cd60.png">

Bonjour,
J’ai des blocages récurrents de l’accès à l’API Tahoma, avec a priori des messages disant que les ids/pwd sont faux, alors que ce n’est pas le cas….
Ci-dessus, un impri écran des logs
J’ai également la log complète en .txt si vous voulez

Un grand merci :)

**Comment by LionelPKX64** [comment]
CF https://github.com/dubocr/homebridge-tahoma/issues/481#issuecomment-1605293919
