### ISSUE TITLE
Homekit display stop button

### ISSUE THREAD

**Issue by fiky16** [dubocr/homebridge-tahoma#479]
Hello, thank you very much for this plugin.
I know that topics on a stop button already exist but I can't find any solution. My rolling shutters being in RTS, I have no feedback, OK. I would nevertheless like to be able to stop the roller shutter but impossible. 

When I activate the roller shutter, it opens or closes depending on the last action performed. 

Is there a solution? Thanks in advance !

Bonjour, déjà merci beaucoup pour ce plugin qui me simplifie la vie (vraiment !). 

Je possède des volets roulant RTS donc sans retour d'état (c'est la vie). J'aimerais néanmoins pouvoir "stopper" un volet pendant sa course (comme sur l'application tahoma). Seulement je ne peux pas sur Homekit. J'ai vue des topics similaire cloturé mais impossible d’effectuer un "stop".  

Sur homekit je possède soit la vue basique ou quand je clique dessus sa ouvre/ferme en fonction de l'état actuel (volet ouvert ou fermé) mais jamais de "stop". Quand j'ouvre la vue plus complète, une barre s'affiche ( permet de configurer un pourcentage d'ouverture mais ne fonctionne pas avec mon rts) mais aucun bouton "stop". 

Existe t'il une solution ? Merci d'avance !

**Comment by dubocr** [comment]
Bonjour,

Malheureusement HomeKit n'offre pas la possibilité d'ajouté un bouton STOP (tout simplement parce qu'HomeKit n'accepte pas officiellement les produits sans retour d'état).

Par contre vous pouvez configurer le paramètre "movementDuration" sur vos volets, ce qui vous permettra d'utiliser le pourcentage d'ouverture à définir. Ce paramètre correspond à la durée (en secondes) que met le volet pour passer de la position ouverte à fermée.

Exemple :

```
"devicesConfig": [
				{
					"key": "UpDownRollerShutter",
					"movementDuration": 30
				}
			]
```
"UpDownRollerShutter" devra peut-être étre adapté selon le type de volets ou si vous souhaitez l'appliquer volet par volet (en saisissant le nom du volet à la place)


Si besoin vous pouvez aussi ajuster un paramètre "offsetMovementDuration" pour affiner le réglage car le délai d'envoi de la commande 'STOP' peut générer un décalage par rapport à la position attendue :

```
"devicesConfig": [
				{
					"key": "UpDownRollerShutter",
					"movementDuration": 30,
                                          "offsetMovementDuration": 3
				}
			]
```
