### ISSUE TITLE
IO roller blind works reversely. only RTS works correctly

### ISSUE THREAD

**Issue by motaker** [dubocr/homebridge-tahoma#48]
Hi,
Thank you for your great plugins.

I have RTS and IO operated blinds/curtains/projector screen.
It seems that RTS devices works correctly but only IO devices works reversely.
when I press "open" on homekit menu, it will "close", then "close"  is working as "open"

Please kindly give me advice how to fixt it.
Thank you

**Comment by dubocr** [comment]
Hi,

Can you browse and log [home.dubocr.fr/tools/setup](home.dubocr.fr/tools/setup)

Thanks

**Comment by dubocr** [comment]
Do you have the latest version of plugin ? v0.1.19 ?

**Comment by dubocr** [comment]
We just correct the behavior with @navjul in the issue #40
He has the same IO products as you and the last version is OK for him.

**Comment by motaker** [comment]
Hi,
I am using Latest version but still not fixed.
or should I rewrite/modify Awning.js file ?

**Comment by dubocr** [comment]
Can you try to update Awning.js file to replace `setDeployment` by `setClosure` in the line 31.

**Comment by dubocr** [comment]
Remove `converted = value;` at line 247.
However there is something wrong somewhere. Can you give me the model of your 4 IO devices.
@navjul peux-tu également me donner la référence de ton équipement. Les deux sont similaires d'un point de vue de l'API mais pour autant ils semble bien gérés par vos applis TaHoma. Il doit y avoir quelque chose qui permet de les distinguer.

Merci.

**Comment by motaker** [comment]
Thank you ! its working now :)
my IO device is "Sunea Screen 40 io"

Takeru

**Comment by MrClou1A** [comment]
have the same issue with my blinds. It is completely reversed ;-) No big deal for me, but bad for everyone who is using it without IT knowledge and understanding how things are working.

Is it something in general, or only to my Somfy shutters?
BTW: The issue just came up, after I updated this npm package after several month.

**Comment by dubocr** [comment]
@MrClou1A did you logged at [home.duboc.pro/tools/setup](http://home.duboc.pro/tools/setup).
If not, can you after putting your blinds fully opened, fully closed then at 25% with Tahoma app.

@navjul peux-tu également te reconnecter sur [home.duboc.pro/tools/setup](http://home.duboc.pro/tools/setup) après avoir ouvert complètement puis fermé complètement puis placé ton store à 25% depuis TaHoma

Thanks/Merci

**Comment by dubocr** [comment]
Could try this file : [Awning.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2443091/Awning.js.zip)

**Comment by navjul** [comment]
Hello, as tu des nouvelles à ce sujet ?

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous essayer ce fichier en ajoutant dans votre configuration 
`"RollerShutter": { "reverse": true }`

[Awning.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2943207/Awning.js.zip)

Merci par avance.

**Comment by navjul** [comment]
Hello,

Cela ne fonctionne pas chez moi avec ton fichier et le paramètre renseigné dans la configuration. Que je mette à false ou true, j'ai toujours le soucis. Voici ce que je vois dans les logs :

1|homebrid | [2019-3-9 08:37:19] [Tahoma] [Store Ouest Vertical] device type: ExteriorScreen, name: io:VerticalExteriorAwningIOComponent, protocol: io

1|homebridge  | [2019-3-9 08:38:04] [Tahoma] [Store Ouest Vertical] setClosure[22]
1|homebridge  | [2019-3-9 08:38:08] [Tahoma] [Store Ouest Vertical] setClosure[0]
1|homebridge  | [2019-3-9 08:38:10] [Tahoma] [Store Ouest Vertical] setClosure CMDCANCELLED
1|homebridge  | [2019-3-9 08:38:17] [Tahoma] [Store Ouest Vertical] setClosure COMPLETED

Merci pour ton aide.

**Comment by navjul** [comment]
Je retrouve le bon fonctionnement en modifiant ton fichier comme suit :

[Awning.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2948202/Awning.js.zip)

Voici ce que j'ai dans les logs :

1|homebrid | [2019-3-9 09:12:41] [Tahoma] [Store Ouest Vertical] device type: ExteriorScreen, name: io:VerticalExteriorAwningIOComponent, protocol: io

1|homebridge  | [2019-3-9 09:14:39] [Tahoma] [Store Ouest Vertical] setDeployment[29]
1|homebridge  | [2019-3-9 09:14:46] [Tahoma] [Store Ouest Vertical] setDeployment[10]
1|homebridge  | [2019-3-9 09:14:48] [Tahoma] [Store Ouest Vertical] setDeployment CMDCANCELLED
1|homebridge  | [2019-3-9 09:14:50] [Tahoma] [Store Ouest Vertical] setDeployment COMPLETED
1|homebridge  | [2019-3-9 09:14:55] [Tahoma] [Store Ouest Vertical] setDeployment[0]
1|homebridge  | [2019-3-9 09:15:00] [Tahoma] [Store Ouest Vertical] setDeployment COMPLETED

**Comment by dubocr** [comment]
Sorry, as you have ExteriorScreen, the config to set is :
`"ExteriorScreen": { "reverse": true }`

**Comment by dubocr** [comment]
But in the latest release you installation will be considered as "normal" so you won't need to set the reverse parameter.

**Comment by navjul** [comment]
All is OK with latest version and this config :

"ExteriorScreen": { "reverse": false }

Without this parameters, that's not OK.

Thanks again.

**Comment by artik** [comment]
navjul, you had to edit Awning.js too, or just adding "ExteriorScreen": { "reverse": false } without nothing else is working?

**Comment by navjul** [comment]
@artik  with latests versions I'm only using this parameter : 

"WindowCovering": { "reverse": true },

without nothing else !

**Comment by artik** [comment]
Merci pour ta réponse @navjul , j'ai test:

`"WindowCovering": { "reverse": true }`

mais ça m'inverse tout du coup (ce qui est normal quand je regarde les logs):

```
[11/30/2019, 1:53:43 AM] [My TaHoma Box] [Salon entrée] type: ExteriorScreen > PositionableScreen, protocol: io
[11/30/2019, 1:53:43 AM] [My TaHoma Box] Instanciate Salon entrée as WindowCovering
[11/30/2019, 1:53:43 AM] [My TaHoma Box] [Salon frigo] type: ExteriorScreen > PositionableScreen, protocol: io
[11/30/2019, 1:53:43 AM] [My TaHoma Box] Instanciate Salon frigo as WindowCovering
[11/30/2019, 1:53:43 AM] [My TaHoma Box] [Salon terrasse] type: ExteriorScreen > PositionableScreen, protocol: io
[11/30/2019, 1:53:43 AM] [My TaHoma Box] Instanciate Salon terrasse as WindowCovering
[11/30/2019, 1:53:43 AM] [My TaHoma Box] [Salon focale] type: ExteriorScreen > PositionableScreen, protocol: io
[11/30/2019, 1:53:43 AM] [My TaHoma Box] Instanciate Salon focale as WindowCovering
[11/30/2019, 1:53:43 AM] [My TaHoma Box] [Salon big right] type: Awning > PositionableHorizontalAwning, protocol: io
[11/30/2019, 1:53:43 AM] [My TaHoma Box] Instanciate Salon big right as WindowCovering
[11/30/2019, 1:53:43 AM] [My TaHoma Box] [Salon big left] type: Awning > PositionableHorizontalAwning, protocol: io
[11/30/2019, 1:53:43 AM] [My TaHoma Box] Instanciate Salon big left as WindowCovering
```
Les 2 volets qui posent problème sont les 2 "type: Awning". J'ai donc essayé:

```
            "Awning": {
                "reverse": true
            }
```
 Mais ça ne fonctionne pas (de même que "false"). Qu'est ce que je peux essayer ?

**Comment by dubocr** [comment]
Hi,

Sorry for this long silence... working hard lasts months : 

So actualy 2 options 👍 

If you have this init logs : 

ˋˋ
[DeviceName] type: Awning > PositionableHorizontalAwning, protocol: io
Instanciate DeviceName as WindowCovering
ˋˋ

You can reverse behaviour by HomeKit widget type like that : 
ˋ"WindowCovering": { "reverse": true }ˋ

Or by TaHoma widget type like that :
ˋ"PositionableHorizontalAwning": { "reverse": true }ˋ to affect only this kind of TaHoma device.
