### ISSUE TITLE
scenarios are not longer visible

### ISSUE THREAD

**Issue by jub11** [dubocr/homebridge-tahoma#480]
Since yeseterday I can‘t see my scenarios anymore in homebridge & HomeKit. The „expose scenarios„ is not set, here is my config:

```json
{
            "name": "My TaHoma Box",
            "service": "somfy_europe",
            "user": "email@mail.de",
            "password": "password",
            "exposeScenarios": false,
            "exclude": [
                "Alarm",
                "Bad links",
                "Bad rechts",
                "Küche",
                "KZ Tür",
                "SZ Fenster",
                "SZ Tür",
                "Markise"
            ],
            "platform": "Tahoma"
}
```

I haven‘t changed any config these days.

**Comment by dubocr** [comment]
Hi,

Are you using local API ?
What if you switch "exposeScenarios" to true ?

**Comment by jub11** [comment]
Hi dubocr,
if I set the configuration to „true“ I can see the scenarios again in my Apple Home App.
So the configuration is in the incorrect interpretation of true /false in this version.

Thanks for your help!
