### ISSUE TITLE
VenetianBlind.js this.stateless breaks blindMode

### ISSUE THREAD

**Issue by mman** [dubocr/homebridge-tahoma#522]
The commit https://github.com/dubocr/homebridge-tahoma/commit/b2fda5c91cc34f42b22a66b0df380196e889fc98

introduced the change around VenetianBlind.js line 45 https://github.com/dubocr/homebridge-tahoma/blob/8d476b13998d1f547529cbf46041c92ae26f898d/src/mappers/VenetianBlind.ts#L45 where if the device is reported as `!this.stateless` it will only allow full open or full close. I read that if the device is `!this.stateless` it is `stateful` and therefore able to report back its states?

I am not sure where `this.stateless` actually comes from, but it appears that my Somfy IO blinds are being reported as `!this.stateless` (therefore stateful) and therefore never reach the branch handling the `blindMode: true` setting on line 58.

https://github.com/dubocr/homebridge-tahoma/blob/8d476b13998d1f547529cbf46041c92ae26f898d/src/mappers/VenetianBlind.ts#L58

I have fixed this by reverting the commit above but I suppose there should be a more systematic fix.

**Comment by dubocr** [comment]
Hi everyone,

Sorry I was really busy and didn't have equipments anymore to test my changes. However, I made some changes based on your comments. Hope it will fix for you.

Let me know if it seems OK.

**Comment by mman** [comment]
@dubocr I have updated to 2.2.57 and can confirm that it works for me as before! Thanx!
