### ISSUE TITLE
Z-wave as fan

### ISSUE THREAD

**Issue by Jer3m** [dubocr/homebridge-tahoma#55]
Hello,
First, thanks for the plugin you did a great job.

I get a z-wave module connect to a fan, a roof fan.
Actually, HomeKit get this z-wave as a light, i can change image, but always for light.
I was wondering if there is a way to get a fan icon fan.
Is it possible to get a field into the config.json file like:
"fan_ids": []
Or anything else.

Regards

Jerem

**Comment by dubocr** [comment]
Bonjour Jerem,

Je regarderai avec la config que j’obtiendrai par l’analyse du problème de connexion. Il faudrait qu’il soir reconnu comme un switch ce qui te permettrait de choisir sur Homekit entre lumière/switch/ventilateur. En fonction de comment il apparaît sur Tahoma je verrai ce qu’on peut faire.

**Comment by Jer3m** [comment]
Super,

J’aurai quelques petites choses à te signaler concernant donc le ventilateur et le thermostat connecté, mais sinon c’est un vrai plaisir ce plugin.
En attendant je vais essayé de me focus sur le problème "loggin fail”.

Je suis dispo si tu as besoins de testeur.

Cordialement

**Comment by dubocr** [comment]
Ton module fait-il variateur ? Si oui tu ne pourrais plus le faire varier si il apparaît en switch sur Home. Il apparaît comme un DimmerLight sur Tahoma.
Comme tu as réussi à te logger sur ma page, peux-tu ressayer sur homebridge en visionnant les logs et m’envoyant les premières erreurs. Le too many request vient du fait que le plugin essaie de se connecter à plusieurs reprises mais ce n’est pas le problème initial.

Merci

**Comment by Jer3m** [comment]
> Ton module fait-il variateur ? Si oui tu ne pourrais plus le faire varier si il apparaît en switch sur Home. Il apparaît comme un DimmerLight sur Tahoma.
> 
Oui c’est bien un module avec variateur (Z-wave).
Les ventilateurs sous HomeKit apparaissent comme switch? Comment faire varier l’intensité alors ?
> Comme tu as réussi à te logger sur ma page, peux-tu ressayer sur homebridge en visionnant les logs et m’envoyant les premières erreurs.
> 

> Le too many request vient du fait que le plugin essaie de se connecter à plusieurs reprises mais ce n’est pas le problème initial.
> 
Je pensais à quelque chose comme ça.
Ce qui est étonnant c’est que j’ai installé unbuntu server 16.01 sur un bananapi, puis homebridge et enfin homebridge-tahoma avec un démarrage au lancement du système et j’avais jamais eu ça.

**Comment by Jer3m** [comment]
Bonjour,

As-tu pu jeter un œil sur le problème ?

**Comment by Jer3m** [comment]
Bonjour Romain,

J'ai eu une réponse d'un Yellow de chez Somfy concernant les messages d'erreurs lors des tentatives de loggin
Voici sa réponse:

_J'ai l'impression que votre box jeedom ou eedomus. essaie de ce connecté a votre compte trop souvent ce qui vous empêche de vous connecter a votre compte. 
Il faudra désactiver votre plug in tahoma et/ou changer la temporisation d’accès au compte a 6x par heure maximum (6 tokens/heure)._ 

Est-ce que le problème pourrait-être résolu en diminuant, dans le plugin, la fréquence de connection au compte ?

Cordialement

**Comment by dubocr** [comment]
Bonjour Jerem,

La fréquence d’actualisation par defaut est de 10min (6x/heure). Si tu as plusieurs systèmes qui se connectent simultanément cela peut effectivement poser problème. Tu peux réduire la fréquence avec le paramètre ‘refreshPeriod’ (en secondes) dans la config. Peut-être le passer à 1800 voir 3600 pour voir si c’est mieux.
Les ventilateurs ne sont effectivement pas réglables de ce fait. Je regarde si il existe un type spécifique autre.

**Comment by Jer3m** [comment]
Merci de ton retour,

Je n’ai plus d’autres systèmes qui tournent.
J’ai fait une nouvelle tentative avec les anciens paramètres mais toujours le même problème.
En revanche, si je fais sudo systemctl stop homebridge et que je le lance manuellement Homebridge, ça fonctionne, mais j’ai besoin que cela fonction sur un redémarrage.

Peux-tu être un peu plus précis concernant le ‘refreshPeriod’, je ne le trouve pas dans /usr/lib/node_modules/homebridge-tahoma/config.json.
Faut-il le rajouter, si oui comment ?

Cordialement

**Comment by dubocr** [comment]
Il faut le configurer dans la config homebridge, voir partie configuration du plugin : https://github.com/dubocr/homebridge-tahoma/blob/master/README.md
Tu dois arrêter homebridge sinon le plugin doit probablement essayer de se connecter en permanence. Une fois arrêté, cela permet à Tahoma d’accepter des nouvelles connexions je pense

**Comment by Jer3m** [comment]
Mais du coup quelle est la différence entre les tentatives de connection au démarrage et manuelle ?
Qu’est ce qui fait que lors d’un démarrage auto du plugin les demandes saturent le compte alors que manuellement ça passe ?

Jérémie

**Comment by dubocr** [comment]
Dans un cas (lancement via le service) homebridge redémarre en cas d’erreur et le plugin essaie de se connecter sans arrêt alors que dans l’autre (manuel) Tahoma n’est pas sollicité avant de lancer homebridge. Mais le problème semble ailleurs. Peux-tu stoper le service 10 minutes puis le lancer en regardant les logs m’envoyer les premières erreurs. Je pense qu’il y a une erreur de connexion au début puis qu’elle est masquée par la suite du fait que le plugin realise des tentatives en boucles.
Je vais apporter une amélioration pour réduire le rythme des tentatives en cas d’erreur.

**Comment by Jer3m** [comment]
Bonjour Romain,

Pour ton information, plus aucun système domotique n’est raccordé à mon routeur afin d’éviter tout conflit ou saturation du loggin, sauf quand je l’allume pour faire des essais.
Comme tu me l’as demandé voici le log homebridge au démarrage.


N’hésite pas si tu as la moindre question ou le moindre test à me faire faire.

**Comment by dubocr** [comment]
Je ne vois pas les logs. C’est un fichier ?

**Comment by Jer3m** [comment]
C’est une capture d’écran, que j’obtiens par la commande: journalctl -f -u homebridge

**Comment by dubocr** [comment]
Impec c'est bon, mais ce sont les logs du 3. Est-ce que tu observes toujours l'erreur getaddrinfo au démarrage ?

**Comment by dubocr** [comment]
Impec merci. Tu sembles avoir systématiquement l'erreur getaddrinfo. Mais pas en lancement manuel du coup ? Je vais t'envoyer un fichier avec plus de traces pour voir.

**Comment by Jer3m** [comment]
Super, désolé pour la perte de temps..
Les logs du 3 ? c'est un log effectué tout à l'heure, le système n'est pas configuré au niveau de la date.

J'observe à chaque log, suite à un démarrage auto, que je fais cette erreur de getaddinfo

**Comment by Jer3m** [comment]
Je peux t'envoyer le daemon.log si tu veux.
Je ne connais pas la commande pour "exporter" un fichier parcmètre.

**Comment by dubocr** [comment]
Peux-tu essayer les commandes suivantes :
`ping tahomalink.com`
et
`sudo ping tahomalink.com`

qu'obtiens tu ?

Peux tu ensuite remplacer le fichier overkiz-api.js dans le repertoire du plugin par celui-ci puis relancer homebridge.
[overkiz-api.zip](https://github.com/dubocr/homebridge-tahoma/files/2745303/overkiz-api.zip)

**Comment by Jer3m** [comment]
ping tahomalink.com
![ping tahomalink com](https://user-images.githubusercontent.com/46055914/50969299-4ab23900-14de-11e9-884e-6b7c90a104b5.png)

sudo ping tahomalink.com
![sudo ping tahomalink com](https://user-images.githubusercontent.com/46055914/50969314-57cf2800-14de-11e9-83f3-6e6a66584a6f.png)

Quelle commande faut-il taper pour ajouter un fichier ?

**Comment by dubocr** [comment]
Tu peux modifier le fichier en FTP/SFTP sinon tu le modifie avec vim ou nano :
echo "" > /chemin_dossier_plugin/overkiz-api.js
vi /chemin_dossier_plugin/overkiz-api.js
Copier/Coller le fichier puis enregistrer.

**Comment by Jer3m** [comment]
Bon, j'ai ouvert _overkiz-api.js_ en nano, effacer le contenu puis remplacer par le nouveau.
C'est pas très classe mais ca doit le faire :).

**Comment by dubocr** [comment]
Pourras-tu me dire si l'erreur apparaît quand même au démarrage mais que ça se poursuit néanmoins.

**Comment by Jer3m** [comment]
Apparemment je n'ai plus d'erreurs.

![capture d ecran 2019-01-10 a 14 18 59](https://user-images.githubusercontent.com/46055914/50970988-36246f80-14e3-11e9-829c-faf67f8653a2.png)

Je t'avais parlé de quelques petits trucs concernant
Le ventilateur reconnu comme lampe (micro module Z-wave à intensité réglable)
Du thermostat connecté:
     Apparaît grisé, on ne peut donc rien paramétrer via Homekit
     Affiche 0,0°C
     Le capteur d'humidité intégré n'apparaît pas
![image-1](https://user-images.githubusercontent.com/46055914/50971278-ea25fa80-14e3-11e9-9964-c747f500f0cb.jpeg)

Devrais-je ouvrir un nouveau topic pour éviter de polluer celui-ci et surtout aurais-tu la possibilité de voir ça ?

**Comment by dubocr** [comment]
Dans le répertoire accessories du plugin, ajoute le fichier (dézipé) suivant (ou `nano HumiditySensor.js` puis colle le contenu du fichier)
[HumiditySensor.zip](https://github.com/dubocr/homebridge-tahoma/files/2745550/HumiditySensor.zip)

Dans le fichier de config homebridge, ajoutes le paramètre 'exclude' avec les capteurs à rattacher au thermostat :
`exclude: ["Humidité","T°C S.à M."]`

Pour intégrer le thermostat Somfy, peux-tu exécuter des opérations (monter T°, déscendre T°, mettre en arrêt, mettre en auto, mettre en manuel, arrêter) puis te reconnecter à [https://home.duboc.pro/tools/setup](https://home.duboc.pro/tools/setup) pour que je puisse récupérer l'historique des commandes et les intégrer.

Merci.

**Comment by Jer3m** [comment]
Fait.

Le capteur d'humidité n'apparait toujours pas.
En revanche la temperature pour thermostat est correcte et t° S. à M. est bien exclue.
Je me suis connecté à ta page suite aux différentes manip.

**Comment by dubocr** [comment]
Voici le fichier pour remplacer accessories/HeatingSystem.js

[HeatingSystem.zip](https://github.com/dubocr/homebridge-tahoma/files/2745903/HeatingSystem.zip)

Il doit apporter la gestion du capteur d'Humidité et un premier jet pour la gestion du Thermostat avec la gestion suivante des modes :
A la maison/Géofencing/Manuel : Chauffage
Nuit/Fenêtre ouverte ? : Rafraîchissement
Absent/Hors Gel : Off

**Comment by Jer3m** [comment]
Super !!

![image-1](https://user-images.githubusercontent.com/46055914/50979697-5827ed00-14f7-11e9-9cc6-47b1910bf957.jpeg)
Dans l'affichage en haut des favoris sur HomeKit, la température du salon est suivi de .chauffage, est-il possible de l'enlever?

Dans les réglages du thermostat j'ai cette fenêtre.
![image-1-1](https://user-images.githubusercontent.com/46055914/50979916-d08eae00-14f7-11e9-86be-52895a2c32bb.jpeg)
A quoi correspond chacun de ces 4 éléments ?
Si tu es obligé de restreindre la quantité d'option à 4, peux-tu privilégier mode eco, mode normal, mode automatique et mode nuit?

Enfin, j'ai enlevé humidité des exclusions du fichier de config, j'ai bien son affichage en haut dans les favoris d'homekit, en revanche serait-il possible d'avoir le même genre d'accessoire que pour la t°c plutôt qu'un switch ?
![image-1-2](https://user-images.githubusercontent.com/46055914/50980010-06cc2d80-14f8-11e9-9b41-48612fd2b064.jpeg)

En tous les cas un grand merci pour ta disponibilité et ta réactivité.

**Comment by dubocr** [comment]
Super,
Concernant l’humidité ce n’est pas un switch mais un capteur qui est représenté par le picto. Et malheureusement comme pour le ventilateur tout ces points concernent l’application Home ou HomeKit.
Tu peux avoir un rendu différent avec une application comme Eve Elgato mais globalement les différentes capteurs ne changeront pas.
Pour le thermostat, c’est le mieux qui existe côté HomeKit (un thermostat type climatisation réversible). Rien du type eco/confort à l’heure actuelle a ma connaissance. La mention « chauffage » ne peut pas être enlevée toute cette partie est gérée par l’appli Home.

**Comment by dubocr** [comment]
Oui les capteurs de Tº s’affichent differement.
L'humidité peut s’afficher si elle est activé (réglage du capteur > etat et notification > inclure dans état) mais le nombre de ligne est limité. Pour l’humidité rattachée au thermostat pas sûr effectivement je n’ai pas ce genre de capteur et n’ai pas eu l’occasion d’observer le comportement.

J’ai mis plus haut les correspondances il faut inverser effectivement pour les commandes mais ça donne :

Auto : Mode non dérogé (automatique probablement oui)
Chauffer : A la maison
Rafraîch. : Nuit
Off : Absent

**Comment by Jer3m** [comment]
OK je note ca.
J'ai modifié le message précédent, l'humidité intégré au thermostat s'affiche bien en haut.
Une petite icône de ventilateur animé aurait-été la cerise sur le gateau ;)
Devrais-je modifier à nouveau les fichiers .js que tu as réécrit si réinstaller homebridge-tahoma ou le plugin sera t-il mise à jour ?

En tous les cas  maintenant tout est fonctionnel.
Je te remercie énormément pour le temps passé et ton efficacité, ton plugin est une tuerie ;)

**Comment by dubocr** [comment]
Oui le plugin sera mis a jour en cas de réinstallation la version intégrera ces évolutions.
Bon usage 😉

**Comment by dubocr** [comment]
J’ai trouvé un service spécifique pour le ventilateur. Je vais t’envoyer un nouveau fichier demain par contre celui ci ne sera pas intégré dans les mises a jour car il n’y a pas de moyen de déterminer si il s’agit d’une lampe ou d’un ventilateur. Je réfléchis comment rendre ca parametrable par la suite.

**Comment by Jer3m** [comment]
Génial, vivement demain ;)

**Comment by dubocr** [comment]
Ou ce soir...
Fichier à remplacer dans accessories
[Light.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2747038/Light.js.zip)

**Comment by Jer3m** [comment]
Ah bah si….. y'a la cerise sur le gâteau :D
Testé et approuvé, un très grand merci à toi Romain.
![image-1-4](https://user-images.githubusercontent.com/46055914/50997497-05652a00-1525-11e9-84c2-810c3dfcc6bd.jpeg)

**Comment by Jer3m** [comment]
Le ventilateur s’appelait ventilateur pour que Siri me comprenne, mais je vais pouvoir le nommer comme je le veux maintenant.
Pas de soucis pour le fichier, je testerai ça avec plaisir.

**Comment by dubocr** [comment]
Voici les fichiers. Fan.js et Light.js dans accessories et index.js à la racine.
[Fan.zip](https://github.com/dubocr/homebridge-tahoma/files/2748674/Fan.zip)
[Light.zip](https://github.com/dubocr/homebridge-tahoma/files/2748688/Light.zip)
[index.zip](https://github.com/dubocr/homebridge-tahoma/files/2748680/index.zip)

Ensuite il faudra ajouter la configuration suivante :
`"forceType" : { "Ventilateur" : "Fan" }`

En espérant que ça fonctionne du 1er coup.

**Comment by dubocr** [comment]
Non les 3 fichiers sont à mettre manuellement pour que tu puisses tester pour l'instant encore.
Oui "forceType" : { "Ventilateur" : "Fan” } à ajouter dans le config.json d'homebridge au même niveau que "exclude", "user", "password", etc.

**Comment by Jer3m** [comment]
_Dans accessories du plugin_
Modification du fichier Light.js -> fait
Création du fichier Fan.js ->fait
Création du fichier index.js ->fait

_Dans le fichier de config homebridge_
Rajout de "forceType" : { "Ventilateur" : "Fan" } ->fait

Sudo reboot, homebridge ne semble pas démarrer.

Le log me dit ceci:
![capture d ecran 2019-01-11 a 09 52 42](https://user-images.githubusercontent.com/46055914/51023244-bd76ef00-1586-11e9-8e0b-3c7619a7b3fb.png)

**Comment by Jer3m** [comment]
Désolé Romain, j'avais oublié une virgule à la suite de la ligne à rajouter dans le fichier de config.
Le fichier est maintenant correct.

Mais après un redémarrage, homebridge ne s'est pas lancé.
![capture d ecran 2019-01-11 a 10 08 24](https://user-images.githubusercontent.com/46055914/51024082-de404400-1588-11e9-9fdc-e4d3db152d42.png)

**Comment by dubocr** [comment]
Le fichier index.js existe déjà normalement, à la racine. Essai dans un premier temps sans modifier le fichier de config.

**Comment by Jer3m** [comment]
Si à la racine c'est dans le fichier accessories du plugin, alors nano index.js m'a ouvert un fichier vide.
Si j'enlève "forceType" : { "Ventilateur" : "Fan" }, du fichier de config j'obtiens ça

![capture d ecran 2019-01-11 a 10 17 26](https://user-images.githubusercontent.com/46055914/51024534-1d22c980-158a-11e9-936b-4c988f10948a.png)

**Comment by dubocr** [comment]
Stop le service homebridge et attend 10min avant de le relancer.
Une petite mise à jour du fichier index.js : 
[index.zip](https://github.com/dubocr/homebridge-tahoma/files/2749157/index.zip)

**Comment by Jer3m** [comment]
Modification du fichier.
![capture d ecran 2019-01-11 a 11 14 39](https://user-images.githubusercontent.com/46055914/51027852-33348800-1592-11e9-9cc3-133acdee6ef0.png)

**Comment by dubocr** [comment]
Ta connexion internet est bonne en débit montant ? Ce problème de résolution DNS ponctuel est soit lié à la connexion soit à des requêtes en masse. Essai en lançant manuellement.

**Comment by Jer3m** [comment]
Bah j'ai pas la fibre mais la connection est bonne, l'upload est pas folle mais j'ai jamais eu de soucis particuliers.
Homebridge se lance au démarrage (manuel ou automatique), j'ai bien le pont homebridge sous HomeKit mais aucun accessoires Somfy.
J'ai le même log que précédemment.

**Comment by dubocr** [comment]
Quand tu quittes l'application Home et que tu retournes dessus, est-ce que les logs affichent à nouveau des choses ?

**Comment by Jer3m** [comment]
Je viens de relancer homebridge après un moment d'inactivité.
Le problème est toujours le même mais il y a une petite différence du Main PID
![capture d ecran 2019-01-11 a 16 17 15](https://user-images.githubusercontent.com/46055914/51042459-a81cb780-15bc-11e9-9942-a61b91c411c7.png)

**Comment by Jer3m** [comment]
Du coup, je reviens à la config fonctionnelle ?

**Comment by dubocr** [comment]
Oui tu peux pour l’instant mais je doute que cela change quelque chose car rien de lié au problème n’a été modifié depuis le début. Essaie tout de même de revenir a la configuration présente au moment où ca à marché on sait jamais.

**Comment by Jer3m** [comment]
Oui revenir à l’étape où ça fonctionnait.

Tu sais d’où provient le problème rencontré?

**Comment by dubocr** [comment]
Non, tu me diras si c’est mieux en revenant en arrière mais en principe il n’y a pas de lien. On verra déjà et je vais revoir le dernier jeux de fichier la semaine prochaine.

**Comment by Jer3m** [comment]
Après la désinstallation du plugin, je l’ai réimplanté et réédité les premiers fichiers modifiés.
Tout est ok.
👌

**Comment by Jer3m** [comment]
Bonjour Romain,

J'espère avoir été clair en répondant à tes questions.

J'ai remarqué que la température du chauffage ne changeait pas lorsque je la modifie à partir de l'application HomeKit, le thermostat passe bien en dérogation mais la température éditée sous HomeKit ne semble pas appliquée au thermostat, une idée ?

Autre question, je vais recevoir des interfaces de chauffage io Somfy.
Ces interfaces sont-elles intégrées dans le plugin ?

Cordialement

Jérémie

**Comment by dubocr** [comment]
Bonjour Jerem,

Oui c'est clair pour moi, il faut que je me penche sur les derniers fichiers mais il faut que j'ai accès à mon installation ce qui n'était pas les cas ces derniers jours. Je regarderai le problème de T° en même temps.
Pour les interfaces IO, je pense qu'elles le sont (SomfyPilotWireElectricalHeater présent dans un fichier) mais sous forme de switch ON/OFF (Confort/Eco)

**Comment by Jer3m** [comment]
Ok super.

ll semblerait que les interfaces puissent piloter, en mode manuel:
Confort
Eco
Hors Gel
Off
Serait-il possible de faire correspondre ces réglages avec les 4 boutons HomeKit Éteint, Chauffer, Refroidir, Automatique, quand tu auras le temps bien évidemment ?

**Comment by dubocr** [comment]
Oui c'est ce que je pensais faire en regardant. Mais il n'y aura pas de T° du coup et l'association serait plutôt la suivante :
Auto <-> Automatique
Confort <-> Chauffer
Eco <-> Refroidir
Hors Gel <-> Arrêt

**Comment by Jer3m** [comment]
Ah....il ne pourra pas être de la même forme que le thermostat avec l'indication de température...
De toute façon on verra cela au moment venu.

**Comment by dubocr** [comment]
Si mais la T° sera à 0 car il n'y a pas de capteur de T° à rattacher.

**Comment by Jer3m** [comment]
Et oui, évidemment....

Tu as la possibilité de "retour" d'informations avec Tahoma?
Lors de la première mise en route du plugin, les volets par exemple, sont réglés à 50% sur HomeKit, or il ne peuvent être que ouverts ou fermés.
J'ai remarqué la même chose avec le ventilateur, iil s'est lancé suite à une SMART, en allant sur HomeKit, il apparaissaient bien comme actif mais avec l'intensité à 0% or il tournait à 95%.

**Comment by dubocr** [comment]
Ca dépend des capteurs. Les volets RTS ne remontent pas d'information (ils sont donc dans un état "par défaut" au démarrage d'homebridge). Pour le ventilateur c'est qu'il y a un nouvel état coté TaHoma visiblement, je vais l'ajouter également.

**Comment by Jer3m** [comment]
Donc il faut privilégier le io pour le retour d'informations :D

Au démarrage d'homebridge, il n'est pas possible d'aller chercher les informations dans Tahoma?
Si les volets sont fermés, Tahoma le sait donc homebridge-Tahoma devrait pouvoir le savoir non ?

J'avais aussi remarqué ça pour le thermostat connecté...

**Comment by Jer3m** [comment]
Alors que sur mes essais de ce week-end je pouvais modifier la temperature via HomeKit si je refais la même manip maintenant il se remet sur la température initiale avec la mention _"Sans réponses"_ en revenant sur la page de la pièce, l'accessoire thermostat est grisé et si je clic à nouveau dessus j'ai ça:
![image-1](https://user-images.githubusercontent.com/46055914/51178639-714be780-18c3-11e9-882f-449ab4d76339.jpeg)

J'ai malgré tout fait la manip sur l'application Tahoma et je me suis loggé sur ta page.

**Comment by Jer3m** [comment]
Bon apparemment, après être allé sur l'application dédié au thermostat connecté et être revenu sur HomeKit, je peux refaire la manip donc refait.

En fait ça semblait fonctionné, vérifie.

Je sais pourquoi ça bug, si je demande une température trop importante sous HomeKit, alors l'accessoire thermostat bug, apparemment au-delà de 26°C.
Il faut que je quitte HomeKit, que je fasse quelques manip sous l'application du thermostat connecté, puis en rouvrant HomeKit, l'accessoire semble débuggé...

**Comment by dubocr** [comment]
Tu devrais avoir des choses dans les logs homebridge au moment ou ça plante.

**Comment by Jer3m** [comment]
Ok voici le log après le plantage.
![capture d ecran 2019-01-15 a 14 49 30](https://user-images.githubusercontent.com/46055914/51184544-d825cc80-18d4-11e9-852e-af0c6ba90b86.png)

**Comment by Jer3m** [comment]
Plus simple, voici le log suite à l'augmentation de la température qui fait bugguer l'accessoire thermostat
![capture d ecran 2019-01-15 a 16 53 36](https://user-images.githubusercontent.com/46055914/51192151-39a26700-18e6-11e9-9c1f-56f7ea5bd451.png)

**Comment by dubocr** [comment]
Voici les derniers fichiers
Dans le sens TaHoma -> Homekit, le rafraîchissement se fait toutes les 10 min (paramètre refreshPeriod)
[homebridge.zip](https://github.com/dubocr/homebridge-tahoma/files/2761353/homebridge.zip)

**Comment by Jer3m** [comment]
Apparemment toujours le même soucis.
![capture d ecran 2019-01-15 a 22 02 16](https://user-images.githubusercontent.com/46055914/51209801-6324b800-1911-11e9-8879-52daec0f6e86.png)

**Comment by dubocr** [comment]
Peux tu modifier la t° avec Tahoma dans les différents modes et te connecter sur https://home.duboc.pro/tools/setup
Si tu remets les fichiers index.js du zip, cela produit à nouveau l'erreur et si tu le retire à nouveau l'erreur disparaît ? Essai de mettre à jour le plugin complètement.
Le pas de T° est bien de 0,1° par défaut tu dois pouvoir le définir à cette précision avec Eve probablement.

**Comment by Jer3m** [comment]
Je viens de me logger après avoir modifié les T°C des modes:
À la maison
Absent
Nuit

Après que tu m'aies envoyé le fichier homebridge hier soir, j'ai tout installé mais error 443.
J'ai remis l'ancien fichier overkiz-api.js je relance, error 443.
J'ai remis le nouveau fichier overkiz-api.js et changé le fichier index.js avec l'ancien (celui téléchargé avec le plugin il y a une semaine à peu près) là pas d'erreur de loggin, en revanche le ventilateur apparaît avec l'icône lumière, je sais pas si c'est lié ou si c'est un bug dans le fichier Fan.js ou Light.js.

Quand je change la température sur HomeKit c'est au pas de 0,5°, c'est en réalité plus précis car dans le log je vois que je suis à 17,3 ou 17,4.
Peut-être que tu ne peux pas modifier cela.

**Comment by Jer3m** [comment]
En fait, je n'arrive pas à savoir qu'elle serait la méthode la plus simple pour ce chauffage.
On est obligé d'avoir Eteint, Chauffer, Refroidir, Automatique.
Sur la cette page est affichée la température de la pièce (dans le cercle) et la température demandée derrière la mention chauffage.
La où je m'embrouille c'est que chaque mode affiche la même chose or la température demandée devrait affichée celle qui a été intégré à Somfy/Tahoma (A la maison 19°, Absent 16°, Nuit 17,5°)
Quand je modifie la température du mode A la maison, il faudrait que ca modifie la température enregistré du mode A la maison, sans pour autant que cela me mette en mode manuel.

Tout l'interêt réside dans le fait de savoir si il est possible d'avoir les données de Tahoma sur HomeKit. Sinon ca restera illisible, à mon avis mais ton avis et tes conseils sont les bienvenus :).

Tu m'as dit que Tahoma -> Homekit rafraîchissement toutes les 10 min donc HomeKit peux avoir les informations de Tahoma ?
Pourquoi toutes les 10 min il faudrait que cela soit plus rapide sans que ça sature ?

Excuse moi pour ces questions un peu naïves mais j'essaye de comprendre :)

**Comment by dubocr** [comment]
A priori rien n'est envoyé quand tu changes la T° (dans la partie History quand tu te logues il n'y à rien cet après-midi).
Pour gérer la T° en fonction des modes, il faudrait savoir si TaHoma met à jour "core:TargetTemperatureState" quand on change de mode (mettre un mode, se connecter sur ma page et regarder la valeur de core:TargetTemperatureState (dans HeatingSystem > SomfyThermostat) puis changer de mode et faire la même chose). Car jusqu'à présent je n'ai eu que le mode manuel d'affiché.
Oui on peut avoir les données de TaHoma (celles présentes lorsque tu te connectes sur ma page). Mais comme TaHoma ne "pousse" pas ces données, il faut aller les "chercher" et comme nous sommes limité à 1 connexion toutes les 10 minutes alors on ne peut rafraîchir que toutes les 10 min.

Pour le Ventilateur, il faut ajouter `"forceType": {"Ventilateur": "Fan"}` dans la config.

Dernièrement, j'ai modifié pour que la mise à jour de la T° sur Homekit n'envoi plus `setDerogation(T°)` qui provoque le passage en mode manuel visiblement mais `setModeTemperature(modeCourant, T°)` qui devrait selon moi mettre à jour la T° du mode en cours. Mais il est possible que celle-ci ne soit alors pas prise en compte sur le Thermostat ?

**Comment by Jer3m** [comment]
Impec pour le ventilateur mais après modification j'ai redémarré le server du coup je n'ai pas le bon pourcentage, j'ai 0%.

Sous Tahoma, il ne m'est pas possible de changer la temperature des modes sauf si je me met en mode manuel.
Pour changer les températures des modes je le fais via l'application thermostat...

Via Tahoma je viens de:
1-Passer de Programmation à dérogation -> mode à la maison
2-Passer en Mode absent
3-Passer en Mode Nuit
4-Passer en Mode manuel
5-Augmenter puis diminuer de la temperature
6-Passer en mode à la maison
7-Retour au mode programmation

**Comment by dubocr** [comment]
Dans ce cas le comportement précédent était le bon (changement de T° => passage en mode manuel). Tu ne peux pas avoir plus que ce que ne permet TaHoma. Homebridge ne fait qu'associer ce que fait TaHoma avec ce que permet de faire Homekit (ou Home).
Peux tu prendre un copie d'écran de ma page (de la partie HeatingSystem > SomfyThermostat uniquement) pour le mode auto, manuel, à la maison pour essayer de comprendre le fonctionnement.

Pour le ventilateur, tu devrais avoir sur Home ce que tu as sur ma page pour core:LightIntensityState (dans Light > DimmerLight)

**Comment by Jer3m** [comment]
Oui je pense que tu as raison.
Dès que l'on change la T°C alors dérogation en mode manuel.

![capture d ecran 2019-01-16 a 18 06 07](https://user-images.githubusercontent.com/46055914/51265702-a5a1cf80-19b9-11e9-9b66-e58b8f815c93.png)

Pour le ventilateur, actuellement il tourne mais affiche 0% sur HomeKit
![capture d ecran 2019-01-16 a 18 10 22](https://user-images.githubusercontent.com/46055914/51265867-08936680-19ba-11e9-9df4-76980f9854da.png)

**Comment by dubocr** [comment]
Tu peux mettre à jour le plugin c'est corrigé.
Tu peux continuer à analyser le comportement des states pour comprendre quoi sert à quoi.
De mon côté je pense que :
core:DerogatedTargetTemperatureState : Température en mode manuel ?
core:DerogationActivationState : Dérogation en cours ou non (donc mode auto actif ou non)
core:TargetTemperatureState : T° de consigne en cours (c'est celle que j'affiche sur HomeKit comme consigne)
somfythermostat:[...]TargetTemperatureState : T° de consigne du mode concerné

Il manquerait : T° de consigne en mode auto et comment la modifier.

**Comment by Jer3m** [comment]
> Tu peux mettre à jour le plugin c'est corrigé.
> Tu peux continuer à analyser le comportement des states pour comprendre quoi sert à quoi.
> De mon côté je pense que :
> core:DerogatedTargetTemperatureState : Température en mode manuel ?
Oui, c’est la température du mode sélectionné en dérogation (A la maison, absent, nuit, geofencing et manuel)
>  core:DerogationActivationState : Dérogation en cours ou non (donc mode auto actif ou non)
Ca à l’air d’être ça mais ça prend beaucoup de temps à s’actualiser environ 3-4 min.
>  core:TargetTemperatureState : T° de consigne en cours (c’est celle que j'affiche sur HomeKit comme consigne)
Cela aussi l’air d’être ça, T°c des modes en dérogation et du mode auto, là aussi prend beaucoup de temps à s’actualiser.
>  somfythermostat:[...]TargetTemperatureState : T° de consigne du mode concerné
C’est ça, ce sont les températures que l’on éditent seulement dans l’application Thermostat, qui sont fixes et que l’on ne peut pas modifier sous Tahoma.
> Il manquerait : T° de consigne en mode auto et comment la modifier.
T° de consigne core:TargetTemperatureState
Le mode auto est en fait un mode composé des modes à la maison, absent, nuit et geofencing, la T° du mode auto est la T° d’un des modes (hormis le manuel)
Si je suis en mode auto sur Homekit (programmation chez Somfy), et que je choisi de modifier la température,
alors je passe en dérogation mode manuel comme pour les autres modes en fin de compte.


Hormis des temps d’actualisation assez long mais qui ne viennent probablement pas du plugin, c’est plutôt pas mal, j’espère que cela sera utile à la communauté.
Je te remercie énormément pour le temps passé, ta disponibilité et ton efficacité c’est un vrai plaisir.
N’hésite pas à me contacter si tu as besoin de faire des tests, dans la limite des mes accessoires et de mes compétences :)

Je vais très prochainement recevoir des interfaces de chauffage, je me permettrais de te contacter si tout n’était pas fonctionnel.

Bien cordialement

Jérémie

**Comment by dubocr** [comment]
Quand tu parles d'actualisation tu veux dire entre l'action TaHoma et Home ou entre l'action TaHoma et quand tu te connectes à ma page ?
Pas de souci pour les interfaces, tiens moi au courant.

**Comment by Jer3m** [comment]
Les deux en fait.
Une fois l’action effectuée sur Tahoma que ça soit sur ta page ou HomeKit, l’actualisation est longue (au moins pour les deux actions précédemment signalées).
Quand c’est actualisé sur ta page, alors ça l’est sur HomeKit et inversement.

**Comment by dubocr** [comment]
OK,
En fonction du fonctionnement du Thermostat l'état n'est peut-être pas synchronisé instantanément avec TaHoma car visiblement c'est un thermostat indépendant puisqu'il peut-être géré via une appli autre que TaHoma. La box TaHoma n'est donc pas le contrôleur principal et en fonction du moyen de synchronisation entre les deux le délais peut s'expliquer effectivement.

**Comment by Jer3m** [comment]
Ouai j’y avais pensé.
Tout fonctionne 👍 merci.

J’arrête d’alimenter ce topic que tu as clos.
