### ISSUE TITLE
IO Thermor/Atlantic radiators

### ISSUE THREAD

**Issue by Alcor72** [dubocr/homebridge-tahoma#56]
Hi,

First, thanks for the job done!
For myself, the 6 RTS roller shutters works fine with your plugin. 
That was my first goal, to get the roller shutters in homekit world. That's done!

I also have 5 IO radiators connected to the tahoma box.
They appears in homekit but in a strange way.
I could command the temperature I want with a slider (that is declared as a clim) but it does not work (got "no response" message when I tried to modify the temperature). In addition, the temperature shown on this clim accessory is 0.0°C...
I also got a temperature sensor (that seems to get the info from the radiator) and a controlled outlet (also coming from the radiator). 

I have smart radiator valves (homekit compatible) and the temperature command and feedbacks is in the same accessory, here I have 2 different accessories for normally one only.

Any chance to get this modified to work properly?

Again, very good job for RTS Roller shutters!

**Comment by dubocr** [comment]
Hi,

Can you control one of your heaters with your Cozytouch app to execute each commands that fails with the plugin then log to this page https://home.duboc.pro/tools/setup

This will let me retrieve your Cozytouch config and last command history to implement it or fix it in the plugin.

When done, could you tel me what command (in the good order) you executed.

Thank you.

**Comment by dubocr** [comment]
To regroup the Tº widget and thermostat, add ´"exclude": ["Name of your widget"]’ in your config file.
For the non response, please log the link above.

Thanks
