### ISSUE TITLE
[Tahoma] Loggin fail: Too many requests, try again later

### ISSUE THREAD

**Issue by iWebbers** [dubocr/homebridge-tahoma#57]
I'm certain that my credentials are correct. After adding the needed lines to my config file Homebridge won't start up. It gives me the following log error:

**[Tahoma] Loggin fail: Too many requests, try again later**

When I remove the Tahome platform lines in config again, everything is starting up nicely but without Tahoma 👎

**Comment by dubocr** [comment]
Hi Guys,

Can you disable plugin in homebridge then wait several minutes and try to login to your tahoma app. If succeed, than try to login with your credential here : https://home.duboc.pro/tools/setup
And tel me if succeed.

Thanks.

**Comment by Jer3m** [comment]
Merci beaucoup de ton retour,

J’ai enlevé la partie Tahoma dans le fichier de config, essayé de me connecter à l’appli qui a fonctionné.
J’ai donc suivi le lien que tu mis.

**Comment by dubocr** [comment]
Passer refreshPeriod à 3600
