### ISSUE TITLE
Interface de Chauffage Somfy

### ISSUE THREAD

**Issue by Jer3m** [dubocr/homebridge-tahoma#59]
Bonjour Romain,

Je viens d'installer une interface de chauffage Somfy io.
Il est bien reconnu sous Tahoma, fonctionne.

En revanche lors de l'ajout à HomeKit, il me signale que l'accessoire est "sans réponse".
Il est pourtant bien chargé par homebridge, il s'appelle Veranda.
![capture d ecran 2019-01-19 a 14 59 41](https://user-images.githubusercontent.com/46055914/51427680-fa805880-1bfa-11e9-909b-69b69456c4ed.png)

Une idée ?

**Comment by dubocr** [comment]
Salut Jerem,

Il s’affiche sans réponse avant même de chercher a le piloter ? Peux-tu te connecter à ma page que je regarde comment il se présente.

Quand tu cliques dessus, des choses apparaissent elles dans les logs homebridge ?

Merci

**Comment by Jer3m** [comment]
Oui il s'affiche sans réponse avant même de chercher à le piloter et iil n'affiche rien sur le log enfin pas quand je clic dessus.

**Comment by dubocr** [comment]
Tu t’es connecté avec le même compte ?
Sous forme de quel appareil apparaît - il sous Home ? Un switch, un thermostat ?

**Comment by Jer3m** [comment]
Non effectivement c'est un nouveau compte.
Sous HomeKit cela apparait sous cette forme
![image-1](https://user-images.githubusercontent.com/46055914/51437259-12f47f80-1c9c-11e9-88cf-43d161918c88.jpeg)
![image-1-1](https://user-images.githubusercontent.com/46055914/51437263-1a1b8d80-1c9c-11e9-84e0-e17be7b3372a.jpeg)

**Comment by dubocr** [comment]
J'ai mis à jour le plugin, peux-tu faire la mise à jour et me dire si tu as du changement. J'ai fait quelques évolutions même si pour l'instant je ne vois pas d'où vient le problème. On sait jamais.

**Comment by Jer3m** [comment]
Super je regarde ça en rentrant ce soir.

**Comment by Jer3m** [comment]
Impeccable ça fonctionne

Eteint -> OFF (7°)
Chauffer -> Confort (19°)
Refroidir -> Econ (17,5°)
Auto->Auto

Le truc qui prête toujours à confusion, je trouve, c'est la température annoncé par Homekit qui ne correspond pas à la température des mode Eco et Confort.
Étant donné qu'en plus, avec les interfaces de chauffage, les températures des modes Eco et Confort sont fixes et sont celles du radiateur je pensais à la chose suivante.
Serait-il possible d'avoir dans le fichier de config du plugin une température pour le mode confort, eco et éteint (0°) qui soit paramétrable par l'utilisateur, on rentre la température de ces modes correspondant à celle des radiateurs et comme ça sous HomeKit la température du mode correspond à celle du radiateur.
Si on change la température d'un mode sur le radiateur, on va sur Homebridge et on la modifie aussi.
En plus avec l'UI de configuration l'accès à ton plugin et à sa configuration serait aisé.
Qu'en penses-tu ?

**Comment by dubocr** [comment]
J'ai effectivement mis les t° recommandées par l'ADEME pour ne pas laisser 0 mais dans tout les cas ce seront des T° fixes et la T° courante ne correspondra jamais à la réalité.
Tu peux néanmoins déjà fixer en général les T° avec la config suivante :
`"HeatingSystem" : { "temperature" : { "comfort": 21, "eco": 18 }}`
et ce fichier
[HeatingSystem.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2779142/HeatingSystem.js.zip)

**Comment by Jer3m** [comment]
J'ai remplacé le fichier HeatingSystem.js.
C'est dans config.json que je rajoute la ligne "HeatingSystem" : { "temperature" : { "comfort": 21, "eco": 18 }} car il ne semble pas valider la config ?

**Comment by dubocr** [comment]
Peix tu rajouter une ) avant le ; a la ligne 370

Pour obtenir.  ...comfort);

**Comment by Jer3m** [comment]
Fait, j'obtiens ça
![capture d ecran 2019-01-21 a 17 13 06](https://user-images.githubusercontent.com/46055914/51486052-f2155280-1d9f-11e9-96e2-dae6d62b93ae.png)

**Comment by dubocr** [comment]
Peux tu chercher ces deux ligne au début du fichier
this.temperature.comfort = config.temperature.comfort || 19;
	this.temperature.eco = config.temperature.comfort || 17;

Et ajouter celle-ci avant :
this.temperature = {};

**Comment by Jer3m** [comment]
Ca à l'air d'aller, en revanche la température indiqué par Homekit pour les accessoires ne correspond pas à celle indiquée dans le fichier de config. quelques soit mode, j'ai 19°C.

**Comment by Jer3m** [comment]
J'ai rajouté la ligne
![capture d ecran 2019-01-21 a 17 54 11](https://user-images.githubusercontent.com/46055914/51488357-9f3e9980-1da5-11e9-98f7-2d2ac6e5325e.png)

**Comment by Jer3m** [comment]
MàJ v0.1.30 effectuée.
Fonctionne parfaitement.

Merci mille fois Romain

**Comment by Jer3m** [comment]
Une autre chose,

j'ai plusieurs interfaces de chauffage et la temperature des modes eco et comfort n'est pas la même sur chacun des chauffages, je pense que tu me vois venir :)
Crois-tu qu'il serait possible de différencier les interfaces et de pouvoir rentrer dans le fichier de config les températures éco et comfort pour chacune des interfaces ?

**Comment by dubocr** [comment]
J'avais déjà compris cette demande :-) mais malheureusement je ne peux pas récupérer une config par instance mais uniquement par type (HeatingSystem) sans rentrer dans un début d'usine à gaz. Mais j'ai déjà ouvert la boite de pandore alors je vais aller au bout.

Le widget le plus approprié serait presque un simple switch mais nous n'aurions que 2 états (Confort/Off ou Confort/Eco) ce qui est plutôt dommage. Le choix du widget thermostat permet d'avoir 4 boutons mais apporte effectivement la tentation de faire quelques chose avec la T° et c'est une mauvaise démarche.
En espérant qu'un autre widget plus approprié fasse son apparition mais je pense que d'ici là Somfy aura déployé la compatibilité HomeKit. Je penses d'ailleurs que c'est pour ce genre de capteurs qu'ils ont pris du retard sur la compatibilité HomeKit car Apple n'accepterait pas ce genre de bidouilles.

C'est dans la version 1.32, voila la nouvelle config à mettre :
`"HeatingSystem": {"Rose":{"comfort":20,"eco":17}, "Bleu":{"comfort":19,"eco":18}}`

**Comment by Jer3m** [comment]
Je lisais sur le forum du site de Somfy que ça n'était pas prêt d'arriver.
Il y a notamment une histoire de retour d'informations qu'exigerait Apple de ses partenaires que Somfy ne serait pas en mesure de donner...
En espérant que cela arrive un jour sans que l'on soit obliger de changer tous les équipements, il y a des plugins bien pratiques fait par des artistes et qui nous sont très pratiques ;)

En tous les cas la v1.32 fonctionne à merveille avec les différentes zones, génial.
Au risque de me répéter, merci vraiment beaucoup pour ton travail et ta disponibilité.

Bien cordialement

Jérémie

**Comment by dubocr** [comment]
C’est vrai qu’il y a également cet histoire de retour d’info je pense que cela concerne les capteur RTS qui sont les capteurs historiques de Somfy, ne pas les rendre compatibles serait difficile à expliquer et c’est effectivement très bloquant.

Le vrai problème pour nous c’est qu’il n’y a eu aucun nouveau type de widget/capteur depuis longtemps et que c’est un peu pauvre pour répondre à tout les cas de figure.
Et pour le chauffage c’est vraiment le pire, chauffer/refroidir c’est vraiment limitant.
Ravi que cela te convienne en tout cas, bonne utilisation 😉.

**Comment by DylanJandala** [comment]
Bonjour, je cherche à rajouter mes volets TaHoma à HomeKit par l’intermédiaire de Homebridge
J’ai déjà installer Homebridge via l’invite de commande mais je n’ai pas pus faire le reste, comment faire ?

**Comment by MXCZK** [comment]
Bonjour,

Je me permets de poster ici car ma question concerne le chauffage Somfy IO via homebridge. J'utilise déjà le plugin Tahome Homebridge.

Ma question est la suivante : que permet ce plugin sur le chauffage IO ? 
- On/Off du chauffage ?
- Réglage de la température ?

Merci par avance pour la réponse.
