### ISSUE TITLE
Portes de garage et portail RTS

### ISSUE THREAD

**Issue by Kermarc44** [dubocr/homebridge-tahoma#60]
Bonjour,

J'ai installé le plugin tahoma sur mon raspberry pi.
Les volets (RTS) fonctionnent parfaitement dans homekit.
Par contre les portes de garage et le portail ne fonctionnent pas.
J'ai les messages suivants : 
[Portail] cycle[]
Error 400 Managed action group is invalid : No such command : cycle on device rts://1206-7815-0303/15711817 (rts:SlidingGateOpenerRTSComponent) (UNSPECIFIED_ERROR)

[Porte Garage 1] cycle[]
Error 400 Managed action group is invalid : No such command : cycle on device rts://1206-7815-0303/16721696 (rts:GarageDoorWithVentilationPositionRTSComponent) (UNSPECIFIED_ERROR)

[Porte Garage 2] cycle[]
Error 400 Managed action group is invalid : No such command : cycle on device rts://1206-7815-0303/16759743 (rts:GarageDoorWithVentilationPositionRTSComponent) (UNSPECIFIED_ERROR)

Merci pour votre aide.

Marc

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous vous connecter sur https://home.duboc.pro/tools/setup avec vos identifiants TaHoma afin de récupérer votre configuration.

Merci

**Comment by Kermarc44** [comment]
Voilà c'est fait

**Comment by dubocr** [comment]
Merci,

Vous pouvez mettre à jour le plugin ou remplacer le fichier Gate.js dans le répertoire accessoires du plugin par celui-ci
[Gate.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2776947/Gate.js.zip)

Cela devrait corriger le problème.

**Comment by Kermarc44** [comment]
Ça fonctionne. Merci beaucoup pour votre réactivité!

**Comment by Kermarc44** [comment]
Bonjour,

J’ai un nouveau petit souci.
Ce matin j’ai ouvert et refermé le portail et le garage 2. Depuis, dans l’application maison, ces 2 accessoires indiquent fermeture en cours.

Bonne journée.
Marc

**Comment by dubocr** [comment]
Effectivement il n'y a pas de retour d'état sur ces ouvrants, voici une mise à jour :
[Gate.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2779086/Gate.js.zip)

**Comment by Kermarc44** [comment]
Merci.
Étant débutant dans la programmation sur Raspberry Pi, pouvez-vous me dire comment remplacer le plugin avec le fichier zip? J’arrive bien à mettre à jour avec la commande npm install -g homebridge-tahoma mais remplacer le fichier gate.js je ne maîtrise pas.

**Comment by Kermarc44** [comment]
J'ai maintenant un message d'erreur : 
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /opt/node/lib/node_modules/homebridge-tahoma/accessories/AbstractAccessory.js:41:39
