### ISSUE TITLE
Alarme Somfy Home alarm

### ISSUE THREAD

**Issue by Kermarc44** [dubocr/homebridge-tahoma#62]
Bonjour,

J'ai une alarme Somfy Home Alarm que j'ai intégrée dans Tahoma.
Dans l'application Maison, il y a 4 états : 
  Désactivée
  Nuit
  A distance
  Domicile

Dans Tahoma, il y a 3 états : 
  Total
  Nuit
  Off

Apparemment il y a la gestion du retour d'état.
Aujourd'hui, la désactivation fonctionne bien.
Par contre j'ai noté quelques bugs : 
Quand j'active le mode "Nuit" dans l'application maison, le mode "Nuit" est bien activé dans Tahoma, mais le retour d'état dans l'application maison est "Domicile".
Quand j'active le mode "Domicile" dans maison, c'est en fait le mode "Nuit" qui est activé dans Tahoma.
Pour activer le mode "Total" de Tahoma, il faut choisir "A distance" dans l'application Maison.
Pour moi, je pense que "Domicile" dans l'application Maison doit correspondre à l'activation "Total" de Tahoma.
Par contre je ne vois pas à quoi sert le mode "A distance".

Bon week-end
Marc

**Comment by dubocr** [comment]
Bonjour,

Les modes homekit ont été interprétés de la façon suivante :

Désactivé : alarme off
Nuit : alarme partielle (protection des extérieurs et zones de vie)
A distance : Total (occupant hors de la maison)
Domicile : alarme perimetrique (occupant à domicile, protection du jardin)

Comme il n’existe pas de mode domicile dans Tahoma, c’est le mode nuit qui est activé (c’est le plus proche puisque partiel également). Je vais corriger pour que ce soit le mode nuit qui soit activé dans le retour d’etat puisque il est plus parlant.
