### ISSUE TITLE
Hitachi Climatisation

### ISSUE THREAD

**Issue by Seb0101** [dubocr/homebridge-tahoma#63]
Hi,
I was like Fabulon in october could not manage to make things work anymore with hitachi climatisation and homebridge-tahoma.
I have seen that you have made some modifications after, but it still does the same "TypeError: value.replace is not a function (...)", then crashes, reloads and now can't connect to tahoma with the message seen on other issues "Login fail: Too many requests, try again later".
Excluding all the air conditioners it works well after a while, I see the other IO equipments.
Am I doing wrong or does it mean I won't be able to connect anymore to my a/c ?
I'm on the latest release.
Thanks.

**Comment by dubocr** [comment]
Hi,

Can you try this file (replace file or content of file located in accessories of plugin directory).

[HitachiHeatingSystem.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2849198/HitachiHeatingSystem.js.zip)

Thanks

**Comment by Seb0101** [comment]
Bsr, j'ai remplacé le fichier, homebridge peut maintenant démarrer sans erreur. Mais uniquement tant que je ne lance pas l'app Home sur iOS. 
J'ai essayé avec ma config initiale, puis en supprimant l'import des scénarios, puis en réinitialisant complètement homekit+homebridge. La même erreur se produit, dès qu'il cherche l'état d'une des clim Hitachi.
Dans le fichier le log avec la séquence : [log homebridge.txt](https://github.com/dubocr/homebridge-tahoma/files/2853346/log.homebridge.txt)
Puis le QR code, et à nouveau l'erreur _[Tahoma] Login fail: Too many requests, try again later_
Si je patiente, je peux redémarrer homebridge sans erreur, mais uniquement jusqu'à utilisation de l'app Home...
Pour info, homebridge sur synology via docker et le package homebridge-syno-spk.
Merci à vous.

**Comment by dubocr** [comment]
Bonjour,

AS tu toujours l'erreur TypeError: data.replace is not a function
    at /homebridge/node_modules/homebridge-tahoma/accessories/HitachiHeatingSystem.js
dans la dernière version ?

Merci

**Comment by Seb0101** [comment]
Bsr, oui l'erreur est toujours là.
Petit changement : l'app maison voit toujours la passerelle homebridge mais pas les accessoires, il me semble qu'avant ce n'était pas le cas.
Voici le log ce soir : [homebridge.log](https://github.com/dubocr/homebridge-tahoma/files/2932818/homebridge.log)
Merci de tes efforts ! 
Cdt

**Comment by dubocr** [comment]
Bonsoir,

Peux-tu tester en remplaçant ce fichier. Il faudra peut-être mettre à l'arrêt homebrige quelques minutes afin de libérer le blocage TaHoma.

[HitachiHeatingSystem.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2932925/HitachiHeatingSystem.js.zip)

**Comment by Seb0101** [comment]
Bsr,
C'est mieux, les accessoires restent visibles et l'erreur TypeError: data.replace is not a function ne se produit plus.
Je peux accéder aux modes des clims, par contre nouvelle erreur si je modifie les températures (en mode chauffage ici) : "Error 400 Managed action group is invalid : globalControl() : Invalid value for command parameter p2 : expected integer value but got 26.5 (UNSPECIFIED_ERROR)". Ce qui m'a l'air moins problématique ?
Voici le log : [homebridge.log](https://github.com/dubocr/homebridge-tahoma/files/2963814/homebridge.log)
Merci !

**Comment by dubocr** [comment]
Oui effectivement on va juste arrondir la consigne car à priori cela n’accepte pas les décimales.
Je t’envoi un fichier pour tester dans la matinée.

Merci

**Comment by dubocr** [comment]
Peux tu tester avec ce fichier à dé zipper+remplacer dans le répertoire accessories du plugin :
[HitachiHeatingSystem.zip](https://github.com/dubocr/homebridge-tahoma/files/2965918/HitachiHeatingSystem.zip)

Merci

**Comment by Seb0101** [comment]
Bsr,
C'est parfait ! Plus de problème, contrôle opérationnel des 4 unités.
Merci encore, du coup je vais pouvoir les intégrer à Home Assistant via homekit, ou peut-être essayer un jour direct avec homekit. 
Je ne sais pas si tu connais le plugin tahoma de home assistant, vu tes talents il pourrait peut-être intégrer directement les clims hitachi...
See you.

**Comment by dubocr** [comment]
Parfait.
J'ai regardé un peu home Assistant mais il faut faire une SD complète. Du coup je m'y essaierai à l'occasion en récupérant une SD libre. Notamment pour essayer Google Home. Mais HomeKit seul à le mérite de simplifier au maximum en centralisant tout.

Bon usage ;-)

**Comment by Seb0101** [comment]
Je n’y manquerai pas. Je suis curieux de tes avancées côté home assistant, à l’occasion.
À+
