### ISSUE TITLE
Thermostat température erronée

### ISSUE THREAD

**Issue by navjul** [dubocr/homebridge-tahoma#64]
Bonjour,

Je dispose d’un thermostat connecté radio ajouté à TaHoma. Il apparaît dans homekit via 2 accessoires : le premier avec la température relevée correcte et le second avec la bonne température de consigne mais avec une température relevée toujours de 0 degrés.

**Comment by navjul** [comment]
Merci pour ton retour. En revanche, je ne souhaite pas l'exclure car c'est celui qui me permet de régler le thermostat via homekit. Son seul soucis apparent c'est que la remontée de la température ambiante reste à 0° en permanence (alors que le second capteur affiche la bonne température).

**Comment by dubocr** [comment]
En fait, en excluant le capteur d’ambiance, le widget HomeKit disparaîtra et le capteur sera alors rattaché au thermostat. Le widget thermostat affichera alors la T° de consigne (issue du thermostat) et la T° ambiante (issue du capteur d’ambiance)

**Comment by navjul** [comment]
Ah entendu ! je comprends, je vais faire le changement de configuration, merci.

**Comment by navjul** [comment]
Changement de conf effectué, je confirme, c'est parfait à présent, merci encore pour ton travail !

**Comment by anthonyplaisir** [comment]
bonjour je débute juste. j'ai bien mon thermostat  qui affiche la température, et l'état de la chaudière dans homekit mais je ne peux pas régler la température cela m'indique une erreur. une petite aide?

No target command for Zone 2

ma config toute simple : 
{
    "platform": "Tahoma",
    "name": "My Cozytouch",
    "user": "admin",
    "password": "mdp",
    "service": "Cozytouch",
    "exposeScenarios": "True",
    "exclude": "Zone 1"
}

**Comment by dubocr** [comment]
Bonjour @anthonyplaisir peux-tu ouvrir une nouvelle issue si tu as toujours ton problème.
Celle-ci étant fermée je n’avais pas vu ta question.
Merci

**Comment by anthonyplaisir** [comment]
Bonjour tous fonctionnent apparement

Cordialement,
________________________________
Anthony PLAISIR
233 route de Gorge
01800 Joyeux
0680463898<tel:0680463898>

[X]<https://www.linkedin.com/in/anthonyplaisir/>[X]<https://www.facebook.com/AnthonyPlaisirOff>



Le 30 mars 2021 à 23:21, Romain DUBOC ***@***.***> a écrit :

﻿

Bonjour @anthonyplaisir<https://github.com/anthonyplaisir> peux-tu ouvrir une nouvelle issue si tu as toujours ton problème.
Celle-ci étant fermée je n’avais pas vu ta question.
Merci
