### ISSUE TITLE
Bad credentials for connexoon 

### ISSUE THREAD

**Issue by bowana** [dubocr/homebridge-tahoma#65]
Hi, I appear to be having a similar issue to previous users. I have a Connexoon RTS that is registered in Australia at Somfy.com.au. I get the error message below

[2/2/2019, 2:10:02 PM] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.3
[2/2/2019, 2:10:02 PM] Registering platform 'homebridge-tahoma.Tahoma'
[2/2/2019, 2:10:02 PM] ---
[2/2/2019, 2:10:02 PM] Loading 1 platforms...
[2/2/2019, 2:10:02 PM] [Connexoon RTS] Initializing Tahoma platform...
[2/2/2019, 2:10:02 PM] Loading 0 accessories...
[2/2/2019, 2:10:04 PM] [Connexoon RTS] Login fail: Bad credentials
[2/2/2019, 2:10:04 PM] [Connexoon RTS] Login fail: Bad credentials
[2/2/2019, 2:10:04 PM] [Connexoon RTS] Bad credentials
[2/2/2019, 2:10:05 PM] [Connexoon RTS] Login fail: Bad credentials
Setup Payload:

I username / password are correct for .com.au
Any ideas?

Many thanks!
Tim

**Comment by dubocr** [comment]
Hi Tim,

Can you log there : https://home.duboc.pro/tools/setup
And tel me if succeed.

Thks,

**Comment by jxg81** [comment]
Same issue here - login to .com.au and receive bad credentials.  Tested using above link and same error (bad credentials)

**Comment by dubocr** [comment]
Hi,

You have to find your server URL if you think the server is not your.
Log in to your account with the website and track requests to find the server. Then I'll be able to add it.

**Comment by bowana** [comment]
Apologies Romain, I'm a bit confused as to how to do this.  Could you provide a little more direction?

As far as I can tell, authentication occurs with www.somfy.com.au
(see https://www.somfy.com.au/login )

Does this help?

Tim

**Comment by dubocr** [comment]
You have to look further or give me an access with a temporary password if you're OK. You could contact me by mail at dubocr[at]gmail[dot]com.
Or log in, then when you are on a page with your devices, open you browser dev tools (MacOS : alt+cmd+I or Windows : CTRL+MAJ+I) then open "network" tab (chrome) or "ressources" tab and "XHR" folder (safari) then do some actions on devices and check the URL of requests.

**Comment by bowana** [comment]
Thanks - I understand what you are looking for now.  The only catch is that I can't control my products through the website.  The website is just for registering your connexoon, after that all control is via the "Connexoon Window RTS" app.  I'm not sure how to see what URL requests the app is making?

Tim

**Comment by dubocr** [comment]
Don't think it is a specific app. Can you try again to log here with your credentials (and with TaHoma Server).
https://dev.duboc.pro/tools/setup

Thanks

**Comment by bowana** [comment]
Bad credentials

**Comment by dubocr** [comment]
Is it this app : https://play.google.com/store/apps/details?id=com.somfy.connexoon_window&hl=fr ?
This app uses "Connexoon/TaHoma" server. Tell me if it's another one as I can't find "Connexoon Window RTS". May it's specific to AU store.
Did you try to change you password with a basic one to try if yours contains very specific characters ?

**Comment by bowana** [comment]
Its this app
Connexoon Window RTS by SOMFY SAS
https://itunes.apple.com/au/app/connexoon-window-rts/id1168009218?mt=8

**Comment by dubocr** [comment]
OK, it's not available here. Do you know someone in AU having an Android phone and some technicals skills ? A can give you a procedure to try to find the server with Android phone.
Just need to install Android Studio on a computer and "Connexoon Window RTS" on the phone.

**Comment by dubocr** [comment]
Ho wait, I found the APK on the web.
Retry to log there : https://dev.duboc.pro/tools/setup
And select "Connexoon AU ?" as server.

**Comment by bowana** [comment]
Bingo!  That login works perfectly.

**Comment by dubocr** [comment]
Great, you can now update the plugin `sudo npm update -g homebridge-tahoma` then set `Connexoon RTS` as service.

**Comment by bowana** [comment]
Excellent.  Brilliant help, can't thank you enough.  This is now connecting and I'll give is some testing over the next few days.  Thanks once again.

**Comment by dubocr** [comment]
👍

**Comment by grizto** [comment]
Hi @dubocr 

Sorry to reopen this issue, but I am facing the same problems just with a somfy connexxon registered in germany. 
Any ideas?
Chris
