### ISSUE TITLE
Impossible de voir mes accessoires

### ISSUE THREAD

**Issue by SlyBall912** [dubocr/homebridge-tahoma#66]
Bonjour,

Je suis débutant et un peu perdu. J'ai installé Homebridge et le plugin tahoma-homebridge. J'ai mis à jour le fichier config-sample.js avec les credentials tahoma.
Je les vois bien en allant sur ta page. Par contre, je ne vois rien dans l'application home de mon tel. je vois uniquement mon homebridge.

Ai-je raté une étape ?

Merci pour ton aide.

**Comment by dubocr** [comment]
Bonjour,

Config-sample.js doit être un fichier d’exemple. Le fichier de config s’appelle config.js (étape 5 du Quick Overview installation homebridge). Tu peix renommer config-sample.js en config.js puis redémarrer homebridge.

Tiens moi au courant

**Comment by SlyBall912** [comment]
Bonjour,

Merci pour la réponse. J'ai pu résoudre le problème.
