### ISSUE TITLE
Contrôle impossible des têtes thermostatiques Honneywell Evohome

### ISSUE THREAD

**Issue by SlyBall912** [dubocr/homebridge-tahoma#67]
Bonjour,

Je possède des têtes thermostatiques connectées HonneyWell Evohome. Elle sont bien intégrées dans Tahoma. Par contre je ne vois que la température de celles-ci (pièce par pièce) et il est impossible de les contrôler. Elles sont vues comme des TemperatureSensors :

9 TemperatureSensor > TemperatureSensor
Devices click on a device to display current states
Salon Ch Parents DHW T° Salle de jeux Palier Ch Bapiste Ch Juliette Bureau Lingerie 

ramses://0220-6203-7120/49751/7#2
States Ch Bapiste
core:NameState Ch Bapiste
core:SensorDefectState (dead,lowBattery,maintenanceRequired,noDefect)
core:TemperatureState 21.7
Commands
getName
setName + 1 parameter

Elles sont également présentes sous :

8 EvoHome > HeatingSetPoint
Devices click on a device to display current states
Salon Ch Parents Salle de jeux Palier Ch Bapiste Ch Juliette Bureau Lingerie 

ramses://0220-6203-7120/49751/7#1
States Ch Bapiste
core:NameState Ch Bapiste
core:TargetTemperatureState 21.5
core:TemperatureState 21.7
ramses:RAMSESSetPointOverrideDurationState
ramses:RAMSESSetPointOverrideModeState NoOverride
ramses:RAMSESZoneTimeProgramState
Commands
getName
setName + 1 parameter
setTargetTemperature + 1 parameter
setSetpointOverride + 3 parameter
setTimeProgram

Comment faire pour avoir sous le même bouton la température relevée, la température de consigne et pouvoir contrôler le tout ?

Merci pour ton aide.

**Comment by dubocr** [comment]
Le Thermostat HonneyWell n'est pas compatible HomeKit ?
Voici deux fichiers : 
[Archive.zip](https://github.com/dubocr/homebridge-tahoma/files/2923560/Archive.zip)
A placer dans le dossier "accessoires" (dont 1 à remplacer). Puis redémarrer Homebridge.
Le changement de T° devrait fonctionner mais pour les modes il faudra que tu fasses des changement depuis TaHoma puis que tu te connectes sur ma page à nouveau afin que j'ai l'historique des changements pour les reproduire.

**Comment by SlyBall912** [comment]
En fait, il ne s'agit pas des thermostats T6, mais de la solution Evohome qui permet de piloter des têtes thermostatiques de type HR92.
J'ai procédé aux changement que tu as proposé, mais ça n'a rien changé.
Je viens de changer la température du salon via Tahoma (passage de 21,5° à 22,5°)

Avant :
8 EvoHome > HeatingSetPoint
Devices click on a device to display current states
Salon Ch Parents Salle de jeux Palier Ch Bapiste Ch Juliette Bureau Lingerie 

ramses://0220-6203-7120/49751/7#1
States Salon
core:NameState Salon
core:TargetTemperatureState 21.5
core:TemperatureState 22.3
ramses:RAMSESSetPointOverrideDurationState
ramses:RAMSESSetPointOverrideModeState NoOverride
ramses:RAMSESZoneTimeProgramState
Commands
getName
setName + 1 parameter
setTargetTemperature + 1 parameter
setSetpointOverride + 3 parameter
setTimeProgram 

Après :
8 EvoHome > HeatingSetPoint
Devices click on a device to display current states
Salon Ch Parents Salle de jeux Palier Radiateur Bapiste Ch Juliette Bureau Lingerie 

ramses://0220-6203-7120/49751/7#1
States Salon
core:NameState Salon
core:TargetTemperatureState 22.5
core:TemperatureState 22.2
ramses:RAMSESSetPointOverrideDurationState 4/3/2019 -- 0:0
ramses:RAMSESSetPointOverrideModeState PeriodicOverride
ramses:RAMSESZoneTimeProgramState
Commands
getName
setName + 1 parameter
setTargetTemperature + 1 parameter
setSetpointOverride + 3 parameter
setTimeProgram + 1 parameter

Egalement, la solution comprend un controller qui gère l'ensemble. Voilà ce qu'il dit :
1 EvoHome > EvoHomeController
Devices click on a device to display current states
Evohome Maison 

ramses://0220-6203-7120/49751/255#1
States Evohome Maison
ramses:RAMSESOperatingModeState (auto,eco,holidays,off) auto
ramses:RAMSESOperatingModeTimeoutState
Commands
setOperatingMode + 2 parameter

Merci encore pour ton aide !

**Comment by dubocr** [comment]
[Archive.zip](https://github.com/dubocr/homebridge-tahoma/files/2923765/Archive.zip)
Voici 3 fichiers à remplacer (1 à la racine du plugin et 2 dans accessories).
Pour le changement de mode, il me faut un historique. Tu dois modifier le mode sur l'application (changer pour chaque modes) puis mettre à jour via ma page (inutile de m'envoyer le résultat de la page).

Merci.

**Comment by SlyBall912** [comment]
Hello

Je viens de faire les changements mais je ne peux toujours pas régler la température des têtes thermostatiques. J'ai un nouveau problème : Homebridge n'arrive plus à se connecter à Tahoma (too many requests). C'est peut-être du à un trop grand nombre d'essais.

J'ai aussi fait les changements de modes sur le contrôler et je me suis reconnecté à chaque fois sur la page. Je te laisse regarder.

Merci.

**Comment by dubocr** [comment]
Bonjour,

Pour le réglage de la T°, il devrait y avoir 2 widgets sur Home pour chaque tête thermostatique. 1 qui affiche la T° (capteur de T°) et 1 qui affiche la T° et permet de la régler (thermostat).
En principe, il faut ajouter dans la config des exclusions pour masquer les capteur de T° mais dans ton cas ils portent le même nom que les thermostats donc je n'ai pas encore de solution à part déplacer sur Home les capteurs de T° dans une pièce "fourre tout".
Concernant le problème "too many request", il faut que tu stoppe homebridge (pendant plusieurs heures) avant de le relancer.

Parfait pour les changements de mode. Je regarde pour intégrer ça mais cela risque d'être un peu bancale car il n'y à qu'un seul thermostat pour toutes les têtes thermostatiques mais il faut aussi pouvoir piloter indépendamment la T° de chaque tête ce qui n'existe pas sur homekit.
Est-il possible sur TaHoma de piloter individuellement le mode des têtes ?

Merci.

**Comment by dubocr** [comment]
[EvoHome.zip](https://github.com/dubocr/homebridge-tahoma/files/2924887/EvoHome.zip)

Voici de quoi piloter en auto/off le thermostat principal.

**Comment by SlyBall912** [comment]
Bonjour,

Je viens de tester. Concernant le 1er point, je n'ai toujours qu'un seul widget par tête thermostatique (celui qui affiche uniquement la température). Je viens de faire la manipulation suivante sous Tahoma : J'ai renommé chaque capteur de température en Temp "Nom de la pièce". J'ai renommé chaque widget de reglage de température en Chauffage "Nom de la pièce". Sous Tahoma, les deux éléments portent bien des noms différents. Par contre en relançant Homebridge, je n'ai que les Temp "Nom de la pièce" qui sont présents. Je n'ai pas les Chauffages "Nom de la pièce'.
Je me suis reconnecté à ta page pour que tu puisses avoir le résultat.

Enfin, avec le nouveau Evohome.js, je n'ai pas de changement concernant le thermostat principal. je ne peux rien modifier. C'est le Evohome maison qui devrait être présent. Or il n'y a que le DHW T° qui apparait (en plus des capteurs de température de chaque pièce).

Pour finir, il n'y a pas la possibilité sous Tahoma de piloter le mode de chaque tête. Cela se passe uniquement sur Evohome Maison.

Merci.

**Comment by dubocr** [comment]
Peux tu regarder les log homebridge. Tu ne devrais pas avoir le DHW mais justement les autres avec le dernier fichier. Il y a quelque chose qui cloche.
Lors du démarrage de homebridge, tu peux voir quels capteurs sont instanciés. Si tu peux regarder et m'envoyer également les logs.

Merci.

**Comment by SlyBall912** [comment]
On avance !
J'avais fait une erreur. J'ai réinstallé le plugin avec ta dernière release et je vois maintenant pour chaque tête la sonde de température et le widget de réglage.
Par contre, concernant le widget de réglage, je peux modifier la température, mais j'ai une erreur concernant les le changement des modes pour chaque tête et ensuite la tête est incontrôlable (sans réponse). Il ne faudrait pas qu'on puisse modifier les modes je pense. Voici l'erreur en question :

[3/4/2019, 3:40:03 PM] [Tahoma] Error 400 Managed action group is invalid : Error invoking LUA function <runtime:1>('auto','auto','auto',nil) : ramses-utils.module:151 attempt to perform arithmetic __mul on string and number (UNSPECIFIED_ERROR)

Je vois bien le DHW Set Point et le Evohome Maison. Mais ils ne sont non gérés

**Comment by dubocr** [comment]
Voici déjà une petite évolution qui devrait permettre d'éviter les erreurs et j'espère de rendre le Evohome Maison géré (j'ai forcé la T° à 0 je pense que c'est ce qui coince comme elle n'est pas initialisée)
[EvoHome.zip](https://github.com/dubocr/homebridge-tahoma/files/2927201/EvoHome.zip)

**Comment by SlyBall912** [comment]
J'ai toujours les erreurs quand je change le mode sur les têtes.
J'ai la T à 0° sur le DHM T°. Le Evohome maison n'est pas géré.

**Comment by dubocr** [comment]
Voici la dernière version pour la gestion initiale du thermostat. Normalement rien n'est envoyé pour les têtes c'est étonnant. A voir si c'est toujours le cas avec cette version.
[EvoHome.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2927704/EvoHome.js.zip)

**Comment by SlyBall912** [comment]
Je viens de faire des tests et cela fonctionne correctement !!

Merci 1000 fois pour ton aide !

**Comment by SlyBall912** [comment]
Une dernière question : sais tu comment créer des automatismes à partir d'un capteur de température ?
Par exemple, lancer mes modules de clim Mitsubishi MelCloud quand mes capteurs de température evohome dépassent une certaine température.

**Comment by dubocr** [comment]
Parfait. De rien.
Pour déclencher des actions en fonction de la température utilise l’application Eve pour créer des scénarios plus complexes que sur home.

**Comment by dubocr** [comment]
Ou Hesperus
