### ISSUE TITLE
Suppression du mode DOMICILE sur la home alarm

### ISSUE THREAD

**Issue by Tomnils** [dubocr/homebridge-tahoma#68]
Bonjour @dubocr ,

il y aurai t'il moyen de supprimer le mode domicile de la Home Alarm sur Homebridge (comme sur la honewell t4r) et de supprimer le capteur de la home alarm pour que quand elle se déclenche tout est dit dans l'icone de l'alarme .

Bon courage !!)

**Comment by dubocr** [comment]
Bonjour,

Tout ce qui concerne l'interface n'est pas géré par le plugin. Il n'est donc pas possible de supprimer des modes. Quel capteur faut-il supprimer. Peux tu te logger sur https://home.duboc.pro/tools/setup pour que je puisse voir ta config.

Merci.

**Comment by dubocr** [comment]
C'est une alarme my fox ? Effectivement il y à un capteur de présence supplémentaire pour reporter l'état de détection d'intrusion. J'ai également ajouté le déclenchement du widget alarme en cas de détection d'intrusion sur la dernière mise à jour 0.1.37.

**Comment by dubocr** [comment]
´npm update -g homebridge-tahoma’

**Comment by Tomnils** [comment]
Non malheureusement pas

meme en executant npm update -g homebridge-tahoma

je pence que sa vien de se secteur

`this.currentState.updateValue(converted);
            if (!this.isCommandInProgress()) // if no command running, update target
                this.targetState.updateValue(target);
        } else if ((name == 'core:IntrusionState' || name == 'core:IntrusionDetectedState') && this.occupancyState != null) {
        	this.occupancyState.updateValue(value == 'detected' ? Characteristic.OccupancyDetected.OCCUPANCY_DETECTED : Characteristic.OccupancyDetected.OCCUPANCY_NOT_DETECTED);
        	if(value == 'detected') {
        		this.currentState.updateValue(Characteristic.SecuritySystemCurrentState.ALARM_TRIGGERED);`

**Comment by dubocr** [comment]
Peux tu te logger sur la page https://home.duboc.pro/tools/setup lorsque l’alarme est déclenchée.
Merci

**Comment by Tomnils** [comment]
Tien la config sur ton site

myfox://SOMFY_PROTECT-WkESTjDPYEOSXPzNz9J2wAByoBgBkdlL/site_alarm
States Link
core:CloudDeviceStatusState (offline,online,uninstalled) online
core:IntrusionState (detected,notDetected) notDetected
core:NameState
myfox:AlarmStatusState (armed,disarmed,partial) disarmed
myfox:AlertTrespassState {"deviceId":"site_alarm","sendAt":"2019-02-25T07:32:51.000000Z"}
Commands
arm
disarm
getName
partial
setName + 1 parameter
refreshAlarmStatus
setAlarmStatus + 1 parameter

**Comment by dubocr** [comment]
Si tu vois le capteur de présence alors tu devrais aussi avoir le déclenchement de l'alarme en cas d'intrusion. Mais lorsque tu t'es loggué l'alarme n'était pas déclenchée.
Mais je pense qu'on ne parle pas de la même chose. Je cherche à faire activer l'alerte dans le widget d'alarme lors du déclenchement de celle-ci et je pense que tu parles du fait que le widget détection de presence est encore présent n'est-ce pas ?

Normalement pour le supprimer il faut ajouter son non dans le paramètre `"exclude": ["Nom du capteur"]` de la config.
Mais puisque l'alerte sera déjà visible dans le widget alarme je vais rendre inactif par défaut le widget détection de presence.

Tu peux essayer en replaçant le fichier Alarm.js dans le dossier accessories par le suivant :
[Alarm.js.zip](https://github.com/dubocr/homebridge-tahoma/files/2946321/Alarm.js.zip)
Puis redémarrer homebridge.

**Comment by Tomnils** [comment]
[Tahoma] Login fail: Too many requests, try again later
[2019-3-8 18:00:13] [Tahoma] Too many requests, try again later
[2019-3-8 18:00:25] [Tahoma] Login fail: Too many requests, try again later

**Comment by dubocr** [comment]
Stoppe homebridge pendant quelques minutes (heures) puis lance le à nouveau
`sudo systemctl stop homebridge`
wait
`sudo systemctl start homebridge`

**Comment by Tomnils** [comment]
Hey @dubocr !

il y a moyen de m'indiquer le chemin pour alarm.js puis oui on parle bien du détecteur qui est joins a l'alarme

**Comment by dubocr** [comment]
Plus simple tu peux directement mettre à jour le plugin:
`sudo npm update -g homebridge-tahoma`

**Comment by Killator** [comment]
Bonjour, je me permet une petite question... J'ai moi aussi une Home Alarm Somfy mais PAS la box Tahoma... J'imagine quelle est obligatoire pour faire le relais avec le plugin via l'API Web ? (Mon ID est refusé sur https://home.duboc.pro/tools/setup).

Merci d'avance.

**Comment by dubocr** [comment]
Ton ID Cozytouch est refusé ?
Pour l’alarme, commercialement l’inverse est possible (utiliser la box Tahoma pour y connecter des chauffages du groupe atlantic). Dans ton sens cette possibilité n’est pas offerte. Mais contacte moi par mail dubocr[at]gmail[dot]com pour en discuter.

**Comment by Tomnils** [comment]
Hello @dubocr ,
Il y a moyen que tu supprimes le capteur de mouvement qui est join avec l’alarme (le widget que tu me parle) ?

Puis pour supprimer le mode home (domicile) inspire toi du plugin homebridge HomeKit-http-securitysystem (https://www.npmjs.com/package/homebridge-http-securitysystem) !
Lui il map dans la config ses modes donc toi tu peux faire sa mais dans alarm.js !
Bonne chance 🍀👍🏻 !!
Tom

**Comment by dubocr** [comment]
Hi @Tomnils,

C'est ce dont il est question dans ce topic. Ton capteur de mouvement apparait toujours ? As-tu fait la mise à jour ? Il faut également retirer "occupencySensor" de la config Alarm.
Tiens moi au courant.

Pour ce qui est du mode domicile, je vais regarder de plus près mais je n'ai pas l'impression qu'il soit question de la supprimer dans le plugin que tu me donnes. Il s'agit uniquement de le mapper à des fonctionnalisés. Mais il y a toujours les 4 modes quoi qu'il arrive. Est-ce que j'ai regardé trop rapidement ?

**Comment by Tomnils** [comment]
Cc @dubocr ,
Oui il apparait toujours (le capteur).
Je pence que pour le plugin , oui on peut le supprimer (je pence) mais je peut pas test car je sait pas si on peux la contrôler en HTTP.
il fa

**Comment by dubocr** [comment]
J'ai vérifié en reprenant ta configuration. le capteur de mouvement est bien absent. Si ce n'est pas le cas il faut que tu mettes à jours le plugin.
`sudo npm update -g homebridge-tahoma`

**Comment by dubocr** [comment]
Mode domicile supprimé pour les alarme MyFox dans la dernière mis à jour du plugin.
