### ISSUE TITLE
suppression du widget detecteur intrusion alarm

### ISSUE THREAD

**Issue by Tomnils** [dubocr/homebridge-tahoma#70]
Bonjour @dubocr ,

Il y aurait moyen de faire disparaître le widget déclenchement de l'alarme pour tout soit dans un widget ??

Bon courage .)

**Comment by dubocr** [comment]
Bonjour,

N’est-ce pas la même demande que la #68 ? C’est normalement le cas dans la dernière version.
Merci de poursuivre dans le fils de discussion #68
