### ISSUE TITLE
Exterior screen issues after update 0.1.40

### ISSUE THREAD

**Issue by EdiVip** [dubocr/homebridge-tahoma#71]
Hello!

After Update to latest (0.1.40) version od plugin I can’t use exterior screen and awning. I see them in Homekit but when I try to open/close I have Error 400 Invalid JSON format or type in request body (INVALID_API_CALL)

Can I install order version? 0.1.32 or how can I fix this?

**Comment by dubocr** [comment]
Hi,

Do you have other logs preceding this error ?
You can install previous version with `npm install <package>@<version>`

Ex `npm install homebridge-tahoma@0.1.32`

**Comment by dubocr** [comment]
I found something please wait.

**Comment by dubocr** [comment]
Update to 0.1.41 please. It must fix.

Thank you for your feedback.
