### ISSUE TITLE
Default Position for RTS Awning

### ISSUE THREAD

**Issue by BigKrisch** [dubocr/homebridge-tahoma#72]
Hello,

is it possible that the "default position" from the config.json also applies to awnings?
Currently, I always change the default position for my RTS awning manually in the file Awning.js.

That would make the whole thing a little more comfortable.

Thank you for your effort!

**Comment by dubocr** [comment]
Hi,
This is bot documented but you can already do it.
Just add defaultPosition as child of Awning object parameter :

"Awning": { "defaultPosition": 50 }

Tell me if it doesn’t apply.

**Comment by BigKrisch** [comment]
The setting of the default position works so far on the config.json.

However, the 0 position will not be accepted for closed. Here then default value of 50 is taken. Is there a possibility of a change, so that also 0 can be entered in it config.json?

![Bildschirmfoto 2019-03-17 um 00 12 29](https://user-images.githubusercontent.com/35509005/54482812-738ddc00-4849-11e9-8870-b3c51b73b9f2.png)

![Bildschirmfoto 2019-03-17 um 00 12 46](https://user-images.githubusercontent.com/35509005/54482813-75579f80-4849-11e9-90ad-902ed507320d.png)

**Comment by dubocr** [comment]
You can update the plugin, it must be fixed in the last release.

**Comment by BigKrisch** [comment]
Super. Works perfect!

Many Thanks!
