### ISSUE TITLE
Missing accessory: 'ExteriorHeatingSystem'

### ISSUE THREAD

**Issue by asheiner** [dubocr/homebridge-tahoma#74]
Hi,

thanks for the homebridge-tahoma.
When initializing it I found that I'm having an unsupported accessoy type.
It's a Heating Slim Receiver RTS and identifies itself as 'ExteriorHeatingSystem'.

As a workaround I copied an modified the Light.js file and removed everything but the setOn function and onStateUpdate function.
`ExteriorHeatingSystem.UUID = 'ExteriorHeatingSystem'`

As I'm not a real programming expert, I'd ask if you could add this to your git.

Best regards
Andreas

**Comment by dubocr** [comment]
Hi,

Of course I can integrate your file. But may there is more functionalities than on/off possible for your device ? Can you log there : https://dev.duboc.pro/tools/setup with your credential to let me obtain your current config and have a look to the params of this device.

Thanks

**Comment by asheiner** [comment]
done.
Hope my config helps.
What I can see is that there are indeed more commands than I was aware of before ....
but usually I only switched in on/off.

```
1 ExteriorHeatingSystem > StatelessExteriorHeating
Devices click on a device to display current states
Heizstrahler
Commands
    down
    identify
    my
    off
    on
    onWithTimer + 1 parameter
    rest
    stop
    test
    up
```

**Comment by dubocr** [comment]
Hi,

I added on/off switch for this kind of device in last release as other commands are internal commands.
