### ISSUE TITLE
Impossible de piloter les portails extérieurs

### ISSUE THREAD

**Issue by photos13x** [dubocr/homebridge-tahoma#75]
Bonjour,

J'ai l'erreur suivante quand j'essaie d'ouvrir ou fermer mon portail :
open PRIORITY_LOCK__NO_SECURITY_DEVICE

Le portail ne réagit pas. Si j'utilise l'app Tahoma alors aucune problème.
Pouvez vous m'aider ?

Merci

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous vous connecter sur cette page afin de déterminer votre configuration.

Merci

**Comment by photos13x** [comment]
Bonjour,

C'est fait.

**Comment by dubocr** [comment]
Merci, je regarderai ca cette semaine. Tu peux également t’y connecter avec le compte cozytouch pour le chauffe-eau car je n’ai pas encore eu de config avec chauffe-eau.

Bonne journée

**Comment by dubocr** [comment]
Pour le portail, peux-tu l’ouvrir depuis Tahoma puis te reconnecter sur ma page afin que je puisse vérifier quelle commande est utilisé dans Tahoma.
Quand tu essaie de l’ouvrir avec Homekit, quelle commande s’affiche dans les logs homebridge ?

Merci

**Comment by photos13x** [comment]
Bonjour,

Je me suis déjà connecté avec mon compte Cozytouch via votre outil (juste avant la tahoma). Je peux le refaire si besoin pas de problème.
La commande open s’affiche via homebridge puis le message indiqué dans mon post.
Je viens de refaire la manipulation pour le garage.

Merci pour votre aide

**Comment by dubocr** [comment]
Ha désolé, c’est que l’adresse mail doit être la même et ca écrase la config. J’ai pu jeter un œil sur celle Tahoma, je veux bien que vous vous connectiez à nouveau avec Cozytouch.
Concernant Tahoma, le problème est-il présent pour le portail ET le garage ?

**Comment by photos13x** [comment]
Pas de soucis je vais me reconnecter ;)
Le problème est présent uniquement pour le garage. 
Merci

**Comment by dubocr** [comment]
J'ai mis de coté ta config Cozytouch. Peux-tu te connecter une dernière fois avec TaHoma pour que je puisse avoir les deux en //. Je n'ai rien repéré l'autre fois sur le garage mais je vais revérifier.
De mon côté je constate que l'appli déclenche "open" pour l'ouverture ce qui également la même commande qui est envoyée par Homebridge.
C'est assez étrange et je n'arrive pas à interpréter le message d'erreur PRIORITY_LOCK__NO_SECURITY_DEVICE.

**Comment by photos13x** [comment]
Je viens de me reconnecter avec mon compte tahoma.
Pour le garage, oui c’est assez étrange...

**Comment by dubocr** [comment]
Ces deux paramètres doivent définir une règle de sécurité.
```
io:PriorityLockLevelState
io:PriorityLockOriginatorState
```
Ils sont habituellement inactifs dans les autres configuration mais chez toi ils sont définis à 
```
comfortLevel1
localUser
```

Est-ce qu'il existerait quelques part dans les paramètres de TaHoma quelque chose qui permet de verrouiller la porte selon des critères ?
Peux-tu me donner la référence de ta porte de garage (modèle/marque)

Merci.

**Comment by photos13x** [comment]
Bonjour,

C'est un Rollixo IO.
Je ne peux rien modifier sur la Tahoma. Peut être faudrait il faire une nouvelle association ?...

**Comment by dubocr** [comment]
Bonne idée, la réassociation devrait réinitialisé les paramètres, en espérant que rien ne les définissent à nouveaux. Juste après l'association, connecte toi sur la page pour vérifier qu'ils sont bien vides.

Merci

**Comment by photos13x** [comment]
Je viens de refaire l'association, et le problème est toujours présent : cela fonctionne avec l'app mobile Tahoma mais pas via l'app Home.
![image](https://user-images.githubusercontent.com/49096308/55488521-8a497680-5630-11e9-88a1-71848dee784e.png)

**Comment by dubocr** [comment]
C’est pourtant écrit qu’il ne peut pas non plus être piloté par TaHoma.
Quel message est affiché sous le triangle orange ?

**Comment by photos13x** [comment]
Oui c’est écrit mais y’a qu’avec l’app home que je ne peux pas le piloter... avec Tahoma aucun soucis.
Il n’y a rien d’écrit de plus.

**Comment by newbeetle59** [comment]
Peut-être une piste: avez-vous des cellules de détection infra rouge raccordées à votre motorisation garage ? Il me semble que tahoma impose la présence de ces dispositifs pour éviter les accidents lors des manœuvres distantes. Si elles sont absentes cela pourrait expliquer le message d’erreur et le blocage.

**Comment by dubocr** [comment]
Merci pour cette piste concernant le pourquoi ce device est différent des autres.
Dans tout les cas, comme il est pilotable depuis TaHoma j'ai regardé les différences entre les deux requêtes et je ne voit qu'une seule chose.
Peux-tu essayer d'ajouter la ligne suivante dans le fichier `overkiz-api.js` après la ligne 336.
`headers: {'User-Agent': 'TaHoma iPhone'},`

Ce qui devrait te donner :
```
this.post({
      url: that.urlForQuery('/exec/'+oid),
      headers: {'User-Agent': 'TaHoma iPhone'},
      body: execution,
      json: true
}
```

Puis redémarrer homebridge et tester à nouveau.

**Comment by photos13x** [comment]
Je viens de faire la modification et le résultat est le même :/

**Comment by dubocr** [comment]
Zut :-(.
Peux-tu te connecter à ma page pour voir déjà si la modif à bien eu un effet. Le reste de la requête est exactement le même.
Sur TaHoma en ligne (site WEB) l'ouverture fonctionne ? Tu pourrais regarder dans les requêtes envoyées par le navigateur ce qui est transmis quand tu demandes l'ouverture ?
Il faudrait faire CTRL+MAJ+I sous windows puis afficher la partie network (sous chrome), et regardé la requête qui apparaît en demandant l'ouverture.

Merci

**Comment by photos13x** [comment]
Désolé pour le retard, je m'en occupe ASAP

Merci

**Comment by photos13x** [comment]
Bonjour,

Je viens de me connecter à ta page ;)
Pour la requête envoyé pour ouvrir, voici quelques infos 
URL : https://www.tahomalink.com/enduser-mobile-web/enduserAPI//exec/apply/highPriority
Méthode : POST
Requête payload : {"label":"Garage - Ouvrir - TaHoma PC","actions":[{"deviceURL":"io://YYYY-XXXXXXXXX","commands":[{"name":"open","parameters":[]}]}]}

**Comment by dubocr** [comment]
Bonjour,

Super, tu peux essayer de modifier la ligne 324 du fichier overkiz-api.js par la suivante :
`this.execute('apply/highPriority', execution, callback);`

**Comment by photos13x** [comment]
C'est bon ça fonctionne !! Merci beaucoup !

**Comment by dubocr** [comment]
Parfait, tu devras le rajouter manuellement pour l'instant si tu mets à jour le plugin mais j'intégrerai un correctif dans une grosse mise à jour à venir.
Je garde le ticket ouvert en attendant.

**Comment by dubocr** [comment]
J'ai mis à jour le plugin et intégrer cette gestion. A tester si cela fonctionne toujours après la mise à jour.

Merci.
