### ISSUE TITLE
Cozytouch sur thermostat Atlantic températures fausses

### ISSUE THREAD

**Issue by photos13x** [dubocr/homebridge-tahoma#76]
Bonjour,

J'ai connecté mon cozytouch à mon gainable atlantic via le thermostat.
Tout est ok sur l'app Cozytouch mais les températures affichées sont fausses (toutes à 0) via homebridge dans l'app maison.
J'ai pourtant exclu les sondes de températures comme expliqué dans le post https://github.com/dubocr/homebridge-tahoma/issues/64

Rien n'y fait, la température reste à 0.

Pouvez vous m'aider ?

Merci

**Comment by photos13x** [comment]
Bonjour,

Avez vous pu regarder cette anomalie ?

Merci

**Comment by dubocr** [comment]
Bonjour,

Pardon, peux-tu déjà tester avec le jeu de fichiers présents dans le fil de conversation #73 ([ce post](https://github.com/dubocr/homebridge-tahoma/issues/73#issuecomment-476893484)).
C'est encore en cours de test mais cela devrait déjà corriger pas mal de choses. Tu n'auras pas besoin d'exclure les capteurs de T°.
Je te laisse mettre tes retours/problèmes sur le fil de conversation en question pour simplifier.

Merci.

**Comment by dubocr** [comment]
Je croyais que cela concernait le chauffage. Pour le chauffe-eau on va continuer ici avec ce fichier :
[WaterHeatingSystem.js.zip](https://github.com/dubocr/homebridge-tahoma/files/3031003/WaterHeatingSystem.js.zip)
Peux-tu le remplacer dans le répertoires accessories et redémarrer Homebridge.

**Comment by photos13x** [comment]
Je pense avoir corriger le problème dans AbstractAccessory.js :
_```
function AbstractAccessory(log, api, device) {
    this.api = api;
    this.log = log;

    this.name = device.label;
    this.deviceURL = device.deviceURL;

    this.device = device;
    
    this.services = [];
    **this.zones = [];**
```_

Mais maintenant j'ai cette erreur :
_Device Bureau merged with Zone Control
/usr/local/lib/node_modules/homebridge-tahoma/index.js:144
                                                                               subAccessory.onStateUpdate(state.name, state.value, device.deviceURL);
                                                                                            ^

TypeError: subAccessory.onStateUpdate is not a function
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:144:24_

**Comment by dubocr** [comment]
Voici un nouveau jeu de fichiers. Je n'ai pas la possibilité de tester pour l'instant mais tu peux déjà essayer.
[homebridge-tahoma.zip](https://github.com/dubocr/homebridge-tahoma/files/3032886/homebridge-tahoma.zip)

**Comment by photos13x** [comment]
J'ai cette erreur maintenant :

/usr/local/lib/node_modules/homebridge-tahoma/index.js:118
                                                that.log.info('[' + device.label                                        + ']' + ' device type: ' + uiClass + ', name: ' + device.controllableName + ',                                        protocol: ' + protocol);
                                                                                                                                                   ^

ReferenceError: uiClass is not defined
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:118:67
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:183:5
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebrid                                       ge-tahoma/overkiz-api.js:215:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node                                       _modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_m                                       odules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahom                                       a/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by dubocr** [comment]
Voici de nouveaux fichiers.
J'ai pu tester le démarrage et l'affichage avec ta config. Tout devrait correctement s'afficher. Reste à tester le fonctionnel et notamment les commandes envoyées car faire correspondre les modes Homebridge à ceux de la PAC n'est pas toujours trivial. Ton avis d'utilisateur de la PAC sera le bienvenu.
Il faut, à partir des 4 modes HomeKit (Off/Auto/Chauffer/Refroidir) et du sélecteur de T° choisir comment agir sur la PAC.

[homebridge-tahoma.zip](https://github.com/dubocr/homebridge-tahoma/files/3035535/homebridge-tahoma.zip)

**Comment by dubocr** [comment]
Je repasse sur l'autre fil de discussion pour la suite. J'ai ajouté un nouveau fichier permettant la dérogation lorsque la PAC est en mode auto/prog.

**Comment by photos13x** [comment]
Bonjour,

J'ai ce message d'erreur maintenant :
[2019-4-3 16:09:35] [Cozytouch] Instanciate device IO (9921398#2)
/usr/local/lib/node_modules/homebridge-tahoma/index.js:152
                                                                        accessory.addSubAccessory(subAccessory);
                                                                                  ^

TypeError: accessory.addSubAccessory is not a function
    at /usr/local/lib/node_modules/homebridge-tahoma/index.js:152:20
    at /usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:183:5
    at Request.authCallback [as _callback] (/usr/local/lib/node_modules/homebridge-tahoma/overkiz-api.js:215:17)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tahoma/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by dubocr** [comment]
Récupère également les fichiers index.js et Abstract.. dans le zip du post précédent.
Je vais mettre à jour la totalité ce soir pour ne travailler désormais que sur HeatingSystem ce qui sera plus simple à suivre.

**Comment by photos13x** [comment]
Ok, c'est mieux, plus d'erreur :D
Par contre, les températures ne sont pas les mêmes que sur l'app Cozytouch
On dirait que les températures réelles sont arrondies à 0,5° dans Home, alors que via l'app Cozytouch c'est à 0,1° près. Normal ?
De plus, le zone control apparaît comme appareil non gérable.

**Comment by dubocr** [comment]
Oui c’est le sujet sur l’aut Thread. A priori Homekit ne gère pas a 0,1 mais à 0,5 au niveaux du curseur donc j’ai forcé la consigne à un pas de 0,5. Mais la T° actuelle n’est pas concernée normalement. Si elle l’est c’est une limitation d’Home. Sur des app comme Eve cela devrait être bon.
Pour le zonecontrol il sera pilotable dans le prochain fichier mais la T° Affichée  sera forcée à 0 puisque gérée au niveau des zones. Sinon j’hesites à mettre un simple on/off mais du coup on ne pourra pas passer de chauffage à refroidissement depuis Homekit.

**Comment by photos13x** [comment]
La température actuelle est concernée oui, je parlais de celle là.
Sur Eve c'est bon effectivement.
Cela serait effectivement mieux de pouvoir gérer le chaud/froid/ON/OFF via le zone control ;)

**Comment by dubocr** [comment]
Après reflexion c'est étrange que le ZoneControl ne soit pas encore pilotable. Est-ce que c'est mieux avec ce fichier ?
[HeatingSystem.js.zip](https://github.com/dubocr/homebridge-tahoma/files/3039995/HeatingSystem.js.zip)

**Comment by photos13x** [comment]
C'est mieux, mais ça affiche 0° en température. La température ne devrait pas apparaître si ?

**Comment by dubocr** [comment]
Oui c’est « normal ». Comme indiqué j’hesites entre un simple bouton On/Off qui ne permet pas de choisir entre chauffage et rafraîchissement ou alors un thermostat complet mais comme il n’y a pas de T° sur le zonecontrol alors je n’ai rien a mettre comme valeur.
Je suis pas sur que tant de monde que ça dispose du rafraîchissement et de mémoire il faut un délai entre le mode chauffage et rafraîchissement donc c’est une opération assez rare. Peut-être qu’un simple switch qui réactive le dernier état (chauffage ou rafraîchissement) serait plus approprié.
Je vais creuser la question.
