### ISSUE TITLE
How to control Awning horizontal tilt with Siri - suggested fix

### ISSUE THREAD

**Issue by mman** [dubocr/homebridge-tahoma#77]
Hi Romain,

thanks for your excellent piece of software. Installed at home controlling Somfy IO external blinds via old Somfy Tahoma gateway.

Everything works perfect using the Home app. Opening blinds, closing blinds, setting to certain percentage of open and adjusting the horizontal tilt.

Thank you for your hard work!!!

When using Siri to control the blinds, I can successfully open, close, or set the blinds to certain percentage.

> Hey Siri open the blinds

> Hey Siri close the blinds

> Hey Siri are blinds open?

> Hey Siri set blinds to 50%

However, there does not seem to be a way currently to control the horizontal tilt of the blinds using Siri, or I did not find the right phrase to adjust the blinds. And in fact we only use the blinds and fully open, or fully closed while adjusting the horizontal tilt.

So I was wondering whether it would be possible to modify the code in a way that the following works:

> Hey Siri open the blinds

This will open the blinds fully.

> Hey Siri close the blinds

This will close the blinds and set horizontal tilt to fully closed.

> Hey Siri set blinds to 10%, 50%, 90%

This will actually **close** the blinds and set horizontal tilt to certain angle depending on what percentage was passed.

In all cases the open/closed/percentage state should be reported correctly to the Home app as well, so that dragging the main open/close slider in the Home app will actually affect not only the openness of the blinds but also the tilt.

I'm willing to open a PR or experiment with the code, I just need a few pointers where to start and if you think that it is possible to implement.

What do you think?
Martin

**Comment by dubocr** [comment]
Hi Martin,

May you can try to replace the Awning.js file of your plugin "accessories" folder by this one :
[Awning.zip](https://github.com/dubocr/homebridge-tahoma/files/3042680/Awning.zip)

Then add this to your homebridge config
`"ExteriorVenetianBlind": {"blindMode" : true}`

Then restart homebridge and tell me if the is error.

**Comment by mman** [comment]
Hi @dubocr,

thanks for the code. It's a great first step. I have made a couple modifications and got it working with the following start of the ``setBlindPosition`` method

```
    setBlindPosition: function(value, callback) {
        var that = this;
	this.log("setBlindPosition: " + value + " for " + this.name);
		var commands = [];
		if(value == 100) {
			commands = new Command('open');
		} else {
			commands.push(new Command('close'));
			commands.push(new Command('setOrientation', [value]));
		}
		this.executeCommand(commands, function(status, error, data) {
...
...
```

So when the requested position is 100, triggered by ``Hey Siri open the blinds`` or ``Hey Siri set blinds to 100%`` the blinds will open.

any other value will make sure that the blinds are first closed and then orientation changes.

I need your help to make one final modification to not close every time, because now they first close completely and orientation changes to completely closed, and they they set new orientation.

Is there a way to get the current blind position and close only when the position is not already closed?

**Comment by mman** [comment]
Studying your original code, it looks like you actually had what I need in mind, but it did not work. Setting the blind to 50% would not close the blinds first, it only adjusted their orientation, probably the ``that.positionState.value == 100`` check did not succeed. 

I will make some more experiments but I need to restart Homebridge slowly as it seems to fail to login after many fast restarts. Is there a way to force Homebridge/node to watch and hot reload ``.js`` files during development?

```
   setBlindPosition: function(value, callback) {
        var that = this;
                var commands = [];
                if(value == 100) {
                        commands = new Command('open');
                } else {
                        if(that.positionState.value == 100) {
                                commands.push(new Command('close'));
                        }
                        commands.push(new Command('setOrientation', [value]));
                }
```

**Comment by dubocr** [comment]
Unfortunately, I don't know a way to hot reload.
I fact, I think about this behaviour :

If blind is open (position from 100 to 1), requesting position beetween 100 and 1 will change the opening position and requesting 0 (close) will fully close the blind.
If blind is closed (position 0), requesting position beetween 0 and 99 will change the horizontal tilt and requesting 100 (open) will fully open the blind.

Is this behaviour could fit your needs ?

**Comment by dubocr** [comment]
So if you want to deal with horizontal tilt when position is not fully closed, you'll have to firstly ask Siri to close the blind, then tell him to open between 0 and 99.
If you want to deal with opening position when position is fully closed, you'll have to firstly ask Siri to open the blind, then tell him to close between 0 and 99.

Just try that ;-) [Awning.zip](https://github.com/dubocr/homebridge-tahoma/files/3043671/Awning.zip)

**Comment by dubocr** [comment]
Or maybe this one if tilt is reversed at startup [Awning.zip](https://github.com/dubocr/homebridge-tahoma/files/3043701/Awning.zip)

**Comment by mman** [comment]
Hi @dubocr, I tried the second one and I think the idea is great and it will work fine... however there a strange feedback issue, please see the video here: https://www.dropbox.com/s/8k400df77q1c6hb/IMG_0002.MOV?dl=0

The blinds are closed and positioned at 32. I drag the slider in Home app to adjust orientation, it will adjust, but once completed, it will again reorient back to 32.

Similar thing is happening in other situations. Do you known what's going on?

**Comment by dubocr** [comment]
Could you please update the plugin. Hope it will fix.

**Comment by mman** [comment]
Thanks @dubocr, have updated to the latest ``homebridge`` and ``homebridge-tahoma`` via ``npm`` and the double set problem is gone. Thank you! Great Job!

However, couple small issues remain:

The ``Hey Siri Close the Blinds`` will not close the blinds fully, but will rather close them down and leave the orientation at open horizontal flat. This makes it inconvenient to configure the "Good Night" scene using HomeKit because you can not simply close the blinds for the night, you need to set them to 1%.

Also ``Hey Siri Set the blinds to X%`` (where X >= 1 && <= 99) behaves differently depending on what state the blinds are in. If they are closed, it will change orientation, if they are open or half open, it will adjust how opened they are. Again this makes it impossible to set a custom scene using HomeKit because depending on what state each blind is in, the command achieves different thing.

I believe the HomeKit command or Siri command must do always the same thing regardless of what current position/orientation the blinds are in.

I believe the better behavior would be:

- ``Hey Siri Close the Blinds`` - close the blinds and set orientation to fully closed
- ``Hey Siri Open the Blinds`` - open the blinds (window) fully
- ``Hey Siri Set the Blinds to X%`` (where X >=1 && X <= 99) will make sure to close the blinds first if they are not closed, and then changes the orientation.

This will make the HomeKit scenarios like Good Morning and Good Night consistent no matter how are the blinds positioned and oriented (for example by controlling them using the manual Somfy controllers)...

This will also make it impossible to half-open the blinds using HomeKit, but I think this is consistent to how these types of blinds are actually used in practice, either fully open, or fully closed with changing orientation. Never half the window.

What do you think?
Martin

**Comment by dubocr** [comment]
First point `Hey Siri close the Blinds` will be fixed. It's an issue.
Second one `Hey Siri Set the blinds to X%` is effectively the limits of this behavior. However, you can always create scene that act on the orientation only. But acting on the position will be position dependent.
I've updated plugin with full orientation behavior, can you try it and tell me if it's more natural for you. I'll think of alternative solution.

**Comment by mman** [comment]
Hi Romain, updated to the latest version of the plugin and I think it works great. In ``blindMode: true`` you can now control the blinds naturally with only one slider and it passes the WAF == "WIFE ACCEPTANCE FACTOR", which is great.

Merci beaucoup :), I think we can close this issue now :)

P.S. I have tried to create a HomeKit scene with the previous versions of the plugin changing both the blind's open percentage as well as orientation, and it did not work properly, which is why I filed the bug in the first place. For example closing the blinds and setting the orientation to horizontal fully open would first adjust the orientation, then close the blinds and leave the orientation closed. I do not know whether this is a general behavior of HomeKit or a bug in the plugin but I think there definitely was an issue with the order of the commands submitted from the Home app to the plugin. And also creating a scene by playing with the unnamed slider in the Home app where it's not obvious what the slider does also makes the ``blindMode: true`` as it works now much better behavior, at least for now that is iOS 12. Perhaps in iOS 13 the custom characteristics get a better support in the Home app and we can revisit this later :)

thanks for your work, much appreciated :)
Martin

**Comment by dubocr** [comment]
Hi,

Starting 0.3.41, you will have to change your config for using blinds in "orientation mode".
Here is the new config

			"WindowCovering": {
				"blindMode": "orientation"
			}
