### ISSUE TITLE
Deux commandes fil pilote somfy

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#78]
Bonjour, merci pour votre excellent travail!!
J’ai un souci avec mon interface fil pilote de chauffage.
J’ai fait une automatisation dans Maison: dès que la fenêtre est ouverte je coupe le chauffage, et dès que la fenêtre se ferme, je met le chauffage en mode « clim » (ce qui correspond au mode eco.
Cela fonctionne à peu près, des fois le chauffage ne se coupe pas ( je pense que le détecteur n’envoie pas bien l’info) et d’autres fois le chauffage se met en mode chauffe (mode normal du radiateur) lors de la fermeture de la fenêtre.
J’ai remarqué aussi que dans Tahoma il y a systématiquement deux commandes passées à chaque automatisation.

**Comment by dubocr** [comment]
Bonjour,

Pouvez-vous vous connecter sur https://dev.duboc.pro/tools/setup afin que je puisse voir les commandes envoyées.

Merci.

**Comment by Tontonpat** [comment]
Merci pour votre réponse rapide! C’est fait

**Comment by Tontonpat** [comment]
Afin d'être plus précis, le problème ne se présente que lors de l’automatisation. Si je passe en mode « clim » ou « chauffage » en sélectionnant le mode moi même, il n’y a bien qu’une seule commande qui est envoyé à la Tahoma.

**Comment by dubocr** [comment]
As-tu essayé de désactiver ou supprimer l’automatisation voir si elle continue de s’executer mais avec une seule occurrence du coup ? Il arrive que des automatisations qui n’apairaissent plus continuent de s’exécuter un moment et du coup elle serait en double avec celle qui apparaît.

**Comment by Tontonpat** [comment]
Bonjour, j’ai déjà essayé de supprimer les automatisations et il ne se passe plus rien.
Les commandes envoyées en double ne sont pas les mêmes. 
Exemple à l’ouverture: commande confort puis commande off dans la même seconde
A la fermeture: commande confort puis commande eco dans la même seconde également.
Si tu regarde sur la page de setup on voit bien les deux commandes différentes au même moment

**Comment by Tontonpat** [comment]
Bonjour, avez vous trouvé quelque chose?

**Comment by dubocr** [comment]
Bonjour,

Oui je pense. Peux-tu supprimer les lignes 187 à 192 du fichier HeatingSystem.js (les suivantes) :
```
case 'AtlanticElectricalHeater':
if(value >= this.currentState.value)
	command = new Command('setHeatingLevel', ['comfort']);
else
	command = new Command('setHeatingLevel', ['eco']);
break;
```
L'automatisation doit baisser la consigne ET passer en off. Mais de mon coté, baisser la consigne équivaut à passer en eco. Du coup on passe en eco et en off au même moment.

Je vais revoir un peu comment gérer le chauffage électrique en confort/eco/off mais en attendant la suppression des ligne devrait corriger.

**Comment by Tontonpat** [comment]
Merci pour ta réponse, je comprend ta logique de programmation. Comment accéder à ce fichier? Homebridge est installé sous docker sur mon NAS Synology.

**Comment by dubocr** [comment]
Mmm peut-être /docker/homebridge/node_modules/homebridge-tahoma/accessories/HeatingSystem.js ? Il faudra redémarrer Homebridge après. Sinon je vais mettre à jour le plugin d'ici demain il suffira de le mettre à jour `npm update -g homebridge-tahoma`

**Comment by Tontonpat** [comment]
Je ne trouve pas ce fichier, encore moins le dossier node_modules.
J’ai bien un dossier accessories, mais il est vide.
Désolé mais je ne pourrai pas te confirmer si ça marche ou pas. J’attendrai la mise à jour.

**Comment by dubocr** [comment]
Pas de souci, je te tiens au courant.

**Comment by dubocr** [comment]
Tu peux mettre à jour cela devrait désormais être bon.

**Comment by Tontonpat** [comment]
Ça fonctionne! Bravo!
Tu as enlevé le mode auto du chauffage? En même temps ça ne me servait à rien car ça correspondait au mode confort.
Par contre l’automatisation ne fonctionne que lorsque j’ouvre Maison, alors que j’ai mon iPad en concentrateur.

**Comment by dubocr** [comment]
Oui j’ai supprimé le mode auto pour essayé de coller au maximum aux modes de chauffe. Le must serait de pouvoir renommer et supprimer la T° mais bon.
Je n’ai pas compris le lien entre l’ouverture de Maison et l’automatisation.?

**Comment by Tontonpat** [comment]
Jusqu’à présent l’automatisation se faisait toute seule en « arrière plan », si j’ouvrais la fenêtre le chauffage se coupait (enfin quand ça voulait 😁) sans que j’ai besoin d’ouvrir l’appli Maison. Maintenant si j’ouvre la fenêtre l’automatisation démarre que lorsque j’ouvre l’appli

**Comment by dubocr** [comment]
Ah OK je vois. J'ai déjà rencontré ce genre de bug avec des automatisations. Je pense qu'il s'agit d'un soucis de synchro côté Homekit surtout lorsqu'on bidouille un peu les règles (ajout/suppression/modification pour tester).
Essai peut-être de désactiver "Maison" dans les paramètres iCloud puis le réactiver pour forcer la synchro.

**Comment by Tontonpat** [comment]
Je viens de désactiver Maison dans les réglages de l"iPad et de l'iphone puis je les ai ré-activer sans succès.
En tout cas, ta modification fonctionne très bien car il n'y a plus qu'une seule commande envoyée. Merci

**Comment by dubocr** [comment]
Tu peux aussi essayer de supprimer / recréer à nouveau la règle (éventuellement en désactivant/réactivant Maison entre temps). Sinon d'expérience ca fini par revenir tout seul au bout d'un moment mais je ne sais pas ce qui pose problème et c'est vrai que c'est agaçant.

**Comment by Tontonpat** [comment]
Je viens de faire ce que tu m’as dit, mais ça ne change rien.
Merci pour ton temps. Je te tiendrai au courant si ça revient à la normal

**Comment by Tontonpat** [comment]
Bonjour, je me suis rendu compte que MQTT n’était pas installé sur mon NAS, du coup les détecteurs fonctionnait mais pas forcément en temps réels. 
Maintenant ta modification fonctionne à merveille.
Encore merci pour ton travail et le temps que tu passes.
PS: j’ouvrirai un autre topic au sujet des volets RTS (commande STOP)

**Comment by dubocr** [comment]
Slt,

Impec, no souci pour les volets RTS.
