### ISSUE TITLE
[Alarm.js] Suppression du mode Domicile

### ISSUE THREAD

**Issue by Tomnils** [dubocr/homebridge-tahoma#79]
Hello @dubocr ,
j’ai rechercher sur le net pour sup le mode domicile . il y a moyen je discute sur disocrd avec des dev de plugin alarme et il faut faire une exclusion de mode .
je te dit quoi plus tard!!

**Comment by dubocr** [comment]
Hello @Tomnils,

Bonne nouvelle, je viens de tester ça fonctionne effectivement. Peux-tu me donner 3 caractères de ton identifiant que je retrouve ta config pour voir dans quel cas supprimer le mode.

Merci.

**Comment by dubocr** [comment]
C'est bon j'ai trouvé inutile de répondre.

**Comment by dubocr** [comment]
J'ai mis à jour le plugin, peux-tu faire un nom update et me dire si c'est OK pour toi.

Merci pour ton aide.

**Comment by Tomnils** [comment]
Hello @dubocr ,
OUI c bon merci !!!
Maintenant mon père utilise homekit  !
