### ISSUE TITLE
Tahoma and iOS 11

### ISSUE THREAD

**Issue by EdiVip** [dubocr/homebridge-tahoma#8]
I have some problems with Tahoma after install iOS 11 beta 4. When I try to use plugin (paste config to config file) HomeKit devices (home bridge ones) are not responding and Homebridge is blocked. 

The strange thing is that this worked until last week. Other findings:

The Homebridge seems to run fine. It does not show any issues or errors (nothing in the error log, nothing in the log)
Rebooting iOS devices and the Bridge does not bring the devices back, still "No Response"
Disabling plugins does not change anything
Deleting the persistent folder and the accessories folder and restarting home bridge does not change anything
Reinstalling the homebridge and the plugins does not change anything
However, there is one combination that brings back the devices for a couple of minutes:

Stopping the homebridge
Removing the bridge from HomeKit
Deleting persistence and accessories
Starting the homebridge
Adding the bridge to HomeKit
This brings back all devices and accessories for a couple of minutes. After then they go grey again with the obvious "No Response".

I read on the other topic that this is plugin issue. Something is wrong in the code:

https://github.com/nfarina/homebridge/issues/1390

Others plugins (when Tahoma plugin is off) works perfectly. One more thing... I don't know why but first time when I updated iOS only one device was "blocked" and unsupported by HomeKit. It was one screen the same like the others... No idea why?

**Comment by dubocr** [comment]
Do you have an Apple TV or iPad as HomeKit concentrator ?
Can you tel me which screen (its name) were blocked after update.

**Comment by EdiVip** [comment]
I have 2 Apple TV 4g and 1 iPad :)  "Sypialnia" Screen. Now I modify Rollershutter.js to use for ExteriorScreen and look like now work properly. I see another problems with the names. I mean I cannot change the name of the device because is "already use" but is not :) "Roleta" is blocked but "Rolety" is ok

**Comment by dubocr** [comment]
I noticed quite similar behavior when my Apple TV concentrator was sleeping but could be irregular and don't reproduce it last times. Waking up the concentrator seems to unlock the situation.
Names are completely managed by HomeKit and some word are reserved. May "Roleta" is system reserved because it's a key word for Siri.

**Comment by EdiVip** [comment]
After last update (iOS, Homebridge and Plugin) everything is ok.

**Comment by nanoupi42** [comment]
Hello,
J'utilise tous les jours ton plugin c'est un réel bonheur :-) 

Petite question, est-ce possible pour moi de modifier la température qui s'affiche en dessous de la bulle (cf photo) ? J'ai tenté de voir cela dans heatingsystem.js mais je n'ai pas trouvé :( 

Comme tu peux le voir dans la photo quand je suis en mode Clim (mode éco en fait) il me dit que la température va descendre à 10°. Je voulais modifier cela par la valeur réelle de mon mode éco qui est de 19° : 
![img_289c9e264729-1](https://user-images.githubusercontent.com/32174046/33397792-0d72df1c-d54d-11e7-8630-6840cf37efe3.jpeg)
Cela concert le T-Salon

Je n'ai pas le problème pour le plancher chauffant, j'ai bien la valeur de l'éco : 
![img_6406dbfe3617-1](https://user-images.githubusercontent.com/32174046/33397864-4b962bdc-d54d-11e7-9137-0f90fbb75db7.jpeg)

Merci encore !!
