### ISSUE TITLE
[Somfy Protect] Mise en place des inteltags

### ISSUE THREAD

**Issue by Tomnils** [dubocr/homebridge-tahoma#81]
Hey @dubocr  👋 ,

Est ce que tu peux ajouter les capteurs '' inteltag '' de Somfy protect dans ton plugin ?
et si tu peux les capteur de mouvement de Somfy Protect .

Merci pour ton aide !!
@Tomnils

**Comment by dubocr** [comment]
Hello,

Peux-tu te reconnecter sur https://dev.duboc.pro/tools/setup pour que je vois à quoi cela resemble.
Concernant les capteurs de mouvement, l'utilisation ne sera pas optimale pour le moment car il n'existe pas de flux direct entre TaHoma et Homebridge. Les mise à jour ne se répercutent donc pas en temps réel. Actuellement, les états sont mis à jour toutes les 10 minutes.
Je vais essayer de voir avec TaHoma comment réduire ce délais mais dans l'immédiat le rendu sera limité au rafraichissement toutes les 10 minutes.

Merci d'avance pour la config.

**Comment by Tomnils** [comment]
Re,
Tien la config 
![AD5DA869-3985-4550-AD9B-03AD2C430B39](https://user-images.githubusercontent.com/33373907/56077809-beffbf80-5de0-11e9-9a6d-ac4a5a70266d.jpeg)

Si ce n’est pas le bon truc alors tu peux on peut voc via Discord !
Et de rien pour la config

**Comment by dubocr** [comment]
Les tags ne sont pas exposés on ne peut rien faire avec. Peut-être que le capteur de mouvement sera associé avec le bon état en ajoutant la config suivante :
"Alarm": {"occupancySensor": true}

Mais il ne pourra pas servir dans les automatisations à cause du délai de rafraîchissement.
