### ISSUE TITLE
Volets sans réponses + retour état alarme

### ISSUE THREAD

**Issue by Kermarc44** [dubocr/homebridge-tahoma#82]
Bonjour,

Je rencontre plusieurs problèmes : 
- Certains volets RTS restent à tourner en boucle sur ouverture, alors que d'autres restent sans réponse (voir image ci-dessous). Le seul moyen que tout refonctionne est de redémarrer homebridge.
![IMG_1779](https://user-images.githubusercontent.com/46869862/56053937-c0d07100-5d55-11e9-83b2-e430c41c18c0.jpeg)

- J'ai une alarme My Home Alarm de Somfy (ex My Fox). Quand je l'actionne via l'application Somfy ou via le badge, le retour d'état dans l'application maison de Apple se fait soit instantanément, ce qui est parfait, soit avec un délai variable pouvant aller de 1 à 30 minutes environ, ce qui est gênant pour les automatisations.

Merci pour votre aide.
Marc

**Comment by henkied** [comment]
I have the same issues, Please respond in english

**Comment by dubocr** [comment]
Hi,
Please update plugin. Fixed in last release.
There is no realtime feed between TaHoma and Homebridge so you can't expect realtime update. Actually, states are refreshed every 10 minutes.
I expect to reduce this delay but I need to deal with TaHoma to be sure there won't be any impact on server load.

**Comment by Kermarc44** [comment]
Hi,

Thanks for the update.
Concerning the alarm, isn't it possible to speak directly to Somfy Home Alarm server (Tahoma is not needed for Somfy Home Alarm, ex MyFox) ? There's perhaps an API for that.

**Comment by dubocr** [comment]
En fait que je parle de « TaHoma » c’est effectivement incorrect car je parle du système TaHoma en général et surtout de l’infrastructure cloud (pas de la box en particulier). Et je pense (pour ne pas dire je suis sur) que la Somfy Home Alarm utilise cette même infrastructure, donc avec les mêmes contraintes.
Tu as la TaHoma et la somfy home de ton côté ?

**Comment by Kermarc44** [comment]
Oui j'ai les 2.
J'ai eu l'alarme avant la Tahoma et à l'époque c'était encore MyFox.
Je ne sais pas si ça peut aider, mais voilà ce que j'ai noté :
La communication (changement d'état) entre la l'application Tahoma et l'application Somfy Home Alarm se fait instantanément et dans les 2 sens.
Quand on active l'alarme depuis l'application Maison, l'état est changé instantanément dans l'application Tahoma et l'application Somfy Home Alarm.
C'est quand on active l'alarme depuis l'application Tahoma ou Somfy Home Alarm que le changement d'état est aléatoire. Tu parles de refresh toutes les 10 minutes, mais ce qui est étrange c'est que dès fois c'est instantané et d'autre fois c'est beaucoup plus de 10 minutes (une fois il a fallu presque 1H pour que l'état change).
Voilà, j'espère que ça peut aider.

**Comment by dubocr** [comment]
Bonjour,

J'ai fait une erreur, par défaut le refresh est toutes les 30 minutes. (mais cela n'explique pas le 1h).
A titre expérimental pour tester et à utiliser avec précaution vous pouvez ajouter les paramètres suivants dans vos configurations :
```
"alwaysPoll": true,
"pollingPeriod": 10
```
Je ne garanti pas le fonctionnement ni le respect d'un éventuel contrat d'utilisation du système TaHoma. Dans tout les cas, merci de rester au dessus de 5 secondes pour le paramètre `pollingPeriod` (10 secondes dans l'exemple ci-dessus).

**Comment by Kermarc44** [comment]
Bonjour,

Je veux bien essayer ces lignes de commande, mais comment dois-je faire? Quel fichier modifier?
Je ne suis pas un expert Raspberry Pi...
Merci pour votre aide.

**Comment by dubocr** [comment]
Bonjour,

Il faut ajouter ces paramètres là où tu as renseigné le nom d’utilisateur de mot de passe tahoma dans le fichier config.json
