### ISSUE TITLE
Commande STOP volets RTS

### ISSUE THREAD

**Issue by Tontonpat** [dubocr/homebridge-tahoma#83]
Bonjour, serait il possible de rajouter une commande stop sur les équipements RTS ( volets, store, etc...) ? Un peux comme dans Tahoma.
Et, est ce que les stores sont reconnus en tant que stores dans HomeKit? Car pour ma part, dans Tahoma ce sont bien des stores, mais dans HomeKit ce sont des volets.

**Comment by dubocr** [comment]
Bonjour,

Il n'existe pas de type "stores" dans HomeKit. Tout apparaît donc comme des volets.
Concernant la commande "stop", j'ai ajouté une gestion dès lors qu'une nouvelle commande est envoyée alors que la précédente est en cours. A voir si cela correspond.
C'est en cours dans une version importante du plugin que je mettrait à disposition à partir du 6 mai car je ne pourrais pas faire de support d'ici là.
Tu pourras faire la mise à jour le 6 mai et tester pour me faire tes retours.

Merci.

**Comment by chicochaleur29** [comment]
> Bonjour,
> 
> Il n'existe pas de type "stores" dans HomeKit. Tout apparaît donc comme des volets.
> Concernant la commande "stop", j'ai ajouté une gestion dès lors qu'une nouvelle commande est envoyée alors que la précédente est en cours. A voir si cela correspond.
> C'est en cours dans une version importante du plugin que je mettrait à disposition à partir du 6 mai car je ne pourrais pas faire de support d'ici là.
> Tu pourras faire la mise à jour le 6 mai et tester pour me faire tes retours.
> 
> Merci.

Bonjour
Vous avez toujours bien prévu une mise à jour ce jour?

Merci
Cordialement

**Comment by dubocr** [comment]
Bonjour,

J’ai pris un peu de retard car je dois tester davantage certains chauffe-eau. J’espère pouvoir mettre à jour demain.
Je vous tiens au courant.

**Comment by dubocr** [comment]
Bonjour,

Je viens de mettre à jour. Pouvez-vous mettre à jour le plugin et voir comment cela ce comporte.
Pour déclencher la commande stop, il faut appuyer à nouveau sur le widget tant qu'un mouvement est en cours.
Si le comportement est à améliorer, pourrez-vous d'abord accéder à la page : [https://dev.duboc.pro/tools/setup](https://dev.duboc.pro/tools/setup) afin que je puisse analyser le comportement.

Merci.

**Comment by chicochaleur29** [comment]
Bonjour
De mon côté, ça bug. Cela marchait mieux dans la précédente version. Es-ce qu'il est possible de la re-télécharger?
L'état des volets n'est plus mis à jour correctement (on ne sait plus si ils sont ouvert ou fermé)
Je ferai plus de test ce week-end


Cordialement

**Comment by dubocr** [comment]
Pouvez-vous accéder à la page que je puisse comprendre ce qui pose problème ? Qu’entendez-vous pas l’etat n’est plus mis à jour ?
Pour installer une version spécifique du plugin il faut ajouter @version après le nom du plugin.
Ex : npm update -g homebridge-tahoma@0.1.51

**Comment by chicochaleur29** [comment]
L'état sur homekit ne bouge plus, le volet reste toujours en état ouvert à 50% que le volet soit ouvert ou fermé
Quand je veux faire STOP, cela fait tourner en boule le volet sur homekit puis passe ensuite en non réponse. Après quelques minutes, le volet reviens ensuite à "ouvert à 50%"

**Comment by dubocr** [comment]
Avez-vous des messages dans les logs homebridge ?
Les volets RTS n'ont pas de retour d'état c'est donc normal qu'il reste à 50% mais après une action il doit passer à la valeur demandée (ce n'est pas le cas ?).
Éventuellement, vous pouvez remplacer `Log.debug` par `Log` à la ligne 135 du fichier overkiz-device.js puis relancer homebridge et me transmettre les logs.

**Comment by chicochaleur29** [comment]
Oui, il ne passe plus à la valeur demandée sur Homekit. (c'était OK dans la précédente version)
OK, je fais de plus amples tests dès que j'ai un peu de temps.

Merci à vous
Cordialement

**Comment by Tontonpat** [comment]
Bonsoir, après un test ce soir, la commande stop provoque bien l'arrêt du volet mais il devient « sans réponses ». Après plusieurs essais pour le refermer, il s’est bien fermé.
Je ferai d’autres essais ce week-end. Je me suis quand même connecter sur ta page si ça peux aider

**Comment by dubocr** [comment]
La dernière version pourrait corriger les problèmes rencontrés.

**Comment by Tontonpat** [comment]
Tu as refait une mise à jour? Je l’avais mis à jour hier

**Comment by dubocr** [comment]
Oui la 0.2.2 il y à quelques minutes.

**Comment by chicochaleur29** [comment]
OK, je testerai aussi cette version ce week-end.
Merci pour le travail effectué

**Comment by Tontonpat** [comment]
Bonjour, je viens de refaire un test. La commande stop n’arrête plus le volet, mais lui donne l’ordre inverse. Je me suis connecté sur ta page.

**Comment by dubocr** [comment]
Bonjour,

Peux-tu réaliser le comportement attendu avec TaHoma puis te connecter à ma page afin que je vois comment cela se comporte.
Pourras-tu également me donner les timing entre les actions. Ex :
-T0 : lancement fermeture 
-T+15sec : stop

Merci

**Comment by Tontonpat** [comment]
Je viens de le faire sur Tahoma. J’ai demandé la fermeture du volet puis 5 secondes après j’ai appuyé sur stop. Je me suis connecté sur ta page.

**Comment by Tontonpat** [comment]
Du coup je viens de le faire avec HomeKit, de la même manière que sur Tahoma. Le volet s’est bien arrêté dans sa descente, mais il est indiqué ouvert

**Comment by dubocr** [comment]
OK parfait merci. Je vois comment faire. Je m’en occupe demain.

**Comment by Tontonpat** [comment]
Super!! Tu es très réactif!! Merci beaucoup

**Comment by dubocr** [comment]
C'est déjà prêt. Tu peux essayer avec la dernière mise à jour.
Concernant le retour d'état, le timing est identique par contre pour pouvoir tenir compte de la box débranchée j'attends désormais le démarrage effectif de la commande pour valider l'action HomeKit. Néanmoins cela ne change en principe rien à part le petit spinner qui s'affiche plus longtemps. L'état ouvert/fermé quand à lui est toujours mis à jour lors de la fin de la commande (qui s'avère être la fin du mouvement sur les volets/portes).

Je t'ai fait un fichier spécifique à remplacer après la mise à jour pour afficher davantage de logs par rapport au retour d'état :
[WindowCovering.js.zip](https://github.com/dubocr/homebridge-tahoma/files/3178909/WindowCovering.js.zip)

**Comment by Tontonpat** [comment]
Cela fonctionne à merveille!! Merci beaucoup.
Du coup j’ai une autre question: ma porte de garage est IO, ainsi que mon portail, est ce possible d’avoir un slider comme pour les volets roulants? Car je ne peux que ouvrir ou fermer, aucune possibilité de l’ouvrir à un certain pourcentage

**Comment by Tontonpat** [comment]
Je me suis un peu emballé, la position my n’est plus possible. Si je règle le volet à 50% ou un autre pourcentage, le curseur repasse à « ouvert », du coup il descend un peu puis remonte en « ouvert »

**Comment by dubocr** [comment]
Bonjour,

Je pense voir d'où peut venir un problème mais le comportement ne correspond pas tout à fait. Si tu peux essayer quand même avec ce fichier [WindowCovering.zip](https://github.com/dubocr/homebridge-tahoma/files/3181105/WindowCovering.zip)

Le comportement devrait être :
1er appuis sur le widget : ouvre ou ferme
2nd appuis sur le widget lors d'un mouvement en cours : stoppe
Positions intermédiaires (1 à 99%) sur le slider : my

Concernant la porte de garage, pour ajouter un slider le seul moyen serait de la passer en volet roulant (la porte de garage ne dispose pas de slider dans HomeKit).
Pour la passer en volet roulant, tu peux essayer d'ajouter à ta configuration :
`"forceType": { "Garage": "WindowCovering"}`

Dis-moi si c'est bon pour toi et si tu penses que je dois l'appliquer par défaut sur le plugin pour les portes de garage IO.

**Comment by Tontonpat** [comment]
Je suis sur un NAS synology, donc je ne peux pas tester tes fichiers.
Pour la partie IO, ça risque de poser problème de le passer en volet car avec Siri faudra demander d’ouvrir le volet garage.
J’essaierai de forcer le type pour tester mais à voir

**Comment by dubocr** [comment]
Tu dois pouvoir dire « ouvrir le garage » ce suffit. Tu peux quand même modifier la config ?

**Comment by Tontonpat** [comment]
Je dois pouvoir dans la config. Je te tiens au jus dès que je peux faire les tests

**Comment by LaurentCole** [comment]
Bonjour Romain.
Je viens faire la dernière maj et la commande stop fonctionne impeccable avec mes stores Somfy RTS.
Beau travail.
En revanche j'ai un autre problème que je mets dans un autre fil.

**Comment by Tontonpat** [comment]
Je n’ai pas testé de forcer le type porte de garage io en volet. Par contre as tu pu voir le problème de la position my?

**Comment by dubocr** [comment]
Normalement la position my devrait fonctionner mieux avec la dernière version.

**Comment by Tontonpat** [comment]
Pour ma part la position my ne fonctionne pas. La commande stop fonctionne très bien

**Comment by dubocr** [comment]
Qu’est-ce qui ne marche pas ? Toujours le même comportement ?
Peux-tu te connecter à la page setup.

Merci

**Comment by dubocr** [comment]
Merci,
Est-ce que cela fonctionne en demandant à siri douvrir a X% ? Il semblerait que le slider ne s’arrête pas sur 1 valeur et du coup provoque un stop.

**Comment by Tontonpat** [comment]
Avec Siri ça fonctionne

**Comment by dubocr** [comment]
J’ai fait une nouvelle mise a jour qui devrait corriger le problème.

**Comment by Tontonpat** [comment]
Tout fonctionne parfaitement!! Merci encore

**Comment by fiky16** [comment]
Bonjour, je suis de communiquer sur une page ancienne. Mais je n'arrive pas à utilisé (même trouver) le bouton stop. 
Sur homekit je n'ai que la possibilité (en appuyant sur le volet) de l'ouvrir ou fermer. Quel est la procédure pour utiliser le bouton stop svp ?
