### ISSUE TITLE
Don't remove accessories on API error

### ISSUE THREAD

**Issue by iRonin** [dubocr/homebridge-tahoma#86]
The biggest annoyance with Tahoma is that the accessories are removed from HomeKit on API error - and it's very easy to exceed the request quota. I lost a lot of configuration time trying to recreate the scenes. It's related to my earlier request - #19 .

I was thinking that it could be solved by storing the last state of the accessories.
One approach could be to save API response to a temp file so it could be reused to retrieve the last state.

@dubocr let me know which approach would be acceptable here.
Maybe I could sponsor this feature or help a little bit.

**Comment by dubocr** [comment]
Hi,
I was not aware that accessories are removed on error. I'll check that and keep you informed next month as I won't be able to work on it next couple of weeks.

**Comment by iRonin** [comment]
Thank you. It happened when Homebridge is restarted. Eg. I was playing with another plugin that required a lot of restarts - even if I disabled Tahoma, I would lost my devices from configuration.

**Comment by dubocr** [comment]
Oh OK I understand. This concerns startup if we can't retrieve TaHoma devices (request fails or plugin disabled). I often had this kind of problem when testing so I migrated to 2 distinct homebridge instances.
I'll have a look on what we can do as homebridge already has a cache system, I'll look at it.

**Comment by dubocr** [comment]
Fixed in 0.3.11. You won't have this behavior anymore.
