### ISSUE TITLE
Windows screens going in reverse since recent updates

### ISSUE THREAD

**Issue by sabiwa** [dubocr/homebridge-tahoma#87]
I have 4 somfy screens connected to a connexion box and it operated perfectly until a few updates ago. Now they go up when I say down and vice versa. Even setting the option reverse to true in the config isn't helping.

What is wrong ?

**Comment by dubocr** [comment]
Hi,

Could you please update the plugin and tell me if the it's better now ?
If no, could you just add this new config param :
`"WindowCovering": { "reverse": true }`

Thanks

**Comment by sabiwa** [comment]
Hi,

For me it works now again thanks for fixing this.

Thanks
