### ISSUE TITLE
Mapping / Interface CozyTouch Sauter

### ISSUE THREAD

**Issue by jptoucas** [dubocr/homebridge-tahoma#96]
Bonjour,

J'ouvre ce point pour éviter de polluer celui relatif au Chauffe-Eau.

J'ai un sèche-serviette Sauter raccordé via une interface Cozytouch (via fil pilote : https://boutique.confort-sauter.com/interface-cozytouch.html)
Vue Tahoma, j'ai 4 états, Mode éco, Confort, Hors Gel et Off
Vue plugin, l'interface est vue comme un climatiseur
Les ordres Homebridge sont bien pris en compte:
Refroidir -> Déclenche le mode éco en climatiseur 19° (je ne sais pas d'ou vient cette température)
Chauffer -> Déclenche le mode confort
Eteindre -> Eteint le sèche serviette

Dans l'autre sens je n'ai pas réussit à observer de mise à jour de l'état dans l'application Maison (il y a un statut HorsGel côté Tahoma qui me semble ne pas avoir de correspondance coté plugin)

J'ai fait plusieurs chargements via https://dev.duboc.pro/tools/setup, la premiere chose qui m'a paru bizarre c'est que l'interface Sauter est vue comme un chauffage électrique Atlantic, mon soucis bien peut être de la ?
-> Est-ce quelque chose sur lequel il est possible d'agir?
Merci pour tout aide :)

Je joins quelques screenshots du site donnant l'état des appareils, on y retrouve les 4 modes et le statut on/off si ç peut aider.
![image](https://user-images.githubusercontent.com/35664908/57524013-dfab2e80-7326-11e9-8639-351615b9b691.png)
![image](https://user-images.githubusercontent.com/35664908/57524021-e5a10f80-7326-11e9-81d8-7316d333c653.png)
![image](https://user-images.githubusercontent.com/35664908/57524024-e89c0000-7326-11e9-8d0c-ab2f5340c7ce.png)
![image](https://user-images.githubusercontent.com/35664908/57524030-ec2f8700-7326-11e9-81d3-f720378351a2.png)

@jptoucas HomeKit ne dispose pas d'autant de mode que le fil pilote. D'où le mapping déséquilibré.
La mise à jour des états se fait toute les 30 minutes car l'API de Cozytouch ne permet pas de pousser les informations en temps réel.

@dubocr 
Merci pour ce retour ! les 30 minutes expliquent pas mal de choses :)
Effectivement, sans équipement proche d'un sèche serviette côté HomeKit, difficile de faire de magie.
-> Il aurait presque fallu avoir un switch a 4 positions à paramétrer au besoin..

**Comment by jptoucas** [comment]
J'ai fait quelques recherches, le mapping pourrait être celui-ci :
[MappingCozytouch.xlsx](https://github.com/dubocr/homebridge-tahoma/files/3166250/MappingCozytouch.xlsx)

Pour éviter de basculer sur le mode climatisation, il faut toujours que le paramètre HomeKit "Current Heater Coller State" soit à "Heating". Sinon pour que HomeKit sache que l'appareil est éteint, il faut que le paramètre "Active" soit à "Inactive".
Les valeurs de température n'ont aucune importante, j'imagine qu'elles soit initialisées avec une valeur par défaut puis ignorées?

Dans l'état, je ne vois pas comment faire en sorte que le choix "Refroidir" dans HomeKit soit rendu invisible.
(J'espère que les noms de paramètres que j'ai mentionné sont OK, je les ai tirés de "HomeKit Simulator"...

Cela semble jouable d'adapter le mapping ? Je n'ai pas de visibilité sur d'éventuels effets de bord mais il faudrait pouvoir faire la différence entre un périphérique Sauter/Atlantic capable ou non de climatiser.
-> A priori le fait de savoir que le périphérique IO est l'interface Cozytouch permet de déduire les possibilités liées au fil pilote : Confort, Confort -1°C, Confort-2°C, Eco, hors gel et arrêt (les modes confort -1 et confort -2 n'ont pas de correspondance sur le sèche serviette, ou à défaut matchent au mode confort)

**Comment by dubocr** [comment]
En fait Target et Curent ne peuvent pas être différents en dehors d’un état transitoire. Sinon le widget affichera un spinner HomeKit en permanence.

**Comment by jptoucas** [comment]
Effectivement ça parait logique, la Target et le Current doivent êtres égaux pour qu'il considère que le job est fait.
Le Simulator laisse à penser qu'ils sont indépendants :(
<img width="1001" alt="Capture d’écran 2019-05-10 à 14 13 59" src="https://user-images.githubusercontent.com/35664908/57526534-e4271580-732d-11e9-9974-650abe5693cc.png">

**Comment by dubocr** [comment]
Oui il sont effectivement indépendants mais sur l'application Home ils sont pris en compte de façon conjointe pour définir si le produit est en cours de changement.
