### ISSUE TITLE
Stores RTS Somfy

### ISSUE THREAD

**Issue by LaurentCole** [dubocr/homebridge-tahoma#97]
Je viens d'ouvrir un store et ça indique fermé sur l'appli.

Comment utiliser la position MY qui fonctionne avec ma télécommande.

Merci.

**Comment by dubocr** [comment]
La fonction my s’active en plaçant le volet dans une position intermédiaire (1 a 99%).
Le mouvement du store est-il allé à sont terme lors du problème ?

**Comment by dubocr** [comment]
En fermant le store le comportement est-il similaire ? L’appli affiche ouvert.

**Comment by LaurentCole** [comment]
La position MY fonctionne. C'est cool. 
Et je viens de refaire un essai qui fonctionne en ouverture/fermeture avec la bonne info sur l'écran. 
C'est le retour d'info qui semble être un peu long. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
