### ISSUE TITLE
Closed Velux blinds show 1% open

### ISSUE THREAD

**Issue by mahuch** [dubocr/homebridge-tahoma#98]
Hello,
After a long time I have updated my system. Now a closed velux blind in the home kit shows that it is 1% open. My Velux IO remote control reports 0% open - so completely closed. The end positions are set automatically at Velux. There is no separate process for this. At the config files I did not change anything.
Can you help me?
Martin

**Comment by dubocr** [comment]
Hi,

Could you please log at https://dev.duboc.pro/tools/setup.
There is a workaround for some blinds that are closed but indicated 99% closure and I see the is a bug on it. I'll just check if your blind is well fixed by this workaround and I'll fix it and tell you informed.

**Comment by mahuch** [comment]
Hi,
Many thanks for the quick reply. The problem occurs with the Velux Venetian blind, which was produced after 2012. I think that the error lies in the Somfy software. This also does not interpret the state as 100% closed.
I saw the workaround, but so far nothing changed in my files.

**Comment by mahuch** [comment]
I found instructions on how to re-learn the end positions of the blinds. According to this manual the blind is closed at 100%. Thank you for your help.

**Comment by dubocr** [comment]
Hi, I'll still correct the issue but can you give me where you found the instruction to re-learn the position. I'll transmit it to others user who are in the same case.

Thank you too ;-).

**Comment by mahuch** [comment]
Here was the first clue:
https://blog.neo17k.com/raspberry-pi/velux-solarrollladen-endlage-neu-einlernen/?unapproved=15&moderation-hash=496a792c2ff68360efb641965fb9bf9b#comment-15


But since I have the non-solar version, it worked for me like this:

1. Drive up the roller blind with the remote control
2. drive blind down and ...
3. when driving down (about 20-30 cm) turn off the fuse. Turn off the power. The solar variant has a switch on the blind.
4. Wait 30s
5. Switch on the fuse. Immediately press STOP on the remote control and then immediately press down on the remote control.
6. Roller blind moves down and remembers the end position again.

**Comment by dubocr** [comment]
Thanks Martin.
